ome/bioformats

components/formats-bsd/src/loci/formats/in/OBFReader.java

in addition to pull request #1480

take new dimensions into account

---

components/formats-bsd/src/loci/formats/ResourceNamer.java
components/formats-gpl/src/loci/formats/in/BDReader.java
components/formats-gpl/src/loci/formats/in/WlzReader.java

See https://trello.com/c/zvzrb0lN/122-copyright-policies.  This fixes the few obviously incorrect copyright blocks noted on the card.

Fix duplicate or missing copyrights

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Fix at least one typo.

---

docs/sphinx/developers/components.txt

See https://github.com/openmicroscopy/bioformats/pull/1559.
/cc @hflynn, @imunro

Add Maven module names to components page

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

As usual, this should be the last dev_5_0 PR merged before 5.0.7 is tagged.
--no-rebase

Update POM version numbers to 5.0.7

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12560.  To test, verify that ```PFS Offset``` and ```PFS Status``` entries appear in the original metadata table for .nd2 files that have PFS data listed in the acquisition metadata tab in NIS Elements Viewer.  I was testing with ```nd2/fiji-655/01.nd2```, though it might be a good idea to spot check one or two others.
I would expect builds to remain green.

ND2: add the PFS offset and status to the original metadata table

---

components/formats-bsd/src/loci/formats/codec/JPEG2000Codec.java

This checks for both the 0xff4f and 0xff51 markers, so that escaped
0xff4f markers in the box will be removed as expected.
Fixes http://trac.openmicroscopy.org/ome/ticket/12631.  To test, import the file from QA 10341 into OMERO and wait for pyramid generation to complete (should be < 10 minutes).  Verify that the clock icon is replaced by a thumbnail and that the full viewer can be opened.   The thumbnail may be very dark; enabling all channels in the full viewer should help.

JPEG-2000: make sure the entire box is removed

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

With this commit, Bio-Formats top-level findbugs target should be compliant with Findbugs 3.0.0
--no-rebase

Fix remaining DM_BOXED_PRIMITIVE_FOR_PARSING warnings

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Update version numbers to 5.0.8-SNAPSHOT

---

docs/sphinx/about/whats-new.txt

Stub version history like we did for 4.4.8

Add version history for 5.0.8

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Update POM version numbers to 5.0.8

---

docs/sphinx/index.txt

See https://trello.com/c/bm6wvqIt/147-data-model-docs-updates
--no-rebase

Updating schema version for 5.1

---

components/autogen/src/format-pages.txt

See https://github.com/openmicroscopy/bioformats/issues/1581
This is the UK redirect with prettier graphics 
I've also removed the extra link as the main one goes to the equivalent page.

Updating DeltaVision link

---

docs/sphinx/formats/index.txt
docs/sphinx/formats/pattern-file.txt

See https://trello.com/c/3Tl6RgGg/51-documentation-for-pattern-files.

Add a description of pattern file usage

---

.travis.yml
components/xsd-fu/python/configobj.py
components/xsd-fu/python/ome/modeltools/model.py
components/xsd-fu/python/ome/modeltools/object.py
components/xsd-fu/python/ome/modeltools/property.py

This should fix all W503 line break before binary operator warnings
--no-rebase

Fix Python files for PEP8 1.6.2

---

docs/sphinx/formats/deltavision.txt

Generated by build [BIOFORMATS-5.1-latest-docs-autogen#292](http://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-docs-autogen/292/).
----
--no-rebase

Update auto-generated documentation

---

ant/toplevel.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml

ant: Remove metadata-src
maven: Remove unused build helpers (at least, I think they are unused)
--------
Testing: Should all continue to be green.

build: Remove unused targets and logic for code generation

---

components/formats-api/src/loci/formats/FormatTools.java

Add bit to supported pixel type (used by OMERO)

formats tools

---

components/formats-bsd/src/loci/formats/in/FlowSightReader.java

Fixes the file in QA 10450.
/cc @zeb

FlowSight: default to 1 channel if channel tags are missing

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java

This is helpful in multi-file datasets with many files.

MinimalTiffReader: say which file is invalid

---

.gitignore
components/specification/build.xml

Exclude files `*.xpr` and `omeOxygenDocConfig.xml`

Add exclude for oxygen files

---

components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

* import the files from master https://github.com/openmicroscopy/samples (not the updated ones from @will-moore's PR)

XML reader

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

See https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7750 and https://trello.com/c/urm1ZpPz/144-threaded-jpeg-2000.
To test, download the file linked on the forum thread, uncompress it and import into OMERO.  Pyramid generation should occur without an exception, and is expected to complete in under 10 minutes.

TIFF: expand single-tile special case

---

components/specification/released-schema/2008-02/catalog.xml

Corrects incorrect entries in the catalog that lead to validation failures of 2008-09 files.
----
--no-rebase

Correct the 2008-02 catalog

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

@pwalczysko : This PR should fix the Stroke-width bug suggested here : https://github.com/openmicroscopy/bioformats/pull/1671#issuecomment-82458999

ImageJ Strokewidth update

---

docs/sphinx/themes/globalbftoc.html

See https://trello.com/c/xEcNAqQq/237-bio-formats-c
Adds C++ download to the docs sidebar
Is 'Main' downloads ok for everything else or do we want to brand it Bio-Formats (Java) or something else?

Adding cpp downloads to the docs sidebar

---

components/specification/src/ome/specification/OmeValidator.java

Input stream

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be merged once 5.1.0-rc1 is tagged, and before any other PRs are merged.

Update POM version numbers to 5.1.0-SNAPSHOT

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Update POM version numbers to 5.1.0-rc2

---

docs/sphinx/conf.py

Release docs need a new banner

Updating docs banner from PREVIEW to release

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

As usual, this should be the last PR merged before 5.1.0 is tagged.
--no-rebase

Update POM version numbers for 5.1.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the first PR merged after 5.1.0 is tagged.
--no-rebase

Update POM version numbers to 5.1.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/BioRadReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-5.1-merge-test_images_good-win/
This should attempt to sanitize existing file paths to fix remaining failures on windows for `test_images_good`
--no-rebase

Fix sane use files on Windows

---

components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Fix ticket https://trac.openmicroscopy.org.uk/ome/ticket/12628
To test this PR
* Use the files from QA 10344
* Select the ```.mdb```. The problem will only be seen when it is selected
* run ```./showinf -omexml  PathToQA/10344/2014.10.30/2014.10.30.mdb```
* All 40 rois should now be read.

Lsmreader roi

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

1) Update the Bioformats_Package.jar in your imageJ plugins folder.
2) Now open imageJ --> open an image, add ROI's to the same (add them to the ROIManager.
3) Export the image as an ome-tiff, using the Plugins-->Bio-Formats-->Bio-Formats Exporter (keep the default options)
4) The image should get exported with the ROI's.
5) Now : Reimport the image using the Bio-Formats Importer : in the import options menu, keep the following checkboxes selected : Display OME-XML metadata and Display ROIs.
6) This should import your image and add the ROI's to the ROIManager.
To Check 
1) Check the OME-XML to see if the newly added ROI's have the correct Z,C and T information.
Also try the following,
1) Open an Image from OMERO using the Omero-IJ plugin.
2) Check the OME-XML to see …

Roi handler update C Z T

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

Remove trailing character.
To test: 
* Import an image from QA : 9456
see https://trac.openmicroscopy.org/ome/ticket/12529#comment:3

Flex reader

---

components/formats-api/src/loci/formats/DelegateReader.java
components/formats-bsd/src/loci/formats/in/NativeQTReader.java
components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/formats-gpl/src/loci/formats/in/InveonReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository-win/2.
This will need one more commit after the next build of BIOFORMATS-5.1-merge-full-repository-win, so doesn't need to be reviewed quite yet.  I would expect all other builds to remain green, and the test failure count to be reduced by 95.  The 92 failures on QuickTime datasets are not yet resolved, but logging has been added to help determine the cause.
/cc @sbesson

Final Windows fixes

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

If a BigTIFF extension is used, or we know that more than 4GB of data
will be written, then BigTIFF is used automatically.  This does not
attempt to switch to BigTIFF when compression is used and a BigTIFF
extension is not present, as we can't easily predict the actual size
of the output file in that case.
Fixes https://trac.openmicroscopy.org/ome/ticket/6589.
To test, take a file with 4GB or more of pixel data, e.g. ```large-file&sizeX=2048&sizeY=2048&sizeZ=1200.fake```  Run bfconvert with an output file name that has ```.btf```, ```.tf8```, or ```.tf2``` as the extension and no other arguments; the output file should be in the BigTIFF format, and there should be a ```Switching to BigTIFF``` message printed.  The same test with an output file name that ends in ```.tif``` or ```.tiff``` …

TIFF writer: automatically switch to BigTIFF when possible

---

docs/sphinx/developers/matlab-dev.txt

Fix for ref : https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7790#p15654

BF Matlab Doc-Fix

---

docs/sphinx/users/fiji/index.txt

Replicate steps given in the documentation to check if the upgrade works.

Documentation for manual upgrade of Bio-Formats in FIJI

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last PR merged before 5.1.1 is tagged.

Update POM version numbers to 5.1.1

---

components/formats-bsd/src/loci/formats/in/AVIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2015-April/003252.html and QA 11011.
To test, use the ffmpeg command from the thread on the file from QA 11011:
```ffmpeg -y -i M-flow10001.avi -qscale:v 1 -c:v mjpeg M-flow1_1.avi```
(on some Ubuntu systems, you may need to use ```avconv``` instead of ```ffmpeg```)
Verify that the converted ```M-flow1_1.avi``` opens in ImageJ - you will likely need to use a virtual stack and scroll through all of the planes.

AVI: fix how 0-length MJPEG planes are handled

---

components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12383 and https://trac.openmicroscopy.org/ome/ticket/12384.
To test, use ```test_images_good/zeiss-lsm/QA images/10052011_R1_GR1_B1_L49.lsm```.  Without this change, ```showinf``` should report that the images are indexed, but a lookup table should not be present - both images will appear gray/black.  With this change, the same test should show that the images are indexed and that a lookup table with 65536 entries is present.  The first image should be colored gray/white, and the second image should be colored red.

Zeiss LSM: fix lookup tables for 16-bit data

---

docs/sphinx/developers/matlab-dev.txt

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005331.html
This PR should document the issue with `PermGenSpace` errors on MATLAB.

Add instructions to the MATLAB developers page for PermGenSpace errors

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

This PR fixes issue https://trac.openmicroscopy.org/ome/ticket/12808
To test:
* Import ```leica-lif/niko/6-2-15MF2-Pos3-S1.lif```
* Check that the excitation wavelength is correctly set.

LIF reader wavelength

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java

First version of new SlideBook6 reader plugin.
- this reader is based on a JNI DLL wrapper that calls SlideBook 6 file format reader DLL
- reader includes simple meta data support
- DLLS are for Windows and x64 only
To work, the following .dll files must be in the ImageJ bin path (eg. jre/bin):
SlideBook6Reader.dll  [x32](https://drive.google.com/open?id=0B5XYovwfrhQDfnRlTHBJUURJbHdBREJuZGJlYUVHdnN3Z1NzSUthMm0zWWZ5WEpPQl93a1E&authuser=0) [x64](https://drive.google.com/open?id=0B5XYovwfrhQDflN2QU1INUwzRC1pMVA3WHlyWExiUjQ2bWptcGIyLTZTXy1jZ250Uzc2RDA&authuser=0)
SBReadFile.dll  [x32](https://drive.google.com/open?id=0B5XYovwfrhQDfnRlTHBJUURJbHdBREJuZGJlYUVHdnN3Z1NzSUthMm0zWWZ5WEpPQl93a1E&authuser=0)  [x64](https://drive.google.com/open?id=0B5XYovwfrhQDflN2QU1INUwzRC1pMVA3WHlyWExiUjQ2bWptcGIyL …

SlideBook 6 reader

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/formats-api/src/loci/formats/ClassList.java
components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/in/DefaultMetadataOptions.java
components/formats-api/src/loci/formats/in/MetadataOptions.java
components/formats-api/src/loci/formats/meta/MetadataConverter.java
components/formats-api/src/loci/formats/meta/ModuloAnnotation.java
components/formats-api/src/loci/formats/meta/OriginalMetadataAnnotation.java
components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/metakit/src/ome/metakit/ColumnMap.java
components/metakit/src/ome/metakit/MetakitReader.java

See https://trello.com/c/U8HDtN3O/159-review-private-method-javadocs.  This only covers the ```bio-formats-tools```, ```metakit```, and ```formats-api``` components; I likely won't have time to review others before 5.1.2.
Please focus on reviewing the readability and correctness of what's here; if a method is undocumented, it can be listed on the card, but the focus at this point is not on an exhaustive review of all private methods.

Progress on private method Javadocs

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12802.
To test, use the file from the ome-users thread linked to ticket 12802.  Check the original metadata table, and verify that the invalid entries noted in the thread are no longer present.

Metamorph: expand UIC1 tag parsing

---

tools/bf.bat
tools/bf.sh

ref: https://github.com/openmicroscopy/bioformats/pull/1778
Adding the remaining parts to complete the fixes.
1) Build bioformats locally.
2) Now remove : loci_tools.jar and bioformats_plugins.jar from the artifacts folder.
3) Run ./ijview  "path/ to/ image" , 
ex: tools bramalingam$ ./ijview /Users/bramalingam/Desktop/IMG_1355.JPG 
With this PR in,the image should open in IJ without any issues.
Without this PR you should get the following exception with the above workflow,
``
Error: Could not find or load main class loci.plugins.in.Importer
``

Bftools update

---

docs/sphinx/about/whats-new.txt

As usual, every single bug fix is not listed, but I think this catches the notable ones.  Happy to add/remove if needed.

Add version history for 5.1.2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last PR merged before 5.1.2 is tagged.

Update POM version numbers to 5.1.2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the first PR merged now that 5.1.2 is tagged.

Update POM version numbers to 5.1.3-SNAPSHOT

---

components/formats-common/src/loci/common/Location.java

Ref: https://github.com/openmicroscopy/bioformats/issues/1851
To test:
1) Plugins--> Bio-Formats--> Bio-Formats Remote Importer
and paste this url : https://s3.amazonaws.com/dpwr/s3test/bus.png
This should open the image in ImageJ.
Without this PR you should be getting a "File not found" exception.

Bug Fix : Read https urls

---

components/formats-gpl/src/loci/formats/in/ImspectorReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/11722.
To test, use the files from QA 7702 and QA 9468.
The file from QA 9468 should have two channels with this change, as indicated by http://lists.openmicroscopy.org.uk/pipermail/ome-users/2014-August/004673.html.  The .msr files in QA 7702 should match dimensions/images with the corresponding OME-TIFF file(s) in the same directory.  Without these changes, the .msr files from both QA issues will have thrown an exception upon initialization.

Imspector: better detection of Z stacks

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last PR merged before 5.1.3-rc1 is tagged.

Update version numbers to 5.1.3-rc1

---

docs/sphinx/about/whats-new.txt

Usual caveats apply, /cc @hflynn 
I didn't mention C++ on Windows, since the state of that for release isn't yet clear.  Happy to add a "progress on ..." or whatever note if that's useful or necessary, /cc @rleigh-dundee

Update version history for 5.1.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last PR merged before 5.1.3 is tagged.

Update version numbers to 5.1.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the first PR merged after 5.1.3 is tagged.

Update version numbers to 5.1.4-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

Use NumberFormat to parse string.
To test:
* Run ``` ./showinf ``` against the image from QA 11356

Gatan Reader

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/formats-gpl/src/loci/formats/in/InCellReader.java
components/formats-gpl/src/loci/formats/in/MIASReader.java
components/formats-gpl/src/loci/formats/in/ScanrReader.java

This PR rewrites some GPL reader code in a minor way to increase readability and/or efficiency:
* FV1000Reader
* InCellReader
* MIASReader
* ScanrReader
CI does the testing.

minor code adjustments to a few GPL readers

---

components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/SlidebookReader.java

This PR rewrites some GPL reader code in a minor way to increase readability and/or efficiency:
* LeicaReader
* LIFReader
* SlidebookReader
CI does the testing.

minor code adjustments to Leica and Slidebook readers

---

docs/sphinx/developers/cpp/schema.txt
docs/sphinx/developers/cpp/tutorial.txt
docs/sphinx/developers/index.txt

As requested by (I think) @joshmoore

cpp: Document use of 2013-06 schema by bioformats-cpp

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See https://trello.com/c/eVA44U4R/42-dallas-nd2-dimensions.
The file is being uploaded to ```nd2/dallas/```, but is very large, so will take a while yet.  I'll update here when it's finished.  The main thing to check is that the output of ```showinf -nopix``` shows 20 positions x 621 timepoints (this is one more timepoint than Elements shows, but is consistent with the fact that 12420 images are actually stored).

ND2: parse position counts from non-XML metadata

---

docs/sphinx/about/whats-new.txt

Usual disclaimers apply with respect to date and verbosity.
/cc @hflynn, @mtbc for general review
/cc @rleigh-dundee for C++ review/additions

Updated version history for 5.1.4

---

components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/ome-xml/pom.xml

This should remove some of the project failures when
importing the project via m2eclipse.

fix xsd-fu/eclipse usage

---

components/formats-bsd/src/loci/formats/in/BMPReader.java

Adding support for RLE_8 and RLE_4 compression formats
Bug: BMP Reader failed to read a specific image
https://trac.openmicroscopy.org/ome/ticket/12971
This was due to the compression encoding RLE 8, which is not currently supported
OpenBytes method has been modified to deal with RLE 8 and RLE 4 compression encodings
Raw data is handled as before and is unaffected
Test Steps - 
1. Download the bmp (foo.bmp) attached to the trac ticket https://trac.openmicroscopy.org/ome/ticket/12971
2. Import using bio formats bmp reader
3. Compare the resulting image with the correct and incorrect expected images in the ticket
Other useful links -
To read more about RLE encoding the following links may be helpful:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183383(v=vs.85).aspx …

Adding RLE compression support for BMP's

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

This PR fixes the problem reported by @pwalczysko see comment
https://github.com/openmicroscopy/bioformats/pull/1954#issuecomment-139589989
Follow the testing instruction described in the comment above.
cc @pwalczysko @stelfrich 
Note that the OMERO part has not yet been updated.

Roi position

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

use OME XML meta data in file format version 2

---

components/formats-bsd/src/loci/formats/in/BMPReader.java

This should fix the error in https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/628/console.

BMP: fix cropping of compressed images

---

docs/sphinx/developers/cpp/overview.txt

This should have been updated some time back, but was forgotten.

docs: OME-TIFF writing is now available

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This PR should bump the version number in preparation of the regions work /cc @mtbc

Bump Bio-Formats version to 5.2.0-SNAPSHOT

---

components/bio-formats-plugins/src/loci/plugins/in/Calibrator.java

cope with pixel unit length

---

components/formats-gpl/matlab/bfCheckJavaPath.m
components/formats-gpl/octave/PKG_ADD

See all discussion on issue #2018

matlab and octave: add flexibility to the filename of bioformats jar

---

components/bio-formats-plugins/src/loci/plugins/in/Calibrator.java

This is the same as gh-2030 but rebased onto dev_5_1.
----
please review

cope with pixel unit length (rebased onto dev_5_1)

---

components/formats-api/src/loci/formats/FormatTools.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Rebased PR https://github.com/openmicroscopy/bioformats/pull/2050 onto develop branch

Test suite reafctor native units

---

components/formats-gpl/src/loci/formats/in/AnalyzeReader.java

Using millimetres and milliseconds rather than converting

AnalyzeReader - Using native units

---

components/formats-gpl/src/loci/formats/in/APLReader.java

Updating to use native units for physical size x and y

APLReader - Update to use native units

---

components/formats-gpl/src/loci/formats/in/UnisokuReader.java

See https://trello.com/c/nO35TKXK/3-units-and-readers

Use native units for the pixels physical size of UnisokuReader

---

components/formats-gpl/utils/writeMapAnnotationsExample.java

Rebased from https://github.com/openmicroscopy/bioformats/pull/2062
@melissalinkert @sbesson @jburel

Rebase write map annotations example 5 1

---

components/formats-gpl/utils/writeMapAnnotationsExample.java

Code review cc: @melissalinkert @jburel

Bio-Formats: Add example for writing Map Annotations to OME-XML

---

docs/sphinx/about/whats-new.txt

A couple of yet-unmerged PRs are referenced here, so depending on how Friday goes this may need one more commit.

Add version history for 5.1.6

---

docs/sphinx/users/imagej/load-images.txt

Requested/suggested by @joshmoore on https://trello.com/c/X4OxB2FS/385-minor-cross-link-patterns
Although this page is aimed at ImageJ users, the cross-link may also help people searching for the functionality to find the content they need.

linking grouping files to pattern file page

---

components/formats-common/src/loci/common/xml/ValidationSAXHandler.java

find non default namespace ome

---

components/formats-common/src/loci/common/xml/ValidationSAXHandler.java

This is the same as gh-2080 but rebased onto dev_5_1.
----
please review

find non default namespace ome (rebased onto dev_5_1)

---

docs/sphinx/users/imagej/load-images.txt

This is the same as gh-2118 but rebased onto develop.
----
Requested/suggested by @joshmoore on https://trello.com/c/X4OxB2FS/385-minor-cross-link-patterns
Although this page is aimed at ImageJ users, the cross-link may also help people searching for the functionality to find the content they need.

linking grouping files to pattern file page (rebased onto develop)

---

components/formats-gpl/utils/writeMapAnnotationsExample.java

@melissalinkert , @sbesson 
ref: https://trello.com/c/WgZKOpA4/20-clients-support-support-map-annotations-from-ome-tiff

Fix ImageAnnotationRef and clean up

---

components/formats-gpl/src/loci/formats/in/AliconaReader.java

Using metres rather then micrometers

AliconaReader - Using native units

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

Using metres for physical size rather than micrometres

FEITiffReader - Using native units

---

components/formats-gpl/src/loci/formats/in/AliconaReader.java

This is the same as #2044 but rebased onto develop.
---
Using metres rather then micrometers

AliconaReader - Using native units (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This is the same as https://github.com/openmicroscopy/bioformats/pull/2117 but rebased onto develop.
---
Reported Issue: http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-November/005745.html
This is a follow up to : #1997
To reproduce:
Using uploaded from file QA 16928
Import with bioformats and view metadata
Verify that the PhysicalSizeZ and TheZ are set correctly and PositionZ is 0 for each image
To test the PR:
Follow the same steps above but verify that PositionZ is now set for each image, PositionZUnit should also now be µm rather than reference frame

Andor - Plane Position Z (rebased onto develop)

---

components/formats-gpl/utils/writeMapAnnotationsExample.java

This is the same as gh-2122 but rebased onto develop.
----
@melissalinkert , @sbesson 
ref: https://trello.com/c/WgZKOpA4/20-clients-support-support-map-annotations-from-ome-tiff

Fix ImageAnnotationRef and clean up (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

Filenames won't necessarily be given in the .xdce file, so this attempts
to guess at the correct file names.  This won't cover all cases, but
should work as a place to start.  It also fixes field position
population to allow for positions being recorded out of order.
See https://trello.com/c/9V2wbtvD/139-idr0017-breinig-drugscreen

InCell: attempt to find TIFF files in Analyzer 2000 datasets

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/ucDe9nB2/16-update-whatsnew-to-mention-no-c-changes-in-5-1-7

Adding C++ no changes to whatsnew

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2152 but rebased onto develop.
----
See https://trello.com/c/ucDe9nB2/16-update-whatsnew-to-mention-no-c-changes-in-5-1-7

Adding C++ no changes to whatsnew (rebased onto develop)

---

components/ome-xml/src/ome/xml/model/MapPairs.java

This should fix the failing `testValidXML` tests from https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-full-repository/4/console.

Fix map namespace post schema unification

---

docs/sphinx/developers/java-library.txt

@melissalinkert @sbesson @jburel @joshmoore

BF: Java Binding Documentation Template

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/SPEReader.java

This is a new reader to add support for Princeton Instruments .spe files
Specification and sample files can be found on the related ticket:
https://trac.openmicroscopy.org/ome/ticket/12852
Splitting from https://github.com/openmicroscopy/bioformats/pull/1964

Adding support for Princeton Instruments .spe data

---

components/specification/released-schema/2016-DEV0/ome.xsd

This PR should not change behavior. Everything should still work and CI should be green. The keen may want to try upgrading an OME-XML file to 2016-DEV0 then validating it.
--no-rebase

minor cleanup for 2016-DEV0/ome.xsd

---

components/formats-bsd/src/loci/formats/AxisGuesser.java

Fixes javadocs for `AxisGuesser`.

AxisGuesser: fix javadocs

---

components/formats-bsd/test/loci/formats/utests/FilePatternTest.java

This should fix a problem where invalid filename characters break the test on Windows (See @sbesson's comment on #2161). I'm using the conditional here because I could not test it on a Windows box, so I'm waiting for Jenkins' opinion on the matter.

Fix FilePatternTest on Windows

---

components/formats-bsd/test/loci/formats/utests/FileStitcherTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Adds a new unit test for `FileStitcher`.

Add unit test for FileStitcher

---

docs/sphinx/developers/generating-test-images.txt

Allow for simpler fake plate definition (docs)

---

components/formats-api/src/loci/formats/meta/MetadataConverter.java
components/specification/released-schema/2016-DEV0/ome.xsd
components/specification/transforms/2016-DEV0-to-2015-01.xsl
components/xsd-fu/python/ome/modeltools/config.py

Adds a new model object `Folder` which may contain Images and ROIs and may itself be in a folder.
--no-rebase

add folders to model

---

components/formats-api/src/loci/formats/FormatReader.java

Same as #2227, but rebased onto develop.

getUsedFiles performance fix (develop)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last Pull Request to be merged in preparation of the intermediate 5.2.0-m1 milestone.

Update POM version numbers to 5.2.0-m1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This should be the last PR to be merged before the intermediate 5.2.0-m2 release of Bio-Formats

Update POM version numbers to 5.2.0-m2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

This PR starts the next milestone development cycle of Bio-Formats 5.2.0

Revert POM version numbers to 5.2.0-SNAPSHOT

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/alicona-3d.txt

This should fix https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/171/warnings3Result/

Fixing alicona link

---

docs/sphinx/users/imagej/index.txt

See https://trello.com/c/Sqm8TR76/5-document-the-exporter-big-tiff-workflow
/cc @pwalczysko, @hflynn

ImageJ plugin docs: add note about exporter file extensions

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/perkinelmer-ultraview.txt

fixes the broken link to the microscope information

PerkinElmer UltraVIEW VoX link

---

docs/sphinx/about/whats-new.txt

Preliminary draft for the version history. Please feel free to point out edits/corrections.
@melissalinkert @jburel @sbesson @joshmoore

Add version history for 5.1.9

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Update POM version numbers to 5.2.0-m3

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java

FilePattern docs revision (metadata)

---

components/specification/released-schema/2016-DEV0/ome.xsd

See https://trello.com/c/P3tnL6pY/55-mapannotation-should-not-be-a-textannotation

Change MapAnnotation type to be an Annotation

---

components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/test/loci/formats/utests/FilePatternBlockTest.java

Same as #2349, but rebased onto `metadata`

Fix csv pattern blocks (metadata)

---

components/formats-bsd/test/loci/formats/utests/FilePatternTest.java

Fix FilePatternTest on Windows (metadata)

---

components/formats-bsd/test/loci/formats/utests/FileStitcherTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Add unit test for FileStitcher (metadata)

---

components/formats-bsd/src/loci/formats/AxisGuesser.java
components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/test/loci/formats/utests/AxisGuesserTest.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java
components/formats-gpl/src/loci/formats/in/MIASReader.java

Rebases #2352, #2187, #2368 and #2382 onto metadata.

Misc AxisGuesser and FilePattern fixes

---

docs/sphinx/about/whats-new.txt

Adds version history for 5.1.10 release. Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/about/whats-new.html

Add 5.1.10 version history

---

docs/sphinx/developers/xsd-fu.txt

Reverts openmicroscopy/bioformats#2404

Revert "Fix generateDS link"

---

components/formats-gpl/src/loci/formats/in/HamamatsuVMSReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/11535.
To test, use the three .vms files from ```curated/hamamatsu-vms/openslide```, and compare against the three .ndpi files from ```curated/hamamatsu/openslide```.  The full resolution image for the .ndpi files (== series 0) should be a factor of 2 smaller than the full resolution image for the corresponding .vms.  The whole image can't be opened with showinf/ImageJ, but spot checking several (x, y, w, h) .ndpi tiles against the corresponding (x * 2, y * 2, w * 2, h * 2) .vms tile should give confidence that the tiling is now being done correctly.
Importing into OMERO would also be something to check, but note that this should result in pyramid generation since pyramids are not stored in these .vms datasets.  Not sure how easy that would …

Hamamatsu VMS: fix dimensions of full-resolution image

---

components/formats-bsd/src/loci/formats/in/FlowSightReader.java

See #2317 for more details. The fix is pretty surgical - the only effect is to try harder for a case that previously threw an exception.

Fixes #2317 - infer channel count from channel names

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
components/formats-bsd/test/loci/formats/utests/MemoizerTest.java
components/specification/src/ome/specification/XMLMockObjects.java
docs/sphinx/developers/generating-test-images.txt

This PR rebases most of the Fake reader improvements made during the course of 5.2.0 on the `metadata` branch. Includes commits from #2222, #2225, #2182, #2191, #2244, #2248, #2252, #2270, #2273, #2283 and #2302.

Fake reader: 5.2.0 improvements

---

components/formats-bsd/src/loci/formats/Memoizer.java

If `failIfMissing` is set to true then no `setId` call
will be performed on the underlying reader. Instead, if
`loadMemo` returns null, a `FormatException` will be thrown
signaling that no cache is available.

Memoizer: Add failIfMissing flag for perf

---

components/xsd-fu/templates-java/AggregateMetadata.template
components/xsd-fu/templates-java/DummyMetadata.template
components/xsd-fu/templates-java/FilterMetadata.template
components/xsd-fu/templates-java/MetadataRetrieve.template
components/xsd-fu/templates-java/MetadataStore.template
components/xsd-fu/templates-java/OMEXMLMetadataImpl.template
components/xsd-fu/templates-java/OMEXMLMetadataImpl_Channel_ID.template
components/xsd-fu/templates-java/OMEXMLModelEnum.template
components/xsd-fu/templates-java/OMEXMLModelObject.template
components/xsd-fu/templates-java/OMEXMLModelObject_Reference.template
components/xsd-fu/templates-java/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template
components/xsd-fu/templates-java/OMEXMLModelObject_XMLAnnotation_update_Value.template

Remove tabs and trailing whitespace.  No functional changes.  This is a followup to the recent schema code generation work.
https://github.com/openmicroscopy/bioformats/pull/2450/files?w=1 shows the non-whitespace changes (i.e. none).
--------
Testing: Check jobs are green; review source changes.

xsd-fu: Clean up Java templates

---

CMakeLists.txt
cpp/cmake/Version.cmake
cpp/lib/ome/xml/CMakeLists.txt
cpp/lib/ome/xml/OMEXMLConfig.cmake.in
docs/doxygen/CMakeLists.txt

See https://github.com/ome/ome-common-cpp/pull/21 for full description and testing instructions.

cmake: Find OME components individually

---

components/xsd-fu/templates-cpp/OMEXMLModelEnum.template
cpp/cmake/HeaderTest.cmake
cpp/lib/ome/xml/model/enums/UnitsPressureConvert.cpp
cpp/lib/ome/xml/model/primitives/Color.h

See: https://github.com/ome/ome-common-cpp/pull/22

Windows header portability checks and fixes

---

cpp/LICENSE.md

See https://github.com/ome/ome-common-cpp/pull/23

cpp: LICENSE: Add BSD licence text

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nikon-nis-elements-nd2.txt

See https://trello.com/c/ezNfoTIL/56-clarify-nikon-native-library-status
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/nikon-nis-elements-nd2.html

Clarify note about legacy ND2 reader

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/gatan-digital-micrograph.txt

See https://trello.com/c/KMTuzwmG/172-gatan-format-page-stacks
staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/gatan-digital-micrograph.html

Add note that Gatan reader doesn't support stacks

---

components/ome-xml/src/ome/units/UNITS.java
components/ome-xml/src/ome/units/quantity/Angle.java
components/ome-xml/src/ome/units/quantity/ElectricPotential.java
components/ome-xml/src/ome/units/quantity/Frequency.java
components/ome-xml/src/ome/units/quantity/Length.java
components/ome-xml/src/ome/units/quantity/Power.java
components/ome-xml/src/ome/units/quantity/Pressure.java
components/ome-xml/src/ome/units/quantity/Quantity.java
components/ome-xml/src/ome/units/quantity/Temperature.java
components/ome-xml/src/ome/units/quantity/Time.java
components/ome-xml/src/ome/units/unit/Unit.java

- Link to current name for deprecated units
- Document Unit and Quantity classes
- Document concrete Quantity types

Document ome-xml unit classes

---

docs/sphinx/developers/export2.txt
docs/sphinx/developers/file-reader.txt
docs/sphinx/developers/file-writer.txt
docs/sphinx/developers/index.txt
docs/sphinx/developers/units.txt

This is primarily a simple overview, with links to @dgault's examples.

docs: sphinx: Add units documentation page

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/pCstzf4d/21-version-history-prs
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html

Add 5.2.1 version history

---

ant/toplevel.xml
tools/bfconvert
tools/domainlist
tools/formatlist
tools/ijview
tools/mkfake
tools/showinf
tools/tiffcomment
tools/xmlindent
tools/xmlvalid

Make bftools symlink-able

---

components/bio-formats-plugins/src/loci/plugins/Updater.java
components/bio-formats-plugins/src/loci/plugins/config/ConfigWindow.java
components/bio-formats-plugins/src/loci/plugins/in/ImagePlusReader.java
components/bio-formats-plugins/src/loci/plugins/in/ImportProcess.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterOptions.java
components/bio-formats-plugins/src/loci/plugins/shortcut/ShortcutPanel.java
components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

this is a mechanical change so that a simpler library method can be used. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.
In the event of conflicts I'll remove the problem changes from this PR.

switch to String.indexOf(int) in plugins

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

Rebases #2123 onto develop.
I've tested locally against a small subset of our InCell data and got no errors. If this does not break the build, we can move forward and add a new test case from idr0017.

InCell: attempt to find TIFF files in Analyzer 2000 datasets (develop)

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/SGVCGy82/21-version-history-prs
Check the output of the Sphinx build at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html

Add version history for 5.2.2 release

---

components/xsd-fu/templates-cpp/OMEXMLModelObject.template
cpp/cmake/BoostChecks.cmake
cpp/lib/ome/test/io.h
cpp/lib/ome/xml/model/OriginalMetadataAnnotation.cpp
docs/doxygen/ome-xml.dox.cmake

See https://github.com/ome/ome-cmake-superbuild/pull/93

Boost: Drop support for old versions

---

ant/toplevel.xml

Copy whats-new file to bftools zip as is, but renamed to NEWS.rst
See #2576

Add a NEWS file to the bftools zip

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/micro-manager.txt
docs/sphinx/formats/olympus-scanr.txt

See https://trello.com/c/9qBOB08S/26-additional-format-version-ranges
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/micro-manager.html and https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/olympus-scanr.html

Add max supported versions for MicroManager& ScanR

---

docs/sphinx/about/index.txt
docs/sphinx/developers/java-library.txt

See https://trello.com/c/nuexeTkT/16-versioning-documentation-page
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/index.html

Add versioning policy to docs

---

cpp/cmake/FindBoost.cmake

Pull latest version from cmake upstream.  Adds support for Boost 1.62.

cmake: Update FindBoost for Boost 1.62

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

ref: http://trac.openmicroscopy.org/ome/ticket/13290
Please use the code pasted in the ticket in matlab to check if the seriesMetadata is populated.
And also with FIJI/ImageJ to check if the original metadata table is populated appropriately for all the planes/series.
@melissalinkert @sbesson : As always comments on the code, would be really helpful.

Bio-Formats: CZIReader : Add series metadata,populate position list

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This PR should merge the current `develop` branch into `dev_5_3` and fix the conflicts on all the `pom.xml` (accepting the 5.3.0-SNAPSHOT and confirming the deletion of the dropped ones).
In addition to keeping the CI jobs green, this should allow the `dev_5_3` branch to be mergeable into `develop` again when the work gets reintegrated.

Merge develop into dev_5_3

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/orF7zi5d/20-version-history-prs
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.3-staging/about/whats-new.html

Add m1 history for 5.3.0

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/perkinelmer-ultraview.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/461/warnings3Result/
Hunting around their website, this is the only alternative I could find, assume it's not on their current product list anymore.

Fix ultraview link

---

docs/sphinx/users/octave/index.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/482/warnings3Result/
This should make the build green again.

Fix octave docs link

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/KK3DJFbE/20-version-history-prs
I've maybe summarised too much and missed details that are useful for devs, happy to expand if so.
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.3-staging/about/whats-new.html

m2 version history

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

* Read refractive index from header
* Set refractive index in MetamorphReader

Read refractive index from MetaMorph headers (#1)

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This will revert to the old scanning logic for finding offsets if the chunkmap has missing entries in the middle of the map, irrespective of the order in which entries are stored in the file.  For example, a file with only two entries of ```ImageDataSeq|0``` and ```ImageDataSeq|2``` would trigger this PR's changes, but a file with ```ImageDataSeq|0```, ```ImageDataSeq|2```, and ```ImageDataSeq|1``` would not.
A message is logged at ```WARN``` if the chunkmap is being discarded in this case, so it should be easy to see in repository test logs the full list of affected files.  At a minimum, ```nd2/benjamin/B2.nd2``` should use this change and pass all tests.

ND2: discard chunk map if there are obviously missing chunk map entries

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

This should initiate the development branch for the OME Files 0.3.0 metadata work

Bump version number to 6.0.0-SNAPSHOT

---

docs/sphinx/about/whats-new.txt

See https://github.com/openmicroscopy/bioformats/milestone/46?closed=1

Add version history for 5.3.2

---

pom.xml

Use current ome-model.
Testing: Check builds are green.

build: Bump ome-model.version to 6.0.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

added support for timestamps of lif files created with LAS AF 3.1 or
newer

Support current timestamp format

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

LAS X measures from the center of the top left pixel to the center of
the bottom right pixel

Correct Pixel Size

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This PR is a follow up to https://github.com/openmicroscopy/bioformats/pull/2722
To reproduce:
- Run a read write conversation with write `setWriteSequentially(true)` (for example you could modify one of the examples such as the new OverlappedTiledWriter https://github.com/dgault/bioformats/blob/fdac59c81b01f519b291714d38433b87fc2ba7a9/docs/sphinx/developers/examples/OverlappedTiledWriter.java)
- Verify that when opening the image that the image does not display correctly (tiles should all be the same)
To test:
- With the PR applied rerun the above test to verify that the image is converted successfully
- Ensure that the test works for different image types, eg various dimensions present, interleaved/non interleaved, different pixel types
- Ensure that builds are green and all unit tests …

TiffSaver - Enable tiled sequential writing

---

docs/sphinx/about/whats-new.txt

See https://github.com/openmicroscopy/bioformats/milestone/47?closed=1

Add version history for 5.3.3

---

docs/sphinx/about/whats-new.txt

Missed credit for 5.3.3
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/about/whats-new.html

Add credit for Michael Goelzer

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Backported from private PR.  For Metamorph datasets with multiple series, this should reduce size of the generated OME-XML/OMERO object graph by using a single ```Instrument``` for every ```Image```, instead of one ```Instrument``` per ```Image```.
I tested primarily with ```data_repo/curated/hms/HCT116.nd```, which has 32 series.  Without this PR, ```showinf -nopix -omexml HCT116.nd``` should show 32 ```Instrument```s, only the first of which has a ```Detector```.  Each ```Image``` should be linked to the ```Instrument``` with the same index (so only the first ```Image``` has a valid linked ```Detector```).
With this PR, the same test should show a single ```Instrument``` with a single ```Detector```, which is linked to every ```Image```.
It would also be good to perform the same pair of …

Metamorph: clean up instrument graph for datasets with multiple series

---

docs/sphinx/about/whats-new.txt

See https://github.com/openmicroscopy/bioformats/milestone/48?closed=1

Add version history for 5.3.4

---

components/formats-bsd/test/loci/formats/utests/out/OMETiffWriterTest.java
components/formats-bsd/test/loci/formats/utests/out/Plane.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java
components/formats-bsd/test/loci/formats/utests/out/WriterUtilities.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Initial PR opened for the purposes of judging the timing of automated testing on CI

OMETiffWriterTest - new unit tests for OMETiffWriter

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Discussed today with the Formats team, the nature of the changes already included and planned for the next release make it more suitable as a minor version increment (with no API addition).
/cc @dgault @melissalinkert @bramalingam @simleo

Bump Bio-Formats version to 5.4.0-SNAPSHOT

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Permits the import of idr0025 by excluding particular TIFF readers.

idr-0.3.1 release

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/49?closed=1

Add version history for 5.4.0

---

docs/sphinx/users/focalpoint/index.rst

See https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/646/warnings3Result/ this should make the build green again.
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.4-staging/users/focalpoint/index.html

Update focalpoint link

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Opening to include https://github.com/openmicroscopy/bioformats/pull/2789 in the IDR build.

Bump version to 0.3.2 (IDR groupId)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/cellomics.rst
docs/sphinx/formats/incell-3000.rst

Documents https://github.com/openmicroscopy/data_repo_config/pull/188 to add links to public sample images to the BF format docs.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.4-staging/formats/cellomics.html and https://www.openmicroscopy.org/site/support/bio-formats5.4-staging/formats/incell-3000.html

Sample links for incell 3000 & cellomics

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Primarily for testing https://github.com/openmicroscopy/bioformats/pull/2827

Bump to 0.3.3

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/ColumbusReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

* Rebases https://github.com/openmicroscopy/bioformats/pull/2413 onto develop
* Adds fixes for `ColumbusReader.{isThisType,initFile}`
* Adds a Columbus-specific exception to `FormatReaderTest.testIsThisType`

Columbus export read (develop)

---

docs/sphinx/conf.py.in
docs/sphinx/themes/globalbftoc.html

Updates the documentation configuration to point at the latest 5.5 downloads/API.

Use latest Bio-Formats 5.5 redirects

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/51?closed=1

Add version history for 5.5.0

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This prevents an infinite loop when a resolution in one of the pyramids
is missing, i.e. the pyramids are of different sizes/depths.
See https://trac.openmicroscopy.org/ome/ticket/13320 and
https://trello.com/c/S60YCf0H/95-fiji-zeiss-czi-axioscan-fails-to-open
To test, use the files from QA 17539 and QA 17711 (https://github.com/openmicroscopy/data_repo_config/pull/198).  Without this PR, ```showinf -nopix``` should enter an infinite loop around line 972.  With this PR, ```showinf -nopix``` should complete and ```showinf -nopix -noflat``` should show that the number of pyramids matches the number of scenes shown in ZEN.  The individual images should also match what is shown in ZEN, except for some of the larger resolutions which will show black pixels to indicate a missing tile instead of …

CZI: fix pyramid resolution indexing for pyramids of different depths

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/52?closed=1

Add version history for 5.5.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml
tools/bump_maven_version.py

Bump in order to release that state as of ome2017.
cc: @sbesson

Bump to 0.4.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Unlikely to be needed until post POTN

Bump to 0.3.4-SNAPSHOT

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/53?closed=1
I have not yet included entries for open PR's: https://github.com/openmicroscopy/bioformats/pull/2868 https://github.com/openmicroscopy/bioformats/pull/2867 https://github.com/openmicroscopy/bioformats/pull/2658

Add version history for 5.5.2

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

This adds a new getNextTag(RandomAccessInputStream, boolean) signature,
which allows the caller to control whether or not the core metadata can
be altered.
See https://trello.com/c/apvieSPU/154-bug-dicom-reader and https://github.com/openmicroscopy/data_repo_config/pull/212
Without this change and with https://github.com/openmicroscopy/data_repo_config/pull/212, the subset job will fail on ```curated/dicom/public/samples``` as described in the config PR comments.  With this change, the subset job and full repository jobs should pass.

DICOM: do not allow core metadata to be changed in isThisType

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/54?closed=1

Add version history for 5.5.3

---

components/formats-bsd/src/loci/formats/in/FilePatternReader.java

Rebases all `FilePatternReader` changes introduced in the `metadata` branch.

Rebase FilePatternReader changes from metadata

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

For releasing https://github.com/openmicroscopy/bioformats/pull/2892

Bump to 0.4.1

---

docs/sphinx/formats/quicktime-movie.rst

Attempting to fix link in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-latest-docs/395/warnings3Result/

Fix broken QTFF link

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Rebases `MetamorphReader` and `MinimalTiffReader` changes from #2151 and #2411.

Rebase Metamorph changes from metadata

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/55?closed=1

Add version history for 5.6.0

---

components/formats-bsd/src/loci/formats/in/FlowSightReader.java
components/formats-gpl/src/loci/formats/in/PQBinReader.java

Catch exceptions in isThisType

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See https://trello.com/c/RsDUMigo/160-nd2-chunkmap-issue
To test, use the file in QA 17785.  Without this change, ```showinf -nopix``` should report 31 planes and ```showinf -nopix -option nativend2.chunkmap false``` should correctly report 2000 planes.
With this change, ```showinf -nopix``` should report 2000 planes.  The issue was that the chunkmap lengths are not recorded as expected in this file; ```showinf -nopix -debug``` shows that the position and length are the same for all ```ImageDataSeq``` (== single image plane) entries:
```
ND2 ChunkMapEntry<ImageDataSeq|999@528003072(528003072)>
ND2 ChunkMapEntry<ImageDataSeq|998@527474688(527474688)>
ND2 ChunkMapEntry<ImageDataSeq|997@526946304(526946304)>
ND2 ChunkMapEntry<ImageDataSeq|996@526417920(526417920)>
ND2 …
```

ND2: fix bug in offset calculations when chunkmap is used

---

docs/sphinx/about/whats-new.rst

See https://github.com/openmicroscopy/bioformats/milestone/56?closed=1 for list of included PRs.

Add version history for 5.7.0

---

docs/sphinx/about/whats-new.rst

For a full list of included PRs see https://github.com/openmicroscopy/bioformats/milestone/57?closed=1

Add version history for 5.7.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Bump IDR Bio-Formats version to 0.4.2-SNAPSHOT

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/quicktime-movie.rst
docs/sphinx/users/iqm/index.rst

Should hopefully make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green for the release

Fix remaining link issues

---

docs/sphinx/about/whats-new.rst

For a full list of included PRs see https://github.com/openmicroscopy/bioformats/milestone/59?closed=1

Add version history for 5.7.2

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

This provides better support for large images that are stored as a
single uncompressed tile with multiple interleaved channels.  Requesting
a smaller tile should no longer result in the entire image being read.
To test, use ```data_repo/curated/tiff/big-images/8kx8k.tif```.  Without this change, ```showinf -crop 0,0,512,512 8kx8k.tif``` should throw an ```OutOfMemoryError```.  With this change and no adjustment to memory settings, the same test should result in a 512x512 tile being displayed.
I would expect memo files and automated tests to be unaffected.

TIFF: expand single tile special case to include interleaved multi-channel images

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/amira-mesh.rst

See https://trello.com/c/SJxl2ZCF/20-expose-new-public-amira-dataset

Expose AmiraMesh samples in docs

---

docs/sphinx/about/whats-new.rst

For a full list of included PRs see https://github.com/openmicroscopy/bioformats/milestone/60?closed=1

Add version history for 5.7.3

---

components/formats-bsd/src/loci/formats/in/NRRDReader.java

This allows for the case when the file itself is uncompressed, but the pixels block after the header is a single GZIP stream.  The implementation is modeled after a similar feature in ```ICSReader```.
To test, use ```data_repo/curated/nrrd/samples/gzip/dt-helix.nrrd.gz```, which was generated from ```data_repo/curated/nrrd/samples/dt-helix.*```.  Without this change, ```showinf -separate -normalize dt-helix.nrrd.gz``` should throw:
```
Exception in thread "main" loci.formats.UnsupportedCompressionException: Unsupported encoding: gzip
at loci.formats.in.NRRDReader.openBytes(NRRDReader.java:175)
at loci.formats.FormatReader.openBytes(FormatReader.java:886)
at loci.formats.ImageReader.openBytes(ImageReader.java:441)
at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
at …
```

NRRD: add support for GZIP pixel stream contained within a .nrrd file

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Required for the upcoming [IDR0035 study](https://trello.com/c/juTpMw9a/8-idr0035-bbbc021) /cc @bramalingam

IDR Bio-Formats 0.4.2

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

As a follow up to https://github.com/openmicroscopy/bioformats/pull/2950, this PR stanardises the formatting in the OBFReader to bring it inline with other readers and https://docs.openmicroscopy.org/bio-formats/5.7.3/developers/code-formatting.html
There are no functional changes in this PR, only formatting.
To test:
- Builds and tests should remain green

OBFReader: Use Java variant of K&R braces and remove white space

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nrrd.rst

See https://trello.com/c/aKhTXS7n/31-nrrd-public-samples-and-documentation

Add links to public NRRD samples

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

ref: https://trello.com/c/dqTlLuXf/637-serge-pelet-single-cell-data#comment-5a783cf80e00f887aa369c3f
1) Test via Fiji, Command line tools and check if the file opens appropriately via Bio-Formats.
Without this PR you should get an exception (as shown in the trello card).
2) Check if the subset job listed below is green.
@sbesson

MicroManagerReader: Minor fix to handle metadata block closing

---

docs/sphinx/about/whats-new.rst

For a full list of included PRs see https://github.com/openmicroscopy/bioformats/milestone/58?closed=1&page=1

Add version history for 5.8.0

---

docs/sphinx/conf.py.in

Implements https://github.com/openmicroscopy/ome-internal/pull/381 for the BF docs build for the 5.8.x releases

Improve linkchecker & ignore sourceforge links

---

components/formats-bsd/src/loci/formats/in/NRRDReader.java

See http://teem.sourceforge.net/nrrd/format.html#spacedirections
Backported from a private PR.  This isn't critical for 5.8.0 and should be safe for a patch release, so is fine to push to 5.8.1+ if needed.
To test, use the dataset in ```data_repo/curated/nrrd/public/glencoe/version4```.  Without this change, ```showinf -nopix -omexml``` should not show any values for ```PhysicalSizeX```, ```PhysicalSizeY```, or ```PhysicalSizeZ```.  With this PR, all three should be set and should be 0.5, 0.5, and 2.0 microns respectively.  Existing datasets should be unaffected.

NRRD: support "space directions" and "space units" fields added in version 4

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Bump IDR Bio-Formats version to 0.4.4-SNAPSHOT

---

docs/sphinx/about/whats-new.rst

For a full list of included PRs see https://github.com/openmicroscopy/bioformats/milestone/61?closed=1

Add version history for 5.8.1

---

components/formats-bsd/src/loci/formats/in/JPEGReader.java
components/formats-bsd/src/loci/formats/services/JPEGTurboServiceImpl.java

```TileJPEGReader```/```JPEGTurboServiceImpl``` rely upon restart markers to read tiles without opening the whole image.  If restart markers aren't present, then ```DefaultJPEGReader```/ImageIO does a better job of decoding.
See https://trello.com/c/sRIQUQrr/206-jpg-issue-when-reading-full-slide-dec and https://trello.com/c/BzUB5Fuw/196-jpegreader-turbojpeg-failure-memory-usage-pixel-data
To test, use the two files in ```data_repo/curated/jpeg/human-embryology-2018-01-04``` and ```data_repo/curated/jpeg/darwinjob```.  Without this PR, ```showinf``` on each should show a mostly gray image as shown in one of the original bug reports: https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8393&p=18693&sid=098fb8ec2af6a4eff1dfc6562fa41fb1#p18693
With this PR, ```showinf``` should …

JPEG: use DefaultJPEGReader for big images with no restart markers

---

.appveyor.yml

See https://central.sonatype.org/articles/2018/May/04/discontinue-support-for-tlsv11-and-below/ for more details

Remove Java 7 from Appveyor matrix

---

.appveyor.yml
.travis.yml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
pom.xml

See https://github.com/ome/bio-formats-build/pull/22

Build updates

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

See https://trello.com/c/nik6LmGE/256-deltavision-with-more-than-5-channels and #3120.
To test, use the .rcpnl file from QA 21574.  Without this PR, ```showinf RC_SevenChannelScan.rcpnl``` should throw an ```ArrayIndexOutOfBoundsException``` as noted in #3120.  With this PR, the same test should not throw an exception, and should result in 7 channels being read.  A valid and plausible wavelength (in nm) should be present in original metadata and OME-XML for all 7 channels.  The TIFF file in QA 21574 should match the first image when flipped horizontally (expected since the DV reader flips planes to account for the origin being in the lower-left corner).
I think we had established that adding new ```static final``` variables doesn't impact memo files, but it might be a good idea to …

Deltavision: update to detect up to 12 channels

---

components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/LEOReader.java
components/formats-gpl/src/loci/formats/in/OIRReader.java

Includes all changes from https://github.com/openmicroscopy/bioformats/compare/v5.9.0...v5.9.1 into the `east` integration branch

Merge 5.9.1 into east

---

components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-bsd/src/loci/formats/in/AVIReader.java
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/GatanReader.java
components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Merge changes from https://github.com/openmicroscopy/bioformats/releases/tag/v5.9.2 into the `east` branch.
Together with the corresponding configuration changes this should reduce the false  positives in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-repo/

Merge v5.9.2 into east

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Also adds a ```testUnflattenedSaneOMEXML``` to check for usable OME-XML when
resolution flattening is disabled.  See https://trello.com/c/j6HbJibe/237-tests-check-image-count-matches-series-count
To test, verify that build failures are not introduced.  To check that the test will fail when appropriate, modify one of the readers to create one OME-XML ```Image``` per resolution when resolutions are not flattened (e.g. around https://github.com/openmicroscopy/bioformats/blob/east/components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java#L360).  ```test-automated``` on the affected reader's folder(s) should then fail.

Check series count vs OME-XML Image count

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/KLBReader.java

This reader is for the Keller Lab Block file type and is based on https://bitbucket.org/fernandoamat/keller-lab-block-filetype/overview
Details of the image header and image IO can be found at https://bitbucket.org/fernandoamat/keller-lab-block-filetype/src/8e3c39b75022/src/?at=master
This PR is a follow up to the prototype reader which was being tested in https://github.com/openmicroscopy/bioformats/pull/3150

Add new KLB Reader

---

components/formats-gpl/src/loci/formats/in/ZeissZVIReader.java

See https://trello.com/c/rgUGN9Ll/187-zvi-windows-performance-issuefiji
This reuses each plane's ```RandomAccessInputStream``` when possible, so that the stream is not reopened many times when the same plane (or tiles from the same plane) are being read.  Opening streams is more expensive than usual for ZVI files, as it typically requires assembling many non-contiguous blocks from the internal filesystem-like POI structure.
To test, use the ```test.zvi``` file from QA 21711.  Without this PR, open the file in ImageJ and verify that it takes several minutes for images to be displayed.  Restart ImageJ and open the file again; the performance should be similar (i.e. OS and disk-level caching have a negligible effect).
With this PR, the same test should result in a noticeably faster opening …

ZVI: reuse stream for sequential calls to openBytes on the same plane

---

components/formats-gpl/src/loci/formats/in/KLBReader.java

This is a follow up to the original KLB PR which addresses the issue discussed in https://github.com/IDR/idr0044-mcdole/issues/1

KLB: Allow for flexible channel naming

---

.appveyor.yml

Update to match Travis, by using JDK11 rather than 10.
Testing: Check builds remain green.

ci: appveyor: Test with JDK11

---

components/bio-formats-tools/src/loci/formats/tools/TiffComment.java
components/formats-bsd/src/loci/formats/tools/EditTiffG.java

* Deprecate method not allowing to close resource
* Add method to close resource
See https://trello.com/c/NEWizoBO/90-tiffparser-leaking-resource

Resources tools

---

components/bio-formats-plugins/src/loci/plugins/config/ConfigWindow.java
components/bio-formats-plugins/src/loci/plugins/config/InstallWizard.java
components/bio-formats-plugins/src/loci/plugins/shortcut/ShortcutPanel.java

Make sure all resources are always closed

Formats plugins review

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13247
If minimum and maximum pixel values are present in an InCell .xdce file, then they will be parsed and stored in the reader's ```MetadataStore``` if it is an instance of ```IMinMaxStore``` (expected for OMERO imports).  This should reduce min/max calculation time and thereby improve import performance.
With this PR, ```showinf -trace -minmax``` on an .xdce that defines min/max values should show ```TRACE``` logging indicating that min and max values are parsed, and these should match the min and max values reported by the ```-minmax``` flag.  These values should also match the minimum and maximum reported by ```showinf -minmax``` without this PR (i.e. the values have not changed).
I was testing with the …

InCell: parse min and max values from .xdce file

---

components/bio-formats-tools/src/loci/formats/tools/XMLValidate.java

Add methods to validate files
I have not modified the returned value of the ``process`` method
Background https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8623&p=20270#p20270

Validate xml

---

components/formats-api/src/loci/formats/readers.txt

https://github.com/openmicroscopy/bioformats/pull/3250 is being moved to an external repository

Add external URLReader

---

components/formats-gpl/src/loci/formats/in/SVSReader.java

Backported from a private PR.  See https://trello.com/c/zewt9Ke4/50-svs-z-stack-support
To test, use ```/uod/idr/repos/curated/svs/converted/z-stack/PHAS 01.svs```.  As noted in the corresponding readme, this was converted from an existing .ndpi file using Aperio ImageScope (a screenshot of the .svs in ImageScope is in the same directory).  With this PR, ```showinf -noflat PHAS\ 01.svs``` should show 3 resolutions with ```SizeZ = 4``` plus 2 extra series for the label and macro images.
When multiple Z sections are present, the expected IFD ordering is:
- largest resolution (r = 0), Z= 0
- extra ignored image (see #3137)
- r = 1, Z = 0
...
- r = pyramid depth - 1, Z = 0
- r = 0, Z = 1
...
- r = pyramid depth - 1, Z = 1
...
- r = pyramid depth - 1, Z = SizeZ - 1
- label image
- macro image …

SVS: add support for multiple Z sections

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

See https://trello.com/c/dQfCgPyX/79-fakereader-wellsamplepositions
To test, use a .fake file with a .fake.ini that specifies plane positions and SPW data.  For example:
```
$ touch test.fake
$ cat test.fake.ini
plates=2
plateRows=1
plateCols=3
fields=2
[series_0]
PositionX_0 = -0.5
PositionXUnit_0 = mm
[series_1]
PositionX_0 = 0.25
PositionXUnit_0 = mm
[series_2]
[series_3]
[series_4]
[series_5]
PositionY_0 = 100
PositionYUnit_0 = mm
[series_6]
PositionX_0 = 15
PositionXUnit_0 = nm
```
Verify that ```showinf -nopix -omexml test.fake``` populates both ```Plane``` and ```WellSample``` positions, and that the series tables map to the correct ```Plate```/```Well```/```WellSample``` (the ```WellSample``` ```Index``` should match the series index).  Default positions are set via …

Fake: populate WellSample positions using Plane data (if present)

---

pom.xml

See https://github.com/ome/ome-common-java/blob/v6.0.0/NEWS.md for a list of changes

Bump ome-common component to version 6.0.0

---

pom.xml

For inclusion in Bio-Formats 6.0.0

Bump to ome-model 6.0.0

---

pom.xml

See https://github.com/ome/ome-common-java/blob/b8309d850fcc8ee46ffd5df6dd91e5cc8c933879/NEWS.md for details

Bump ome-common to 6.0.1

---

components/formats-gpl/src/loci/formats/in/LiFlimReader.java

I have made an adaptation on LiFLIMReader.java that now checks for UNINT12 Data and unpacks this to 16 bitt data.
It also checks if there is a dark image, If true, it will be appended to the Dataset.

Support for packed UNINT12 datatype

---

components/formats-api/src/loci/formats/ImageReader.java

Small programming errors in potential readers (e.g.
a NullPointerException during isThisType) can potentially
cause a file of a different type to become unreadable.
ImageReader should catch all such exceptions and considers
readers that throw such exceptions invalid.
fix gh-3343

Make ImageReader defensive against reader errors

---

pom.xml

Includes https://github.com/ome/ome-common-java/pull/43

Bump ome-common to 6.0.2

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/BDVReader.java

BDVReader for the current OME Model, based on https://arxiv.org/pdf/1412.0488.pdf
XML file is read and parsed to locate h5 file and a number of parameters.
H5 file is then read using the jhdf library.
Currently only h5 files supported.

Add new BDVReader

---

pom.xml

See https://github.com/ome/ome-common-java/blob/v6.0.3/NEWS.md

Bump org.openmicroscopy:ome-common to version 6.0.3

---

pom.xml

As a follow up to https://github.com/ome/bioformats/pull/3414
Includes the PR https://github.com/ome/ome-codecs/pull/15

Bump ome-codecs component to version 0.2.5

---

pom.xml

See https://github.com/ome/ome-common-java/blob/v6.0.4/NEWS.md  for the list of changes especially https://github.com/ome/ome-common-java/pull/48

Bump ome-common version to 6.0.4

---

components/bio-formats-plugins/src/loci/plugins/config/SpringUtilities.java

I updated the SpringUtilities.java.

FixIssue#3464:A potential NullPointerException bug

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes #3501
This should fix the issue raised in https://github.com/ome/bioformats/issues/3501
When testing that bug I also noticed that the Detector ID's being used could be more accurate and also that some of the values for a given detector are being copied over to the next even if they dont exist in that later detector. 
A sample file was provided in the GitHub Issue which I will configure before review

CZI: Detector fixes

---

components/formats-bsd/src/loci/formats/services/JPEGTurboServiceImpl.java

Fixes #3059
Without this fix, the bytes between the last restart marker and the end of the original JPEG
stream were ignored.
Without this PR, ```showinf hamamatsu/public/manuel/test3-FITC 2 (485).ndpi``` will show a horizontal gray stripe at the bottom of the image approximately 8 pixels high.  With this PR, the same test should show no stripe.
I'd expect this to be safe for a patch release, but some configuration updates may be necessary depending upon the results of tonight's repo test.

JPEG service: fix off-by-one when using restart markers to build a tile's stream

---

components/test-suite/src/loci/tests/testng/Configuration.java

The plane read time configuration didn't correctly check that the plane size is smaller than 2 GB in addition to fitting into available memory.  This resulted in ```IllegalArgumentException```s when setting ```-Dtestng.memory``` higher than the default value.
The problem was observed when running ```ant -Dtestng.memory=2g ... test-config``` to regenerate configurations for .ndpi files.  The change in this PR was used to create https://github.com/openmicroscopy/data_repo_config/pull/447.

Fix test-config on datasets with planes larger than 2 GB

---

components/formats-gpl/src/loci/formats/in/BDVReader.java

Fixes https://github.com/ome/bioformats/issues/3567
This issue was raised with the idr0048 dataset mentioned in the above issue. This was caused by physical size data being written for all series even in the event of the `noflat` being used.
Without this PR and noflat:
```
<Image ID="Image:0" Name="P_t00000, W_s00_0">
<Pixels BigEndian="false" DimensionOrder="XYZTC" ID="Pixels:0" Interleaved="false" PhysicalSizeX="1.0" PhysicalSizeXUnit="pixel" PhysicalSizeY="1.0" PhysicalSizeYUnit="pixel" PhysicalSizeZ="1.0" PhysicalSizeZUnit="pixel" SignificantBits="16" SizeC="3" SizeT="1" SizeX="19120" SizeY="13350" SizeZ="91" Type="uint16">
<Channel ID="Channel:0:0" SamplesPerPixel="1">
<LightPath/>
</Channel>
<Channel ID="Channel:0:1" SamplesPerPixel="1">
<LightPath/>
</Channel>
<Channel …
```

BDV: Correct series index for no flat physical sizes

---

components/formats-gpl/src/loci/formats/in/SISReader.java

This PR is implementing the recommended changes from https://github.com/ome/bioformats/issues/3598
Opening to test the impact on the data repo
Fixes #3598

SIS: Trim imageName and channelName

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

See sample plate in ```cellomics/samples/sparse-plate```.  With this PR, ```showinf -nopix -omexml``` should show a ```Plate``` structure that matches the acquired wells:
* E3, E4, E6, E7
* F3, F4, F6, F7
* M3, M4
* N3, N4
Without this PR, the ```Plate```/```Well```/```Image``` mappings won't match what was acquired, which leads to errors when importing in OMERO.
Tests should remain green, and I would expect this to be safe for a patch release.

Cellomics: more sparse plate fixes

---

components/formats-api/src/loci/formats/readers.txt

Add external Zarr Reader for testing reader prototype

Add ZarrReader as external reader in readers.txt

---

pom.xml

See https://github.com/ome/ome-model/blob/v6.2.2/NEWS.md for the list of changes.

Bump ome-model version to 6.2.2

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping manually as job is failing (https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/)

Update POM version numbers to 6.6.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping manually as job is failing (https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/)

Update POM version numbers to 6.7.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java
components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/src/loci/formats/in/ScanrReader.java
components/formats-gpl/src/loci/formats/in/VentanaReader.java

See also https://github.com/ome/bio-formats-documentation/pull/202

Register remaining reader options via getAvailableOptions()

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Update POM version numbers to 6.7.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version to 6.8.0-SNAPSHOT

Update POM version numbers to 6.8.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This is a test to attempt to fix the repository test failures seen in https://merge-ci.openmicroscopy.org/jenkins/job/BIOFORMATS-test-repo/924/

ND2: Reset imageMetadataLVProcessed if no order present

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version to 6.8.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Update POM version numbers to 6.8.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version back to 6.9.0-SNAPSHOT after 6.8.1 release

Bump version to 6.9.0-SNAPSHOT

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java

Like showinf, bfconvert is now able to swap dimensions' order using a 
-swap option. For instance -swap XYZTC

bfconvert support -swap option

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

@dgault this is a workaround for the issue at https://forum.image.sc/t/warning-error-loading-thumbnail-for-series-1-for-series-2-and-3/62793
Basically it ignores zlib errors that happen right after all bytes have been decompressed.
It might be preferable to still output some warning in this case.
Is there a standard / preferred way to generate a user visible warning from a Bio-Formats reader?

OBF: Suppress deflate errors when all expected output bytes are available

---

components/formats-bsd/src/loci/formats/services/JPEGTurboServiceImpl.java

This should reduce the amount of memory needed to read large JPEGs, in particular the contents of .ndpi files.  Without this PR, picking an .ndpi file and running something like:
```
$ export BF_MAX_MEM=100m
$ showinf -crop 24000,12000,1024,1024 file.ndpi
```
would work, but setting a lower value for ```BF_MAX_MEM``` would result in an ```OutOfMemoryError``` (the precise limit depends a bit on the file, but ~100MB is about right from what I have seen).  With this PR, setting ```BF_MAX_MEM``` to a much lower value (on the order of 40-50% of the original limit) should work without throwing an ```OutOfMemoryError``` or displaying an incorrect image.
I would not expect tests to fail or memo files to be impacted.  I would suggest testing with QuPath or similar to …

Reduce memory required to read tiles from large JPEGs

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping the poms to 6.9.0 for release

Bump version to 6.9.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version to latest SNAPSHOT

Bump version to 6.9.1-SNAPSHOT

---

.github/workflows/maven.yml

Do not run deploy workflow on forks

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Fixes #3388.
If the file doesn't not contain all of the requested plane, this will log but not throw `IOException` and `IllegalArgumentException` when reading bytes. If the file does contain the whole plane, these exceptions will be caught and re-thrown (so no change in behavior).
We could change the behavior of `FormatReader.readPlane(...)` instead to not throw an exception when skipping or reading past the end of the file, but I'm not sure that's always what we want (and it would impact almost all readers).
This won't affect memo files, and shouldn't affect tests.

Deltavision: allow partial planes to be read from truncated files

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping the poms to 6.9.1 for release

Bump version to 6.9.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bump version to 6.10.0-SNAPSHOT

Bump version to 6.10.0-SNAPSHOT

---

pom.xml

To match the version bumps in other repos.

logback version bump from 1.2.0 to 1.2.9

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version to next SNAPSHOT release

Bump version to 6.10.1-SNAPSHOT

---

pom.xml

Bumping slf4j dependency to 1.7.30 to align with OMERO

Bump slf4j dependency to 1.7.30

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version for release of 6.10.1

Bump version to 6.10.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping to latest SNAPSHOT version

Bump version to 6.10.2-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

The intended use case is something like:
```
$ bfconvert "test%series=10.fake" output_s%s.ome.tiff
$ showinf -nogroup output_s9.ome.tiff
```
https://github.com/glencoesoftware/raw2ometiff/pull/80 is related.
Without this change, `showinf` would have thrown an exception. With this change, it should detect a single series which corresponds to the chosen file.
All of the changes are limited to the case where the dataset has multiple files and file grouping has been turned off explicitly. I would expect this to be safe for a patch release, but don't have strong feelings about including in 6.10.1.
/cc @DavidStirling

OME-TIFF: allow individual file reading for datasets with one file per series

---

components/formats-bsd/src/loci/formats/tools/AmiraParameters.java

This is an initial test PR for an issue reported on https://forum.image.sc/t/error-importing-am-files-bio-formats/29358
A sample file is expected via ftp which will be used for further testing.

AmiraParameters: Use warning for empty key

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version for release of 6.11.0

Bump version to 6.11.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping to latest SNAPSHOT version

Bump version to 6.11.1-SNAPSHOT

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version for release of 6.11.1

Bump version to 6.11.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping to latest SNAPSHOT version

Bump version to 6.12.0-SNAPSHOT

---

.github/workflows/ant.yml
.github/workflows/maven.yml

see also https://github.com/ome/action-gradle/pull/1
Check that the build via GHA is green

upgrade setup-java action. Current version uses set-output

---

components/bundles/bioformats_package/pom.xml

As a follow up to the issues discover with the bioformats_package ant tasks in https://github.com/ome/bioformats/pull/3942

BF package pom: Add logback as optional dependency

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bump pom versions to 6.12.0-m1

Bump version to 6.12.0-m1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bumping version to latest release

Bump version to 6.12.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Bump versions to next SNAPSHOT

Bump version to 6.12.1-SNAPSHOT

---

components/autogen/src/format-pages.txt

Change link to Imaris 5.5 file spec

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

This reads the expected number of compressed bytes into an array, then attempts to decompress the array. This will fail faster on invalid tiles than passing the entire .ets file to a codec, which may attempt to read the entire file in search of the start or end of the compressed block.
This is meant to address a very specific case where a memo file is generated and then the underlying files are changed. In certain circumstances, particularly if the new files are smaller than the old files, this can cause `openBytes` to not return (or at least, be very very slow). This case is not expected to really work, but should at least fail faster.
This is a little tricky to test, but something like the following (without this PR) should show the issue:
```
$ showinf …
```

vsi: slightly rework tile decoding to fail faster on invalid tiles

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

OperettaReader: Do not skip the first filename when validating series

---

components/formats-gpl/src/loci/formats/in/NiftiReader.java

May improve performance for gzip-compressed files. See #3607.
This seems to improve `openBytes` performance during `showinf`, and tests continue to pass locally. This should be OK for a patch release, if deemed useful (otherwise feel free to close).
`showinf` or really anything else is still going to be pretty slow to initialize `.nii.gz` files though. A lot of that comes down to `GZipHandle` needing to calculate the length of the uncompressed stream each time a new handle is opened, which happens several times during type checking in `ImageReader`. The only way to do the length calculation is to skip through the stream and count the number of bytes, then reset. I looked into ways to make better use of the gzip format's internal metadata, but unfortunately the only uncompressed size …

NIFTI: reduce number of backwards seeks
