cpp/lib/ome/bioformats/MetadataMap.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/MetadataTools.h
cpp/test/ome-bioformats/metadatamap.cpp
cpp/test/ome-bioformats/metadatatools.cpp

Additional MetadataTools and related additions.  These are all fairly straightforward changes.
- Use ConvertMetadata
- Add DimensionOrder creation from string
- Add merge/keys methods to MetadataMap
--------
Testing:
No users of ConvertMetadata yet, and no unit tests.  The latter two changes have unit tests.

C++: Additional metadata additions

---

components/formats-bsd/src/loci/formats/codec/LZWCodec.java

This is the same as gh-1497 but rebased onto dev_5_0.
----
See http://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7705.  For each of the three files linked in the forum thread, the values of the last column of pixels should be compared against the last column of pixels returned by ```imread``` in Matlab.  Without this change, each of the files should have a handful of rows for which the values differ; with this change, the values should match for all rows.
See also gh-1200.

LZW: fix one more off-by-one (rebased onto dev_5_0)

---

components/formats-bsd/src/loci/formats/FilePattern.java

This makes sure that file patterns are detected consistently, regardless
of how the file separator is escaped.
To test, run ```ant "-Dtestng.directory=\path\to\test_images_good\eps" test-automated``` on Windows without this PR, and verify that the ```SizeZ``` test fails.  With this PR, the same test should pass.
All builds are expected to remain green.  See also https://trello.com/c/0Rdx4AMl/113-nfs-on-windows

Fix FilePattern grouping Windows

---

components/autogen/src/gen-meta-support.sh
components/test-suite/bftest
docs/sphinx/users/comlinetools/index.txt
tools/bf.bat
tools/bf.sh
tools/bfconvert
tools/config.sh
tools/domainlist
tools/formatlist
tools/ijview
tools/mkfake
tools/showinf
tools/tiffcomment
tools/update_copyright
tools/xmlindent
tools/xmlvalid

As we'll run more and more into performance testing, standardizing the way we collect and curate profiling traces across the board will become crucial. Since some of this profiling will be performed on remote machines, a requirement on JVisualVM is certainly overkill.
This PR makes a simple proposal: having a `BF_PROFILE` flag for command-line tools which enables `hprof` profiling and outputs an `.hprof` file to be examined via GUI tools.
Couple of remarks/questions at this point:
- is `hprof` the best candidate here? see http://www.brendangregg.com/blog/2014-06-09/java-cpu-sampling-using-hprof.html for a discussion and I know @joshmoore had other ideas
- where is the best place for documenting this (as well as other command-line tools environment variables), I started working on …

Command line profiling

---

components/autogen/build.xml
components/formats-gpl/build.xml

In particular, this prevents documentation generation builds from
passing when the autogeneration did not succeed.
See gh-1513 and https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs-autogen/151/consoleText.  To test, verify that BIOFORMATS-5.1-merge-docs-autogen fails with this PR merged and before gh-1513 is fixed.
/cc @sbesson

Ant: add 'failonerror' everywhere the 'java' task is used

---

components/autogen/build.xml
components/formats-gpl/build.xml

This is the same as gh-1516 but rebased onto dev_5_0.
----
In particular, this prevents documentation generation builds from
passing when the autogeneration did not succeed.
See gh-1513 and https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-docs-autogen/151/consoleText.  To test, verify that BIOFORMATS-5.1-merge-docs-autogen fails with this PR merged and before gh-1513 is fixed.
/cc @sbesson

Ant: add 'failonerror' everywhere the 'java' task is used (rebased onto dev_5_0)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/leica-lif.txt

This should fix the broken link on the Leica LIF format page.

Fix link to Leica LAS AF Lite software

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/leica-lif.txt

This is the same as gh-1518 but rebased onto dev_5_0.
----
This should fix the broken link on the Leica LIF format page.

Fix link to Leica LAS AF Lite software (rebased onto dev_5_0)

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

The value of SignificantBits/```Bits per pixel``` shown by ```showinf``` should now match the value in the original file's OME-XML.
/cc @sbesson

Parse SignificantBits from OME-XML/OME-TIFF files

---

docs/sphinx/developers/commit-testing.txt

The original ```test-automated``` command will fail on Windows, but adding quotes around each ```-D``` argument should work.

Add note about running data tests on Windows

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/src/loci/formats/IFormatReader.java
components/formats-api/src/loci/formats/ImageReader.java
components/formats-api/src/loci/formats/Modulo.java
components/formats-api/src/loci/formats/ReaderWrapper.java
components/formats-bsd/src/loci/formats/ChannelMerger.java
components/formats-bsd/src/loci/formats/ChannelSeparator.java
components/formats-bsd/src/loci/formats/DimensionSwapper.java
components/formats-bsd/src/loci/formats/FileStitcher.java
cpp/lib/ome/bioformats/FormatReader.h
cpp/lib/ome/bioformats/FormatTools.cpp
cpp/lib/ome/bioformats/FormatTools.h
cpp/lib/ome/bioformats/Modulo.cpp
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatReader.h
cpp/lib/ome/test/main.cpp
cpp/lib/ome/test/test.h
cpp/test/ome-bioformats/formatreader.cpp
cpp/test/ome-bioformats/formattools.cpp
cpp/test/ome-compat/module.cpp

When implementing a modulo-aware viewer, it became quickly clear that computing dimension coordinates when using Modulo was a real pain.  It requires all calculations to be done by the user, which quickly gets quite annoying.  This PR implements Modulo-aware variants of getIndex and getZCTCoords in both FormatReader and FormatTools, and updates the dependent classes to use them.  This allows direct computation of the full ZCTmZmCmT sextuple from an index and vice-versa.  Here, the ZCT coordinates are modified to take the Modulo sizes into account, so the user can work easily using the effective ZCTmZmCmT ranges.
Outstanding question: getIndex overloads naturally due to having extra arguments.  getZCTCoords does not, so was supplemented with getZCTModuloCoords.  In FormatTools, the …

FormatReader/FormatTools Modulo improvements

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

This is the same as gh-1514 but rebased onto dev_5_0.
----
The value of SignificantBits/```Bits per pixel``` shown by ```showinf``` should now match the value in the original file's OME-XML.
/cc @sbesson

Parse SignificantBits from OME-XML/OME-TIFF files (rebased onto dev_5_0)

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

Also updates both copyright blocks to the current year.  See gh-1500.

OBF: add secondary OME copyright

---

components/formats-bsd/src/loci/formats/FilePattern.java

This is the same as gh-1509 but rebased onto dev_5_0.
----
This makes sure that file patterns are detected consistently, regardless
of how the file separator is escaped.
To test, run ```ant "-Dtestng.directory=\path\to\test_images_good\eps" test-automated``` on Windows without this PR, and verify that the ```SizeZ``` test fails.  With this PR, the same test should pass.
All builds are expected to remain green.  See also https://trello.com/c/0Rdx4AMl/113-nfs-on-windows

Fix FilePattern grouping Windows (rebased onto dev_5_0)

---

components/formats-bsd/src/loci/formats/in/ICSReader.java

If reopenFile() is not overridden, then the .ics file will always be
opened, even if it does not contain the pixel data.
Fixes http://trac.openmicroscopy.org/ome/ticket/12700.  To test, verify that importing ```test_images_good/ics/qdna1.ics``` into OMERO and viewing with Insight shows the same image as opening ```test_images_good/ics/qdna1.ics``` in ImageJ.

ICS: re-open the correct file when reading from a memo file

---

components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/turbojpeg/pom.xml
pom.xml

See http://trac.openmicroscopy.org/ome/ticket/11869.  To test, download and unzip the source Zip from BIOFORMATS-5.1-merge-build (after this PR is included) and verify that running ```./tools/test-build cppwrap``` in the source directory is successful (i.e. no ```Build failed``` message).
As this should make cppwrap work outside of Git, documenting the need to build within a Git tree should no longer be necessary.

Fix version detection when building outside of Git

---

components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/turbojpeg/pom.xml
pom.xml

This is the same as gh-1530 but rebased onto dev_5_0.
----
See http://trac.openmicroscopy.org/ome/ticket/11869.  To test, download and unzip the source Zip from BIOFORMATS-5.1-merge-build (after this PR is included) and verify that running ```./tools/test-build cppwrap``` in the source directory is successful (i.e. no ```Build failed``` message).
As this should make cppwrap work outside of Git, documenting the need to build within a Git tree should no longer be necessary.

Fix version detection when building outside of Git (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004988.html
To test this PR, check the samples files uploaded with the thread open correctly without throwing a `NumberFormatException` and that the full repository job stays green.

Prevent NumberFormatException in ZeissCZIReader

---

components/bio-formats-plugins/src/plugins.config

This is the same as gh-1528 but rebased onto dev_5_0.
----
Promote OME-TIFF format
Add option to the Save As menu
To test:
* Install or Update the ```bioformats_package```
* Check the ```OME-TIFF...``` option is available
* Select it and make sure the BF exporter dialog pops up.

Save As (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is the same as gh-1531 but rebased onto dev_5_0.
----
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004988.html
To test this PR, check the samples files uploaded with the thread open correctly without throwing a `NumberFormatException` and that the full repository job stays green.

Prevent NumberFormatException in ZeissCZIReader (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12692.  To test, verify that the ```NDFilter``` on ```Channel``` is ```0.5``` for test_images_good/dv/very_small.d3d.dv.  All builds should remain green.
/cc @will-moore

Deltavision: allow for ND filters stored as percent fractions

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

The metadata value's type is TiffRational, not double.
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004995.html.  To test, check the original metadata of the attached .tif file with this PR included.  Unlike the attached original metadata file, there should not be any very small floating point values.  In particular, keys such as ```Channel #0 Camera Bit Depth```, ```Channel #0 _MagNA_```, and ```Channel #0 _MagRI_``` should have much more reasonable values.

Metamorph: fix type of UIC1 tag 49 metadata

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See QA 10439.
To test, put the files from QA 10439 and QA 10442 in the same directory.  Open the .nd file (showinf, ImageJ, or OMERO) and verify that 15 planes are shown - 5 Z x 3 C.  Without this PR included, the same test should result in an exception as described in the QA issue.

Metamorph: reset timepoint count if timelapse was not performed

---

cpp/lib/ome/bioformats/VariantPixelBuffer.h
cpp/test/ome-bioformats/tiff.cpp
cpp/test/ome-bioformats/variantpixelbuffer.cpp

This method is an extremely slow and inefficient means to access single pixel values.  It was added for testing purposes, not intended for real use.  Adjust the tests to use direct access to `PixelBuffer` data via existing visitors, allowing its removal.
--no-rebase
----------
Testing: Unit tests should continue to pass.

cpp: bioformats: Remove VariantPixelBuffer at method

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This is the same as gh-1536 but rebased onto dev_5_0.
----
Fixes http://trac.openmicroscopy.org/ome/ticket/12692.  To test, verify that the ```NDFilter``` on ```Channel``` is ```0.5``` for test_images_good/dv/very_small.d3d.dv.  All builds should remain green.
/cc @will-moore

Deltavision: allow for ND filters stored as percent fractions (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This is the same as gh-1537 but rebased onto dev_5_0.
----
The metadata value's type is TiffRational, not double.
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004995.html.  To test, check the original metadata of the attached .tif file with this PR included.  Unlike the attached original metadata file, there should not be any very small floating point values.  In particular, keys such as ```Channel #0 Camera Bit Depth```, ```Channel #0 _MagNA_```, and ```Channel #0 _MagRI_``` should have much more reasonable values.

Metamorph: fix type of UIC1 tag 49 metadata (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This is the same as gh-1538 but rebased onto dev_5_0.
----
See QA 10439.
To test, put the files from QA 10439 and QA 10442 in the same directory.  Open the .nd file (showinf, ImageJ, or OMERO) and verify that 15 planes are shown - 5 Z x 3 C.  Without this PR included, the same test should result in an exception as described in the QA issue.

Metamorph: reset timepoint count if timelapse was not performed (rebased onto dev_5_0)

---

components/bio-formats-plugins/src/loci/plugins/in/Colorizer.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12548 and http://trac.openmicroscopy.org/ome/ticket/12656.
To test, verify that ```showinf``` or ImageJ show the same dimensions as NIS Elements Viewer for the following files:
* QA 9507
* QA 10100
* QA 10370
* QA 10366
The QA 10366 file should also be checked to verify that PhysicalSizeZ and the channel colors are set correctly (as described in the QA issue).  Builds are expected to remain green.

Another round of Nikon ND2 metadata issues

---

components/specification/samples/develop/2013-10to06-downgrade-fail-generic.ome
components/specification/samples/develop/2013-10to06-downgrade.ome
components/specification/transforms/2013-10-dev-5-to-2013-06.xsl
components/specification/transforms/units-conversion.xsl

XSLT changes which allow downgrading units to the standard representation. Some values are not yet convertible -- see https://github.com/openmicroscopy/bioformats/pull/1479#issuecomment-70631062 about the ongoing work.
There are currently no automated tests, but ideas for creating one are welcome. To check in the UI:
* import a file with a non-default unit (this can be done with a `.fake` if necessary)
* export the file applying a downgrade
* re-import the downgraded file and compare the values in the UI.
/cc @pwalczysko @jburel
----
--no-rebase

Updated XSLT for units conversion

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12110, http://trac.openmicroscopy.org/ome/ticket/12268, and http://trac.openmicroscopy.org/ome/ticket/8464.
Easiest way to test is with a .fake file:
```
export TEST_FILE='bfconvert-test&sizeZ=5&sizeT=4&sizeC=3.fake'
```
With this PR, the following should all throw an exception (without this PR, there is no error and no output file):
```
bfconvert -channel 3 $TEST_FILE bounds-check1.ome.tiff
bfconvert -z 5 $TEST_FILE bounds-check2.ome.tiff
bfconvert -timepoint 4 $TEST_FILE bounds-check3.ome.tiff
```
With this PR, the following should convert the middle Z section, for a total of 12 planes in the output file (without this PR, it will throw an exception):
```
bfconvert -z 2 $TEST_FILE middle-z.ome.tiff
```
Similarly, this should convert the …

bfconvert: fix indexing for z, timepoint, and channel flags

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java

Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12617.  To test, import the files from QA 10321 and verify that all Z sections (7 for the larger files, 1 for the smaller file) can be viewed without an exception in Blitz-0.log after pyramid generation completes.  Pyramids generated without this change should be read correctly as well, so reimport should not be strictly necessary if all files were previously imported into a develop server.
/cc @jburel, @zeb

TIFF: fix plane count calculation for pyramids with multiple planes

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java

Fixes http://trac.openmicroscopy.org.uk/ome/ticket/9805.  CellSens datasets (including test_images_good/cellsens) should now have PhysicalSizeX and PhysicalSizeY set for the largest resolution in each pyramid.  Smaller resolutions in the pyramid will not have physical sizes set, by design.

Parse physical pixel sizes from CellSens .vsi datasets

---

docs/sphinx/about/whats-new.txt

As usual, the date probably needs updating once we're closer to tagging.

Add version history for 5.0.7

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java
components/formats-gpl/src/loci/formats/in/NDPIReader.java

See files in team/atarkowska/virtual-microscope/VLE_for_edu/.  With this change, magnifications should be parsed and stored for NDPI files, and magnifications/physical pixel sizes should be set correctly for Leica SCN data (regardless of whether or not pyramid resolutions are flattened).  Note that there is also some cleanup of the Leica SCN reader to make it more maintainable going forward.
/cc @aleksandra-tarkowska

Fix NDPI and Leica SCN metadata issues exposed by Virtual Microscope

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

If physical positions are not present, this means that the PositionX and
PositionY values will be set to the relative positions in pixels.
See QA 10445.  Without this PR, PositionX and PositionY on Plane are not populated for the QA file.  With this PR, ```showinf -omexml``` or ImageJ with ```Display OME-XML metadata``` checked should show both values populated for every plane.
Opening in ImageJ with ```Stitch tiles``` checked will arrange the tiles in order according to PositionX and PositionY, so this can be used to verify that the positions are correct - just note that the tile overlap is intentionally not removed, so the resulting images will not have completely smooth transitions between tiles.

Zeiss CZI: set plane positions using pixel row/column values

---

components/formats-bsd/src/loci/formats/codec/JPEGCodec.java

This ensures that the red, green, and blue values do not overflow.
Fixes http://trac.openmicroscopy.org/ome/ticket/12680.  To test, import the file listed in the ticket into OMERO.  Without this PR, there should be odd cyan pixels (usually surrounding white artifacts); with this PR, there should be no odd cyan pixels and nothing obviously wrong with the images.
There will likely be a few test failures as a result of this, since it will change the plane hashes for some files.  I will update the hashes as needed once BIOFORMATS-5.1-merge-full-repository has run once with this PR included.

JPEG: fix calculations for YCbCr correction

---

docs/sphinx/about/whats-new.txt

This is the same as gh-1563 but rebased onto develop.
----
As usual, the date probably needs updating once we're closer to tagging.

Add version history for 5.0.7 (rebased onto develop)

---

components/test-suite/src/loci/tests/testng/TestTools.java
components/xsd-fu/templates-java/AggregateMetadata.template
components/xsd-fu/templates-java/DummyMetadata.template
components/xsd-fu/templates-java/FilterMetadata.template
components/xsd-fu/templates-java/MetadataStore.template
components/xsd-fu/templates-java/OMEXMLMetadataImpl.template

This removes a handful of methods that were deprecated in 5.0 (or earlier) and which are now unused.
See https://trello.com/c/iNieNBuZ/77-remove-deprecated-methods

Remove deprecated methods

---

components/xsd-fu/ez_setup.py
components/xsd-fu/python/ome/modeltools/generateds.py
components/xsd-fu/setup.py

With the latest release of PEP8, `import` needs to be at top-level. The number of Python files is reasonable in the Bio-Formats code base so we can open a quick fix PR. Arguably we could also impose the `pep8` version used by Travis.
To test this PR, check Travis remains green.
--no-rebase

Fix Python files to be PEP8 1.6.0 compliant

---

docs/sphinx/about/whats-new.txt

This is the same as gh-1577 but rebased onto develop.
----
Stub version history like we did for 4.4.8

Add version history for 5.0.8 (rebased onto develop)

---

components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java
components/bio-formats-plugins/src/loci/plugins/in/SwapDialog.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12239 and http://trac.openmicroscopy.org/ome/ticket/12238.
To test, choose a single file with SizeZ > 1 or SizeT > 1 (the remaining dimensions should be 1).  I was using ```test_images_good/andor/VESSEL-DEC-Z.tif```.
For ticket 12239:
1. Start ImageJ, select ```Plugins > Macros > Record...```
2. Select ```Plugins > Bio-Formats > Bio-Formats Importer```
3. Select the test file
4. Check the ```Swap dimensions``` box, but leave everything else unchecked
5. Assign the > 1 dimension to something other than the default
6. Verify that the resulting image window reflects what was chosen in step 5.
7. Select the ```Create``` button in the macro recorder window, then ```Macros > Run Macro``` in the new macro window.
8. The image window created as a …

Fix file grouping and dimension swapping in ImageJ macros

---

.gitattributes
components/formats-bsd/src/loci/formats/in/OBFReader.java

Working on different projects on a Windows system often means switching
between
core.autocrlf=input and core.autocrlf=true.
This is the per-repository solution.
The date fix just slipped in - don't know how to get it 
into a separate pull request.

Enforce LF line endings on text files

---

components/formats-gpl/src/loci/formats/in/TillVisionReader.java

This throws an exception indicating that the .vws file could not be found, instead of attempting to parse the .pst file as a .vws file.  .pst files cannot be read alone, as they are just pixels - an accompanying .vws file is expected and required.
/cc @joshmoore, @dietzc
See also https://github.com/scifio/scifio-bf-compat/issues/11

TillVision: throw a more informative exception when the .vws file is missing

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12725.  To test, verify that the file from QA 10425 has 10 Z sections and 3 channels, just like in NIS Elements Viewer (version 4.20).  For two of the channels, only one Z section will have non-zero data.
I would expect all builds to remain green.

ND2: fix RGB channel splitting

---

components/formats-api/src/loci/formats/FormatReader.java
docs/sphinx/about/index.txt
docs/sphinx/conf.py

See https://trello.com/c/3uqvWhlq/240-faq-issues-needing-moved-to-docs-plone - The FAQs are being deleted from the website for 5.1 as part of a general clean-up.
I grepped so hopefully haven't missed any links in the rest of the codebase.

Removing all references to OME FAQs

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

Fixes http://trac.openmicroscopy.org/ome/ticket/12727.
To test, import the file from QA 10469 into OMERO.  There should be 13 pyramids; the first 7 should have C C, 1 Z, 1 T, and 3 resolutions each.  The last 6 should have 2 C, 1 Z, 1 T, and 4 resolutions each.
I would expect all builds to remain green.

Leica SCN: fix pyramids when multiple channels are present

---

components/forks/jai/src/com/sun/media/imageioimpl/plugins/jpeg2000/J2KImageReader.java

see https://github.com/jai-imageio/jai-imageio-core/pull/2
--no-rebase

J2K image reader memory leak fix from jai-imageio-core

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-February/005037.html for description and test file.
--------
Testing: `Experiment base name` and `Experiment set` will appear as OriginalMetadata annotations which where previously missing.

MetamorphReader: Use ':' as metadata separator

---

components/formats-gpl/src/loci/formats/in/InveonReader.java

See
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2014-December/004972.html
Builds should remain green with this change; the only thing to verify is that the offset passed to ```dat.seek``` is calculated using long (not int) arithmetic.

Inveon: fix offsets for files larger than 2GB

---

components/autogen/src/format-pages.txt

This is the same as gh-1585 but rebased onto dev_5_0.
----
See https://github.com/openmicroscopy/bioformats/issues/1581
This is the UK redirect with prettier graphics 
I've also removed the extra link as the main one goes to the equivalent page.

Updating DeltaVision link (rebased onto dev_5_0)

---

ant/toplevel.xml
tools/source-archive.py

Fixes https://trello.com/c/phbzkRzW/406-fix-openmicroscopy-source-zip
Main changes of this PR:
- add a new target `store-version` which stores the version properties from `release-version` into a properties file. This property file can be consumed by a parent `ant` process
- remove all the `openmicroscopy` specific components in `source-archive.py`. This logic will be handled in the `openmicroscopy` repository.
- restore XML indentation erroneously removed in gh-1597
To test this PR, check the source archive of `bioformats` is still functional with the proper version embedded.
--no-rebase

Add ant target to store version properties

---

ant/toplevel.xml

See https://github.com/openmicroscopy/openmicroscopy/pull/3487#issuecomment-74871610
This should allow the `release-src` target to work from a completely clean OMERO/Bio-Formats repositories.
--no-rebase

Be safe and create the artifacts folder in store-version

---

components/formats-bsd/src/loci/formats/services/JAIIIOServiceImpl.java

See gh-1596.  This was less work than I expected; I think I checked all of the places where JAIImageIOServiceImpl is used to make sure this won't cause a problem, but it's especially important to make sure the builds remain green before merging.
No other testing should be necessary.

Call dispose() on each created J2KImageReader

---

components/formats-common/src/loci/common/DateTools.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java

Millisecond parsing in Joda has different results than with Date/SimpleDateFormat.  If the number of ms digits in the format string exceeds the number of ms digits in the date string, then zero padding happens on the wrong side (e.g. 93 becomes 930 instead of 093).  If the number of ms digits in the date string exceeds the number of ms digits in the format string, then parsing fails.
See https://github.com/JodaOrg/joda-time/issues/62.
Fixes http://trac.openmicroscopy.org/ome/ticket/12117.

Fix Leica .lei timestamp formatting

---

components/autogen/src/format-pages.txt

See http://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/697/warnings3Result/? - ZEN links no longer have 2012 in them.

Updating ZEN Zeiss link

---

components/autogen/src/format-pages.txt

This is the same as gh-1606 but rebased onto dev_5_0.
----
See http://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/697/warnings3Result/? - ZEN links no longer have 2012 in them.

Updating ZEN Zeiss link (rebased onto dev_5_0)

---

components/formats-common/src/loci/common/RandomAccessInputStream.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

LSM reader

---

components/ome-xml/src/ome/units/UNITS.java

Remove the imperial inch as a base, construct it from a metre instead. The conversion code is just more complex and it does not provide an increase in accuracy.

Base inch on metre

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

Fixes NullPointerException from the files uploaded in https://www.openmicroscopy.org/qa2/qa/feedback/10517/.
Note the uploaded samples does not contain the supporting TIFF files so BIo-Formats will fail while trying to access the `.oif.file` folder but the reader should not fail while reading the metadata.

Prevent NPE in FV1000Reader when reading channel wavelengths

---

ant/toplevel.properties
ivy.xml

See http://trac.openmicroscopy.org/ome/ticket/12287; this ensures that xercesImpl 2.8.1 will be available to OMERO.

Add xercesImpl 2.8.1 to ivy.xml and Javadoc classpath

---

components/bio-formats-plugins/src/loci/plugins/BF.java

Add option to display OME-XML and rois.
See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7746
This can be tested using fiji (you need to replace the bio-formats_plugins jar and other B-F jars ( if not already using develop jars i.e. jars/bioformats)
and running the following code
Please select a file with ROI, you can easily generate an ome-tiff with rois using BF- exporter
Edit pathToFile
```
from loci.common import Region
from loci.plugins.in import ImporterOptions
from loci.plugins import BF
options = ImporterOptions()
options.setShowROIs(True)
options.setShowOMEXML(True)
options.setColorMode(ImporterOptions.COLOR_MODE_COLORIZED)
options.setId(pathToFile)
imps = BF.openImagePlus(options)
for imp in imps:
imp.show()
```

display OME-XML and rois.

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

This prevents an exception when initializing the helper reader, particularly during
calls to getOptimalTile* immediately after setId with a memo file.
Fixes http://trac.openmicroscopy.org/ome/ticket/12750.
To test, unzip the file from QA 10526 and import ```Acqusition.xml``` into OMERO.  Verify that the resulting image can be opened in web and/or that the gateway commands in the ticket result in the tile size being shown with no exception.
See also openmicroscopy/openmicroscopy#3512
/cc @will-moore

Micromanager: fix helper reader usage when working with a memo file

---

cpp/lib/ome/bioformats/in/OMETIFFReader.cpp

By default it was being forced to `XYZCT` when not required.
--no-rebase
--------
Testing:
Run showinf on a 2013-06 OME-TIFF whose dimension order is *not* `XYZCT` and which was *not* exported from OMERO.  Without the PR the dimension order will be `XYZCT`; with the PR merged the order will be the intended order matching the OME-XML metadata.

cpp: bioformats: Correct OME-TIFF dimension order when reading

---

docs/sphinx/about/index.txt

This is the same as gh-1628 but rebased onto dev_5_0.
----
http://www.thinkstandards.net/benefits.html is broken and when I investigated the entire domain is gone so I've just removed the link assuming it isn't coming back.

Remove thinkstandards.net link (rebased onto dev_5_0)

---

docs/sphinx/about/index.txt

http://www.thinkstandards.net/benefits.html is broken and when I investigated the entire domain is gone so I've just removed the link assuming it isn't coming back.

Remove thinkstandards.net link

---

docs/sphinx/conf.py

Also, making OMERO link default to 5.1
--no-rebase

Fixing 5 doc link to be 5.0 specific

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

Allow to save the images w/o passing all parameters
if no file specified,  a temporary file using the name of the image selected is created. We may want to change that and stop if no output specified.
To test: 
* Open Fiji, update the b-f_plugins jar and all b-f jars if you are not already using develop jar (jars/bioformats)
* Run the following code (new>script language>python)
```
from loci.plugins.in import ImporterOptions
from loci.plugins import BF
from ij import IJ
options = ImporterOptions()
options.setId(fileToView)
imps = BF.openImagePlus(options)
for imp in imps:
imp.show()
image = IJ.runPlugIn("loci.plugins.LociExporter", "outfile=fileToSaveTo.ome.tif windowless=true ")
```
Remove the outfile param to create the tmp file.

Exporter windowless

---

ant/toplevel.xml
docs/sphinx/build.xml
docs/sphinx/conf.py
tools/test-build

- add `man` target to docs/sphinx `build.xml`
- add manpage generation to toplevel `docs-sphinx` target -- ensures Travis tests them
- manpages are generated in `_build/man`
Known issue: version in the manpages is only major.minor, rather than the full version.
--------
Testing:
- Run `ant man` in `docs/sphinx`
- Run `man -l _build/man/$manpage` and verify it looks OK.

docs: Add support for generating manual pages with Sphinx

---

components/bio-formats-plugins/src/loci/plugins/Slicer.java
components/bio-formats-plugins/src/loci/plugins/in/Colorizer.java

The series value was not preserved when preparing the imageplus
This was noticed when testing https://github.com/openmicroscopy/openmicroscopy/pull/3535
using some lei file (e.g. ```leica/tropo/tropo.lei```)
Testing while reviewing https://github.com/openmicroscopy/openmicroscopy/pull/3535
but this can be tested w/o OMERO
To test, run the following in Fiji. (you will first need to upgrade the b-f plugins jar)
```
from loci.plugins.in import ImporterOptions
from loci.plugins import BF
from ij import IJ, WindowManager
IJ.runPlugIn("loci.plugins.LociImporter", "PathTo/tropo.lei")
for i in WindowManager.getIDList():
print WindowManager.getImage(i).getProperty("Series")
```
When the B-F window pops up select all series
The values printed out should be 0,1,2,3

ImagePlus and series

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/formats-api/src/loci/formats/FormatTools.java
docs/sphinx/users/comlinetools/conversion.txt

Fixes http://trac.openmicroscopy.org/ome/ticket/10292.
There are documentation updates as part of the PR that summarize what the new options are.  To further summarize, the tile size used during conversion can be specified explicitly:
```bfconvert -tilex 256 -tiley 256 input-file output-file.tiff```
and each tile can be written to a separate file:
```bfconvert -tilex 256 -tiley 256 input-file output-file_X%x_Y%y.tiff```
where the ```-tilex``` and ```-tiley``` values can be changed as desired.  Note that this only works if the output format is TIFF at the moment, due to known difficulties with writing other formats tile-wise.
To test, pick one or two of your favorite files and run a few ```bfconvert``` commands using varying values for ```-tilex``` and ```-tiley```.  Also verify that …

Add tiling options to bfconvert

---

components/formats-bsd/build.properties
components/formats-bsd/build.xml
components/formats-bsd/src/loci/formats/in/JPEGReader.java
components/formats-bsd/src/loci/formats/services/EXIFService.java
components/formats-bsd/src/loci/formats/services/EXIFServiceImpl.java
components/formats-bsd/test/loci/formats/utests/MissingEXIFTest.java
components/formats-bsd/test/loci/formats/utests/testng-no-exif.xml
components/formats-bsd/test/loci/formats/utests/testng-no-xerces.xml
components/formats-common/src/loci/common/services/services.properties

This adds an ```EXIFService``` and implementation, which call the ```metadata-extractor``` library.  The service checks for the presence of ```metadata-extractor```, ```xmpcore```, and ```xercesImpl```, and will throw an exception in the constructor if they are missing.
The actual EXIF reading is now wrapped in a try block which catches Throwable, which should prevent an exception from being thrown if the ```xercesImpl``` version precedes 2.8.1.  I couldn't come up with a good way to check the ```xercesImpl``` version in the service constructor.
Tests have also been added to check that the service construction throws an appropriate exception when the ```metadata-extractor``` and ```xercesImpl``` libraries are missing.
To test, verify that all builds are green, and that JPEG files in …

Move EXIF parsing to a service

---

components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

Allow to import OME-XML w/o binary data.
This is useful when testing https://github.com/openmicroscopy/samples/pull/3
To test:
* ```./showinf``` on one of the xml file from samples.
* Import one of the XML files into OMERO.

Ome xml reader

---

cpp/cmake/BoostChecks.cmake
cpp/lib/ome/compat/config.h.in
cpp/lib/ome/compat/cstdint.h

Final boost compatibility addition to match the fallbacks in the other headers.  Not needed on any of the current platforms, but likely needed on Windows where a C++11 `cstdint` and C99 `cstdint.h` were missing until very recently.
--------
Testing: Check jobs are green.  After running `cmake` edit `cpp/lib/ome/compat/config.h` and comment out/delete the OME_HAVE_CSTDINT line; the build should succeed and use the boost header instead.

cpp: compat: Add boost cstdint fallback

---

cpp/lib/ome/bioformats/FormatReader.h
cpp/lib/ome/bioformats/FormatTools.cpp
cpp/lib/ome/bioformats/FormatTools.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/PixelBuffer.h
cpp/lib/ome/bioformats/VariantPixelBuffer.cpp
cpp/lib/ome/bioformats/VariantPixelBuffer.h
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatReader.h
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/tiff/IFD.cpp
cpp/lib/ome/bioformats/tiff/Tags.h
cpp/lib/ome/compat/array.h
cpp/lib/ome/qtwidgets/NavigationDock2D.cpp
cpp/lib/ome/qtwidgets/gl/Grid2D.cpp
cpp/test/ome-bioformats/formatreader.cpp
cpp/test/ome-bioformats/formattools.cpp
cpp/test/ome-bioformats/formatwriter.cpp
cpp/test/ome-bioformats/pixelbuffer.h
cpp/test/ome-bioformats/tiff.cpp
cpp/test/ome-bioformats/variantpixelbuffer.cpp
cpp/test/ome-compat/array.cpp
docs/sphinx/developers/cpp/conversion.txt

This matches the move of shared_ptr, regex etc. in previous PRs.
--no-rebase
--------
Testing: All tests should remain green.  No need for manual testing; any errors should result in compile failure.

cpp: compat: Move std::array into the compat namespace

---

docs/sphinx/developers/index.txt
docs/sphinx/developers/non-java-code.txt

As discussed on #1635 - re-ordering of cpp-bindings docs so they are a sub-set of the Java library docs.

Re-ordering cpp bindings docs

---

.travis.yml

This should fix failing the Travis build due to conflicting versions
--no-rebase

Flake8 2.4.0 imposes cap on PEP8

---

components/formats-gpl/src/loci/formats/in/IMODReader.java

Physical pixel sizes should be populated if the level is not MINIMUM,
not only if the level is ALL (to include NO_OVERLAYS).
This should fix test/build failures exposed by gh-1637.  No testing needed other than to verify that the merge builds turn green with this PR included.

IMOD: fix MetadataLevel checks when populating MetadataStore

---

components/formats-bsd/src/loci/formats/in/JPEGReader.java

The JPEG reader should return nothing when asked for companion files.
--no-rebase

JPEG files have pixels

---

.travis.yml

Sphinx 1.3.0 has been released on March 10 and is installed by default.
However our code currently fails with this version. Fixes will need to
be brought to the documentation. In the meantime, the version is capped
to 1.2.3 to let Travis pass.

Impose Sphinx 1.2.3 for Travis build

---

.travis.yml

This is the same as gh-1657 but rebased onto dev_5_0.
----
Sphinx 1.3.0 has been released on March 10 and is installed by default.
However our code currently fails with this version. Fixes will need to
be brought to the documentation. In the meantime, the version is capped
to 1.2.3 to let Travis pass.

Impose Sphinx 1.2.3 for Travis build (rebased onto dev_5_0)

---

components/formats-gpl/src/loci/formats/in/MRCReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7757&p=15458#p15458 and http://bio3d.colorado.edu/imod/doc/mrc_format.txt.
According to the MRC specification, mode 0 can correspond to `int8` data depending on the value of `imodStamp`. At the moment MRCReader is imposing `uint8`. This PR adds support for `int8` mrc data by adding an extra check for mode 0 and removing the block which flips the pixel type to unsigned bytes depending on the maximum and minimum pixel values.

MRC: add signed bytes support

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/ome-xml/pom.xml

The ome-xml.org domain is retired in favor of openmicroscopy.org.
So let's use the current URLs for the relevant links.
Replaces #1652 
to be rebased to dev_5_0

Update OME-XML URLs

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

If an ```OMEXMLMetadata``` was successfully parsed by ```isThisType(RandomAccessInputStream)``` or ```isSingleFile(String)``` prior to calling ```setId(String)```, it will now be re-used.  In common cases where ```isThisType``` is always called before calling ```setId``` on the same file, this should roughly halve the initialization time.
To test, compare the initialization times logged by ```showinf``` with and without this PR merged.  Also verify that all builds remain green.
/cc @ctrueden

OME-TIFF: reduce the number of times the OME-XML is parsed

---

components/formats-common/build.properties
components/formats-common/pom.xml
components/formats-common/src/loci/common/Location.java

ConcurrentHashMap undergoes API changes among Java 6, 7, 8, so to keep code nicely portable it's generally easier to simply avoid using it given that we already have Guava available and that offers a suitable substitute.
(A larger refactoring could use Guava's CacheBuilder so it would handle expiration for us too, but 5.1.0 has more urgent demands!)
Testing: No tests or builds should break, and the Bio-Formats source should no longer contain direct usage of ConcurrentHashMap.
--no-rebase

remove usage of ConcurrentHashMap

---

components/ome-xml/src/ome/units/UNITS.java
components/specification/released-schema/2015-01/ome.xsd

This adds the unit 'bar' to pressure.
It is the same 2015-01 but has had its version number bumped to 2. This make it a minor release. 
The xsd change should require a major release but coming so soon on the back of the last release and being in a completely new section for the schema no one should have reader/writer code for this to break.
See version info at: http://www.openmicroscopy.org/site/support/ome-model/schemas/index.html
----
Also some other late schema documentation changes for:
http://trac.openmicroscopy.org/ome/ticket/12693
----
--exclude

Adding bar to units

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This is more robust than just checking the file name suffix, as it
prevents initializing corrupt files with correct file names.
Fixes QA 10902.  To test, open all of the filesets from QA 10902 (or import into OMERO) and verify that an exception is not thrown.

OME-TIFF: check file contents in multi-file datasets

---

components/bio-formats-plugins/src/loci/plugins/in/DisplayHandler.java
components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

1) Open an omero Image in Insight, create/modify ROI shape properties (Specifically stroke width and stroke colour of the ROI's) and save them.
2) Now open the Image on ImageJ using the OMERO-IJ Plugin and check if the ROI's are added to the ROIManager (and the shape properties are replicated in ImageJ).

Bug Fix (Color Properties): Open OmeroROI's in ImageJ

---

cpp/lib/ome/qtwidgets/GLView2D.cpp

--no-rebase
--------
Testing:
Run `bf-test view` and open an image.  Without the PR, the "pan" action will be the opposite of the mouse movement i.e. moving the scene rather than the camera.  With the PR the x and y motion is inverted, making panning act like a click-drag operation where the scene being moved will correspond 1:1 with the mouse movement.
/cc @pwalczysko @mtbc

cpp: qtwidgets: Correct camera pan direction in GLView2D

---

cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/in/OMETIFFReader.h

- Cope with OME-TIFF file renaming (invalid UUID filename in the metadata)
- Only use canonical paths
--no-rebase
--------
Testing:
- Use bfconvert to create a 2013-06 OME-TIFF
- Run `bf info` to check this is readable and has valid metadata
- Rename the OME-TIFF (retaining the `.ome.tiff` extension)
- `bf info` will now fail (without this PR) or will continue to work with a warning (with this PR)

C++: Small fixes for the OME-TIFF reader

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/ome-xml/pom.xml

This is the same as gh-1654 but rebased onto dev_5_0.
----
The ome-xml.org domain is retired in favor of openmicroscopy.org.
So let's use the current URLs for the relevant links.
Replaces #1652 
to be rebased to dev_5_0

Update OME-XML URLs (rebased onto dev_5_0)

---

cpp/examples/CMakeLists.txt
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/XMLTools.cpp
cpp/test/CMakeLists.txt
docs/sphinx/conf.py
docs/sphinx/developers/cpp/examples/metadata-io.cpp
docs/sphinx/developers/cpp/examples/model-io.cpp
docs/sphinx/developers/cpp/examples/pixeldata.cpp
docs/sphinx/developers/cpp/overview.txt
docs/sphinx/developers/cpp/tutorial.txt
docs/sphinx/developers/index.txt

- First installment of examples, initially just metadata plus a single bugfix and link addition
--no-rebase
--------
Testing: the examples are tested as part of the unit tests, so jobs should remain green.  The examples on the tutorial page are selected bits pulled out of the example code in `docs/sphinx/developers/cpp/examples`.

C++: Add metadata examples to tutorial

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-March/005128.html
Under some conditions, retrieving `IFD.DATE_TIME` can return a String array. This is already handled by the `getImageCreationDate()` method which returns the first item of the array. This PR re-uses the existing logic to fill the global `DateTime` metadata with a `String` instead of a `String []`.
To test this PR, run `showinf` on the file mentioned in the forum thread. `DateTime` should be populated in the `Global metadata` section with a string. Alternatively, reproduce the MATLAB steps described in the thread.
--no-rebase

Re-use getImageCreationDate logic to populate global DateTime metadata

---

cpp/cmake/TemplateShellWrapper.cmake.in

- Handle the case where stripping the bindir results in an empty string (set to '.')
- Also handle the case where `dirname` does not have a leading slash
- Use `eval` to strip substring with dynamic string; this makes it clear where the string to strip comes from rather than having cmake substitute it in multiple places
--no-rebase
/cc @joshmoore 
--------
Testing:
Obtain and unpack merge build tar archive.
```
tar xfv bioformats-xxx.tar.xz
cd bioformats-xxx
./bin/bf-test
bin/bf-test
$(pwd)/bin/bf-test
```
All three forms of `bf-test` invocation should work, where previously the middle form was broken.

cpp: cmake: Special-case bf-test shell wrapper rootdir determination for empty path

---

cpp/examples/CMakeLists.txt
cpp/lib/ome/bioformats/in/MinimalTIFFReader.h
docs/sphinx/developers/cpp/examples/metadata-formatreader.cpp
docs/sphinx/developers/cpp/examples/metadata-io.cpp
docs/sphinx/developers/cpp/examples/pixeldata.cpp
docs/sphinx/developers/cpp/tutorial.txt

- Examples of bits of the FormatReader API
- Document `in` namespace
Is there anything missing from the tutorial which should be added for 5.1.0?
--no-rebase

C++: Add FormatReader section to tutorial

---

components/formats-gpl/src/loci/formats/in/PCIReader.java

This PR should fix the few Bio-Rad PIC `test_images_good` samples still failing on Windows. Tested against the PCI subset of the full repository. Automated tests should pass under Windows (to be tested manually) and LInux (see full-repository job)
--no-rebase

Fix PCIReader test failures on Windows

---

components/ome-xml/src/ome/units/quantity/Angle.java
components/ome-xml/src/ome/units/quantity/ElectricPotential.java
components/ome-xml/src/ome/units/quantity/Frequency.java
components/ome-xml/src/ome/units/quantity/Length.java
components/ome-xml/src/ome/units/quantity/Power.java
components/ome-xml/src/ome/units/quantity/Pressure.java
components/ome-xml/src/ome/units/quantity/Quantity.java
components/ome-xml/src/ome/units/quantity/Temperature.java
components/ome-xml/src/ome/units/quantity/Time.java

Specifically, this branch makes the `Quantity` superclass nicer to work with, and adds some helpful constructors with default unit specifications, to avoid errors when converting downstream code to the new API.
See [here](https://github.com/scifio/scifio-ome-xml/compare/ome-5.1) for an example where these changes would be helpful.
/cc @qidane

Improve the units API

---

ant/toplevel.xml
tools/source-archive.py

- Add "bioformats-dfsg-$version.zip"; this is a DFSG (Debian Free Software Guidelines) compliant archive which omits binaries (jars and libraries such as .so/.dylib/.dll for which we don't have source in the repository and hence in the source distribution).  This is to make a "clean" source release which is acceptable for public redistribution in compliance with the GPL, for use by upstream homebrew, Debian/Ubuntu/Fedora, BSD ports, etc.
This change is a precursor to being able to provide Bio-Formats (both Java and C++) in distributions directly.  Are there any other generated files imported into git which might also need excising for licence compliance?  How about source files under BSD/GPL-incompatible terms?  Is there a better prefix name than "-dfsg" (which is already used elsewhere …

build: Also provide source zip without binary content

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

Testing Instructions :
Without this PR,
1) Open an Image in Omero. Create Point ROI's and save.
2) Now open the image in ImageJ using the OMERO IJ plugin with "display ROI's" checked. This will open the ROI's without any issue (but the Point ROI's are wrongly converted to Ellipses). This will not be noticeable to the eye, so to confirm, just click "Plugins-->Omero-->Save ROI's to OMERO" without clearing the ROI Handler. 
3) This will create a duplicate copy of the ROI's in OMERO.
4) The only way to check the bug , will be to check the Type column in the Insight ROI tool. This will show that the newly imported ROI's will be ellipse, and the old ROI's will be points. 
With this PR.
The round trop from ImageJ to Omero to ImageJ should preserve the Point ROI type.
Problem noticed during week …

Bug Fix : Conversion of Point Roi from Omero to ImageJ : RoiHandler bug

---

docs/sphinx/developers/cpp/overview.txt

docs: C++ overview: Correct typo

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java

For both formats, if a TIFF file is chosen and file grouping is
disabled, then the file will be treated as a regular TIFF.
Some metadata will be unavailable (as is expected when file grouping is
disabled), but the images will be more quickly accessible.
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-March/005124.html.
I was testing with ```micromanager/scott/MM_1.4/Pos1``` as it's the largest Micro-Manager dataset we have; ```showinf -nopix -nogroup``` on one of the TIFF files with this PR should be significantly faster with this PR, and result in only the chosen file being read.

Fix disabled file grouping for Micro-Manager and OME-TIFF

---

ant/global.xml
ant/java.xml
ant/toplevel.xml
components/forks/jai/src/com/sun/media/imageioimpl/plugins/gif/GIFImageWriter.java
components/forks/mdbtools/src/mdbtools/dbengine/Engine.java
components/forks/mdbtools/src/mdbtools/dbengine/MemoryData.java
components/forks/mdbtools/src/mdbtools/dbengine/SelectEngine.java
components/forks/poi/src/loci/poi/hssf/model/FormulaParser.java
components/forks/poi/src/loci/poi/hssf/usermodel/HSSFWorkbook.java
components/formats-api/src/loci/formats/FormatReader.java
components/formats-bsd/src/loci/formats/Memoizer.java
components/formats-bsd/src/loci/formats/in/IM3Reader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java
components/formats-gpl/src/loci/formats/in/ZeissTIFFHandler.java
components/ome-xml/src/ome/xml/model/primitives/PrimitiveType.java

See gh-1693.  Private fields (e.g. ```minimumElapsed``` in Memoizer) should be present in the Javadocs with this PR included.  Feel free to cherry pick the commit, or close outright if this isn't helpful.

Display private fields and methods in Javadocs

---

docs/sphinx/about/whats-new.txt

This probably needs a little more work before tagging - minimally I would like to add doc links for new formats once the format page PR is opened and merged.
Happy to add anything that seems to be missing - I think all of the major or important changes are here, but there were a ton of PRs to go through so it's possible that a few slipped through the cracks.  Also happy to remove some of the more minor fixes if the list is too long as it is.

Add version history for 5.1.0

---

cpp/test/ome-bioformats/tiff.cpp

--no-rebase
We were already running a reduced number of testcases, so the amount of discspace we were using wasn't really that great, so this problem might recur in the future during the main build itself; the simple fact of this failure is that the travis build nodes don't have enough disc space, so it could affect any job, particularly openmicroscopy.git where the repo size and checkout size is huge.  Hopefully it's a temporary situation the Travis people will resolve.  We could further reduce space by doing a Release rather than Debug build, which should reduce the object file size significantly.
--------
Testing: Unit tests should continue to pass but disc space usage will be reduced.

cpp: test: Delete generated test files to conserve disc space

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See https://trac.openmicroscopy.org.uk/ome/ticket/12409
If the lens NA is filled in the metadata, this commit also  adds it to the OME-XML metadata store.
--no-rebase

Metamorph: parse lens numerical aperture

---

components/formats-gpl/src/loci/formats/in/ImarisHDFReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12170.  Without this change, the file from QA 8019 had 3 Z sections and 1 channel.  With this change, the same file should have 3 Z sections and 3 channels when opened in ImageJ or imported into OMERO.  Note that all planes are fairly dark, so you may need to adjust rendering settings/brightness to see the artifact in the images.

Imaris HDF: fix SizeC if channels are stored in reverse order

---

components/formats-gpl/test/matlab/ReaderTest.m
components/formats-gpl/test/matlab/TestBfGetReader.m
docs/sphinx/developers/matlab-dev.txt

Please check if the following lines work:
```
data = bfopen('/path/to/data/file');
omeMeta = data{1, 4};
stackSizeX = omeMeta.getPixelsSizeX(0).getValue(); % image width, pixels
stackSizeY = omeMeta.getPixelsSizeY(0).getValue(); % image height, pixels
stackSizeZ = omeMeta.getPixelsSizeZ(0).getValue(); % number of Z slices
voxelSizeX = omeMeta.getPixelsPhysicalSizeX(0).value(); % returns value in default unit
voxelSizeXunit = omeMeta.getPixelsPhysicalSizeX(0).unit().getSymbol(); % returns the default unit type
voxelSizeX = omeMeta.getPixelsPhysicalSizeX(0).value(ome.units.UNITS.MICROM); % in µm
voxelSizeY = omeMeta.getPixelsPhysicalSizeY(0).value(ome.units.UNITS.MICROM); % in µm
voxelSizeZ = omeMeta.getPixelsPhysicalSizeZ(0).value(ome.units.UNITS.MICROM); % in µm
```

Doc Fix : Update VoxelSize documentation to include Units

---

components/formats-bsd/src/loci/formats/in/EPSReader.java

This doesn't add support for vector data, but does a better job of
setting the dimensions and throwing a consistent exception during
openBytes.
See https://trac.openmicroscopy.org/ome/ticket/11352 and https://trac.openmicroscopy.org/ome/ticket/11353.  The file for each ticket (QA 7556 and QA 7558, respectively) should now throw a FormatException when reading the image data that indicates that vector data is not supported, instead of the NFE/NPE reported previously.

EPS: consistently detect vector data

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-bsd/src/loci/formats/tiff/IFD.java

Fixes [Ticket 12801](https://trac.openmicroscopy.org/ome/ticket/12801)
Test: Use the image mentioned in the ticket/mail; display the metadata with `./showinf -omexml bBB01-1D_wL08_s3_z1_t1_cCy5_u001.tif`. Check that the PageNumber is shown as `0 1`.

Show full TIFF PageNumber information

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Right now, this just adds debug logging to ```testRequiredDirectories```.  I will update this PR with a fix for the test once https://ci.openmicroscopy.org/view/Experimental/job/BIOFORMATS-5.1-merge-test_images_good-win/ has run with the new logging.
All but one of the failures noted in https://ci.openmicroscopy.org/view/Experimental/job/BIOFORMATS-5.1-merge-test_images_good-win/4/ are a result of ```testRequiredDirectories``` failing without logging an exception or failure message; hopefully the additional logging will shed some light as to why.  I suspect that having the mount point be ```\\squig...``` instead of a letter drive may have something to do with it, as the same test works locally.
/cc @sbesson

Fix testRequiredDirectories with Windows paths

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Fix the sizeX and sizeY if not set.
Also fix some encoding issue noticed while testing the file
to test
* run ```./showinf  PATH_TO/QA/10480/example.lif ```
* Check that the image opened w/ error
* Check that metadata display does not contain any undecoded character i.e. ```ATLConfocalSettingDefinition|ClimateControl|ClimateUnit|DimensionUnit: °C``` should not be displayed correctly.

Leica lif reader

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This should prevent warnings similar to ```ome.xml.model.Channel@579e8e6e reference to null missing from object hierarchy.``` when working with some .czi files.  See https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7669.
To test, use the file from QA 10974.  Verify that ```showinf -nopix -omexml``` shows the above warning without this change; with this change, the warning should not be present.

Zeiss CZI: ignore null FilterSet references

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-bsd/src/loci/formats/in/BaseTiffReader.java

Fixes [Ticket 11399](https://trac.openmicroscopy.org/ome/ticket/11399)
Test: Import the images mentioned in the ticket in OMERO and make sure the unit 'nm' is used.
(Note: As I'm not yet familiar with the bioformats code, I have no idea if this is the way things like this should be done.)

Use the unit from imagej comment

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12569.
To test, check the PositionX and PositionY values from ```showinf -nopix -omexml``` with the file from QA 9529.  These should match the values in the ```Experiment Data``` tab of the ```Image Properties``` window in NIS Elements.

ND2: fix indexing of plane positions

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12673.
To test, use the file from QA 10379 and verify that the images in series 1 and 2 (the middle two) are switched with each other when compared with the same series without this change.

Zeiss CZI: avoid reordering series

---

components/formats-bsd/src/loci/formats/gui/AWTImageTools.java

Fixes https://trac.openmicroscopy.org/ome/ticket/6833.
To test, run:
```
showinf -normalize test_images_good/khoros/head.xv
showinf -normalize -thumbs test_images_good/khoros/head.xv
```
and verify that both produce an image with no exception, and that the latter is a reasonable-looking thumbnail of the former.

Preserve the pixel type for floating-point thumbnails

---

CMakeLists.txt
ant/version.xml
cpp/cmake/Sphinx.cmake
cpp/cmake/list-manpage-dependencies.py
cpp/cmake/list-manpages.py
docs/doxygen/CMakeLists.txt
docs/sphinx/.gitignore
docs/sphinx/CMakeLists.txt
docs/sphinx/Makefile
docs/sphinx/build.xml
docs/sphinx/conf.py
docs/sphinx/conf.py.in
docs/sphinx/developers/cpp/overview.txt

- Allow external configuration of build without environment variables
- Pass release and version numbers with `sphinx-build -D`
- Set nonstandard variables by substitution from `conf.py.in` template
- Versions are obtained from ant's `version.xml` so match the rest of the build, but are overridable using the `sphinx.release` and `sphinx.version` ant properties
- CMake build generates `doc-html` and `doc-pdf` targets if `sphinx-build` and `xelatex` are available, configurable via the `sphinx` and `sphinx-pdf` options (documentation added).  Also adds `doc-linkcheck`
- CMake will install the build documentation into `$CMAKE_INSTALL_PREFIX/share/doc/bioformats` (`manual` subdirectory for the sphinx manual; `cpp-api` for the doxygen API reference)
--no-rebase
--------
Testing: Jobs should …

Refactor sphinx ant build and add cmake build

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

The files that demonstrate the problem are unfortunately private, so the only testing necessary is to verify that the builds are/remain green.
/cc @emilroz

VSI: prevent infinite loop when parsing extended tags

---

components/formats-bsd/src/loci/formats/out/ICSWriter.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12602.
To test, use an input file with more than 2GB of pixel data - I used ```large-file&sizeX=2048&sizeY=2048&sizeZ=1000.fake```.  Use bfconvert to convert the input file to an .ics file, and verify that the conversion succeeds without an exception, the output file is larger than 2GB, and the last plane from the output file can be read.  Without this change, the same test would have resulted in an exception during bfconvert.

ICS writer: fix saving of > 2GB of pixel data

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This adds 0-padding to make the index lengths equal, which should make
the series list easier to read when sorted alphanumerically.
Fixes https://trac.openmicroscopy.org/ome/ticket/12809.  To test, check the output of ```showinf -nopix -omexml``` with the .nd2 file from QA 10945.  The Image names should all be the same length with this change.

ND2: make series names the same length

---

components/formats-gpl/src/loci/formats/in/ImprovisionTiffReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12184.
To test, place the TIFF files from QA 8025 and 9163 in the same directory (unzip as necessary and remove extra zip/log files).  Run ```showinf``` on both files, and import both into OMERO - with this change, each of the files should import as a separate fileset, with one plane and no exception.  Without this change, both would have thrown an exception during import as noted in the ticket.

Improvision TIFF: reset image count if ZCT dimensions are incorrect

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

The typo ("UesrDefName") that existed in previous versions of LAS AF has
apparently now been fixed.  See QA 10980.
To test, verify that channel names are not present for the file in QA 10980 without this change.  With this change, all series should have channel names ```Test BF```, ```GFP```, and ```mKate``` (just like in LAS AF Lite).

LIF: fix user-defined channel name parsing

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Handle empty string before converting into number.
To test this PR
* Try to import or use showinf to open image from QA 10983
* Check that 
```
: empty String
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:992)
at java.lang.Double.valueOf(Double.java:475)
at java.lang.Double.<init>(Double.java:567)
at loci.formats.in.LIFReader.translateFilterSettings(LIFReader.java:1495)
```
No longer appears

LIF reader empty sring

---

components/bio-formats-plugins/src/loci/plugins/in/ImportProcess.java
components/formats-gpl/src/loci/formats/in/CellH5Reader.java

Testing instructions : 
1) Download and update the Bioformats_Package.jar in your ImageJ plugin's folder.
2) Import without ROI's : Import the following image using the Bioformats_Importer: data_repo/from_skyking/cellh5/samples
with the following checkboxes selected in the Importer Options,
- Display OME-XML metadata.
- Use virtual stack.
3) Import with ROI's : Import the following image using the Bioformats_Importer: data_repo/from_skyking/cellh5/samples
with the following checkboxes selected in the Importer Options,
- Display OME-XML metadata.
- Display ROIs.
- Use virtual stack.
4) Compare performance between steps 2 and 3. The performance of "Import without ROIs" should be better than the latter. And the OME-XML metadata should not have the ROI information in step 2.

Bf importer performance

---

cpp/lib/ome/bioformats/CMakeLists.txt
cpp/lib/ome/bioformats/FormatReader.h
cpp/lib/ome/bioformats/FormatWriter.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/MetadataTools.h
cpp/lib/ome/bioformats/PixelProperties.cpp
cpp/lib/ome/bioformats/PixelProperties.h
cpp/lib/ome/bioformats/Types.h
cpp/lib/ome/bioformats/VariantPixelBuffer.h
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.h
cpp/lib/ome/bioformats/in/MinimalTIFFReader.cpp
cpp/lib/ome/bioformats/in/MinimalTIFFReader.h
cpp/lib/ome/bioformats/in/TIFFReader.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.h
cpp/lib/ome/bioformats/tiff/Codec.cpp
cpp/lib/ome/bioformats/tiff/Codec.h
cpp/lib/ome/bioformats/tiff/IFD.cpp
cpp/lib/ome/bioformats/tiff/IFD.h
cpp/lib/ome/bioformats/tiff/Util.cpp
cpp/lib/ome/bioformats/tiff/Util.h
cpp/test/ome-bioformats/CMakeLists.txt
cpp/test/ome-bioformats/formatwriter.cpp
cpp/test/ome-bioformats/minimaltiffwriter.cpp
cpp/test/ome-bioformats/tiff.cpp
cpp/test/ome-bioformats/tiffsamples.cpp
cpp/test/ome-bioformats/tiffsamples.h

This PR adds a TIFF writer.  It also adds infrastructure for future work for TIFF and OME-TIFF, including:
- TIFF codec querying
- Reading a single subchannel from a TIFF
- Writing a single subchannel to a TIFF (interface only)
- Minor refactoring/cleanup of FormatWriter implementation, plus addition of helper methods
- Addition of significant bit sizes for PixelProperties
- Adjustment of CopySubchannelVisitor to use planar layout by default
- Addition of MergeSubchannelVisitor
- Helper functions to set up an OMEXMLMetadataStore from CoreMetadata
- Helper functions to compute total per-series and per-file pixel storage sizes
- Addition of a few TIFF/IFD helper methods
- Refactoring of some of the TIFF test logic for reuse by the writers
What it does *not* add:
- TIFF compression (codec …

C++: Add TIFF writer

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This should fix the 8 test failures that are not logged in https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository-win/3/ and https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-full-repository/454/.
This issue was exposed by gh-1716; if the physical unit is set to 'pixel', then it won't be convertible to ```Units.MICROM```, which results in hidden NPEs when the tests are run.  No testing needed other than to verify that the failure count is reduce by 8 with this PR merged.

Prevent test failures when PhysicalSize* units are in pixels

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12807.  To test, use the .dv files from QA 10945 and 10946.  Place both files in the same directory and create a .log file as described in the ticket.
Without this change, ```showinf -nopix -omexml``` on the *R3D_D3D.dv file should show that only the first channel has a name assigned; with this change, the same test should show that every channel has a name.  The names should be the same as shown by ```showinf -nopix -omexml``` on the *R3D.dv file.

Deltavision: fix channel name order for deconvolved data

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12559.
To test, use the file from QA 9526 and verify that the pixel type with this change is int32.  Without this change, it would have been uint32.  Note that a number of other sample .dm3 files (in the ```gatan``` directory) changed sign; while I did check each one in ImageJ with the DM3 reader plugin (http://rsb.info.nih.gov/ij/plugins/DM3_Reader.html), it might also be worth spot-checking a few to make sure that the DM3 reader plugin concurs as to the pixel values.

DM3: use the DataType tag to set the pixel type

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12789.
To test, use the two files referenced in the ticket (both have been uploaded to ```zeiss-czi/sebastian/fused```).  The ```*_fused.czi``` file would have shown 6 series of strange images without this change; with this change, there should be a single large image that more or less matches what is shown in Zen.  The behavior when opening the ```*_stitched.czi``` file should be unchanged.

Zeiss CZI: fix series count for fused images

---

components/formats-bsd/src/loci/formats/UpgradeChecker.java

The UpgradeCheck logic assumed the upgrade check query returns a string
containing the latest version. This commit reproduces the UpgradeChecker logic
implemented in OMERO which only tests for the length of the returned string.

Fix deprecated UpgradeCheck parsing logic

---

components/formats-bsd/src/loci/formats/UpgradeChecker.java

This is the same as gh-1741 but rebased onto develop.
----
The UpgradeCheck logic assumed the upgrade check query returns a string
containing the latest version. This commit reproduces the UpgradeChecker logic
implemented in OMERO which only tests for the length of the returned string.

Fix deprecated UpgradeCheck parsing logic (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See QA 10987, fixes gh-1719.
To test, verify that opening the file from QA 10987 in Matlab (as described in the issue) or via ```showinf -separate``` no longer throws an exception.  The image is quite large, so you may need to increase the heap size or crop the image to prevent an OOM.

Zeiss CZI: do not set indexed for RGB images

---

components/bio-formats-plugins/src/loci/plugins/macro/LociFunctions.java

Fixes https://trac.openmicroscopy.org/ome/ticket/11145.
To test, use a macro similar to the following in ImageJ:
```
run("Bio-Formats Macro Extensions");
path = "/path/to/multi-series-file";
Ext.setSeries(1);
Ext.openImagePlus(path);
Ext.setSeries(0);
Ext.openImagePlus(path);
```
Verify that without this change, the images for series 0 are opened twice.  With this change, the images for series 1 should be opened first, followed by the images for series 0.

ImageJ: use series state in open*ImagePlus(String) methods

---

components/formats-bsd/src/loci/formats/Memoizer.java

Similarly to what has been done on the Sphinx documentation, this commit expands the Javadoc of the Memoizer class to explain its purposes/workflow and potential limitations.

Expand Memoizer Javadocs

---

cpp/lib/ome/bioformats/CoreMetadata.cpp
cpp/lib/ome/bioformats/CoreMetadata.h
cpp/lib/ome/bioformats/FormatReader.h
cpp/lib/ome/bioformats/FormatWriter.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatReader.h
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.h
cpp/lib/ome/bioformats/in/MinimalTIFFReader.cpp
cpp/lib/ome/bioformats/in/MinimalTIFFReader.h
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/in/OMETIFFReader.h
cpp/lib/ome/bioformats/in/TIFFReader.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.h
cpp/lib/ome/bioformats/tiff/TIFF.cpp
cpp/lib/ome/bioformats/tiff/Util.cpp
cpp/lib/ome/bioformats/tiff/Util.h
cpp/libexec/info/ImageInfo.cpp
cpp/test/ome-bioformats/formatreader.cpp
cpp/test/ome-bioformats/formatwriter.cpp
cpp/test/ome-bioformats/minimaltiffwriter.cpp
docs/sphinx/developers/cpp/examples/metadata-formatreader.cpp

Both the existing readers and writers were making some mistaken assuptions with SizeC/EffectiveSizeC/ImageCount/RGBChannelCount.  This PR corrects these assumptions to use these data correctly, and it also adds some fixes to the API to handle subchannel data and calculations correctly in all circumstances.  I was going to wait on doing this, as discussed, but the impact of getting things wrong is quite severe.  Unlike the Java situation, where using incorrect dimension sizes/indices will at worst give an ArrayOutOfBoundsException, here we will at best immediately segfault or worse, silently corrupt memory and write out junk data.  I thought it better to err on the side of caution rather than give the user incorrect data with potentially catastrophic results.
- CoreMetadata: Make `sizeC` a …

C++: Reader and writer channel-related fixes

---

components/formats-gpl/matlab/bfopen.m

The existing code was modifying the state of the warnings but was turning them all back on instead of restoring to the previous state.
Ideally, this would also turn off only the specific warning that was causing issues but I can't figure out what warning was that. This was done in 664274bb but the commit message does not give me any hints.

matlab: restore state of the warnings instead of turning all of them 'on'

---

.travis.yml

saucy has been removed from the mirrors and was no longer supported.
See https://github.com/openmicroscopy/ome-documentation/pull/1197

travis: Switch from saucy to trusty

---

docs/sphinx/about/whats-new.txt

A few of the really minor NPE-type PRs were omitted, but otherwise this should cover everything that is merged, open, or planned before tagging.  Happy to add to it if it looks like anything noteworthy is missing though.

Update version history for 5.1.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Now that 5.1.1 is tagged, this should be merged before any other PR.
--no-rebase

Update POM version numbers to 5.1.2-SNAPSHOT

---

components/bio-formats-plugins/src/loci/plugins/in/ImagePlusReader.java

See
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005289.html
I was able to reproduce the original exception by copying the ```ics/anke/``` dataset and replacing the ```ch``` in line 5 of the .ics file with ```p```.  With this change, the same dataset should open in ImageJ without an exception; the labels at the top of the image window should show that there are 4 phases.

ImageJ: prevent NPE if one of the sub-channel types is null

---

.travis.yml

This is the same as gh-1759 but rebased onto dev_5_0.
----
saucy has been removed from the mirrors and was no longer supported.
See https://github.com/openmicroscopy/ome-documentation/pull/1197

travis: Switch from saucy to trusty (rebased onto dev_5_0)

---

docs/sphinx/about/index.txt

List of places people look for help with BF issues wasn't complete.
Will be staged on https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/about/index.html#help
Also, rearranged order so OME, ImageJ and Fiji items are grouped together.

Adding addition BF related mailing lists/groups

---

components/formats-gpl/src/loci/formats/in/AIMReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12785.  To test, verify that opening the file from QA 10907 does not result in an exception.
Note though that the images are likely to look weird/wrong.  The dimensional metadata matches the corresponding unprocessed data from QA 10913, so I think everything is fine there.  The file is much too small for the recorded dimensions, though, which leads me to believe that the file is somehow corrupted.  A request for further information (http://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7762) has gone unanswered so far.

AIM: return blank planes for truncated files

---

components/formats-bsd/src/loci/formats/in/JPEG2000MetadataParser.java
components/formats-bsd/src/loci/formats/in/JPEG2000Reader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005300.html.
To test, use the .jp2 file from ```jpeg2000/mario```.  With both commits, ```showinf -debug``` should indicate that 88 comments were found.  The same test with d742be2 reverted should show that 176 comments were found, but the output should otherwise be the same.

JPEG-2000: fix redundant file parsing

---

docs/sphinx/developers/cpp/tutorial.txt

This should fix warnings noted by https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-5.1-merge-docs/.  Should be sufficient to verify that the build is green, and that the four changed links still point to the corresponding named method.

Fix broken anchor links

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

This should prevent ```BIG_TIFF_CUTOFF``` from being negative, which caused all TIFF/OME-TIFF files to be written as BigTIFF.
To test, pick any small file (e.g. ```test_images_good/al3d/Iron Plate.al3d```).  Verify that using ```bfconvert``` to convert the file to TIFF without this change produces a message to the effect that BigTIFF is being used; with this change, the same test should not produce a BigTIFF message.  Running ```file``` on the output files should also indicate BigTIFF without this change and plain TIFF with this change.

TIFF export: use long arithmetic for BigTIFF check

---

tools/ijview

A small change to fix the fact that it was not checking the BF directory, but just the current dir for bioformats_package.jar. Hope this helps!

Search for bioformats_package.jar in BF_JAR_DIR

---

components/formats-bsd/src/loci/formats/tiff/IFD.java

The problem is that during the writing of a OME-TIFF which is made tiled by creating a custom IFD with tiles by using following lines of code and passing that ifd to saveBytes():
IFD ifd = new IFD();
ifd.put(IFD.TILE_WIDTH,  256);
ifd.put(IFD.TILE_LENGTH, 256);
Bioformats allocates too much memory because rowsPerTile variable assigned in [TiffSaver.writeImage()](https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-bsd/src/loci/formats/tiff/TiffSaver.java#L312) is equal to an entire image height instead of the height of a tile unless you manually set IFD.ROWS_PER_STRIP in custom ifd.
The extraneous memory is later ignored anyway, so the behaviour does not change. Allocating this extraneous memory only causes performance implications and possibly an out of
memory …

RowsPerStrip is equal to image height when saved image is tiled

---

components/formats-api/src/loci/formats/FormatWriter.java
components/formats-bsd/src/loci/formats/out/TiffWriter.java

There is a race condition occurring during multithreaded writing of a (OME-)TIFF file resulting in an exception.
It occurs fairly rare but has occurred to me several times when writing huge OME-TIFF file. It ends with a stack trace similar to this one:
Caused by: loci.formats.FormatException: X:184320 must be < 13206
at loci.formats.FormatWriter.checkParams(FormatWriter.java:363)
at loci.formats.out.TiffWriter.saveBytes(TiffWriter.java:211)
at loci.formats.out.OMETiffWriter.saveBytes(OMETiffWriter.java:196)
This exception occurs when one thread enters FormatWriter.checkParams() while different one is in [TiffWriter.prepareToWriteImage()](https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-bsd/src/loci/formats/out/TiffWriter.java#L368).
The cause of the problem is …

Race condition during writing of TIFF leading to an exception

---

components/bio-formats-plugins/src/loci/plugins/macro/LociFunctions.java
components/bio-formats-plugins/utils/macros/planePositions.txt

Fixes https://trac.openmicroscopy.org/ome/ticket/12865.
To test, use the macro added in f074113.  Without ccccf80, running the macro in ImageJ should result in an error - see http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-April/005339.html.
With ccccf80, the macro should run successfully and output the X, Y, and Z positions for each plane.  I was using the .nd2 files from test_images_good to test, but almost any file with populated positions should work.

Fix getPlanePosition* macro commands in ImageJ

---

docs/sphinx/developers/commit-testing.txt

Document requirements (xUnit framework) and commands to run the MATLAB tests
/cc @bramalingam @manics

Add section about MATLAB testing to the developers documentation

---

components/formats-common/test/loci/common/utests/DateToolsTest.java

Follow up of https://github.com/openmicroscopy/bioformats/pull/1764
Two unit tests commits that were not pushed to the previous PR but should extend the test coverage for:
- handling of different patterns (` aa`, `Z`) post milliseconds
- trimming of the date string before date parsing

Joda milliseconds parsing (tests)

---

cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/MetadataTools.h
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.h
cpp/lib/ome/bioformats/in/OMETIFFReader.h
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/tiff/Util.cpp
cpp/lib/ome/bioformats/tiff/Util.h
cpp/test/ome-bioformats/data/brokenchannels-correctable.ome
cpp/test/ome-bioformats/data/brokenchannels-uncorrectable.ome
cpp/test/ome-bioformats/data/validchannels.ome
cpp/test/ome-bioformats/metadatatools.cpp

Major changes include:
- `setId` methods for both FormatReader and FormatWriter always canonicalise the path, so that comparisons always use the same path; previously there was potential for miscomparison where different paths for the same file could be used (relative vs. absolute vs. canonical absolute)
- BigTIFF checking factored out of MinimalTIFFWriter for use by OMETIFFWriter
- detail::FormatWriter methods using channel calculations corrected, and getSeriesCount() method added
- Addition of MetadataTools `validateModel` function, which can optionally correct some channel inconsistencies.
The model validation and correction currently deals solely with ambiguity between *SizeC*, channel element count and SamplesPerPixel (*SPP*) on channels.  The correction ensures that *SizeC* == …

C++: Various writer corrections

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Switching from a Stack to a Deque reversed the order in which the tags
were built.  This fixes the tags by using the Deque's descending
iterator.
See gh-1782.
To test, use any .czi file.  Verify that the original metadata table entries changed between 5.1.0 and 5.1.1; with this PR included, the 5.1.0 behavior should be restored.

Zeiss CZI: fix ordering of metadata tags

---

components/formats-bsd/src/loci/formats/Memoizer.java
components/formats-bsd/test/loci/formats/utests/MemoizerTest.java

This PR fixes a bug with the memoization that can be reproduced following two scenarios:
- at the Bio-Formats level, using a memoizer-decorated reader, call `setId` on an image file in a directory and create an in-place memo file. Close the reader, rename the directory containing both the original file and the memo file. Using the same memoized reader, call `setId()` on the new file location.
- at the OMERO level, set up a server and import and image. Then stop the server, rename the `omero.data.dir` folder and modify the `omero.data.dir/BioFormatsCache` hierarchy to match the new naming scheme. After fixing the server configuration, restart the server and try to access the image.
In both cases, the `setId()` call should fail with `FileNotFoundException` leaving both the reader and the …

Memoizer relocation improvements

---

components/formats-bsd/src/loci/formats/out/OMETiffWriter.java

This allows switching to BigTIFF without using the setBigTiff API method.
See https://trello.com/c/1q2GATUh/171-bigtiff-extensions-for-ome-tiff.
To test, verify that converting any file to a file with the ```.ome.btf```, ```.ome.tf2```, or ```.ome.tf8``` extension via bfconvert or ImageJ results in a BigTIFF file.  When using bfconvert, the output should show a message similar to ```Switching to BigTIFF based on extension```.  The converted files should be readable, and showinf should identify them as being OME-TIFF files.

OME-TIFF: allow BigTIFF extensions during export

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

See gh-1785.
To test, check the file from QA 11061 with ```showinf```.  Without this change, a NegativeArraySizeException should be thrown in DeltavisionReader.  With this change, the format should be listed as ```FEI TIFF``` and no exception should be thrown.

Deltavision: check for valid dimensions in isThisType

---

components/autogen/src/format-pages.txt

Australian link has been giving a 404 since 6th May so I've updated with the international English language link. Also fixed a typo I spotted.
This should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/ green again once it's been built by the autogen job.

fixing link & typo

---

components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaHandler.java

https://github.com/openmicroscopy/bioformats/commit/7345a479d072953d6669c9d8cde140311d136afa introduced a possible bug wherein the natural iteration order for `nameStack` is reversed. This PR reverts that change, following the pattern of #1784.
--no-rebase

fix iteration order for nameStack in Leica readers

---

cpp/lib/ome/common/variant.h

See https://svn.boost.org/trac/boost/ticket/11283
`boost/variant/detail/element_index.hpp` uses `boost::remove_cv` from type_traits, but does not include `boost/type_traits/remove_cv.hpp`, leading to build failure.  Include this header before including variant headers to work around this.
--------
Testing: Builds should remain green.  Should build with current homebrew on MacOS X using Boost 1.58.  Note: Building with -Dcxxstd-autodetect=ON will fail due to https://svn.boost.org/trac/boost/ticket/11285 for which I don't yet have a workaround (other than setting it to OFF, which is the default).

cpp: common: Add workaround for broken header in Boost 1.58

---

components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/src/loci/formats/in/FilePatternReader.java

To test, run ```echo "test_Z<00000-60000>.fake" > fake.pattern```.  ```time showinf -nopix fake.pattern``` should result in an OOM without this change.  The same test with 4b223c4 should run to completion, but be fairly slow (1m50s locally); the same test with all commits should run to completion and be substantially faster (16s locally).

Performance updates for working with large pattern filesets

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12843.
To test, import the file from ```zeiss-czi/sebastian/12843``` into OMERO; wait for the pyramid to be generated, then compare the resulting image with what is shown in Zeiss' Zen software.

Zeiss CZI: fix assembly of overlapping tiles

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java
cpp/lib/ome/bioformats/detail/FormatReader.cpp

Fixes https://trac.openmicroscopy.org/ome/ticket/12848.
To test, import the following .vsi files into OMERO:
```
cellsens/qa-11039/Image_01.vsi
cellsens/olivier/small-tiles/*.vsi
cellsens/olivier/14-09-2012/Image_07.vsi
```
Verify that each results in multiple pyramids, some of which will have a single channel and some of which will have multiple channels.  Open each pyramid in the full viewer and zoom/pan to verify that there is nothing obviously wrong with the image.
When reading through the code, please pay special attention to 76b37a2, as this is a very subtle change to how ```FormatReader.setCoreIndex(int)``` works.

CellSens VSI: fix channel count when multiple pyramids exist

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This should use the native kHz unit included in the log file. Additionally this fixes a bug introduced in 5.1.0 with an incorrect conversion.

Use native kHz units for DeltavisionReader read-out rate

---

components/formats-gpl/matlab/bfCheckJavaMemory.m
components/formats-gpl/matlab/bfCheckJavaPath.m
components/formats-gpl/matlab/bfGetFileExtensions.m
components/formats-gpl/matlab/bfGetPlane.m
components/formats-gpl/matlab/bfGetReader.m
components/formats-gpl/matlab/bfUpgradeCheck.m
components/formats-gpl/matlab/bfopen.m
components/formats-gpl/matlab/bfsave.m
components/formats-gpl/matlab/createMinimalOMEXMLMetadata.m
components/formats-gpl/matlab/private/is_octave.m

These two commits are required for the code to work with GNU Octave.
The first commit only explicitly ends each of the function blocks (and indents them). This is not really required for Octave compatibility but I believe it to be good form, specially when the file has subfunctions (which bioformats does). It is best viewed locally with the `--ignore-all-space` option.
The second commit is the one that actually changes the code but I believe it to still work in Matlab. More details are on the commit message.
Note that even after this changes, the code will not run on the latest release of Octave (3.8.2). However, I have been working on the Octave side to fix the other incompatibilities (which could be treated as Octave bugs) so that bioformats can work on the upcoming Octave release …

Changes for Octave compatibility

---

components/formats-bsd/src/loci/formats/out/OMETiffWriter.java
components/xsd-fu/templates-cpp/OMEXMLMetadata.template
cpp/lib/ome/bioformats/CMakeLists.txt
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/PixelProperties.h
cpp/lib/ome/bioformats/Types.h
cpp/lib/ome/bioformats/detail/FormatWriter.h
cpp/lib/ome/bioformats/detail/OMETIFF.h
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.h
cpp/lib/ome/bioformats/tiff/Util.h
cpp/lib/ome/common/filesystem.h
cpp/lib/ome/common/xml/dom/Document.h
cpp/lib/ome/internal/CMakeLists.txt
cpp/lib/ome/internal/url.h
cpp/lib/ome/qtwidgets/GLView2D.cpp
cpp/lib/ome/test/test.h
cpp/test/ome-bioformats/CMakeLists.txt
cpp/test/ome-bioformats/ometiffwriter.cpp
cpp/test/ome-common/CMakeLists.txt
cpp/test/ome-common/filesystem.cpp
cpp/test/ome-common/variant.cpp

- Minor refactoring to allow code sharing between reader and writer
- Some additional small warning cleanups
- Add writer and tests
--------
Notable differences from the Java OMETiffWriter implementation:
- `close()` does not have a `canReallyClose` finally block; since by this point we already validated and written out all pixel data and metadata, it's not clear what this is for given that there's nothing we can really do.  What's the rationale for this, given that closing should be terminal and unconditional, particularly resetting the IFD counts which looks like it might screw up the metadata?
- Channel count/Channel objects are fixed up if broken, so some of the special casing isn't needed here, e.g. the equivalent of `planeIndex` in `populateImage`.
- The IFD object isn't currently …

C++: Add OME-TIFF writer

---

components/formats-gpl/src/loci/formats/in/ND2Handler.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12880.
To test, use each of the .nd2 files from QA 11064.  Compare the DeltaT, PositionX, PositionY, and PositionZ values from ```showinf -nopix -omexml``` with the Time, X, Y, and Z values in the ```Recorded Data``` tab of NIS Elements Viewer's ```Image Properties``` window.  Also verify that the Z, C, T, and series counts match the Z, C, T, and XY position counts in NIS Elements.
This does also add DeltaT and Position* automated tests, so that going forward we'll have an easier time of catching and fixing these sorts of problems.  I have not gone through all of the .nd2 samples and updated configuration files to include the correct DeltaT and Position* values (it's only been done for ```nd2/qa-11064```).  Follow-up Trello card is …

ND2: better timestamp and plane position population

---

components/formats-bsd/src/loci/formats/Memoizer.java

When the reader is significantly modified (e.g. during major releases), the `loadMemo` logic usually throws an ArrayIndexOutOfBoundsException which results in an ERROR message. Similarly to KryoException, this commit "whitelists" these exceptions and decrease the log level to WARN.
A typical testing workflow for this PR is via an OMERO use case:
- start an OMERO 5.0.x server and import a file which underwent major changes between 5.0.x and 5.1.x (`Deltavision`)
- stop the server and upgrade it to a 5.1.x server with this PR included
- access the same file again to regenerate the memo file, e.g. via the clients
- check Blitz.log shows a WARN-level invalidation message, e.g.
```
2015-05-20 16:20:52,655 WARN  [                   loci.formats.Memoizer] (l.Server-3) deleting invalid memo file: …
```

Improve memo file invalidation error handling

---

components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java

This should prevent exceptions from being logged at WARN when the SlideBook .dlls are missing.
To test, pick any .sld file from ```test_images_good/slidebook``` or ```from_skyking/slidebook```; verify that ```showinf -nopix``` shows a logged exception without this change, and no exception with this change.

Reduce missing library log level

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

This should also ease the testing of Memoizer functionalities which can be invoked in the command-line tools via:
```
showinf -cache /path/to/file
showinf -cache-dir /tmp /path/to/file
```

Add memoize functionality to ImageInfo

---

cpp/lib/ome/qtwidgets/GLView2D.h
cpp/lib/ome/qtwidgets/TexelProperties.cpp
cpp/lib/ome/qtwidgets/TexelProperties.h

- Document the namespace
- Make TexelProperties use the namespace (it was using the bioformats namespace incorrectly)
--------
Testing: None; check job is green.

C++: Document and correct use of qtwidgets namespace

---

cpp/lib/ome/xml/model/primitives/Timestamp.h

- Add sentry (not for this bug, just for general correctness)
- Use a string rather than a character array for the TZ offset;
the use of a character array led to inconsistent behaviour since
it decays to a char* and hence requires NUL termination, which
may or may not occur depending on whether the memory has been
used before, which is unpredictable.
Note: whitespace-only diff: https://github.com/openmicroscopy/bioformats/pull/1799/files?w=1
--------
Testing:
I've used Ubuntu 14.04 to reproduce and test.  Do a build like normal, then run
```
while ./bf-test ./cpp/test/ome-xml/timestamp ; do : ; done
```
Without this PR, you should see the tests fail intermittently if you run this a few times.  With the PR, no failures should be apparent.
Note that you can test on other platforms, but I …

cpp: ome-xml: Correct intermittent incorrect Timestamp timezone offset parsing

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

The datasets that exhibited this problem are unfortunately private.  To test, just verify that builds remain green.
/cc @emilroz

InCell: fix type detection for Cytell datasets

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12585 (GSD refers to http://www.leica-microsystems.com/products/super-resolution-microscopes/details/product/leica-sr-gsd-3d/)
To test, use the file in ```leica-lif/ian/```.  Import into OMERO or view in ImageJ, and compare with the what Leica's LAS AF Lite viewer shows.  The images should look the same; LAS AF will show several additional event list entries (i.e. non-image data), which won't be present in ImageJ/OMERO.
This shouldn't affect other files, and builds should remain green.

Fix handling of Leica LIF files with GSD data

---

components/formats-bsd/src/loci/formats/in/EPSReader.java
components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/tiff/IFD.java
components/formats-bsd/src/loci/formats/tiff/OnDemandLongArray.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/IPWReader.java
components/formats-gpl/src/loci/formats/in/MIASReader.java

See https://trello.com/c/dxVTjrxb/235-logbot-out-of-memory-detected-nightshade.
This makes better use of the ```OnDemandLongArray``` class to prevent keeping all tile/strip offsets and byte counts in memory.  The amount of memory required during setId with or without memoization should be greatly reduced for files with a large number of strips or tiles.

TIFF: reduce memory required for large files

---

components/formats-gpl/src/loci/formats/in/SimplePCITiffReader.java

See QA 11088 and http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-May/005386.html.
To test, verify that the file from QA 11088 throws an exception without this change (as noted in the thread).  With this change, the file should open without any error via showinf/ImageJ.

Fix exceptions when parsing SimplePCI TIFF metadata

---

components/formats-bsd/src/loci/formats/FileStitcher.java

Fixes https://trac.openmicroscopy.org/ome/ticket/11095.
```showinf -stitch Series001_t0_z0_ch00.tif``` or opening in ImageJ with ```Group files with similar names``` checked using QA 7328 should now work correctly.  There are 9 files (3 Z sections x 3 channels), each of which contains a single RGB image, so with stitching/grouping enabled there should be 9 planes.  Without this change, all 9 planes would have been cyan (only the files corresponding to the first channel were used); with this change, there should be 3 distinct channels (cyan, red, and green).

FileStitcher: fix file indexing for RGB images

---

docs/sphinx/about/bug-reporting.txt
docs/sphinx/conf.py.in
docs/sphinx/developers/commit-testing.txt
docs/sphinx/developers/jace/build-windows.txt
docs/sphinx/developers/jace/build.txt
docs/sphinx/developers/matlab-dev.txt

See https://trello.com/c/3tqP1qU9. This PR should hopefully clarify the fact that MATLAB is using the Bio-Formats Java API directly and add an extra link to the Javadocs.

Explain JAVA/Matlab relationship in the docs

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12839.
To test, import the file from ```hamamatsu/qi/``` into OMERO.  Scroll through the zoom levels for the first imported image, pan to the lower right corner, and verify that nothing looks obviously wrong; the tiles should load normally, and there should be no exceptions in the Blitz log.
We have a few other files that may or may not be affected by this change, so it's probably a good idea to import them as well:
```
hamamatsu/tony/2010-02-26 17.39.12.ndpi
hamamatsu/paul/2009-10-29 17.04.12.ndpi
hamamatsu/philippe/fluorescence/PHAS 01.ndpi
```
and also verify that viewing/zooming/panning works without missing tiles or Blitz exceptions.

NDPI: fix tile offsets for files between 2 and 4 GB

---

docs/sphinx/users/comlinetools/display.txt

Following https://github.com/openmicroscopy/bioformats/pull/1808, this PR:
- adds basic documentation for the `-cache`/`-cache-dir` options of `showinf`
- adds basic documentation fro the `-fast`/`-autoscale` options /cc @mtbc 
The last commit implements a proposal to migrate this page to using the `program/option` markup (similarly to what was done for the CLI). The benefit would be 1- to register these options in the generated index and 2- to allow cross-references across the documentation using :option:`showinf -nopix`. On the flip side, this does not fully matches the way this page was originally written. This proposal was implemented in an isolated commit and can be reverted /cc @hflynn

Command-line tools: 5.1.2 docs

---

components/formats-common/src/loci/common/Location.java
components/test-suite/build.xml
components/test-suite/logback-trace.xml
components/test-suite/src/loci/tests/testng/TestTools.java

Related to https://trac.openmicroscopy.org/ome/ticket/6586 and https://trello.com/c/0Rdx4AMl/113-nfs-on-windows - this will hopefully help to see the speed and number of calls in Location.
To test, compare the log files generated by ```ant -Dtestng.directory=/path/to/test_images_good test-automated``` and ```ant -Dlogback.configurationFile=logback-trace.xml -Dtestng.directory=/path/to/test_images_good test-automated```.  The latter should produce log files that include copious quantities of TRACE lines from loci.common.Location; the former should not have any TRACE-level logging.
If this is acceptable, the next step is to temporarily add ```-Dlogback.configurationFile=logback-trace.xml``` to one or more of the Windows merge jobs.

Add TRACE logging to loci.common.Location

---

docs/sphinx/about/whats-new.txt

Just a minor addition to the BF version history to promote the commercial contribution a bit more https://trello.com/c/GLtwSegm/33-slidebook-sdk
Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/about/whats-new.html

Adding 3I website to make attribution clearer

---

components/ome-xml/src/ome/xml/meta/OMEXMLMetadata.java
components/xsd-fu/templates-java/FilterMetadata.template
components/xsd-fu/templates-java/MetadataRetrieve.template
components/xsd-fu/templates-java/MetadataStore.template

Generated MetadataStore, MetadataRetrieve and implementing classes now have a complete set of Javadoc comments.  These have been copied and adapted from doxygen comments in the C++ templates.
--------
Testing:
See 
https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-build/javadoc/ome/xml/meta/package-summary.html
Interfaces: MetadataStore, MetadataRetrieve, OMEXMLMetadata
Classes: AggregateMetadata, DummyMetadata, FilterMetadata, OMEXMLMetadataImpl
They should all have a complete set of javadocs.

xsd-fu: Add javadocs to Java metadata templates

---

components/specification/released-schema/2015-01/ome.xsd

Nothing to test; it's just a comment correction.  We might want to regenerate the published Oxygen documentation if anyone knows how to do that.

specification: Correct psi documentation description to pound-force

---

cpp/lib/ome/bioformats/FormatReader.h
cpp/lib/ome/bioformats/FormatWriter.h
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatReader.h
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.h
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp

- Add getPlane and setPlane to FormatReader and FormatWriter, to match getSeries and setSeries.
- FormatReader sentry saves and restores plane state in addition to series state.
- Current plane is set to zero on series change.
This is the C++ part of #1806 
--------
Testing: Jobs should remain green.  The only code currently exercising the plane state is the writers, and these were already using the methods (the change for FormatWriter is simply moving them up to the public interface to expose them)

C++: Add plane state introspection and manipulation to reader and writer interfaces

---

cpp/examples/CMakeLists.txt
cpp/lib/ome/bioformats/PixelBuffer.h
cpp/lib/ome/bioformats/in/MinimalTIFFReader.cpp
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/in/TIFFReader.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
cpp/lib/ome/bioformats/tiff/IFD.cpp
docs/sphinx/conf.py.in
docs/sphinx/developers/cpp/examples/metadata-formatreader.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter.cpp
docs/sphinx/developers/cpp/tutorial.txt

- Minor cleanups (indent, error message detail increased)
- Make close on destruction reliable (readers and writers)
- Minor fix to existing writer example
- Add OME-TIFF writing example
- Add OME-TIFF writing documentation to tutorial
--------
Testing:
- Take a look at the tutorial https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/developers/cpp/tutorial.html
- Run the example and check you get a 512×512 16-bit image (RGB, planar, 12 signif. bits/pixel):
```
% ./bf-test ./cpp/examples/metadata-formatwriter test.ome.tiff
Image count: 1
Plane count: 1
PixelBuffer PixelType is uint16
VariantPixelBuffer PixelType is uint16
Wrote 786432 uint16 pixels
% tiffinfo test.ome.tiff 
TIFF Directory at offset 0x180008 (1572872)
Image Width: 512 Image Length: 512
Bits/Sample: 16
Sample …
```

C++: Minor writer improvements and writer example with documentation

---

components/formats-api/src/loci/formats/MetadataTools.java
docs/sphinx/developers/reader-guide.txt

Following-up on the work carried out in https://github.com/openmicroscopy/bioformats/pull/1755, this PR backports some of the discussion from the PR into the Javadocs and the Sphinx developer documentation.
- check the Javadocs for `MetadataTools.populatePixels()` describes the various signatures
- check the sections in the reader writing guide about the OME-XML metadata intiialization and the order creation for the model objects are redable

New reader: docs addition

---

CMakeLists.txt
cpp/cmake/BioFormatsCommon.cmake
cpp/cmake/BioFormatsSuperBuild.cmake
cpp/cmake/CompilerChecks.cmake
cpp/cmake/ExternalProjectHelpers.cmake
cpp/cmake/External_png.cmake
cpp/cmake/External_zlib.cmake
docs/sphinx/developers/cpp/overview.txt

Add initial cmake "superbuild" infrastructure.
- Will download and build zlib and libpng as a proof of concept (more will follow); this is to verify that the inter-module dependencies and build logic are functional
- Not enabled by default; existing builds will be unaffected
- When enabled, all builds are relocatable; it's not possible to build with a fixed install prefix.  This is likely what is always wanted on Windows.  This is due to the complications of building with a fixed prefix and then linking against the staged libraries and its interactions with rpath
- Currently hard-coded to use `make` with `DESTDIR` staging, so won't work on Windows yet; I'll get the superbuild setup fully functional on Unix and then tweak it to work on Windows once all the library support is in place (this …

cmake: Add toplevel SuperBuild two-phase processing

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
docs/sphinx/developers/generating-test-images.txt

In order to round trip test the import of fake files,
having a simple way of adding arbitrary fake global
metadata to the reader is necessary. This currently adds
support to fake.ini files for parsing the `[GlobalMetadata]`
section into calls to FormatReader.addGlobalMetadata. Later
work could add series-specific metadata as well.

FakeReader: add support for `[GlobalMetadata]`

---

docs/sphinx/users/comlinetools/conversion.txt
docs/sphinx/users/comlinetools/formatlist.txt
docs/sphinx/users/comlinetools/mkfake.txt

See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=7830
This PR moves to using the `program/option` markup across the command-line tools pages and also documents the usage of the `-bigtiff` flag and/or the BigTiff extension in `bfconvert`.

bfconvert: mention BigTiff flag and extension

---

components/formats-bsd/src/loci/formats/in/AVIReader.java
components/test-suite/src/loci/tests/testng/Configuration.java

Fixes https://trac.openmicroscopy.org/ome/ticket/11264.
To test, use the files from QA 7450 and 11011.  When opened in ImageJ (```Use virtual stack``` may be necessary), each file should have a frame count that matches what is indicated by ```mplayer```.
The only difference between Bio-Formats and mplayer should be with QA 11011 - in this file, there is a conflict between the plane height stored in the AVI container (408) and the plane height stored in each of the MJPEG compressed streams (204).  Bio-Formats is using the MJPEG height instead of scaling the images (which I think is what mplayer does).

AVI: read frame index tables

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12503.
To test, use the files linked from http://fiji.sc/bugzilla/show_bug.cgi?id=868.  ```file1.stk``` and ```file2.stk``` should each be a single time series with this change (i.e. SizeZ = 1).  Without this change, SizeZ would have been > 1.  Builds should remain green; other datasets should not be affected.

Metamorph: better detection of time series

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12926.  This prevents the plane index from being too large for series beyond the first.
To test, choose any MIF (the ticket indicates ```test_images_good/leica-lif/Beta Canenin.lif```), and use ```bfconvert``` to convert to a single OME-TIFF.  With this change, the conversion should be successful, and ```showinf -nopixels``` on both files should show matching metadata.  Without this change, the conversion would have thrown an exception.

bfconvert: fix plane indexes for multi-series exports

---

components/formats-common/src/loci/common/IniWriter.java
components/test-suite/build.xml
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/ConfigurationTree.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java
components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java
components/test-suite/src/loci/tests/testng/TestTools.java

Currently automated tests are relying upon configuration files (`.bioformats`) being present under the same tree as the data repository. The goal of this infrastructure PR is to remove this requirement and allow external configuration tree to bee used to test the data repository. Ultimately, this should simplify our workflow when modifying readers and configuration files /cc @jburel
- check the overall set of changes is sensible. Some refactoring in the test classes to use helper methods and hide parameters of type `${property}` set by `ant`
- check the existing test logic is untouched without specifying a configuration directory
```
ant test-config -Dtestng.directory=/path/to/data  # should create/append .bioformats files in-place
ant test-automated …
```

Automated tests: add support for external configuration directory

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This commits catches any NumberFormatException thrown when parsing multi-file CZI datasets with a file is named 'master (string).czi' and excludes it from the fileset.
Fixes https://github.com/openmicroscopy/bioformats/issues/1840
- check automated tests are still passing especially for czi files
- create a folder with a `master.czi` and a `master (string).czi` file and check `showinf -nopix` fails without this PR but works with it.

Be defensive when trying to group multi-file CZI datasets

---

components/formats-bsd/src/loci/formats/codec/LosslessJPEGCodec.java

I found that the color images I was trying to decompress have 3 Huffman tables (one per color channel). The existing code assumed there was just one table present in the DHT marker segment and stopped processing after that. I added a loop until the entire segment has been processed, and that fixed decompression for color images.
While reading about the handling of 0xff00 in the compressed data, I realized that the existing code didn't properly handle the case where there's a valid JPEG marker with a non-zero byte after the 0xff. I updated it to always skip the byte after a 0xff, but only store the 0xff if that byte is zero.
It's probably very rare that there's a valid JPEG marker in the compressed data, but it is legal so it's good to handle it properly.
I'm afraid I can't provide test …

LosslessJPEG color

---

components/autogen/src/format-pages.txt

Link has been dead since 16th June and the domain doesn't seem to exist any more so I'm assuming it's not coming back (also we have another specification link anyway).

Remove dead MRC specification link

---

components/formats-bsd/src/loci/formats/tiff/OnDemandLongArray.java

This should reduce the seek count to O(1) instead of O(n) when calling
toArray().
Fixes https://trac.openmicroscopy.org/ome/ticket/12930.  To test, use the files from QA 11133 and QA 11125.  Without this change, ```showinf``` on each file should take many minutes to display images.  With this change, the same command should have minimally an order of magnitude improvement in time.  I'd suggest repeating the test several times with each branch, and comparing the average and minimum times (not just the first time).
For reference, on my Linux VM, QA 11133 takes 1m21s and QA 11125 takes 1m6s with this change.

TIFF: reduce number of seeks in OnDemandLongArray

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Back (forward?) ported from a6fb748 and 2e27ca2.
See QA 11128 and http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-June/005429.html.
To test, use the dataset in QA 11128; the .nd file is the one to open/import.  Without this change, choose the second or third series and verify that the first channel appears to be from a different stage position relative to the other two channels.  With this change, all three channels in the same series should clearly be from the same stage position.

Metamorph: fix Z and T settings when the .nd file is inconsistent

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

Update the bioformats_package.jar in the imageJ/plugins folder. (with the merge build)
1) Open an ome-tiff, which has more than 1000 roi's in it, using the Bio-Formats Importer in ImageJ.
and compare performance (with and without this PR).
2)Can also open an existing image within OMERO (trout/latest, user-4, image_id: 29753), and use the omero-ij plugin to open the image. 
In both cases, the performance should be much better with this PR included.

Improve performance of displaying roi's and enable show all labels

---

.travis.yml

- build cppwrap under java7, since this is what our users will be most likely to be using (particularly since it requires being hand-built)
- move the non-java jobs to oraclejdk8; this is to allow future removal of the openjdk6 axis without disturbing other jobs.

travis: Move non-java components to oraclejdk8 and build cppwrap with oraclejdk7

---

components/formats-gpl/src/loci/formats/in/ScreenReader.java

Memoizing a ScreenReader with OpenlabTiff files led to a
NullPointerException. Now each reader in the ScreenReader
has its reopenFile method called.
Testing with OMERO:
* activate the `ScreenReader` in both lib/client and lib/server
* import the Rad52 screen
* view the plate in OMERO.web
Before this PR, no thumbnails were loaded. With this PR, thumbnails load normally. Note: if you try the above with only one import of the screen, it will be necessary to delete the memo file.

ScreenReader: implement reopenFile

---

components/formats-bsd/cppwrap/showinf.cpp
tools/test-build

- Don't instantiate OMEXMLServiceImpl until the JRE is initialised
- Test showinf and minimum_writer with travis
--------
Testing: handled by travis, but if you wanted to build cppwrap and run showinf:
```
./tools/test-build cppwrap
components/formats-bsd/target/cppwrap/build/showinf
```
it should be able to show metadata for image files without faulting.

cppwrap: Correct OMEXMLService initialisation

---

components/formats-bsd/src/loci/formats/in/APNGReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12850.
See also
http://www.libpng.org/pub/png/spec/1.2/PNG-DataRep.html#DR.Interlaced-data-order.
To test, use the file from QA 11038.  Without this change, ```showinf``` on the file should throw an exception; with this change, ```showinf``` should produce the same image as ImageMagick (the ```display``` command) and ```File > Open``` in ImageJ.

PNG: fix interlaced images that have a width or height that is not a multiple of 8

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
pom.xml

This allows the snapshot repository to be changed; by default, the
latest-build profile (== ome.snapshots repository) will be used.  If
'mvn -P merge-build' is run instead, then the merge-build profile (==
ome.unstable repository) is used.
Replaces gh-1838.

Add a merge build profile to POMs

---

components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

This should do a better job of ensuring that Z * C * T is equal to the
number of planes.
Fixes https://trac.openmicroscopy.org/ome/ticket/12940.
To test, use the files from QA 11135.  Verify that there are 61 planes in each file using ```tiffinfo filename.tif | grep -c "TIFF Directory"```.  Without this change, ```showinf``` should show that both files have SizeZ * SizeC * SizeT != 61.  With this change, SizeT should be 61 for both files.

Metamorph TIFF: better check for dimension consistency

---

components/formats-gpl/src/loci/formats/in/PSDReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12629.
To test, use the file from QA 10347.  Without this change, ```showinf``` or ImageJ should show an image that looks obviously wrong.  With this change, ```showinf``` and ImageJ should show the same thing as Image/GraphicsMagick - a single RGB image with three text labels in the upper-left corner.

PSD: fix bug in pixel data offset calculation

---

cpp/cmake/TemplateShellWrapper.cmake.in

Josh found last week while testing the superbuild code that DYLD_FALLBACK_LIBRARY_PATH should be used in place of DYLD_LIBRARY_PATH on MacOS X.  This PR changes this for the `bf-test` script template so that it can work in a superbuild context.
--------
Testing: `bf-test` will continue to work.  You can test with the zip build from any of the Mac build nodes. e.g. https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp/BUILD_TYPE=Debug,CXXSTD_AUTODETECT=ON,node=mackerel/

cmake: TemplateShellWrapper uses DYLD_FALLBACK_LIBRARY_PATH

---

docs/sphinx/about/index.txt

See https://trello.com/c/yZLuJXzt/22-version-history and https://trello.com/c/phTsSDsj/25-documentation-changes-scoping
This updates the intro to the version history section to say that OMERO & BF releases are now decoupled and while I was at it, I rearranged the page to put the more important info further up the page.

Rearranging About index & decoupling versions

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See QA 11163 and http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-July/005488.html.
Without this change, ```showinf``` on the .nd file from QA 11163 should result in an exception, as noted in the thread.  With this change, ```showinf``` should initialize the .nd file without error.  The series count should match the ```NStagePositions``` value in the .nd file, and every series should open without error (this is easiest to test in ImageJ with the ```Open all series``` option).  Only the first 4 series will contain valid image data - everything else should be completely black.

Metamorph: skip TIFF files with no IFDs

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Fixes http://trac.openmicroscopy.org.uk/ome/ticket/12951
With this PR included, Bio-Formats should properly include all TIFF files of the dataset linked in the ticket with the even series being single-Z brightfield images and the odd series being multi-Z fluorescent images e.g. using command-line tools:
```
showinf -series 0 -fast -autoscale /path/to/file.nd
showinf -series 1 -fast -autoscale /path/to/file.nd
```

Metamorph: fix multi-series with mismatching Z

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See https://trello.com/c/buOp7Scd/23-nd2-channel-count.
To test, use the file in ```nd2/damir```.  Verify that Nikon's NIS Elements Viewer shows 700 positions, 4 channels, 1 Z section and 1 timepoint.  Without this change, ```showinf``` only shows 3 channels; with this change, all dimensions and images should match Elements.

ND2: fix channel count correction

---

components/specification/pom.xml

While trying to consume Maven specification.jar for the OMERO exporter integration tests, the transformation catalog could not be found as it currently not bundled.

Also include ome-transforms.xml in Maven specification JAR

---

components/formats-api/src/loci/formats/CoreMetadata.java
components/formats-api/src/loci/formats/Modulo.java
components/formats-gpl/src/loci/formats/in/SDTInfo.java
components/formats-gpl/src/loci/formats/in/SDTReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12918.
To test, use the files from QA 11109.  Both .sdt files should have 2 series, the first of which has 256 timepoints and the second of which has 1024 timepoints.  As noted in the ticket, the SPCM software can be used to double-check.
This shouldn't affect other .sdt files (i.e. builds should remain green), as the MCS_TA metadata blocks were introduced in newer versions of the .sdt specification.  The current SPC handbook and data file header have been uploaded to the ```specs/sdt``` directory for future reference.

SDT: read MCS_TA data

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java

ref: https://trac.openmicroscopy.org/ome/ticket/12964
Testing instructions : 
Please import the 2 files in the following thread in ImageJ using the Bio-Formats Importer,
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-July/005492.html
with the "display-metadata" option checked.
And check if you can see the TimeStamp information in the metadata table in both cases,
ex: Timestamp for Z= *s, C=*s, T=*s
Without this PR : The Old file (FURA.tif) will display the Timestamp but the new file will not show the TimeStamp, in the metadata table.

FluoviewReader: TimeStamp - Accommodate 24 hour time format as well

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

If a directory contains multiple Meas_* directories, each with .flex
files, then each Meas_ directory will be automatically detected as an
acquisition of the same plate.
See https://trello.com/c/dyEq0xsZ/187-flex-runs. I haven't yet thoroughly tested this in OMERO - that's the next step. We haven't had real exposure to the multiple acquisitions use case before, so there may be some things that need changing/fixing.
The small dataset I was testing with was ```flex/karsten/Columbus_ExtendedData/Images/AFo_071214_measurement3...```. This has 8 directories, each with 10 .flex files (one per well). Picking any one of the .flex files results in 80 series, so 80 Images, 80 WellSamples, 1 Plate, 8 PlateAcquisitions. I think all of the linkages are correct, but carefully checking the output of …

Flex: add support for multiple plate acquisitions

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

Has `showinf` print usage information if the user tries to guess an option that will print help. Fixes http://trac.openmicroscopy.org/ome/ticket/12954: try the commands listed in its description. Normal `showinf` workflows should continue to work.

fix #12954: usage help argument

---

components/test-suite/src/loci/tests/testng/ConfigurationTree.java
components/test-suite/src/loci/tests/testng/TestTools.java

```replaceAll``` on Windows path names can quickly become kind of weird due to backslashes.  This replaces ```replaceAll``` with a less platform-dependent method of replacing the directory names.
Locally, I ran ```ant "-Dtestng.configDirectory=C:\Users\melissa\data_repo_config\test_images_good" "-Dtestng.directory=E:\test_images_good" test-automated``` (pointing to the current master branch of data_repo_config and a current copy of test_images_good respectively).  Without this change, every file in test_images_good is logged as "not configured".  With this change, only those files whose parent directory is symlinked (so no corresponding file is in data_repo_config) are logged as "not configured".
/cc @sbesson
See also https://trello.com/c/tbUfkJiE/6-external-configuration-directory-follow- …

Fix config directory path substitution on Windows

---

cpp/lib/ome/xml/model/primitives/Timestamp.h

Move return to the outermost block, to fix a compiler warning.
--------
Testing: builds should remain green, no manual testing required.

cpp: ome-xml: Correct return in Timestamp ostream output

---

cpp/cmake/RegexChecks.cmake

This comes from https://github.com/codelibre-net/schroot/pull/2/files and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=778112 leading to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67015
There's a subly broken regex implementation in GCC, which we weren't detecting.  This PR detects this and will fall back to using boost::regex in this case.
--------
Testing: Travis and the CI builds won't detect this since we aren't using any of the affected compiler versions.  Ideally we would have builds on more recent GCC versions, but we don't at present.  If you build with GCC 4.9.x, 5.0 or 5.1, you will find that where before the `OME_HAVE_REGEX` cmake test would succeed, it will now fail:
- run `cmake /path/to/bioformats` and note OME_HAVE_REGEX and OME_HAVE_BOOST_REGEX results
- merge this …

cmake: Check for broken GCC regex implementation

---

components/xsd-fu/templates-cpp/MetadataRetrieve.template
components/xsd-fu/templates-java/MetadataRetrieve.template

This is purely a docstring change, though you can verify the generated code to check that the parameters are actually used (both for Java and C++).
A perhaps bigger question is why for example `setImageAnnotationRef` and `getImageAnnotationRef` do not have symmetric signatures, or rather do but in the former annotationRefIndex is unused and in the latter it is used, so the behaviour is not the same.  This applies to all `(get|set).*AnnotationRef` methods.  What makes these different than every other method in the model using indexes?  Even if this is valid, it would be helpful to know why and document it.

xsd-fu: MetadataRetrieve: Drop 'unused' from used parameters

---

cpp/lib/ome/common/boolean.h
cpp/test/ome-common/boolean.cpp

Found while fixing an optimisation warning for MSVC.
We were copy constructing using the boolean value rather than the raw value.  No change to the unit tests, though I've added a number of extra tests to check both the logical Boolean value and the raw bit pattern in memory to make sure this is caught properly.
--------
Testing: CI jobs should remain green.
If you want to verify by hand that the change is needed, then apply only the unit test changes without the boolean.h changes, and you'll get:
```
[ RUN      ] Boolean.CopyConstruct
/Users/rleigh/code/bioformats/cpp/test/ome-common/boolean.cpp:50: Failure
Value of: raw
Actual: '\x1' (1)
Expected: std::numeric_limits<uint8_t>::max()
Which is: '\xFF' (255)
[  FAILED  ] Boolean.CopyConstruct (30 ms)
```

cpp: common: Correct boolean copy constructor to copy raw value

---

cpp/lib/ome/common/endian.h

Fixes a compilation failure on Windows.   This failure isn't triggered on any of our other platforms.  Essentially, we should have been using OME_HAVE_NOEXCEPT (see `cpp/cmake/CompilerChecks.cmake` and `cpp/lib/ome/common/config.h.in`).
Testing: CI jobs should remain green.  There's not much in the way of practical testing at this point.

cpp: common: Correct Boost.Endian C++11 noexcept macro

---

components/xsd-fu/templates-cpp/OMEXMLModelObject.template
components/xsd-fu/templates-cpp/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template

Converts the OME-XML model objects to use the pImpl data-hiding idiom to avoid the exposure of internal implementation details in our public headers.  This is for current and future Windows porting efforts to reduce the number of exported templates in DLLs.
Note: this increases the number of memory allocations and may have a performance impact.  Check the performance of the merge build tests with the previous builds to make sure it hasn't regressed significantly.  It uses `shared_ptr` to own the `Impl` object, but could use a bare pointer with a `delete` in the destructor.  This isn't done since this way it's easily switched for `unique_ptr` down the line which will have other bigger performance benefits such as being able to emplace objects and avoid a lot of overhead in copying and …

cpp: ome-xml: Use pImpl idiom in OMEXMLModelObject classes

---

cpp/cmake/XsdFu.cmake

If xsd-fu execution fails when obtaining output or dependency file lists, abort with error.  Previously, errors were silently ignored.
-------
Testing: On a normal system, errors will not be encountered.  If you write some junk into the top of components/xsd-fu/xsd-fu and then run cmake, you'll see an immediate abort with an error message.

cmake: Add error checking for xsd-fu invocation

---

components/xsd-fu/templates-cpp/OMEXMLModelEnum.template

The string_map and value_map static maps were not protected with a static method, required to prevent use in other translation units ahead of construction in the program's static initalisation phase. Wrap these and also the lowercased string map (for case-insensitive lookups) in static methods, and use these methods where the plain maps were originally used.  We did have two static methods, but they just returned a reference to the static maps; they now implicitly initialise and fill the maps on their first invocation.
This is needed for Windows, though it's actually buggy on all platforms.  The reason it worked on Unix is that when using shared libraries, the static initialisation of each shared library is done in dependency order, but when using static libs this implicit ordering no …

xsd-fu: Correct static initialisation order for enum key-value mappings

---

cpp/lib/ome/bioformats/MetadataMap.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/PixelBuffer.h
cpp/lib/ome/bioformats/XMLTools.cpp
cpp/lib/ome/bioformats/detail/FormatReader.cpp
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/in/OMETIFFReader.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
cpp/lib/ome/bioformats/tiff/IFD.cpp
cpp/lib/ome/bioformats/tiff/ImageJMetadata.h
cpp/lib/ome/bioformats/tiff/TIFF.cpp
cpp/lib/ome/xml/meta/Convert.cpp
cpp/lib/ome/xml/model/detail/OMEModelObject.cpp

Fixes warnings about unused variables with MSVC.  GCC and clang don't seem to treat unused exceptions as being problematic.  Comment out as for unused function arguments.
Also mark a couple of exceptions as `const` or else they won't be caught (since all exceptions are const).
--------
Testing: Just check the jobs are green.

cpp: bioformats: Correct unused variable warnings in catch statements

---

cpp/test/ome-bioformats/formatreader.cpp
cpp/test/ome-common/mstream.cpp

This change fixes the nonstandard use of iterators in these unit tests.  This doesn't work on Windows--dereferencing an end iterator is not really allowed but works fine with GCC and Clang.  Use a pointer to the start and size instead, or pointer to the start and pointer to one-past-the-end as pointer arithmetic without using iterators.
--------
Testing: Covered by the mstream unit test; check jobs are green.

cpp: common: Correct string iterator use in mstream and formatreader tests

---

cpp/lib/ome/compat/regex.h
cpp/test/ome-common/units.h

The output of floating point exponents is slightly different for MSVC--it uses three digits rather than two when there are only two significant digits.  This is not specified by the C++ standard and so implementations can differ slightly.  Adjust the output to match what is expected by removing the leading zero with a regular expression.
See http://stackoverflow.com/questions/9226400/portable-printing-of-exponent-of-a-double-to-c-iostreams for some background.
--------
Testing: Check jobs are green (https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp/).  Should be a no-op for the existing Unix CI jobs.  Not tested by the windows jobs yet but will be once the other pending PRs are merged and we can turn on a full Windows build of the whole bioformats library set.

cpp: common: Correct units test for MSVC stream output

---

docs/sphinx/developers/cpp/overview.txt

Currently, all boost dependencies are missing from the
centos Quick Start. Without any boost, or with only
`boost` or `boost boost-regex` the following error
occurs:
```
centos6_1 | -- Performing Test OME_HAVE_BOOST_REGEX
centos6_1 | -- Performing Test OME_HAVE_BOOST_REGEX - Failed
centos6_1 | CMake Error at cpp/cmake/RegexChecks.cmake:84 (message):
centos6_1 |   No working regular expression implementation found
centos6_1 | Call Stack (most recent call first):
centos6_1 |   CMakeLists.txt:91 (include)
```
cc: @rleigh-dundee 
see: http://www.openmicroscopy.org/site/support/bio-formats5.1-staging/developers/cpp/overview.html#quick-start

c++ docs: add `boost-devel` as a centos dependency

---

components/formats-gpl/src/loci/formats/in/SimplePCITiffReader.java

See  http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-July/005511.html and QA 11327
Recent version of HCImage seems to have modified the header of the TIFF file. This commit should fix NumberFormatException when parsing the bit depth and fix a following NullPointerException due to the absence of the Capture table.

Fix new exceptions when parsing SimplePCI TIFF

---

components/formats-bsd/test/loci/formats/utests/OMEXMLServiceTest.java
components/xsd-fu/templates-java/OMEXMLModelObject.template

The values of dimensioned quantities were being serialized as floating-point numbers regardless of their definition in the OME-XML model schema. This PR adjusts the serialization so that dimensioned integers are not serialized with a decimal point in their value. Check that the new unit tests make sense and that they pass.

adjust XML serialization of unit property values

---

components/xsd-fu/templates-cpp/OMEXMLModelEnum.template
components/xsd-fu/templates-cpp/OMEXMLModelObject.template
components/xsd-fu/templates-cpp/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template
components/xsd-fu/templates-cpp/OMEXMLModelObject_XMLAnnotation_update_Value.template

While GCC and Clang provide certain guarantees with regard to the initialisation order (or at least, do so in practice), this is not the case with MSVC.  This PR removes all static variables in the unnamed namespace in the enum template, as well as the XML namespace in the model object template.  It also fixes a potential problem with iterators which MSVC seemed to object to but which the other compilers were happy with.
--------
Testing: Check jobs are green (https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp).  Double-check the code generation changes look sane.

xsd-fu: Correct static initialisation order issues in the C++ templates

---

components/formats-api/src/loci/formats/meta/ModuloAnnotation.java
components/formats-gpl/matlab/bfopen.m
components/formats-gpl/src/loci/formats/in/CellH5Reader.java
components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/VeecoReader.java
components/formats-gpl/src/loci/formats/in/ZeissLMSReader.java
components/formats-gpl/src/loci/formats/in/ZeissTIFFReader.java
components/formats-gpl/src/loci/formats/services/JHDFService.java
components/formats-gpl/src/loci/formats/services/JHDFServiceImpl.java
components/formats-gpl/src/loci/formats/tools/MakeDatasetStructureTable.java
components/formats-gpl/test/loci/formats/utests/JHDFServiceTest.java
components/formats-gpl/test/loci/formats/utests/MissingJHDFServiceTest.java
components/xsd-fu/setup.py
docs/sphinx/about/index.txt
docs/sphinx/about/whats-new.txt
docs/sphinx/conf.py.in
docs/sphinx/developers/export.txt
docs/sphinx/developers/index.txt
pom.xml

This is the Bio-Formats equivalent of https://github.com/openmicroscopy/ome-documentation/pull/1245.
- all Trac URLs are reviewed to use `https://trac.openmicroscopy.org`
- the remaining `Source code` blocks which were not cleaned up as part of https://github.com/openmicroscopy/bioformats/pull/1455 are removed
- some outdated Trac links are redirected to the appropriate resources (documentation, downloads)

Trac URLs cleanup

---

components/formats-bsd/src/loci/formats/in/ICSReader.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

See https://trello.com/c/nO35TKXK/4-units-and-readers
This PR modifies the storage of time metadata in the BSD formats to use the native time unit when appropriate. The `pixelSizes` variable in the `ICSReader` is also renamed as `scales` to prevent confusion as it applies both to the pixels physical size and the pixels time increment.

Formats-bsd: native time units

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

ref: https://trac.openmicroscopy.org/ome/ticket/12967
Testing instructions : 
See fileset uploaded in ​https://www.openmicroscopy.org/qa2/qa2/qa/feedback/11308/
Run:
showinf -nopix -omexml MFGTMP_150418130002_A01f111d0.C01 
do the same for files under: /Volumes/ome/data_repo/from_skyking/cellomics/qa-7352/test/
Run:
showinf -nopix -omexml /Volumes/ome/data_repo/from_skyking/cellomics/qa-7352/test/MFGTMP-PC_130509120002_B02f00d0.C01 
This should not throw any exceptions.
Without this PR: throws an IndexOutOfBoundsException.
Extra Check:
And Try the files on ImageJ as well! Opening just one series during the import.
Check if both the filesets open without any exceptions.

CellomicsReader:Fix for sparsely populated fields

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/bitplane-imaris.txt
docs/sphinx/supported-formats.txt

http://open.bitplane.com/Default.aspx?tabid=268 was announced today, see http://www.bitplane.com/news/bitplane-makes-the-ims-file-format-open-source-130815.
As the documentation is now publicly available, the openness rating is also increased accordingly.

Add new public Imaris HDF documentation to the format page

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/dicom.txt

The wiki page on free health software has had the subheadings removed even though the content is still there so this missing anchor link is making the build unstable.

Remove defunct anchor link from DICOM page

---

cpp/cmake/External_tiff_files/libtiff/CMakeLists.txt

The target properties for the libtiffxx library were being erroneously applied to libtiff, which broke the symbol versioning of exported symbols.  This didn't affect the build, but did make the binaries incompatible with the libtiff built by Linux distributions.  This corrects the target names.
--------
Testing: get a Linux superbuild artefact from https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild/BUILD_TYPE=Release,CXXSTD_AUTODETECT=OFF,node=cod/
Run `objdump -p` on `libtiff.so.5` and you should see toward the end of the output:
```
Version definitions:
1 0x01 0x0bba1ce5 libtiff.so.5
2 0x00 0x0dfcf290 LIBTIFF_4.0
```
If you repeat with a build from before today, the latter version will be LIBTIFFXX_4.0.  This demonstrates that the versioning is now correct.  Also, do …

cmake: Correct tiff superbuild symbol versioning properties

---

cpp/cmake/ExternalProjectEnvironment.cmake
cpp/cmake/ExternalProject_cmake_build.cmake
cpp/cmake/ExternalProject_cmake_install.cmake

Add verbose sub-project building with the Ninja generator when doing a superbuild.
Also consolidates the build logic in `ExternalProject_cmake_build.cmake` to be the same for all generators.
--------
Testing: Configure with
```
cmake -G Ninja -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -Dbioformats-superbuild:BOOL=ON ... /path/to/bioformats
```
with whatever additional options you like.  When you run `ninja` to do the build, you will get verbose output for the sub-project builds.  You can use `ninja -v` to make the top-level build verbose as well.  Without this patch, there will be very little detail for progress and diagnostics from the sub-project builds.

cmake: Allow verbose sub-builds with Ninja generator

---

cpp/lib/ome/bioformats/MetadataMap.h
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/bioformats/MetadataTools.h
cpp/lib/ome/bioformats/detail/FormatReader.h
cpp/lib/ome/bioformats/tiff/TIFF.cpp
cpp/lib/ome/common/config.h.in
cpp/lib/ome/common/variant.h
cpp/test/ome-bioformats/CMakeLists.txt
cpp/test/ome-bioformats/metadatamap.cpp
cpp/test/ome-common/variant.cpp
cpp/test/ome-xml/CMakeLists.txt

- Use correct wide TIFF open call
- Boost.Variant/lexical_cast include ordering fixes
--------
Testing: Will be tested by https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/ once included in the merge build and the job is updated.  Also check https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp/ to ensure that it hasn't broken the Unix builds.

C++: Final fixes to build on Windows

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

Instead use Double.valueOf() directory to create a Double instance for both timestamps and exposure times.
Follow-up of https://github.com/openmicroscopy/bioformats/pull/1913#issuecomment-130858035
Tests should remain green with this change.

MicromanagerReader: do not return intermediate primitive double

---

components/test-suite/src/loci/tests/testng/ConfigurationTree.java
components/test-suite/src/loci/tests/testng/TestTools.java

Follow up of https://github.com/openmicroscopy/bioformats/pull/1894 and https://github.com/openmicroscopy/bioformats/pull/1819.
While the external configuration logic works accurately on Linux and Windows for the main folder, this PR attempts to solve the case of data folders containing symlinks e.g. `test_images_good`. With the data repository structure being organized as follows:
```
/ome/data_repo/test_images_good      # folder containing symlinks to the data /ome/data_repo/from_skyking/
/ome/data_repo/config/breaking           # folder containing configuration files
```
the goal of this PR is to resolve the symlinks and the configuration files with the following command:
```
ant test-automated -Dtestng.directory=/ome/data_repo/test_images_good …
```

Fix automated tests to handle symlinks with external configuration

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

See https://trello.com/c/w49BvpYX/11-save-imagej-metadata-in-tiff.
To test, use ```bfconvert``` to convert any file with SizeZ and/or SizeC > 1 to TIFF and check the output of ```showinf -nopix``` on the converted file.  I used ```test_images_good/andor/FURA-2CH-T.tif```, but anything will do.
The test without this change should result in the converted file having SizeZ == SizeC == 1, with all planes stored in T.  With this change, the Z, C, and T sizes should match between the original and converted files.

TIFF export: save dimensions in ImageJ-style comment

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

In addition to the pyramid images and the macro slide image, some NDPI files contain a trailing image associate to a mask or activation map. Previously, this was handled by assuming the last series only was not part of the pyramid for data with sizeZ=1. This commit uses the tag 65421 instead to determine the macro slide image (-1) and the mask (-2) if applicable.
- check the automated tests remain green
- import `npdi` samples into OMERO with this PR included into Bio-Formats. Check either 2 or 3 images are created depending on the file and that the pyramid image and the macro slide image are always imported as separate images.

Handle NPDI files with macro slide image and mask image

---

components/specification/released-schema/2008-02/catalog.xml

Found while working on catalogue processing and the duplicate/inconsistent filename for the same system ID caused it to throw an exception.
--------
Testing: none.  There's nothing using this particular catalogue at the moment, so just confirm it's matching the `2008-02` schema.

specification: Correct incorrect catalogue entry

---

components/formats-gpl/src/loci/formats/in/IPWReader.java
components/formats-gpl/src/loci/formats/in/ImarisHDFReader.java
components/formats-gpl/src/loci/formats/in/ImarisReader.java
components/formats-gpl/src/loci/formats/in/L2DReader.java
components/formats-gpl/src/loci/formats/in/LiFlimReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java
components/formats-gpl/src/loci/formats/in/TillVisionReader.java

This PR rewrites some GPL reader code in a minor way to increase readability and/or efficiency:
* ImarisHDFReader
* ImarisReader
* IPWReader
* L2DReader
* LiFlimReader
* SVSReader
* TillVisionReader
CI does the testing.

minor code adjustments to several GPL readers

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

If the tag defining the macro/map images is not defined, fallback to the legacy behavior assuming the last IFD is the macro image for non multi-Z NDPI images.
Follow-up of https://github.com/openmicroscopy/bioformats/pull/1935

Prevent potential NullPointerException while checking the pyramid height

---

components/formats-gpl/src/loci/formats/in/PCIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12886.
To test, use the file from QA 11073.  Without this change, SizeX should be 397, and the images should look incorrect as noted in the file attached to the ticket.  With this change, SizeX should be 398, and the images be an obvious split field of view with moving artifacts (you will likely need to open in ImageJ to see this, as it's 16-bit data).

SimplePCI .cxd: adjust SizeX if extra bytes are stored in the planes

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12996.
To test, use the file from QA 11361.  Without this change, the first channel's color should be black; with this change, the channels should be red and green.  This is easiest to see in ImageJ; you'll probably need to open the brightness/contrast window.

CZI: fix channel colors when alpha is not recorded

---

components/formats-bsd/src/loci/formats/in/NativeQTReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12888.
To test, use the file from QA 11074.  Without this change, ```showinf``` on the file will throw an exception as noted in the ticket.  With this change, ```showinf``` should display the entire time series, which can be compared against ```mplayer``` (or some other video player).

QT: use the previous plane if there is no data for the current plane

---

docs/sphinx/conf.py.in

While this shouldn't be encountered in practice (it's a default python2 module?), it was mentioned as a problem by a user on IRC.  This moves the urllib import into the existing try block so that if the import fails, it's not a fatal error.  May also ease future python3 porting, since the docs are likely already buildable directly with a python3 version of sphinx-build.
--------
Testing: Check the jobs are green.

docs: Use urllib conditionally

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12864.
To test, use the file from QA 11049.  Without this change, ```showinf``` should throw an exception as in the ticket; with this change ```showinf``` should report 3 series (to match ```tiffinfo *.scn | grep -c "TIFF Directory"```), all of which should be viewable with ```showinf```/ImageJ.

Leica SCN: do not report more resolutions than there are IFDs

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12993.
To test, use the file attached to the thread in the ticket.  Without this change, all 8 series had all 0 pixel values.  With this change, every plane in each series should match what is shown in Zen.  This is probably easiest to test in ImageJ, optionally with the ```Open all series``` and ```Stitch tiles``` options selected.

CZI: fix coordinates of pre-stitched tiles

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java
docs/sphinx/developers/commit-testing.txt

See https://trello.com/c/wT2zpjrM/41-add-documentation-for-automated-test-output
This PR reviews and updates the content of the Sphinx documentation about automated tests. Additionally, this downgrade the `FormatReaderTest` memo file size and used files lines to `DEBUG` level so that it does not appear in the main console output (but should still be logged in thread log files).

Automated tests documentation

---

components/formats-gpl/src/loci/formats/in/BaseZeissReader.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/src/loci/formats/in/NikonElementsTiffReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java
components/formats-gpl/src/loci/formats/in/ZeissZVIReader.java

This PR rewrites some GPL reader code in a minor way to increase readability and/or efficiency:
* BaseZeissReader
* NativeND2Reader
* NikonElementsTiffReader
* ZeissLSMReader
* ZeissZVIReader
CI does the testing.

minor code adjustments to Zeiss and Nikon readers

---

docs/sphinx/developers/jace/build.txt

Document that Java 6 or 7 is needed, and that Java 8 is not supported.

docs: Document JACE JVM restrictions

---

components/formats-gpl/src/loci/formats/in/SDTReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12893.
To test, use the files from QA 11079.  Without this change, the compressed file should have obviously wrong image data when compared with the uncompressed file.  With this change, the images for both files should match.
/cc @imunro

SDT: add support for Zip-compressed data

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12743.
To test, use the .tif file from QA 10514.  Compare the output of ```showinf -nopix`` with and without this change; there should be noticeably more metadata shown with this change.

FEI TIFF: parse metadata from the Titan system tag

---

components/formats-gpl/src/loci/formats/in/LeicaReader.java

If a TIFF for a particular series was modified/re-exported with a
different pixel type or endianness, then it won't match the values
stored in the .lei file.  This defers to pixel type and endianness
setting for each series to the first corresponding TIFF file.
Fixes https://trac.openmicroscopy.org/ome/ticket/12910.
To test, use the dataset from QA 11114.  Without this change, both series in the .lei file should have pixel type uint8 and be big-endian; reading the second series will result in an exception as noted in the ticket.  With this change, the second series should have type uint16, be little-endian, open without exception, and have reasonable-looking pixel values (you will likely need to open in ImageJ with autoscaling to see this).

Leica .lei: set pixel type and endianness using the TIFFs

---

components/formats-gpl/src/loci/formats/in/LIFReader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/ConfigurationTree.java

See https://trello.com/c/IqYrynEi/98-store-lif-descriptions.
To test, use the file linked from Dropbox on the above card.  Open in Leica LAS AF Lite and verify that image ```10``` and image ```12``` have something in the ```Description``` box (when you right-click the image name and select ```Properties of ...```).  Verify that the output of ```showinf -nopix -omexml``` with this change shows matching text in the ```Description``` attribute of ```Image:9``` (```Name``` == ```10```) and ```Image:11``` (```Name``` == ```12```).  WIthout this change, ```Description``` would have been missing for all Images.

Leica LIF: set descriptions based upon the user comment

---

ant/java.xml
components/formats-gpl/build.properties

See https://trello.com/c/ukrm7pbD/25-make-sure-dlls-end-up-in-formats-gpl-jar.
To test, check the output of ```jar tf artifacts/formats-gpl.jar``` and ```jar tf artifacts/bioformats_package.jar``` without this change.  Verify that no .dll files are present in formats-gpl.jar, and the only .dll files present in bioformats_package.jar correspond to Turbojpeg.
The same commands with this change should show two .dll files in the META-INF directory of formats-gpl.jar; the same two files should be present in bioformats_package.jar.

Fix .dll packaging in formats-gpl

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java
components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java
components/test-suite/src/loci/tests/testng/TestTools.java

SlideBook6Reader is bundled with Bio-Formats on Windows only and is maintained externally. Until we have a proper API in place allowing reader discovery, this commit should allows to remove it from the list of readers when running automated tests against the data repository.

Automated tests: remove SlideBook6Reader class from ImageReader

---

components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

replace gh-1934
This fix is related to https://github.com/openmicroscopy/openmicroscopy/pull/4045
It improves the heuristic for finding out, whether to call `roi.setPosition(int)` or `roi.setPosition(int, int, int)` based on the dimensionality of the image that the ROI is associated with.
cc @stelfrich
Make sure that this change does not affect the other scenarios

Add CZT positions computation for non-hyperstacks

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#5](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/5/).
----
--no-rebase

Update POM version numbers to 5.1.4

---

.travis.yml
tools/test-build

gh-1965 was merged into the daily build and had priority HIGH
findbugs warnings. If findbugs had been activated in travis,
the build status wouldn't have allowed merging.
A possible next step would be to activate findbugs on every
compile.
**Note:** in order to speed up travis (after slowing it down with
findbugs), the `cpp` and and the `sphinx (pdf)` targets have been
removed. This permitted a move to the container-based travis
builds. These removed components are currently being tested by
jenkins.
See: https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-5.1-merge-build/1009/findbugsResult/

Container travis with findbugs

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#8](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/8/).
----
--no-rebase

Update POM version numbers to 5.1.5-SNAPSHOT

---

docs/sphinx/conf.py.in

With the current sphinx version 1.3.1 the pdf creation fails with a
undefined control sequence error. This bug is allready fixed upstream
but is not released yet. See: https://github.com/sphinx-doc/sphinx/issues/1923
The fix will require to define babel as an empty string, this is what
this commit is for.

Fix babel include for upcomming sphinx 1.3.2

---

components/xsd-fu/templates-cpp/OMEXMLModelEnum.template

The `.str()` method of `boost::format` is now required; the format object does not provide a stream operator.
This is a tiny tweak to allow building with the newly-released Boost 1.59.  It will continue to work with older Boost versions.  Boost 1.59 will be coming to homebrew shortly, and Linux distributions over the next few months, so it's important to be able to continue to build on them.
Testing:
Testing with older versions will occur via the non-superbuild CI builds:
- https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp/
Testing with Boost 1.59 will occur with a PR to update the superbuild to use Boost 1.59.
- https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild/
- https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-merge-cpp-superbuild-win/

cpp: ome-xml: Correct Boost.Format use for Boost 1.59

---

cpp/lib/ome/bioformats/tiff/TileInfo.cpp

The calculation here is wrong.  Unit tests are working on square images so the discrepancy wasn't caught.  Not sure why it was ever thought to be correct, but it at least makes sense now.  We should add unit tests for non-square images as well--needs additional PNG test images adding.
Testing: Use http://nyloc.de/public/test.ome.tif
Apply this patch and build:
```
diff --git a/cpp/lib/ome/bioformats/tiff/IFD.cpp b/cpp/lib/ome/bioformats/tiff/IFD.cpp
index eb87c0d..9a92755 100644
--- a/cpp/lib/ome/bioformats/tiff/IFD.cpp
+++ b/cpp/lib/ome/bioformats/tiff/IFD.cpp
@@ -303,6 +303,7 @@ namespace
}
else
{
+              std::cerr << "Reading TIFF tile " << tile << "\n";
tmsize_t bytesread = TIFFReadEncodedStrip(tiffraw, tile, tilebuf.data(), static_cast<tsize_t>(tilebuf.size())); …
```

cpp: TileInfo: Correct tile row and column count computation

---

components/bio-formats-plugins/src/loci/plugins/About.java

The scope of the PR is limited to cosmetic appearance of a dialog box.
* Place the new `bio-formats_plugins.jar` in an ImageJ installation.
* Run Help &#9654; About Plugins &#9654; Bio-Formats Plugins...
* Verify that the dialog is less wide than before, since the 40-character commit hash is now on its own line.

Make the About Bio-Formats dialog less wide

---

cpp/lib/ome/bioformats/CMakeLists.txt

The PlaneRegion.h header file was missing in the CMakeList.txt which
caused the file not to be installed via make install. Wich in turn
resulted in "No such file or directory" compiler errors if one tried to
use the installed libraries.

Add PlaneRegion.h to CMakeLists.txt

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

To fix the physical Z size, the difference between the absolute Z
positions will need to be used.
MetaMorph handler already parses the z positions. The physical z size is
then calculated by subtracting the top and bottom values and dividing by
the number of steps.
Ticket details below:
https://trac.openmicroscopy.org/ome/ticket/12977
Splitting from https://github.com/openmicroscopy/bioformats/pull/1964

Incorrect VoxelSize in MetaMorph Reader

---

components/bio-formats-plugins/src/loci/plugins/in/ImportProcess.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterOptions.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterPrompter.java
components/bio-formats-plugins/src/loci/plugins/in/importer-options.txt

ImageJ plugin - Exception when both 'group files' and 'open individually' options selected
A test case and steps to reproduce are linked from the ticket.
https://trac.openmicroscopy.org/ome/ticket/12941
Splitting from https://github.com/openmicroscopy/bioformats/pull/1964
Issues included:
- IndexOutOfBoundsException when both options selected in Main Dialog
- For certain file formats the regular expression and 'file contains'
file patterns were not being implied
- Entering incorrect values into the Dimensions setting of the
FilePatternDialog resulted in a 'File is not of a supported format'
error
Solution:
- IndexOutOfBoundsException resolved in ImportProcess by reading the
group files option. When both options are selected then group files is
not automatically the inverse of ungroup …

ImageJ plugin - Group files Exception 

---

cpp/lib/ome/bioformats/CMakeLists.txt
cpp/lib/ome/qtwidgets/CMakeLists.txt
cpp/lib/ome/xml/CMakeLists.txt

to follow the general practice
I'm currently packaging the bioformats c++ libraries for my arch linux system and came across this. joshmoore (from the #ome IRC channel) said creating a pull request to get comments on this should be ok.
Some projects like to add a version number to the directory in the cmake dir. I hope that just using ome is ok.

Change the install path of cmake specific config files

---

docs/sphinx/developers/format-documentation.txt
docs/sphinx/developers/index.txt

See https://trello.com/c/bGwmDei8/8-document-how-to-add-update-format-pages
This PR adds a first version of a developer documentation page explaining how the formats and readers pages are generated and can be modified.
/cc @hflynn

Add documentation page on the autogenerated documentation

---

tools/source-archive.py

This script creates both a zip and tar source release.  The zip file is unfortunately incompatible with some extractors, making it break the superbuild on a number of platforms using libarchive to extract.  This includes Ubuntu and BSD systems using the current release of libarchive when using "cmake -E tar xfv" to extract the zips (done in the superbuild).  Since fixing these platforms won't happen in the short-term, making an archive they can extract is a simpler solution.  The content is exactly the same as the zip.
Using a current CMake downloaded from cmake.org for e.g. Windows or Linux works fine since they use a newer (unreleased) copy of libarchive git, where the bug is fixed.  Unfortunately for Ubuntu and BSD systems (and likely others) which provide cmake linked against their …

source-archive: Make tar source release

---

docs/sphinx/conf.py.in
docs/sphinx/developers/cpp/overview.txt

This is to match the content on the download page here: http://downloads.openmicroscopy.org/bio-formats-cpp/5.1.4/ as well as the changes to the build instructions.

cpp: Document new superbuild build instructions

---

components/xsd-fu/templates-java/OMEXMLModelObject.template
cpp/cmake/CompilerChecks.cmake
cpp/lib/ome/bioformats/MetadataTools.cpp
cpp/lib/ome/qtwidgets/CMakeLists.txt
cpp/lib/ome/qtwidgets/GLView2D.cpp
cpp/lib/ome/qtwidgets/GLView2D.h
cpp/lib/ome/qtwidgets/NavigationDock2D.cpp
cpp/lib/ome/qtwidgets/NavigationDock2D.h
cpp/lib/ome/qtwidgets/gl/Axis2D.h
cpp/lib/ome/qtwidgets/gl/Grid2D.h
cpp/lib/ome/qtwidgets/gl/Image2D.h
cpp/lib/ome/qtwidgets/glm.h
cpp/lib/ome/qtwidgets/glsl/v110/GLFlatShader2D.cpp
cpp/lib/ome/qtwidgets/glsl/v110/GLFlatShader2D.h
cpp/lib/ome/qtwidgets/glsl/v110/GLImageShader2D.cpp
cpp/lib/ome/qtwidgets/glsl/v110/GLImageShader2D.h
cpp/lib/ome/qtwidgets/glsl/v110/GLLineShader2D.cpp
cpp/lib/ome/qtwidgets/glsl/v110/GLLineShader2D.h
cpp/lib/ome/xml/Document.h
cpp/test/ome-bioformats/minimaltiffwriter.cpp
cpp/test/ome-bioformats/ometiffwriter.cpp
cpp/test/ome-bioformats/tilecache.cpp
cpp/test/ome-bioformats/tilecoverage.cpp
cpp/test/ome-bioformats/variantpixelbuffer.cpp
cpp/test/ome-common/boolean.cpp
cpp/test/ome-common/variant.cpp
cpp/test/ome-xml/model.cpp

Ignore these warnings:
-  -Wvariadic-macros
-  -Wunused-local-typedef
-  -Wlanguage-extension-token
-  -Wold-style-cast
These had an exeedingly large number of false positives, particularly in external library headers, and these masked real warnings by the sheer volume.
With these warnings ignored, a number of real warnings were exposed which are fixed here.  This should significantly reduce the size of the build log.
--------
Testing: no special testing required; check CPP jobs are green.

cpp: Remove additional warnings

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

Bug: DICOM incorrect maxPixelValue
DICOM incorrect maxPixelValue
For DICOM images using photometric interpretation MONOCHROME1,
bioformats needs to invert the pixel the data. For 16 bit data we had
been using the WINDOW_WIDTH property as a max pixel value, instead this
actually provides us with the pixel range and is not clipped to 0.
Code has been updated to try and read the WINDOW_CENTER value (the
central value in the range) in order to work out an appropriate scale.
If this is not available or not a sensible value then we will use the
full max pixel range.
OME-Users message:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-September/00
5629.html
QA: https://www.openmicroscopy.org/qa2/qa/feedback/11401/
For info on the WINDOW_WIDTH and WINDOW_CENTER properties: …

Dicom max pixel value bug

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13023.
To test, use the file from QA 11381.  Without this change, the image size was 1280x2048 and the images should have diagonal stripes.  With this change, the image size should be larger in both dimensions, and there should be an obvious artifact (which can be compared against almost any other DICOM viewer).
This may conflict with gh-1989; I'll exclude this one if that turns out to be the case.

DICOM: use the last row and column tags instead of the first

---

components/formats-gpl/src/loci/formats/in/ScanrReader.java

See https://trello.com/c/6HeWtnVY/2-idr0009-simpson-secretion-embl-secretion-primary-and-secondary-screen.
/cc @joshmoore, @eleanorwilliams

ScanR: return blank planes instead of skipping missing wells

---

components/formats-bsd/src/loci/formats/FileStitcher.java

This PR fixes a problem where the `ExternalSeries` constructor in `FileStitcher` initializes only the first of its readers. A simple way to trigger the bug is to call `reopenFile` on a `FileStitcher` whose ID is a pattern that expands to more than one element, such as `foo<1,2>.tif`. This leads to a `java.lang.IllegalStateException` as soon as the first reader with a null ID is encountered.

FileStitcher: call setId on all readers in ExternalSeries

---

pom.xml

The conditional for deciding when to build the tests JAR was wrong, because it was keyed to `src/test/java/` instead of `test/`.
Consequently, no `*-tests.jar` files were being produced.
To test, perform a clean Maven build, and then verify that the `*-tests` artifacts are now present. I.e.:
```bash
$ mvn clean
...
$ mvn
...
$ for t in components/*/test/; do echo $t; done
components/bio-formats-plugins/test/
components/formats-api/test/
components/formats-bsd/test/
components/formats-common/test/
components/formats-gpl/test/
components/metakit/test/
components/ome-jxr/test/
components/ome-xml/test/
$ ls -l **/target/*-tests.jar
-rw-r--r--  1 curtis  staff   32732 Oct  6 10:45 components/bio-formats-plugins/target/bio-formats_plugins-5.1.5-SNAPSHOT-tests.jar
-rw-r--r--  1 curtis  staff …
```

Fix activation of test-jar profile

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/specification/src/ome/specification/XMLMockObjects.java

This PR adds a flag to the fake filename, `screens=n` to create multiple screens, in particular `screens=0` will allow for no containing Screen to be created when a Plate is created. The omission of the flag maintains the current behaviour, to create a containing Screen, ie it is equivalent to `screens=1`.
Is this sufficient or are there other areas of the codebase that need to accommodate this change? If this is reasonable then there will also need to be a minor change to the docs.
To test, via OMERO,
```
$ touch "SPW&plates=1&plateRows=1&plateCols=1&fields=1&plateAcqs=1&screens=0.fake"
$ omero import "SPW&plates=1&plateRows=1&plateCols=1&fields=1&plateAcqs=1&screens=0.fake"
```
should import a Plate with no Screen. Importing files
```
$ touch …
```

Allow fake plates to have multiple screens, including none.

---

docs/sphinx/developers/cpp/overview.txt

Noted during release testing, documenting as requested.

docs: Document C++ super-build library dependency caveat

---

components/autogen/build.xml
components/autogen/src/MakeDatasetStructureTable.java
components/autogen/src/format-pages.txt
components/formats-gpl/build.xml
components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java
components/formats-gpl/src/loci/formats/in/GatanReader.java
components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java
docs/sphinx/developers/format-documentation.txt
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/gatan-digital-micrograph.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/2y71bKRs/24-gatan-dm4-support. This PR:
- migrates the dataset structure creation class to the `components/autogen` component
- registers the `dm4` extension in `GatanReader` and in `format-pages.txt`
- fix URL in `SlideBook6Reader` post format pages unification
- regenerates the format pages and dataset structure table
A CI-related task will be to add the `gen-structure-table` to the BIOFORMATS-*-docs-autogen job to keep this table in sync with the latest state of the readers.

Add dm4 to the supported extensions and other doc improvements

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java

User reported bug:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-September/005658.html
Using the stamps data (position data for dimensions other than X and Y)
to retrieve a list of physical z values. By identifying the unique
values and ensuring we have a correct number of values, we can average
the correct physical z size.

Physical Z Size for Andor Tiff

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/z0ZIeT8e/22-version-history-prs
I didn't add C++ changes, on the assumption that those will be written up separately due to the difference in release dates.  Happy to add text in this PR though if that's preferable.

Add version history for 5.1.5

---

pom.xml

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2011.
The PR inadvertently broke https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-maven/507/. The reason is that the activation of the `test-jar` profile deactivated the profile marked as "active by default" (see http://maven.apache.org/guides/introduction/introduction-to-profiles.html) which defines the default deployment configuration. Thus the `mvn clean deploy` command is currently broken whereas `mvn clean deploy -Platest-build` will deploy artifacts as expected.
This commit proposes to remove the requirement for a conditional activation profile in favor of building test JARs unconditionally for every component. Components like xsd-fu with no `test` directory will simply create dummy test JARs (like the `xsd-fu` …

Remove activation profile for building test JARs

---

components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/MNGReader.java
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/gatan-digital-micrograph.txt
docs/sphinx/formats/iplab-mac.txt
docs/sphinx/formats/pgm.txt
docs/sphinx/metadata/MNGReader.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/tpoKZjRa/35-metadata-pages-follow-up
Minor generated documentation improvements for 5.1.5 /cc @hflynn 
None of the format pages have been renamed to prevent breaking URLs, but `Portable Any Map` and `iVision` format pages should likely be renamed to reflect the new name in 5.2.x

Metadata improvements

---

docs/sphinx/about/whats-new.txt

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2019

Add C++ version history for 5.1.5

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#11](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/11/).
----
--no-rebase

Update POM version numbers to 5.1.5

---

docs/sphinx/developers/cpp/tutorial.txt

Correct two broken links for 5.1.5.
/cc @hflynn

docs: Update tutorial doxygen links

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#12](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/12/).
----
--no-rebase

Update POM version numbers to 5.1.6-SNAPSHOT

---

components/formats-gpl/matlab/bfGetFileExtensions.m

This has two commits.  The first is an issue reported on the Octave mailing list by Philip Nienhuis (no github account)
> bfGetFileExtensions.m:
> ----------------------
> ...when run in Octave chokes on
>    fileExt{i, 2} = char(readers(i).getFormat().toString)
> 
> error: sq_string cannot be indexed with .
> error: evaluating argument list element number 1
> 
> ....probably because readers(i).getFormat() is already (un)boxed to a char string.
> See attached patch1 for a fix.
According to [Matlab documentation](http://uk.mathworks.com/help/matlab/matlab_external/handling-data-returned-from-a-java-method.html#f61197), `java.lang.String` objects should be automatically converted into char arrays:
> When a method call returns data of type java.lang.Object, MATLAB converts its value, …

octave - drop unecessary String::toString and char()

---

components/formats-bsd/src/loci/formats/services/JPEGTurboServiceImpl.java

User reported issue: http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005678.html
Sample file: https://drive.switch.ch/public.php?service=files&t=f006627509d481a9af386e1b90efb1eb
For unregular sized tiles (ie tiles at the end of the row), we were
using the width of the tile to increase the input to be copied from the
tile array to the image array. However the tile array which we use still
maintains the regular tile dimensions but with sensible data only being
found in the first section of each row.
Steps to reproduce: 
- Import the user submitted file using bioformats
- Open series 1 (note series 0 is extremely large and will require a lot of RAM, series 2 does not have the reported issue)
- Verify that the image displays the unusual pattern as shown in …

Fix for tiling issue

---

components/specification/transforms/util/write-transforms.py

Following discussion at https://github.com/openmicroscopy/bioformats/pull/1999#issuecomment-147967612 this gets a local utility script of mine into version control. `cd components/specification/transforms/` then run `python util/write-transforms.py` to see a suggested replacement for `ome-transforms.xml` in largely its current style, thus avoiding the manual maintenance headache. Followup PRs from @rleigh-dundee or others can then improve the script or even have the transforms file autogenerated, but right now this PR's better than nothing.
--no-rebase

add Python utility script for generating ome-transforms.xml

---

tools/source-archive.py

Previously the tar archives were uncompressed.  This was done for portability--xz isn't available by default on Windows.  This is the most appropriate place for it though; if anyone cares to run it on Windows, they can put xz in their PATH e.g. with cygwin or standalone xz.  The other alternative is Python3, which has this stuff built in, but probably not useful to use that right now.
Testing: run `ant release`; check the two .tar.xz files under `artifacts`.  Unpack them with e.g. `tar -xvf` and check unpacking works and that the content looks OK.  (The actual content is unchanged, just added compression.)
Followup tasks: update merge/latest/release builds to archive these artifacts; update download page to add them (button already exists).

release: xz compress tar archives

---

components/formats-api/src/loci/formats/meta/MetadataConverter.java

In this PR, we do not record the light settings if the light source is not present in the file
This can be the case with 3rd party generated ome-tiff see https://trac.openmicroscopy.org/ome/ticket/13038
test 1
* Open the image from ​https://www.openmicroscopy.org/qa2/qa/feedback/11402/, using BF importer
* Check the "Display OME-XML metadata" option
* Check that there is no ligthsettings under channel and no light source under instrument. W/o this PR, light settings were present under channels
test 2:
* Follow the same steps but this time opened the sample image https://github.com/openmicroscopy/bioformats/blob/develop/components/specification/samples/2015-01/6x4y1z1t1c8b-swatch-instrument.ome. Check that light settings are present under channel.
The image should now …

XML reading

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This allows reopenFile to reopen the helper readers, which prevents
exceptions when calling get*LookupTable() and other state methods after
reopening.
See https://trello.com/c/kjQdHktu/7-ome-tiff-memoization-issues
To test, use ```showinf -cache -crop 0,0,512,512``` with the file from QA 16852 twice in succession.  Without this change, the second run of the command will throw an exception as mentioned in the thread referenced from the above card.  With this change (and after removing the ```.*.bfmemo``` file from the previous test), both commands should display an image without an exception.

OME-TIFF: override reopenFile

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#1](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/1/).
----
--no-rebase

Update POM version numbers to 5.2.0-SNAPSHOT

---

components/autogen/src/FormatPageAutogen.java
components/autogen/src/doc/FormatTable.vm
components/autogen/src/format-pages.txt
docs/sphinx/formats/hamamatsu-ndpi.txt
docs/sphinx/formats/nikon-nis-elements-nd2.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/9yZdHX52/15-mif-checkbox-in-pff-list. The checkbox seemed to make more sense on the supported formats table, but I can move it to the dataset structure table if anyone feels strongly.
Only testing is to read through the last column on the supported formats table and make sure that none of the values look incorrect.

Add a "Multiple Images" column to the supported formats table

---

components/formats-api/src/loci/formats/FormatTools.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Adding support for the following configuration options:
- TimeIncrementUnits
- ExposureTimeUnits
- PhysicalSizeZUnits
- PhysicalSizeYUnits
- PhysicalSizeXUnits
- EmissionWavelengthUnits
- ExcitationWavelengthUnits
When read the string units types will be converted into an appropriate
Length or Time object. If not present the default units will be used instead (mircometres for
sizes, nm for wavelengths and seconds for time).
FormatTestReader now compares Length objects rather than double values.
Extra utility methods added to FormatTools to easily convert from String to appropriate time and wavelength values.

Test suite refactor native units

---

.travis.yml

Since Oracle JDK 7 should be tested via the OME CI infrastructure, testing it on the Travis matrix is redundant with openjdk7.

Travis: Only test openjdk7

---

docs/sphinx/developers/jace/overview.txt

This PR:
- adds the Video Spot Tracker software to the list of projects using the Jace C++ bindings - see http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005690.html
- removes the BF-CPP abbreviation and uses Jace C++ bindings in the documentation instead to prevent any confusion with Bio-Formats C++. /cc @rleigh-dundee

Video spot tracker

---

components/formats-gpl/src/loci/formats/in/IMODReader.java

See https://trello.com/c/nO35TKXK/3-units-and-readers
This PR adjusts the IMODReader to store the physical pixel size read from `imod` files using the native units. The specification for the units can be found at http://bio3d.colorado.edu/imod/doc/binspec.html.
Since one of the samples IMOD file uses the pixel unit (`0`) which that cannot be converted to micrometers, the format reader automated tests are also adjusted to handle this case (using `isConvertible` similarly to what is done in https://github.com/openmicroscopy/bioformats/pull/2030). The size comparison logic used across all physical size tests is also refactored into a single helper method to simplify future maintenance.
For automated tests, this means we do not differentiate the case where the physical size is 1 micron or 1 …

IMODReader: add support for native length units

---

components/bio-formats-plugins/src/loci/plugins/in/Importer.java

https://github.com/openmicroscopy/bioformats/issues/2057
When the importer has been run from an IJ macro, the options list should
not be loaded from preferences but instead read from the macro arguments
only.
In order to test the PR:
Open Fiji and record 2 macros (Plugins -> Macros -> Record)
Now import a multi channel image using bioformats
For the first macro select the split channels option during import, for the second make sure it is unselected
Now import an image again using bioformats and ensure the split channel option is selected. This will save the option to your Image J preferences.
Now rerun your 2 macros and ensure that the image channels are split in one and combined in the other
Now import an image again using bioformats and ensure the split channel option is not selected. …

Fiji preferences not persistent for macros

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

See QA 16887.  Dual camera acquisitions store two channels side-by-side;
this splits the image and records two separate channels.  The same
feature is already present in MetamorphReader.
To test, verify that the file from QA 16887 is 512x512, 2 channels, 200 timepoints, and that the channels are distinct.  Builds should remain green.

Metamorph TIFF: add dual camera support

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

This warns instead of throwing an exception, and ensures that physical
sizes of 0.0 are not allowed.
To test, compare the behavior of ```showinf -nopix -omexml fake/samples/emptySizes&physicalSizeX=0.0.fake```.  Without this change, XML validation should fail; with this change, PhysicalSizeX should not be populated at all.

Fake: warn on invalid physical sizes

---

components/formats-api/src/loci/formats/FormatTools.java

For some readers we have native units that are not logical for the purpose resulting in very low values.
See https://github.com/openmicroscopy/bioformats/pull/2044 for an example.
This proposed change to FormatsTools getPhysicalSize would implement the following logic as suggested in the PR mentioned above:
1.check if the value is greater than  Constants.EPSILON  
2.if so, use whatever unit was supplied
3.if not, convert to the smallest order of magnitude unit such that (1) passes (or the default unit?)
4.if the value really is 0, or is less than  Constants.EPSILON  for even the smallest defined unit, return null
I have also updated getPhysicalSizeX and Y methods to use the same getPhysicalSize function as we had 2 separate workflows depending on if the units were provided as String or …

Format tools units automatic conversion

---

components/formats-gpl/src/loci/formats/in/ZeissLMSReader.java

See https://github.com/CellProfiler/CellProfiler/issues/1686
The ```in``` variable is only initialized during setId, so this changes isThisType to correctly use the ```stream``` that is passed in.
The easiest way to test is to pick any TIFF file (e.g. from test_images_good/tiff/) and compare the results of executing the following code (or something similar) with and without this change:
```
ZeissLMSReader reader = new ZeissLMSReader();
RandomAccessInputStream s = new RandomAccessInputStream("/path/to/tiff");
boolean isLMS = reader.isThisType(s);
s.close();
System.out.println("is LMS = " + isLMS);
```
Without this change, line 3 should throw an NPE; with this change, there should be no exception, and ```is LMS = false``` should be printed.  This is tricky to test with e.g. showinf, as the …

Zeiss LMS: fix stream variable in isThisType

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2050
- makes the configuration of exposure time, emission wavelength and excitation wavelength units channel-specific
- modifies the `populateINI` method to fill unit symbols as well as values
- drops the special test for physical sizes of `0.0` values now the configuration files have been cleaned up.
To test this PR, run
```
ant -f components/test-suite/build.xml gen-config  -Dtestng.directory=/path/to/file
```
ideally on a file containing physical pixel sizes, time increment, channel wavelengths and exposure times. Check the generated `.bioformats` INI file has both the values and the units stored. Then run the automated tests using the newly generated configuration file and check they all pass:
```
ant -f …
```

Test suite: units (2)

---

components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java

See lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005703.html.
Tested with ```slidebook/emma/WT BY4742 Nem1 mcherry genome.sld``` on Windows (with appropriate .dlls).  Without this change, the physical Z size was not set at all; with this change, it is set to the absolute difference between two adjacent Z sections.

Slidebook: fix physical Z size calculation

---

cpp/lib/ome/bioformats/PixelBuffer.h
cpp/test/ome-bioformats/pixelbuffer.h
cpp/test/ome-bioformats/variantpixelbuffer.cpp

This is extremely expensive for some compilers, such as clang++, so disable unconditionally.  It was always disabled for Release builds; this ensures it's also disabled for Debug builds.
Possibly too late for the freeze, but note it's a trivial one-liner which should shave *several hours* off the build time of the slowest builds.
--------
Testing: check that the build times for Debug builds are reduced for both https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-superbuild/ and https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-5.1-merge-win-superbuild/

cpp: PixelBuffer: Disable debug bounds checking

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java

See https://trello.com/c/efn0T64w/18-metaxpress-multi-line-descriptions
Based upon analysis of various Metamorph TIFF samples, the user-entered
freeform description appears to be stored contiguously, and always
before the "Exposure" key.  The "Exposure" key seems to consistently be
the first official standard Metamorph key, with "Binning", "Region",
etc. following in a predictable order.  This commit takes all lines from
the XML description field up to "Exposure" and assembles them into a
single "User Description" entry in the metadata table.
Non-freeform lines with no value are also now stored in the metadata table, with the key and value being the same.
This should match the behavior described in http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-March/005172.html, using the …

Metamorph TIFF: fix parsing of multi-line freeform descriptions

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/IMetadataConfigurable.java
components/formats-api/src/loci/formats/ImageReader.java
components/formats-api/src/loci/formats/in/DefaultMetadataOptions.java
components/formats-api/src/loci/formats/in/MetadataOptions.java
components/formats-api/src/loci/formats/meta/MetadataConverter.java
components/formats-api/src/loci/formats/services/OMEXMLService.java
components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/src/loci/formats/Memoizer.java
components/formats-bsd/src/loci/formats/in/FilePatternReader.java
components/formats-gpl/src/loci/formats/in/ScreenReader.java

This follows on from gh-1969 and replaces gh-2006. The intent is to speed up the performance of the new `ScreenReader` class for cases where there are many (4K+) files each of which takes a significant amount of time to open.
Especially the introduction of the `Memoizer` *inside* of `ScreenReader` may not be a general solution, but until we can inject some form of context, this may be the only type of solution possible.
NB: one further idea would be to write `Reader` subclasses and inject them via `ClassList` but that has its own issues.

screen-reader-2.0 perf

---

cpp/cmake/Options.cmake
cpp/lib/ome/common/module.cpp
cpp/lib/ome/internal/config.h.in
docs/sphinx/developers/cpp/overview.txt

- Add `relocatable-install` option (see https://github.com/ome/ome-cmake-superbuild/pull/11)
- Support path introspection on Windows, to match the existing Unix support
- Drop unused superbuild options (see again https://github.com/ome/ome-cmake-superbuild/pull/11)
----------
Testing: Covered by unit tests on Unix.  On Windows, apply this patch:
```
diff --git a/cpp/lib/ome/common/module.cpp b/cpp/lib/ome/common/module.cpp
index 0cc5580..42ae249 100644
--- a/cpp/lib/ome/common/module.cpp
+++ b/cpp/lib/ome/common/module.cpp
@@ -47,6 +47,7 @@
#include <cstring>
#include <map>
#include <stdexcept>
+#include <iostream>
namespace fs = boost::filesystem;
@@ -306,6 +307,7 @@ namespace ome
{
fs::path moduledir(module.parent_path());
bool match = true;
+              std::cerr << "MODULEDIR: " << …
```

C++: Path introspection on Windows, and support for relocatable installation (5.1)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005701.html
To test, use the .czi file from the thread (uploaded to ```team/community_images/```).  It's easiest to see the problem by using the ```Histo``` tab in Zen, and comparing the histogram table values for each plane against the output of something like:
```
ImageReader reader = new ImageReader();
reader.setId(args[0]);
for (int t=0; t<100; t++) {
for (int c=0; c<reader.getSizeC(); c++) {
byte[] b = reader.openBytes(reader.getIndex(0, c, t));
int[] counter = new int[256];
for (int pixel=0; pixel<b.length; pixel++) {
int v = b[pixel] & 0xff;
counter[v]++;
}
System.out.println("t = " + t + ", c = " + c);
for (int pixel=0; pixel<counter.length; pixel++) {
if (counter[pixel] != 0) {
System.out.println("  * value = …
```

CZI: update line scan detection for airyscan data

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#13](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/13/).
----
--no-rebase

Update POM version numbers to 5.1.6

---

components/autogen/src/FormatPageAutogen.java
components/autogen/src/doc/FormatTable.vm
components/autogen/src/format-pages.txt
docs/sphinx/formats/hamamatsu-ndpi.txt
docs/sphinx/formats/nikon-nis-elements-nd2.txt
docs/sphinx/supported-formats.txt

This is the same as gh-2038 but rebased onto develop.
----
See https://trello.com/c/9yZdHX52/15-mif-checkbox-in-pff-list. The checkbox seemed to make more sense on the supported formats table, but I can move it to the dataset structure table if anyone feels strongly.
Only testing is to read through the last column on the supported formats table and make sure that none of the values look incorrect.

Add a "Multiple Images" column to the supported formats table (rebased onto develop)

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

This is the same as gh-2073 but rebased onto develop.
----
This warns instead of throwing an exception, and ensures that physical
sizes of 0.0 are not allowed.
To test, compare the behavior of ```showinf -nopix -omexml fake/samples/emptySizes&physicalSizeX=0.0.fake```.  Without this change, XML validation should fail; with this change, PhysicalSizeX should not be populated at all.

Fake: warn on invalid physical sizes (rebased onto develop)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#14](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/14/).
----
--no-rebase

Update POM version numbers to 5.1.7-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java

This is the same as gh-2069 but rebased onto develop.
----
See https://trello.com/c/efn0T64w/18-metaxpress-multi-line-descriptions
Based upon analysis of various Metamorph TIFF samples, the user-entered
freeform description appears to be stored contiguously, and always
before the "Exposure" key.  The "Exposure" key seems to consistently be
the first official standard Metamorph key, with "Binning", "Region",
etc. following in a predictable order.  This commit takes all lines from
the XML description field up to "Exposure" and assembles them into a
single "User Description" entry in the metadata table.
Non-freeform lines with no value are also now stored in the metadata table, with the key and value being the same.
This should match the behavior described in …

Metamorph TIFF: fix parsing of multi-line freeform descriptions (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

This is the same as gh-2074 but rebased onto develop.
----
See QA 16887.  Dual camera acquisitions store two channels side-by-side;
this splits the image and records two separate channels.  The same
feature is already present in MetamorphReader.
To test, verify that the file from QA 16887 is 512x512, 2 channels, 200 timepoints, and that the channels are distinct.  Builds should remain green.

Metamorph TIFF: add dual camera support (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is the same as gh-2076 but rebased onto develop.
----
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005701.html
To test, use the .czi file from the thread (uploaded to ```team/community_images/```).  It's easiest to see the problem by using the ```Histo``` tab in Zen, and comparing the histogram table values for each plane against the output of something like:
```
ImageReader reader = new ImageReader();
reader.setId(args[0]);
for (int t=0; t<100; t++) {
for (int c=0; c<reader.getSizeC(); c++) {
byte[] b = reader.openBytes(reader.getIndex(0, c, t));
int[] counter = new int[256];
for (int pixel=0; pixel<b.length; pixel++) {
int v = b[pixel] & 0xff;
counter[v]++;
}
System.out.println("t = " + t + ", c = " + c);
for (int pixel=0; pixel<counter.length; pixel++) { …
```

CZI: update line scan detection for airyscan data (rebased onto develop)

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

This PR has been used to test https://github.com/openmicroscopy/bioformats/pull/2089 using the command-line tools. It allows to call `FormatReader.isThisType(RandomAccessInputStream)` using `showinf`.
To test this PR, run
```
./showinf -preload -format FORMAT /path/to/file
```
and verify the format type is also checked before caching the bytes.

Showinf: preload format improvements

---

components/formats-gpl/src/loci/formats/in/IMODReader.java

This is the same as gh-2039 but rebased onto develop.
----
See https://trello.com/c/nO35TKXK/3-units-and-readers
This PR adjusts the IMODReader to store the physical pixel size read from `imod` files using the native units. The specification for the units can be found at http://bio3d.colorado.edu/imod/doc/binspec.html.
Since one of the samples IMOD file uses the pixel unit (`0`) which that cannot be converted to micrometers, the format reader automated tests are also adjusted to handle this case (using `isConvertible` similarly to what is done in https://github.com/openmicroscopy/bioformats/pull/2030). The size comparison logic used across all physical size tests is also refactored into a single helper method to simplify future maintenance.
For automated tests, this means we do not …

IMODReader: add support for native length units (rebased onto develop)

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This is the same as gh-2064 but rebased onto develop.
----
Follow-up of https://github.com/openmicroscopy/bioformats/pull/2050
- makes the configuration of exposure time, emission wavelength and excitation wavelength units channel-specific
- modifies the `populateINI` method to fill unit symbols as well as values
- drops the special test for physical sizes of `0.0` values now the configuration files have been cleaned up.
To test this PR, run
```
ant -f components/test-suite/build.xml gen-config  -Dtestng.directory=/path/to/file
```
ideally on a file containing physical pixel sizes, time increment, channel wavelengths and exposure times. Check the generated `.bioformats` INI file has both the values and the units stored. Then run the automated tests using the newly generated configuration …

Test suite: units (2) (rebased onto develop)

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2085 but rebased onto develop.
----
A couple of yet-unmerged PRs are referenced here, so depending on how Friday goes this may need one more commit.

Add version history for 5.1.6 (rebased onto develop)

---

docs/sphinx/developers/jace/overview.txt

This is the same as gh-2040 but rebased onto develop.
----
This PR:
- adds the Video Spot Tracker software to the list of projects using the Jace C++ bindings - see http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005690.html
- removes the BF-CPP abbreviation and uses Jace C++ bindings in the documentation instead to prevent any confusion with Bio-Formats C++. /cc @rleigh-dundee

Video spot tracker (rebased onto develop)

---

components/bio-formats-plugins/src/loci/plugins/in/Importer.java

Rebasing https://github.com/openmicroscopy/bioformats/pull/2061 onto develop
Reported issue: https://github.com/openmicroscopy/bioformats/issues/2057
When the importer has been run from an IJ macro, the options list should
not be loaded from preferences but instead read from the macro arguments
only.
In order to test the PR:
Open Fiji and record 2 macros (Plugins -> Macros -> Record)
Now import a multi channel image using bioformats
For the first macro select the split channels option during import, for the second make sure it is unselected
Now import an image again using bioformats and ensure the split channel option is selected. This will save the option to your Image J preferences.
Now rerun your 2 macros and ensure that the image channels are split in one and combined in the other
Now …

Rebase: Fiji preferences not persistent for macros

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Adding a limit to the decimal precision of BigDecimal divide.
This is required to prevent the following exception: Non-terminating
decimal expansion; no exact representable decimal result.
Issue was reported below:
https://www.openmicroscopy.org/community/viewtopic.php?f=4&p=16439#p16439
Note: This behaviour is the same as we already use in the Fluoview reader. There are no other instances of BigDecimal division that require correcting.

Big decimal exception

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java

This is the same as gh-2107 but rebased onto dev_5_1.
----
Do not split further if dual camera Metamorph image has already been split.
This addresses QA 16915
Metamorph seems to add the wavelength number to the end of the Description field when splitting. Example:
Dual Camera Time Difference: 7 msec 561
[split_488_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39324/split_488_metadata.txt)
[split_561_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39323/split_561_metadata.txt)
[unsplit_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39325/unsplit_metadata.txt)

Detect whether dual camera Metamorph image has been split, and (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/APLReader.java

APLReader - Update to use native units - Rebased from https://github.com/openmicroscopy/bioformats/pull/2067 onto develop
This PR adjusts the APLReader to store the physical pixel size read from apl files using the native units.
To test this PR, check apl files (cellr) are read correctly and automated tests are passing.

Rebased: APLReader - Update to use native units

---

pom.xml
tools/update_copyright

To test, build bioformats_package.jar using Maven and copy to your ImageJ plugins folder.  Without this change, ```Help > About Plugins > Bio-Formats Plugins``` in ImageJ should show the end copyright year as 2013.  With this change, the same test should show the end copyright year as 2015.

Fix current year in POM file

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This is the same as https://github.com/openmicroscopy/bioformats/pull/2102 but rebased onto develop.
Adding a limit to the decimal precision of BigDecimal divide.
This is required to prevent the following exception: Non-terminating
decimal expansion; no exact representable decimal result.

Using MathContext with Big Decimal (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java

Do not split further if dual camera Metamorph image has already been split.
This addresses QA 16915
Metamorph seems to add the wavelength number to the end of the Description field when splitting. Example:
Dual Camera Time Difference: 7 msec 561
[split_488_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39324/split_488_metadata.txt)
[split_561_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39323/split_561_metadata.txt)
[unsplit_metadata.txt](https://github.com/openmicroscopy/bioformats/files/39325/unsplit_metadata.txt)

Detect whether dual camera Metamorph image has been split, and

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-czi.txt

See https://trello.com/c/FAR5LQH2/4-czi-jpeg-xr-doc-limitation
Hopefully this wording is okay.
Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/formats/zeiss-czi.html once built.

Adding JPEG-XR note to CZI format page

---

components/formats-gpl/src/loci/formats/in/MINCReader.java

For short, int, float and double data in MINC2 format, the endianess of
the pixel format must be set before unpacking the data.
Issue was reported here: https://github.com/openmicroscopy/bioformats/issues/2110
To reproduce:
- Using a sample 16bit minc2 image open with bioformats
- Verify that the outline of the data is visible but the pixel values appear to noise
To verify:
- Reopen the image with the PR
- Verify that the data is no longer appearing as noise and instead as sensible values

MINC2 - Endianess 

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-czi.txt

This is the same as gh-2119 but rebased onto develop.
----
See https://trello.com/c/FAR5LQH2/4-czi-jpeg-xr-doc-limitation
Hopefully this wording is okay.
Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.1-staging/formats/zeiss-czi.html once built.

Adding JPEG-XR note to CZI format page (rebased onto develop)

---

pom.xml
tools/update_copyright

This is the same as gh-2111 but rebased onto develop.
----
To test, build bioformats_package.jar using Maven and copy to your ImageJ plugins folder.  Without this change, ```Help > About Plugins > Bio-Formats Plugins``` in ImageJ should show the end copyright year as 2013.  With this change, the same test should show the end copyright year as 2015.

Fix current year in POM file (rebased onto develop)

---

components/formats-gpl/matlab/bfCheckJavaPath.m

In bfCheckJavaPath.m, only check MATLAB static javaclasspath once by using a persistent variable. 
The static javaclasspath can only be changed at startup by adding a javaclasspath.txt file in either the MATLAB startup directory or in `prefdir`. Therefore, we only need to check the static classpath once for the jars. On subsequent calls to `bfCheckJavaPath.m`, just recheck the dynamic path and merge the results.
As the static classpath is quite long and the dynamic classpath is quite short in MATLAB the efficiency gains by not constantly rechecking the static classpath are substantial.
This change is against 5.1.x only and thus is against dev_5_1. It would need be reconciled with the version in develop ( 549b8673a619dce95e482234fad54367a8975b97 ) which does no analysis of the classpath …

bfCheckJavaPath.m: Only check MATLAB static javaclasspath once

---

components/formats-gpl/src/loci/formats/in/MINCReader.java

--rebased-from #2114
For short, int, float and double data in MINC2 format, the endianess of
the pixel format must be set before unpacking the data.
Issue was reported here: #2110
To reproduce:
•Using a sample 16bit minc2 image open with bioformats
•Verify that the outline of the data is visible but the pixel values appear to noise
To verify:
•Reopen the image with the PR
•Verify that the data is no longer appearing as noise and instead as sensible values

Rebased: MINC2 - Endianess

---

components/formats-api/src/loci/formats/FormatTools.java

When converting the units the value must also be converted.
Have to use a workaround of using a temporary created Length in order to
get the new Unit<Length> as opposed to the UnitsLength
This a a bug fix for the merged PR https://github.com/openmicroscopy/bioformats/pull/2071

Bug fix - Convert values

---

components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-bsd/src/loci/formats/in/OBFReader.java

See https://trello.com/c/ZNENhFMs/5-obf-reader-improvements
We don't have any example OBF files with OME-XML metadata, so code/job stability review is probably the best that can be done.  The idea is to allow image data to be read if the metadata is invalid or otherwise cannot be parsed.

OBF: add fallback case for unparseable OME-XML

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Reported Issue: http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-November/005745.html
This is a follow up to : https://github.com/openmicroscopy/bioformats/pull/1997
To reproduce: 
- Using uploaded from file QA 16928
- Import with bioformats and view metadata
- Verify that the PhysicalSizeZ and TheZ are set correctly and PositionZ is 0 for each image
To test the PR:
- Follow the same steps above but verify that PositionZ is now set for each image, PositionZUnit should also now be µm rather than reference frame

Andor - Plane Position Z

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://trello.com/c/dx5t3btt/14-gatan-locale-issues
There is already a check for the "," separator not being present, so
using Locale.ENGLISH for parsing should be safe across the board.
This is thankfully the only place where we're using NumberFormat and Collator.
To test, pick any Gatan .dm3 file.  Verify that without this change, ```export BF_FLAGS="" && showinf -nopix -omexml``` shows valid values for PhysicalSizeX and PhysicalSizeY, and that ```export BF_FLAGS="-Duser.language=fr -Duser.country=FR" && showinf -nopix -omexml``` does not.  With this change, both tests should show the same valid values for PhysicalSizeX and PhysicalSizeY (and jobs running with fr_FR should pass).

Gatan: explicitly set the locale used for parsing physical sizes

---

components/bio-formats-plugins/test/loci/plugins/in/ImporterTest.java
components/formats-bsd/src/loci/formats/FilePattern.java

This PR addresses a problem that occurs when `FilePattern` is initialized with a string corresponding to a single but nonexistent file. In this case, `files` is left empty but the pattern is still marked as valid, leading to an `ArrayIndexOutOfBoundsException` in code that assumes that at least one element will be present. This [happens in FileStitcher](https://github.com/openmicroscopy/bioformats/blob/metadata/components/formats-bsd/src/loci/formats/FileStitcher.java#L275), and the error is currently being triggered by `loci.plugins.in.ImporterTest`.
Since not allowing nonexistent files breaks `.fake` support, the fix consists of removing the existence check. This PR also fixes a few problems in the aforementioned test. Note that the fixes proper are in the first commit, while subsequent …

FilePattern: allow nonexistent single files

---

docs/sphinx/about/whats-new.txt

Just what it says on the tin.  I didn't add C++ changes since there don't seem to be any dev_5_1 C++ PRs not tagged for 5.1.6 - happy to add if I missed anything.

Add version history for 5.1.7

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#15](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/15/).
----
--no-rebase

Update POM version numbers to 5.1.7

---

components/formats-api/src/loci/formats/FormatTools.java

This is the same as #2071 but rebased onto develop.
---
For some readers we have native units that are not logical for the purpose resulting in very low values.
See #2044 for an example.
This proposed change to FormatsTools getPhysicalSize would implement the following logic as suggested in the PR mentioned above:
1.check if the value is greater than Constants.EPSILON
2.if so, use whatever unit was supplied
3.if not, convert to the smallest order of magnitude unit such that (1) passes (or the default unit?)
4.if the value really is 0, or is less than Constants.EPSILON for even the smallest defined unit, return null
I have also updated getPhysicalSizeX and Y methods to use the same getPhysicalSize function as we had 2 separate workflows depending on if the units were provided as String or …

Format tools units automatic conversion (rebased onto develop)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#16](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/16/).
----
--no-rebase

Update POM version numbers to 5.1.8-SNAPSHOT

---

components/formats-api/src/loci/formats/FormatTools.java

This is the same as #2084 but rebased onto develop.
---
When converting the units the value must also be converted.
Have to use a workaround of using a temporary created Length in order to
get the new Unit as opposed to the UnitsLength
This a a bug fix for the merged PR #2071

Bug fix - Convert values (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

This is the same as #2046 but rebased onto develop.
---
Using metres for physical size rather than micrometres

FEITiffReader - Using native units (rebased onto develop)

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

This is the same as gh-2129 but rebased onto develop.
----
See https://trello.com/c/dx5t3btt/14-gatan-locale-issues
There is already a check for the "," separator not being present, so
using Locale.ENGLISH for parsing should be safe across the board.
This is thankfully the only place where we're using NumberFormat and Collator.
To test, pick any Gatan .dm3 file.  Verify that without this change, ```export BF_FLAGS="" && showinf -nopix -omexml``` shows valid values for PhysicalSizeX and PhysicalSizeY, and that ```export BF_FLAGS="-Duser.language=fr -Duser.country=FR" && showinf -nopix -omexml``` does not.  With this change, both tests should show the same valid values for PhysicalSizeX and PhysicalSizeY (and jobs running with fr_FR should pass).

Gatan: explicitly set the locale used for parsing physical sizes (rebased onto develop)

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2135 but rebased onto develop.
----
Just what it says on the tin.  I didn't add C++ changes since there don't seem to be any dev_5_1 C++ PRs not tagged for 5.1.6 - happy to add if I missed anything.

Add version history for 5.1.7 (rebased onto develop)

---

components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-bsd/src/loci/formats/in/OBFReader.java

This is the same as gh-2068 but rebased onto develop.
----
See https://trello.com/c/ZNENhFMs/5-obf-reader-improvements
We don't have any example OBF files with OME-XML metadata, so code/job stability review is probably the best that can be done.  The idea is to allow image data to be read if the metadata is invalid or otherwise cannot be parsed.

OBF: add fallback case for unparseable OME-XML (rebased onto develop)

---

components/formats-api/src/loci/formats/meta/MetadataConverter.java
components/formats-gpl/src/loci/formats/in/FlexReader.java

See https://trello.com/c/ZZGjfe10/120-sysgro-continued.  This should resolve all three stack traces noted in the card.  I haven't tried full OMERO imports, so it's possible that there are still issues, but everything I could see from ```showinf -omexml``` works now.

Flex fixes for new sysgro data

---

components/formats-gpl/src/loci/formats/in/ScanrReader.java

This fixes the case where the files for the first recorded well were removed.
See https://trello.com/c/a3M5iBxQ/156-secretionb-failure

ScanR: read core metadata from first non-null TIFF file

---

components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/OMEXMLReader.java
components/formats-bsd/src/loci/formats/out/OMEXMLWriter.java
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/ome-tiff.txt
docs/sphinx/formats/ome-xml.txt
docs/sphinx/supported-formats.txt

This extension is currently supported by the permissive nature of the reader but unsupported by the writer. There are a couple of reasons why we want to consider it as official including our own usage, the symmetry with the OME-TIFF format extension and the usability with other software.
To test this PR, try to convert an OME-XML into another one with the `.ome.xml` extension
```
./tools/bfconvert test.ome.xml test2.ome.xml
```
/cc @rleigh-dundee @mtbc @hflynn @joshmoore @melissalinkert 
Replaces #2133

Whitelist .ome.xml as an official extension of the OME-XML format

---

components/bundles/bioformats_package/pom.xml

This PR modifies bioformats_package's pom to add `bio-formats-tools` as a dependency, so that the following classes are included in the bundle:
```
loci/formats/tools/ImageConverter.class
loci/formats/tools/ImageFaker.class
loci/formats/tools/ImageInfo.class
```
**To test:**
```
mvn install
cd tools
ln -s ~/.m2/repository/ome/bioformats_package/5.2.0-SNAPSHOT/bioformats_package-5.2.0-SNAPSHOT.jar bioformats_package.jar
./mkfake
./showinf 
./bfconvert 
```
Check that you get the expected usage help for all three tools. *Without* this patch, instead, you should get, respectively:
```
Error: Could not find or load main class loci.formats.tools.ImageFaker
Error: Could not find or load main class loci.formats.tools.ImageInfo
Error: Could not find or load main class …
```

Add bio-formats-tools to bioformats_package

---

components/formats-bsd/src/loci/formats/AxisGuesser.java
components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/src/loci/formats/Memoizer.java
components/formats-bsd/src/loci/formats/in/FilePatternReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See https://trello.com/c/vpc8NKAC/163-idr-metamorph-stk-per-channel.
The Metamorph changes use stage labels starting with ```Scan ``` to detect when a whole plate is saved in a single .stk file.  That doesn't allow for Z stacks/time series as well as a plate being stored, but I imagine we could extend it if/when we have an example.
The AxisGuesser changes allow a pattern block such as ```<53bp1,dapi>``` to be automatically detected as 2 channels, instead of 2 Z sections

Updates for Metamorph plates with one file per channel

---

README.md

Java 1.7+ code can now be added to the repo since Java 6 support has been dropped. Also removing the reference to "test_per_commit" as suggested by @sbesson

Update README.md to current status

---

components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/src/loci/formats/IllegalBlockException.java
components/formats-bsd/test/loci/formats/utests/FilePatternBlockTest.java

This PR adds a unit test for `FilePatternBlock` and fixes a few problems in its behavior, most notably the fact that alphanumeric range delimiters can't go beyond `"p"` due to a misinterpretation of the `radix` argument in `BigInteger`.
**To test:** check that the code compiles and *all* tests pass.

FilePatternBlock: fixes and unit test

---

CMakeLists.txt

This is a temporary change to permit the model source to be generated without a dependency upon ome-common, which isn't needed for source generation.  The source will not build with this option enabled, but the code generator will run.
When the model code is split into a separate repository, this option can be moved there, or redone in a better way.
--------
Testing: Add `-Dmodel-source-only=ON` to source generation job, and it should work again.  Done in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-DEV-merge-generated-sources/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-DEV-latest-generated-sources/ -- the latter will require the PR merging before it will go green.

cmake: Add model-source-only option

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java

This PR adds a new unit test for `FilePattern`. In addition, it changes the `FilePattern(String)` constructor to accept nonexistent single files (see #2131).

Unit test & fix for FilePattern

---

cpp/lib/ome/test/main.cpp
docs/sphinx/developers/cpp/examples/metadata-formatreader.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter.cpp
docs/sphinx/developers/cpp/examples/metadata-io.cpp
docs/sphinx/developers/cpp/examples/model-io.cpp
docs/sphinx/developers/cpp/examples/pixeldata.cpp

It's set automatically at startup, but for some reason this isn't happening on Windows.  Likely related to being built as a static library.
--------
Testing: Check the size of the build log.  It should be vastly reduced, since it will no longer be logging everything at TRACE level (it's WARNING only).

cpp: Set default log level by hand

---

components/formats-gpl/src/loci/formats/in/SPEReader.java

Fixes a couple of minor issues noticed when reviewing gh-1965.
To test, compare the output of ```showinf -nopix -omexml``` on the ```curated/pi-spe``` files with and without this PR.  The only visible difference with this PR should be that the valid bits/bitsPerPixel/BitsPerSample values now match the full bit width of the pixel type, instead of being the number of bytes.  The ROI indexing changes shouldn't visibly affect the existing sample data, only files that have multiple ROIs (so careful code review is sufficient).

Princeton SPE follow-up

---

docs/sphinx/developers/cpp/schema.txt

Guidance about missing XSLT transforms.  Should be possible to remove in the next few weeks, but adding to document the current state.  I'll remove it in the PR adding transform support.

docs: Add note about missing C++ XSL transforms

---

components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/SpiderReader.java

Resolves https://trac.openmicroscopy.org/ome/ticket/13058 and https://trac.openmicroscopy.org/ome/ticket/13059.
To test, use the files from QA 16850, ignoring ```cvim006036.0.img``` as it is raw data without the corresponding header file.  Without this change, ```showinf``` on the three remaining files should report ```UnknownFormatException```.  With this change, the same test should show ```15_movie_gc.mrcs``` being detected as MRC, and both .dat files being detected as Spider.  EMAN2 should be able to read all three (per http://blake.bcm.edu/emanwiki/EMAN2ImageFormats), so hopefully can be used to validate the images themselves.

EM format type checking fixes

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java

This PR extends the javadocs for `FilePattern{,Block}`. Part of the new docs for `FilePattern` are taken from a long non-javadoc section at the end of the file, which has been deleted. A few `FilePattern` methods had a commented out deprecation tag, so they were actually not deprecated. New javadocs have been added for these methods, and they are now checked by the unit test.

FilePattern docs revision

---

components/formats-common/src/loci/common/NIOFileHandle.java

Modified setLength(..) method for faster saving operation.
With the previous implementation, saving a 700 MB 5D dataset in OME TIFF format was taking about 45 minutes, now it takes about 3 minutes. It's still slow but already a nice improvement.

Modified setLength(..) method of NIOFileHandle.java for faster save operation.

---

docs/sphinx/developers/generating-test-images.txt

This PR brings the docs into line with the `screens` key added in https://github.com/openmicroscopy/bioformats/pull/1984
I'd be happy to add any further improvements to the docs from https://trello.com/c/f9tTxVFz/372-improve-fake-parameter-handling here is necessary. /cc @mtbc 
The later two commits attempt to address the documentation issues raised above.

docs: Improve page on generating test images

---

docs/sphinx/developers/cpp/overview.txt

Documents https://github.com/ome/ome-cmake-superbuild/pull/27 by documenting how to use Ninja on Unix and Windows, and the tradeoffs with the default build systems on these platforms.
See http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/cpp/overview.html
--------
Testing.  Tested by the above PR; if you really wanted you could run the superbuild with the above PR merged following the instructions, but it's run by the Windows superbuild job already, and now also on cowfish for the unix superbuild:
https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/BUILD_TYPE=Release,node=cowfish/42/consoleText
This confirms it works for both Unix and Windows builds, both in general and in the jenkins-build shell script and batch files.

doc: cpp: Document use of the Ninja generator

---

docs/sphinx/developers/cpp/overview.txt

Update the documentation for the CMake options.
See https://github.com/ome/ome-cmake-superbuild/pull/29 for the changes this is documenting.

docs: Document superbuild changes following repo split

---

docs/sphinx/developers/cpp/maintenance.txt
docs/sphinx/developers/index.txt

This is to provide guidance for managing the superbuild and other C++ code.  Primarily for internal use but may also be useful for external contributors.
Note that once the repo split is complete, the superbuild docs could move into the individual packages so it's documented directly where it's needed; there's already a README file for each package, and this information could supplement it there.  For now, it's fine here.

docs: Add C++ maintenance page

---

docs/sphinx/developers/reader-guide.txt

Fixes `reader-guide.txt` in the Sphinx docs

Minor fix for reader-guide

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

This change allows for fake plates to be created by simply having one of the relevant keys in the name set to 1 or more. All non-set keys are then assumed to be equal to 1. See https://trello.com/c/f9tTxVFz/372-improve-fake-parameter-handling
Thus,
```
SPW&plates=1.fake
SPW&plates=1&plateRows=1&plateCols=1&plateAcqs=1&fields=1.fake
```
would both generate the same plate form.
I'm not sure how best to test this. I have done so locally using the breaking build of OMERO - and in fact the fake plate tests in https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroPy/test/integration/clitest/test_import.py in that build should pass with this PR included in Bio-Formats. The Bio-Formats unit tests can't easily be changed to test this as they don't appear to test …

Allow for simpler fake plate definition

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

According to http://stackoverflow.com/questions/4567636/java-sax-parser-split-calls-to-characters , the processing should be done in endElement instead so that XML element value "1.943794245326921E-09" doesn't get split in two characters calls.

Fix FEITiffReader metadata parser. Fix #2179

---

components/formats-gpl/src/loci/formats/in/PyramidTiffReader.java

The assumeEqualStrips was only being set in isThisType().  It was causing the following error during import into OMERO:
```
2016-01-07 12:49:38,824 WARN  [        ome.services.util.ServiceHandler] (.Server-12) Unknown exception thrown.
java.lang.ArrayIndexOutOfBoundsException: 1
at loci.formats.tiff.TiffParser.getTile(TiffParser.java:699) ~[formats-bsd.jar:na]
at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:995) ~[formats-bsd.jar:na]
at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:790) ~[formats-bsd.jar:na]
at loci.formats.in.PyramidTiffReader.openBytes(PyramidTiffReader.java:90) ~[formats-gpl.jar:na]
at loci.formats.ImageReader.openBytes(ImageReader.java:453) ~[formats-api.jar:5.1.4]
```
By also setting assumeEqualStrips for the parser in openBytes() this problem …

Also set assumeEqualStrips during reading for PyramidTiffReader

---

pom.xml

Latest Travis builds on the dev_5_1 branch have uncached dependencies and the logs show they are is primarily hitting the OME artifactory to retrieve artifacts that should be retrieved from Maven Central.
This PR amends the changes made in https://github.com/openmicroscopy/bioformats/pull/1867 to remove the OME repositories from the profiles. Is there any reason why `ome.snapshots` and `ome.unstable` should not be used for anything other than publishing?
- clean your local Maven repository
- run `mvn install`
- in the log especially in the initial steps, check `artifacts.openmicroscopy.org` is only hit on purpose (i.e. for artifacts not available via Maven Central).

Remove artifactories repositories from the profiles

---

cpp/CMakeLists.txt
cpp/cmake/TemplateCmdWrapper.cmake.in
cpp/cmake/TemplateInternalCmdWrapper.cmake.in
cpp/cmake/TemplateInternalShellWrapper.cmake.in
cpp/lib/ome/xml/CMakeLists.txt
cpp/lib/ome/xml/OMETransformResolver.cpp
cpp/lib/ome/xml/OMETransformResolver.h
cpp/test/ome-xml/CMakeLists.txt
cpp/test/ome-xml/transform-resolver.cpp

- Install transforms
- Set transform directory inside and outside the build, and when running tests
- `OMETransformResolver` detects all available transforms and builds a graph (vertices are schemas, edges are transforms between schemas)
- This class permits querying of available schemas and of the set of transforms to apply to change from a given source to target schema.  Schemas are discovered by searching the transforms directory for "{source}-to-{target}.xsl" files.
- Transform quality is determined using the same algorithm as in `components/specification/transforms/util/write-transforms.py`, and used to weight the edges for use in a shortest path search.
Note it is based upon https://github.com/openmicroscopy/bioformats/pull/2185 and so includes the commits for this PR as well.  The …

C++: Add model transform resolver for discovery and graph-based query

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This prevents earlier tiles from being overwritten by later tiles.
Strip-based data, single channels, and interleaved RGB tiles should be
unaffected.
See:
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-October/005680.html
https://trello.com/c/nFq6AzGi/53-writing-tiff-in-tiles
http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2015-December/003531.html
I was able to reproduce the problem mentioned in the October 2015 thread using:
```bfconvert test_images_good/tiff-big-images/2kx2k.tif 2kx2k-tiled.ome.tiff -tilex 1000 -tiley 1000```
Without this change, ```2kx2k-tiled.ome.tiff``` should not match the original file (mixed up colors and tiles).  With this change, the two files should match when viewed in showinf/ImageJ/ImageMagick.
It would also be good to test the following …

TiffSaver: fix recorded offsets to non-interleaved RGB tiles

---

components/formats-bsd/test/loci/formats/utests/testng.xml

Adds `FilePattern{,Block}Test` so they are run with `ant test`

Add missing formats-bsd tests to the testng config file

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

I also modified the end element code so that even if the string builder is empty, the parentNames get peeked (to be consistent with the code before #2181 ).

Fix FEITiffReader stage position parsing.

---

pom.xml

This is the same as gh-2193 but rebased onto develop.
----
Latest Travis builds on the dev_5_1 branch have uncached dependencies and the logs show they are is primarily hitting the OME artifactory to retrieve artifacts that should be retrieved from Maven Central.
This PR amends the changes made in https://github.com/openmicroscopy/bioformats/pull/1867 to remove the OME repositories from the profiles. Is there any reason why `ome.snapshots` and `ome.unstable` should not be used for anything other than publishing?
- clean your local Maven repository
- run `mvn install`
- in the log especially in the initial steps, check `artifacts.openmicroscopy.org` is only hit on purpose (i.e. for artifacts not available via Maven Central).

Remove artifactories repositories from the profiles (rebased onto develop)

---

docs/sphinx/users/qu-matlab/index.txt

The current docs claims that qu-matlab is a toolset analysis of N-dimensional datasets. However, this is not true. On [their website](http://www.scs2.net/next/index.php?id=120):
> It allows the visualization and analysis of 4D (XYZT) datasets with any number of color channels. 
Since colour is another dimension, then technically it should be 5 dimensions. I went with "multi-channel 4 dimensional data" to reflect that qu treats the channel dimension different.

docs: Qu for Matlab only supports up to 4 dimensions

---

docs/sphinx/users/index.txt
docs/sphinx/users/octave/index.txt

Adding instructions on how to install bioformats package in Octave as requested in openmicroscopy/ome-release#177
Note: I have added octave on the list above idl, and not in alphabetic order, because on the build the link appears as "GNU Octave" (so it is alphabetic order but of the end result).

doc: install and usage instructions for Octave package (issue ome-release 177)

---

docs/sphinx/users/qu-matlab/index.txt

This is the same as gh-2199 but rebased onto dev_5_1.
----
The current docs claims that qu-matlab is a toolset analysis of N-dimensional datasets. However, this is not true. On [their website](http://www.scs2.net/next/index.php?id=120):
> It allows the visualization and analysis of 4D (XYZT) datasets with any number of color channels. 
Since colour is another dimension, then technically it should be 5 dimensions. I went with "multi-channel 4 dimensional data" to reflect that qu treats the channel dimension different.

docs: Qu for Matlab only supports up to 4 dimensions (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

This prevents exceptions when an OnDemandLongArray is loaded from a memo
file, resulting in an invalid default stream.
See https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7980
To test, convert the file from QA 16966 to .ome.btf using bfconvert.  Import the .ome.btf into OMERO; without this change, pyramid generation will throw an exception as noted in the forum thread.  With this change, pyramid generation should succeed, and the image should be viewable in OMERO.

TiffParser: always set the stream for any OnDemandLongArrays

---

components/formats-bsd/pom.xml
pom.xml

In some Maven POM files, include patterns are so general that they also match files under `target` directories. Due to this, some jars end up containing duplicate `.cpp` source files (in the following, stars denote legitimate instances):
```
loci_formats_in_LegacyND2Reader.cpp
[ ] ./formats-gpl-5.2.0-SNAPSHOT-sources.jar/target/classes/target/classes/loci/formats/in/loci_formats_in_LegacyND2Reader.cpp
[*] ./formats-gpl-5.2.0-SNAPSHOT-sources.jar/loci/formats/in/loci_formats_in_LegacyND2Reader.cpp
[ ] ./formats-gpl-5.2.0-SNAPSHOT-sources.jar/target/classes/loci/formats/in/loci_formats_in_LegacyND2Reader.cpp
[ ] ./formats-gpl-5.2.0-SNAPSHOT-sources.jar/target/classes/src/loci/formats/in/loci_formats_in_LegacyND2Reader.cpp
[ ] ./formats-gpl-5.2.0-SNAPSHOT-sources.jar/src/loci/formats/in/loci_ …
```

More specific .cpp include patterns

---

components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/OMEXMLReader.java
components/formats-bsd/src/loci/formats/out/OMEXMLWriter.java
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/ome-xml.txt
docs/sphinx/supported-formats.txt

This is the same as gh-2142 but rebased onto dev_5_1.
----
This extension is currently supported by the permissive nature of the reader but unsupported by the writer. There are a couple of reasons why we want to consider it as official including our own usage, the symmetry with the OME-TIFF format extension and the usability with other software.
To test this PR, try to convert an OME-XML into another one with the `.ome.xml` extension
```
./tools/bfconvert test.ome.xml test2.ome.xml
```
/cc @rleigh-dundee @mtbc @hflynn @joshmoore @melissalinkert 
Replaces #2133

Whitelist .ome.xml as an official extension of the OME-XML format (rebased onto dev_5_1)

---

components/bundles/bioformats_package/pom.xml

This is the same as gh-2125 but rebased onto dev_5_1.
----
This PR modifies bioformats_package's pom to add `bio-formats-tools` as a dependency, so that the following classes are included in the bundle:
```
loci/formats/tools/ImageConverter.class
loci/formats/tools/ImageFaker.class
loci/formats/tools/ImageInfo.class
```
**To test:**
```
mvn install
cd tools
ln -s ~/.m2/repository/ome/bioformats_package/5.2.0-SNAPSHOT/bioformats_package-5.2.0-SNAPSHOT.jar bioformats_package.jar
./mkfake
./showinf 
./bfconvert 
```
Check that you get the expected usage help for all three tools. *Without* this patch, instead, you should get, respectively:
```
Error: Could not find or load main class loci.formats.tools.ImageFaker
Error: Could not find or load main class loci.formats.tools.ImageInfo
Error: …
```

Add bio-formats-tools to bioformats_package (rebased onto dev_5_1)

---

components/formats-common/src/loci/common/NIOFileHandle.java

This is the same as gh-2056 but rebased onto dev_5_1.
----
Modified setLength(..) method for faster saving operation.
With the previous implementation, saving a 700 MB 5D dataset in OME TIFF format was taking about 45 minutes, now it takes about 3 minutes. It's still slow but already a nice improvement.

Modified setLength(..) method of NIOFileHandle.java for faster save operation. (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

This is the same as gh-2181 but rebased onto dev_5_1.
----
According to http://stackoverflow.com/questions/4567636/java-sax-parser-split-calls-to-characters , the processing should be done in endElement instead so that XML element value "1.943794245326921E-09" doesn't get split in two characters calls.

Fix FEITiffReader metadata parser. Fix #2179 (rebased onto dev_5_1)

---

docs/sphinx/users/index.txt
docs/sphinx/users/octave/index.txt

This is the same as gh-2200 but rebased onto dev_5_1.
----
Adding instructions on how to install bioformats package in Octave as requested in openmicroscopy/ome-release#177
Note: I have added octave on the list above idl, and not in alphabetic order, because on the build the link appears as "GNU Octave" (so it is alphabetic order but of the end result).

doc: install and usage instructions for Octave package (issue ome-release 177) (rebased onto dev_5_1)

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/src/loci/formats/services/OMEXMLService.java
components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-bsd/src/loci/formats/out/EPSWriter.java
components/formats-bsd/src/loci/formats/out/OMETiffWriter.java
components/formats-bsd/src/loci/formats/out/OMEXMLWriter.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This should resolve https://trello.com/c/R1x1tmaP/78-bfconvert-writes-invalid-ome-tiff and https://trello.com/c/L0Mq3BSV/351-fill-the-creator-field-when-generating-ome-tiff.
To test, use the file mentioned in https://trac.openmicroscopy.org/ome/ticket/13131.  Run ```bfconvert vessels.ome.tiff -channel 0 c0.ome.tiff``` without this change and verify that the reported error occurs during ```showinf c0.ome.tiff```.  The same command with this change should not result in an error upon ```showinf c0.ome.tiff```.  ```tiffcomment c0.ome.tiff``` should show the following:
* 144 TiffData elements
* no TiffData elements representing C > 0
* Creator (on root OME node) set to ```OME Bio-Formats```

OME-TIFF export fixes

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nifti.txt

http://nifti.nimh.nih.gov/nifti-1/data and http://nifti.nimh.nih.gov/nifti-1/ have been down since last week and it seems the sysadmin has left so unclear if/when they will work again, so replacing with working links.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again.

Fixing nifti links

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nifti.txt

This is the same as gh-2211 but rebased onto dev_5_1.
----
http://nifti.nimh.nih.gov/nifti-1/data and http://nifti.nimh.nih.gov/nifti-1/ have been down since last week and it seems the sysadmin has left so unclear if/when they will work again, so replacing with working links.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/ green again.

Fixing nifti links (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

This is the same as gh-2196 but rebased onto dev_5_1.
----
This prevents exceptions when an OnDemandLongArray is loaded from a memo
file, resulting in an invalid default stream.
See https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7980
To test, convert the file from QA 16966 to .ome.btf using bfconvert.  Import the .ome.btf into OMERO; without this change, pyramid generation will throw an exception as noted in the forum thread.  With this change, pyramid generation should succeed, and the image should be viewable in OMERO.

TiffParser: always set the stream for any OnDemandLongArrays (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

This is the same as gh-2194 but rebased onto dev_5_1.
----
I also modified the end element code so that even if the string builder is empty, the parentNames get peeked (to be consistent with the code before #2181 ).

Fix FEITiffReader stage position parsing. (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See https://trello.com/c/mVFYhwcJ/87-qa16988
To test, use the file from QA 16990.  Without this change, ```showinf``` on the file should throw an exception as indicated in the QA and above card.  With this change, ```showinf``` should display the image without an error, but note that it will be detected as plain TIFF and not OME-TIFF.
No configuration yet as QA 16990/16991 should be detected as a Micromanager dataset, but that will require a separate more involved PR to fix MicromanagerReader.

OME-TIFF: make sure BinaryOnly files reference a valid MetadataFile

---

docs/sphinx/developers/examples/bftest.m

This simplifies the creation of a directory on the tmporary directory by making use of Matlab and Octave core functions instead of the java stuff. While this makes it much simpler, the main reason is Octave compatibility since the example uses Matlab dot notation to call java methods that hasn't been implemented in Octave yet.
With this change, the example runs fine in Octave until the call to im2frame (again, a missing feature in Octave).

developers/examples/bftest.m: simplify by using Matlab and Octave core functions

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This is the same as gh-2215 but rebased onto dev_5_1.
----
See https://trello.com/c/mVFYhwcJ/87-qa16988
To test, use the file from QA 16990.  Without this change, ```showinf``` on the file should throw an exception as indicated in the QA and above card.  With this change, ```showinf``` should display the image without an error, but note that it will be detected as plain TIFF and not OME-TIFF.
No configuration yet as QA 16990/16991 should be detected as a Micromanager dataset, but that will require a separate more involved PR to fix MicromanagerReader.

OME-TIFF: make sure BinaryOnly files reference a valid MetadataFile (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

See https://trello.com/c/499UGA5U/72-micromanager-stage-positions-and-json
This reads the JSON data from each TIFF and stores the key/value pairs
in the original metadata table.  Stage position values ("*PositionUm")
will also be stored in OME-XML, if they are present.
As each TIFF tag contains a single JSON object, simple parsing of the
key/value pairs without an external library was the easiest solution for now.
We'll likely want to revisit this once we have a better plan for dealing
with JSON data in general though.
To test, use the dataset in ```curated/micromanager/nico/Untitled_4_multi_file``` (config PR forthcoming).  Without this change, ```showinf -omexml``` should not show PositionX, PositionY, or PositionZ values for Plane in the OME-XML.  With this change, all 3 values should …

Micromanager: parse JSON tag in each TIFF

---

components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Fixes a temp dir creation problem that led to random test failures (see [the Trello card](https://trello.com/c/ZAN4K973/91-random-failures-in-fakereadertest) for details).
Also adds the test itself to `testng.xml`.

Fix random failures in FakeReaderTest

---

components/formats-gpl/src/loci/formats/in/PyramidTiffReader.java

This is the same as gh-2173 but rebased onto dev_5_1.
----
The assumeEqualStrips was only being set in isThisType().  It was causing the following error during import into OMERO:
```
2016-01-07 12:49:38,824 WARN  [        ome.services.util.ServiceHandler] (.Server-12) Unknown exception thrown.
java.lang.ArrayIndexOutOfBoundsException: 1
at loci.formats.tiff.TiffParser.getTile(TiffParser.java:699) ~[formats-bsd.jar:na]
at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:995) ~[formats-bsd.jar:na]
at loci.formats.tiff.TiffParser.getSamples(TiffParser.java:790) ~[formats-bsd.jar:na]
at loci.formats.in.PyramidTiffReader.openBytes(PyramidTiffReader.java:90) ~[formats-gpl.jar:na]
at loci.formats.ImageReader.openBytes(ImageReader.java:453) ~[formats-api.jar:5.1.4]
```
By also setting …

Also set assumeEqualStrips during reading for PyramidTiffReader (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

This is the same as gh-2213 but rebased onto dev_5_1.
----
See https://trello.com/c/499UGA5U/72-micromanager-stage-positions-and-json
This reads the JSON data from each TIFF and stores the key/value pairs
in the original metadata table.  Stage position values ("*PositionUm")
will also be stored in OME-XML, if they are present.
As each TIFF tag contains a single JSON object, simple parsing of the
key/value pairs without an external library was the easiest solution for now.
We'll likely want to revisit this once we have a better plan for dealing
with JSON data in general though.
To test, use the dataset in ```curated/micromanager/nico/Untitled_4_multi_file``` (config PR forthcoming).  Without this change, ```showinf -omexml``` should not show PositionX, PositionY, or PositionZ values for …

Micromanager: parse JSON tag in each TIFF (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This fixes several issues with the new datasets from Thomas Julou - see https://github.com/openmicroscopy/data_repo_config/pull/76 for configuration and gh-2213 for discussion.
For each of the four new datasets, check that ```showinf``` on the ```*metadata.txt``` file shows images without an error (with this change).  Without this change, ```showinf``` on ```test_sep/Pos0/metadata.txt``` should work, but all others will throw an exception.
For ```test2_sep```, ```test_stack```, and ```test2_stack```, check each image (this may be easier in ImageJ) and verify that each image is unique and not blank.
For ```test_stack``` and ```test2_stack```, the 51123 tag should be parsed for each plane.  Compare the original metadata tables with and without this change; there should be several new …

Micromanager: *_metadata.txt and 51123 tag parsing

---

cpp/examples/CMakeLists.txt
cpp/lib/ome/bioformats/FormatHandler.h
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter2.cpp

Fixes https://trac.openmicroscopy.org/ome/ticket/13154
- Always close and clean up on `close()` in writers
- Use correct plane index when setting UUID metadata in the metadata store
- Update metadata-formatwriter example to use multiple series
- Add metadata-formatwriter2 to use multiple planes
- Make writer close implementations fully idempotent to prevent corruption/double close/inconsistent state
This should ensure that this type of failure will be caught by the unit tests in the future.
--rebased-from #2230
--------
Testing: This is tested automatically by the unit tests, so check the jobs are green.  The metadata-formatwriter tests create OME TIFF as output (`cpp/examples/*.tiff`), which can be viewed with the Java showinf or imported into OMERO to check their validity with other …

C++: OMETIFFWriter metadata and close fixes (5.1)

---

cpp/examples/CMakeLists.txt
cpp/lib/ome/bioformats/FormatHandler.h
cpp/lib/ome/bioformats/detail/FormatWriter.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter.cpp
docs/sphinx/developers/cpp/examples/metadata-formatwriter2.cpp

Fixes https://trac.openmicroscopy.org/ome/ticket/13154
- Always close and clean up on `close()` in writers
- Use correct plane index when setting UUID metadata in the metadata store
- Update metadata-formatwriter example to use multiple series
- Add metadata-formatwriter2 to use multiple planes
- Make writer close implementations fully idempotent to prevent corruption/double close/inconsistent state
This should ensure that this type of failure will be caught by the unit tests in the future.
--------
Testing: This is tested automatically by the unit tests, so check the jobs are green.  The metadata-formatwriter tests create OME TIFF as output (`cpp/examples/*.tiff`), which can be viewed with the Java showinf or imported into OMERO to check their validity with other implementations, though …

C++: OMETIFFWriter metadata and close fixes

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This is the same as gh-2226 but rebased onto dev_5_1.
----
This fixes several issues with the new datasets from Thomas Julou - see https://github.com/openmicroscopy/data_repo_config/pull/76 for configuration and gh-2213 for discussion.
For each of the four new datasets, check that ```showinf``` on the ```*metadata.txt``` file shows images without an error (with this change).  Without this change, ```showinf``` on ```test_sep/Pos0/metadata.txt``` should work, but all others will throw an exception.
For ```test2_sep```, ```test_stack```, and ```test2_stack```, check each image (this may be easier in ImageJ) and verify that each image is unique and not blank.
For ```test_stack``` and ```test2_stack```, the 51123 tag should be parsed for each plane.  Compare the original metadata tables with …

Micromanager: *_metadata.txt and 51123 tag parsing (rebased onto dev_5_1)

---

components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java

This PR simplifies `FakeReaderTest` and makes sure temporary files and directory trees are created only when necessary (except for the root working directory, which is used for the global teardown).

Refactor FakeReaderTest

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/spider.txt

This is the same as gh-2234 but rebased onto dev_5_1.
----
The spider docs have been moved. This should make all the BF docs builds green again once rebased.

Fix spider format links (rebased onto dev_5_1)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/spider.txt

The spider docs have been moved. This should make all the BF docs builds green again once rebased.

Fix spider format links

---

components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
docs/sphinx/formats/micro-manager.txt

Explains new Micro-Manager metadata.txt file handling on MM file format page and in the dataset structure table (will need an autogen docs build run to generate table changes in the docs I think).
Sample links still be added.

Adding metadata file notes to Micro-Manager

---

components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
docs/sphinx/formats/micro-manager.txt

This is the same as gh-2236 but rebased onto dev_5_1.
----
Explains new Micro-Manager metadata.txt file handling on MM file format page and in the dataset structure table (will need an autogen docs build run to generate table changes in the docs I think).
Sample links still be added.

Adding metadata file notes to Micro-Manager (rebased onto dev_5_1)

---

components/formats-gpl/test/matlab/TestBfGetReader.m
components/formats-gpl/test/matlab/TestBfMatlab.m
components/formats-gpl/utils/writeMapAnnotationsExample.java
components/specification/transforms/ome-transforms.xml
components/specification/transforms/util/write-transforms.py
cpp/cmake/BioFormatsCommon.cmake
cpp/cmake/TemplateShellWrapper.cmake.in
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.cpp
cpp/lib/ome/bioformats/out/MinimalTIFFWriter.h
cpp/lib/ome/bioformats/out/OMETIFFWriter.cpp
cpp/lib/ome/bioformats/out/OMETIFFWriter.h
cpp/lib/ome/bioformats/tiff/Codec.cpp
cpp/lib/ome/bioformats/tiff/Codec.h
docs/sphinx/developers/cpp/examples/metadata-formatwriter2.cpp

Bumps the year to 2016, and fixes text so that ```update_copyright``` can pick these up in the future.
See https://github.com/openmicroscopy/bioformats/pull/2239#issuecomment-182476425

Fix copyrights missed by update_copyright

---

docs/sphinx/about/whats-new.txt

As usual, the date is best guess - happy to change it.
I didn't see any C++ PRs since 5.1.7, so assuming a placeholder is enough (/cc @rleigh-dundee).

Add version history for 5.1.8

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#17](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/17/).
----
--no-rebase

Update POM version numbers to 5.1.8

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#18](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/18/).
----
--no-rebase

Update POM version numbers to 5.1.9-SNAPSHOT

---

components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
docs/sphinx/developers/generating-test-images.txt

This PR reviews and clarifies the unit support in the `FakeReader` key/value pair in the documentation and the tests:
- add concrete example of the keys with unit support in the documentation with and without INI file
- remove unit support from `exposureTime` (not implemented)
- add unit tests to `FakeReaderTest` covering the `physicalSize{XYZ}` keys
/cc @ximenesuk @chris-allan @jburel

Fake reader: physical size unit support

---

components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java

This forces INI files written by ```FakeReaderTest``` to be UTF-8, even on Windows.  As noted in the commit message for 2f80775, this is consistent with the rest of our I/O stack, which enforces UTF-8 for both reading and writing across the board.  To validate the fix, the angstrom case has been re-introduced in ```FakeReaderTest```.
See https://trello.com/c/qTAgtVHT/99-fakereader-add-unicode-units-tests

Enforce UTF-8 encoding in FakeReaderTest

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Following 5.2.0-m1, this should revert to the `SNAPSHOT` lifecycle

Revert POM version numbers to 5.2.0-SNAPSHOT

---

docs/sphinx/developers/generating-test-images.txt

In order to safely allow encoding unit symbols like
angstroms and micrometers cross-platform, fake.ini
files are now *required* to be UTF-8.
See: https://github.com/openmicroscopy/bioformats/pull/2248

Specify the encoding (UTF-8) for fake.ini files

---

components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

The "Is SPW file" global metadata was added as part of 2e9d34c9f74213c94ed3c6df3584f08a6c64c87c but has unexpected impact when upgrading OME-XML samples.

Remove "Is SPW file" global metadata stored when reading OME-XML files

---

components/formats-gpl/src/loci/formats/in/SDTReader.java

See https://trello.com/c/57Xzqhzz/95-sdtreader-issue-in-openbytes
To test, use the file from QA 17017.  Without this change, ```showinf``` on the file will throw an exception as noted in the Trello card.  With this change, the entire (single pixel) image should be read without an error.  A configuration PR for QA 17017 is forthcoming.
/cc @imunro for validation with previously-working version of FLIMfit

SDT: fix width padding calculation for single-pixel image

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/improvision-openlab-liff.txt
docs/sphinx/formats/improvision-openlab-raw.txt
docs/sphinx/formats/improvision-tiff.txt

This should make the latest docs green again.
The current problem is actually just that their redirect is not working properly but given that Improvision doesn't exist as a separate entity any more, I figured best to just update the links anyway. Also removed the Openlab links as although they weren't breaking the build, the content doesn't exist any more, it was just redirecting to a 'We're sorry' page and searching for Openlab on the main PE page gives no useful results.

Updating Improvision format links

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

See https://trello.com/c/y5FN422r/61-deltavision-reader-date-parsing
With this PR included,:
- Deltavision datasets like the one liked from the card should have their date correctly parsed by Bio-Formats 
- working distance should be stored using the native unit (MM)
- check the automated tests pass agains the repository with the new sample DV file included
- open the sample file with `showinf -nopix -omexml-only ` and check that no warning is output regarding the date format, the `AcquisitionDate` is populated in the OME-XML metadata and the `Objective` `WorkingDistanceUnit` is expressed in `mm`.

Deltavision: new date format and native units

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-common/src/loci/common/RandomAccessInputStream.java
components/formats-gpl/src/loci/formats/in/GelReader.java
components/formats-gpl/src/loci/formats/in/NDPIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-January/005834.html
To test, use the ```myfile.tif``` file attached to the thread.  Without this change, ```showinf -nopix``` should confirm that the ```XResolution``` and ```YResolution``` keys in the original metadata table are both 0.  ```tiffinfo``` on the same file should show ```  Resolution: 42.42, 0 (unitless)``` as mentioned in the thread.
With this change, ```showinf -nopix``` should show ```42.419...``` and ```0.0``` for ```XResolution``` and ```YResolution``` respectively.

Fix TiffRational integer overflow

---

components/formats-bsd/src/loci/formats/tiff/TiffCompression.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12596.
To test, use the files in ```curated/tiff/samples/tiling-variants```.  Without this change, any of the tiled files with tile width less than 64 should show a "weird" image when viewed with showinf (```*-tiles-*``` where the tile size is at the end of the file name).  The ```*-strips-*``` files show what the image should look like by comparison.
With this change, every test file should show the same image when viewed with showinf; this can be compared with ImageMagick at a minimum.  The pixel values should also be the same across all files (since compression is lossless), so visually checking a few of the files and doing something clever in Matlab or similar to verify that all pixel values are equal may be easier than visually …

TIFF: fix predictor handling for tiled data

---

ant/toplevel.xml
components/ome-jxr/src/ome/jxr/JXRException.java
components/ome-jxr/src/ome/jxr/JXRReader.java
components/ome-jxr/src/ome/jxr/constants/File.java
components/ome-jxr/src/ome/jxr/constants/IFD.java
components/ome-jxr/src/ome/jxr/constants/Image.java
components/ome-jxr/src/ome/jxr/ifd/IFDContainer.java
components/ome-jxr/src/ome/jxr/ifd/IFDEntry.java
components/ome-jxr/src/ome/jxr/ifd/IFDEntryType.java
components/ome-jxr/src/ome/jxr/ifd/IFDMetadata.java
components/ome-jxr/src/ome/jxr/ifd/JXRRational.java
components/ome-jxr/src/ome/jxr/ifd/PixelFormat.java
components/ome-jxr/src/ome/jxr/ifd/PixelType.java
components/ome-jxr/src/ome/jxr/image/BitDepth.java
components/ome-jxr/src/ome/jxr/image/ComponentMode.java
components/ome-jxr/src/ome/jxr/image/FrequencyBand.java
components/ome-jxr/src/ome/jxr/image/InternalColorFormat.java
components/ome-jxr/src/ome/jxr/image/OutputColorFormat.java
components/ome-jxr/src/ome/jxr/parser/DatastreamParser.java
components/ome-jxr/src/ome/jxr/parser/FileParser.java
components/ome-jxr/src/ome/jxr/parser/IFDParser.java
components/ome-jxr/src/ome/jxr/parser/Parser.java
docs/sphinx/developers/components.txt

See https://trello.com/c/urA9fvFj/104-deprecate-jpeg-xr-classes
Add references to the corresponding mailing list thread and blog post

Mark all ome.jxr classes as deprecated

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java

In preparation of the upcoming [addition of support for regions](https://trello.com/c/HeAwzPRO/34-regions-in-fakereader) in the fake images reader, this PR:
- refactors the logic filling the acquisition dates and the annotations for each image into helper methods
- adds unit tests covering both cases

Fakereader annotations

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See QA 17040.  This should correctly parse various types of arrays and
keys with child attributes.  As noted previously, this should eventually be replaced
by use of a real JSON library.
To test, use the *.txt files from QA 17040.  Without this change, as noted in the comments for QA 17040:
```
You should see lines like this in the metadata display:
Plane #0 08 39 -0800
Plane #0 ] Camera-SaturatePixels
Plane #1 08 40 -0800
Plane #1 ] Camera-SaturatePixels
et cetera. 
```
With this change, none of the metadata keys should contain ```]``` or ```[``` or be just numbers, the ```Camera-SaturatePixels``` key should be present for every plane, and in general there shouldn't be anything that looks odd.  It's also possible to double-check against the actual JSON strings by turning on TRACE-level …

Micromanager: clean up JSON metadata parsing

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13095
To test, use the file from QA 16882.  Without this change, ```showinf -minmax``` should show that the first series has non-zero pixels, and the remaining four series have all zero pixels.  With this change, the same test should show that all five series have non-zero pixels (which should also be obvious from looking at the images).  The images and dimensions can also be compared against Zeiss' ZEN software.

Zeiss CZI: turn off prestitched flag for separate scenes

---

components/formats-common/src/loci/common/DebugTools.java
components/formats-common/src/loci/common/Log4jTools.java
components/formats-common/src/loci/common/LogbackTools.java
components/formats-gpl/matlab/bfInitLogging.m
components/formats-gpl/matlab/bfopen.m
components/formats-gpl/test/matlab/TestBfInitLogging.m
docs/sphinx/developers/examples/bftest.m
docs/sphinx/developers/matlab-dev.txt

Fixes https://github.com/openmicroscopy/bioformats/issues/2233
This PR addresses the issues reported in https://github.com/openmicroscopy/bioformats/issues/2233 by:
- adding a MATLAB function initializing the logging system with a logic similar to [logging.basicConfig](https://docs.python.org/3/library/logging.html#logging.basicConfig).
- set the default logging level to `WARN` if no argument is passed
- use this logging initialization function in `bfopen` to prevent logging set by the user to be overriden
- add some logic checking whether logging is enabled to `loci.common.DebugTools`
- try the following workflow from a clear MATLAB session using the test artifacts:
```
% Open an image - logging should be initialized at WARN level
data = bfopen(id);
% Check whether …
```

MATLAB: add logging initialization function

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java

Issue raised by QA-17055
If MetadataOptions has the MetadataLevel set to minimum then the
readStamps function will not be called and stamps will be equal to null.
This results in the following NPE:
java.lang.NullPointerException
at loci.formats.in.FluoviewReader.initStandardMetadata(FluoviewReader.java:328)
at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98)
at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:577)
at loci.formats.FormatReader.setId(FormatReader.java:1426)
at loci.formats.ImageReader.setId(ImageReader.java:835)
To reproduce:
- Import the sample file from QA-17055 via Omero Insight 5.2.2
- Verify that the same Null Pointer Exception is reproduced
To test:
- Update the formats-gpl lib from this branch
- Re import the sample file
- Verify that …

FluoviewReader - Null Pointer Fix

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13029
To test, use the dataset from QA 11394.  Note that the files as uploaded to the QA system are not in the correct directory structure; ```curated/cellsens/qa-11394``` contains the dataset in the correct directory structure.
Without this change, ```showinf``` on the .vsi file should show that the first series has 38 Z sections and 1 timepoint.  With this change, the same test should show 38 Z sections and 18 timepoints.  The dimensions and images can be compared with Olympus' OlyVIA software (http://www.olympus-lifescience.com/en/support/downloads/#!dlOpen=%23detail847249644).
Note that the dimension type constants are taken from  the ```curated/specs/VSI File Format v1.6.pdf``` document.

CellSens .vsi: detect dimensions using the "dimension meaning" tag

---

components/formats-gpl/src/loci/formats/in/ZeissTIFFReader.java

CaseInsensitiveLocation.exists() can (by design) return true even if the
path from which it was constructed does not actually exist.  This fixes
ZeissTIFFReader to report the CaseInsensitiveLocation's path after
lookup, rather than the path passed to the constructor.
This should fix intermittent test failures, see
https://trello.com/c/EWS9dntP/101-zeiss-zvi-improve-tile-handling
This will be difficult to completely verify, but the test failures noted on the card do seem to correlate with abnormally long build execution times (~20 hours vs. ~14-16).  It might be easiest to just let this sit for a few weeks to see what happens.

Zeiss TIFF: fix getSeriesUsedFiles to return actual paths on disk

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/alicona-3d.txt

This is the same as gh-2278 but rebased onto dev_5_1.
----
This should fix https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/171/warnings3Result/

Fixing alicona link (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

This prevents large multi-tile files from having incorrect plane offsets after the 2GB mark.
See
https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=4710&p=16480#p16480
In the process of uploading the test file; test instructions and configuration PR forthcoming.

LIF: use long offsets for tile acquisitions

---

components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/SpiderReader.java

This PR adds native length support for EM readers. To test this PR, open some MRC and Spider datasets and check the pixel size is stored in Angstroms.
Note the last commit 7a474b2 modifies the content of the original metadata stored for the MRC format to sotre the values read  from the [MRC header](http://bio3d.colorado.edu/imod/doc/mrc_format.txt).

EM formats: use native physical size units

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://trello.com/c/11hj6Ixk/47-fix-gatan-dm4-metadata-parsing.
This PR:
- fixes the erroneous metadata parsing reported in https://github.com/openmicroscopy/bioformats/pull/1979#issuecomment-140699287 by excluding the `Scale` key/value pairs associated with `Calibration` groups - the physical sizes of the QA file mentioned in the PR should be 0.01255um in X and Y and 0.05um in Z
- stores the physical sizes using native units instead of converting unilaterally to micrometers

Gatan: fix physical size parsing and use native units

---

components/xsd-fu/templates-java/OMEXMLMetadataImpl.template

Fix for issue seen in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-generated-sources/152/
Extra comments such as the below were appearing in the Java generated version of OMEXMLMetadataImpl:
// <"TiffData" XschemaElement instance at 0x106aaff38>
This was a debug comment which should not be present in the generated file, 
To test: 
- Generate OMEXMLMetadataImpl.java
- Verify that there are no instances of XschemaElement mentioned in any comments in the file

OMEXMLMetadataImpl Template - Remove unwanted comment

---

tools/bump_maven_version.py

Originally opened as https://github.com/openmicroscopy/bioformats/pull/2158
this modifies the bump_maven_version script to allow changing the groupId
property. Use of a separate groupId prevents confusing version re-use in
the local repository, which is especially hard to detect in the case of
SNAPSHOTs.
To test:
* Try a command like `tools/bump_maven_version.py --old-group=ome --new-group=idr 0.0.3-SNAPSHOT` and see if your regular dev workflow continues to work.

Refactor bump_maven_version.py for setting groups

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
docs/sphinx/developers/generating-test-images.txt

See https://trello.com/c/HeAwzPRO/34-regions-in-fakereader and https://trello.com/c/ZMNhFXl7/106-strange-regex-in-fakereader
This PR:
- improves the parsing of quantities with units (`physicalSize`) to throw RunTimeException with the corresponding unit tests
- adds a first implementation of regions support in fake files with the corresponding unit tests
The regions support is currently limited to `Point` shapes for initial feedback. It assumes the following semantics: `foo&series=n&points=m.fake` is read as  `n` images containing `m` ROIs each where each ROI contains only one `Point` shape. 
To test this PR, check the following creates 20 `Point` ROIs:
```
./tools/showinf -omexmlonly "foo&series=2&points=10.fake"
```
Currently all shapes are at the same XY position with no ZCT. Should we …

FakeReader: regions

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
components/formats-bsd/test/loci/formats/utests/MemoizerTest.java

See https://trello.com/c/XkVbBZ2X/111-fakereader-reset-variables-when-reader-is-closed and https://trello.com/c/IdLyg8yn/89-fakereader-reopenfile-fails-with-filenotfoundexception
The unit tests additions should cover these test cases so checking Travis and the daily builds should be sufficient. To be thorough, a simple workflow as follows could be tested and should not raise any exception:
```
IFormatReader reader = new FakeReader();
reader.setId("foo&points=10.fake");
reader.reopenFile();
reader.close();
reader.setId("foo.fake");
```

FakeReader: fix close() and reopenFile()

---

docs/sphinx/formats/index.txt

See https://trello.com/c/visx1plk/36-schema-samples-migration
This PR adds a link to the top level of the sample images folder on downloads to the Format index page in the BF docs for completeness-sake. Also fixes whitespace (apologies for doing both on one commit but it is only one short page of content).
Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/index.html once the merge build has run.

Add sample image link to formats index page

---

components/xsd-fu/templates-cpp/OMEXMLModelEnum.template
components/xsd-fu/xsd-fu
cpp/test/ome-xml/enum.cpp

This is to allow direct code generation with the C++ preprocessor by looping over the available enum values.
A better approach would be to use C++11 variadic templates, but this is not yet a possibility, and they too are broken on Windows.  See http://stackoverflow.com/questions/35360908/alternative-to-expanding-templates-in-a-switch-statement/ for further details.
This is the second attempt to make this build.  It's the same as before, but the nested loops are skipped on Windows due to the preprocessor being broken.
Purpose: It will be used to simplify code working with model enums, but the primary intent is model units support (to be added in a future PR).
See also: https://github.com/ome/ome-files-cpp/pull/5
Generated source changes: …

cpp: ome-xml: Add enum value list macros

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
components/specification/src/ome/specification/XMLMockObjects.java
docs/sphinx/developers/generating-test-images.txt

See https://trello.com/c/hzWe7ZNR/115-fakereader-fix-regions-with-hcs
The default `XMLMockObjects.createPlate()` was creating a `MicrobeamManipulation` object with an associated `ROI` which was conflicting with the annotation indexing in the `FakeReader` semantics. The default is modified to remove this creation although it might be possible to selectively enable it using a flag i.e. `XMLMockObjects.createPlate(int, boolean)`.
The flip effect of this change is that fakes should now be able to combine HCS and Regions features, i.e. the following
```
touch "HCSanalysis&plates=10&plateRows=16&plateCols=24&rectangles=100.fake"
```
should allow us to manipulate objects that approach the scale at which folders should be tested. /cc @mtbc

Fake reader: HCS with regions

---

components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/SpiderReader.java

This is the same as gh-2275 but rebased onto dev_5_1.
----
This PR adds native length support for EM readers. To test this PR, open some MRC and Spider datasets and check the pixel size is stored in Angstroms.
Note the last commit 7a474b2 modifies the content of the original metadata stored for the MRC format to sotre the values read  from the [MRC header](http://bio3d.colorado.edu/imod/doc/mrc_format.txt).

EM formats: use native physical size units (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/SDTReader.java

This is the same as gh-2253 but rebased onto dev_5_1.
----
See https://trello.com/c/57Xzqhzz/95-sdtreader-issue-in-openbytes
To test, use the file from QA 17017.  Without this change, ```showinf``` on the file will throw an exception as noted in the Trello card.  With this change, the entire (single pixel) image should be read without an error.  A configuration PR for QA 17017 is forthcoming.
/cc @imunro for validation with previously-working version of FLIMfit

SDT: fix width padding calculation for single-pixel image (rebased onto dev_5_1)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/improvision-openlab-liff.txt
docs/sphinx/formats/improvision-openlab-raw.txt
docs/sphinx/formats/improvision-tiff.txt

This is the same as gh-2259 but rebased onto dev_5_1.
----
This should make the latest docs green again.
The current problem is actually just that their redirect is not working properly but given that Improvision doesn't exist as a separate entity any more, I figured best to just update the links anyway. Also removed the Openlab links as although they weren't breaking the build, the content doesn't exist any more, it was just redirecting to a 'We're sorry' page and searching for Openlab on the main PE page gives no useful results.

Updating Improvision format links (rebased onto dev_5_1)

---

components/specification/transforms/2015-01-to-2016-DEV0.xsl

This change is required as the Xerces processor does not support the previously implemented XSLT 2.0 solution. Issue was raised in a previous PR - https://github.com/openmicroscopy/bioformats/pull/2286#issuecomment-197889060
To test:
•	Ensure that the Schema Upgrade tests run successfully

Transforms - String tokenize xslt 1.0

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

This is the same as gh-2276 but rebased onto dev_5_1.
----
See https://trello.com/c/11hj6Ixk/47-fix-gatan-dm4-metadata-parsing.
This PR:
- fixes the erroneous metadata parsing reported in https://github.com/openmicroscopy/bioformats/pull/1979#issuecomment-140699287 by excluding the `Scale` key/value pairs associated with `Calibration` groups - the physical sizes of the QA file mentioned in the PR should be 0.01255um in X and Y and 0.05um in Z
- stores the physical sizes using native units instead of converting unilaterally to micrometers

Gatan: fix physical size parsing and use native units (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This is the same as gh-2262 but rebased onto dev_5_1.
----
See QA 17040.  This should correctly parse various types of arrays and
keys with child attributes.  As noted previously, this should eventually be replaced
by use of a real JSON library.
To test, use the *.txt files from QA 17040.  Without this change, as noted in the comments for QA 17040:
```
You should see lines like this in the metadata display:
Plane #0 08 39 -0800
Plane #0 ] Camera-SaturatePixels
Plane #1 08 40 -0800
Plane #1 ] Camera-SaturatePixels
et cetera. 
```
With this change, none of the metadata keys should contain ```]``` or ```[``` or be just numbers, the ```Camera-SaturatePixels``` key should be present for every plane, and in general there shouldn't be anything that looks odd.  It's also possible to double-check …

Micromanager: clean up JSON metadata parsing (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java

This is the same as gh-2274 but rebased onto dev_5_1.
----
Issue raised by QA-17055
If MetadataOptions has the MetadataLevel set to minimum then the
readStamps function will not be called and stamps will be equal to null.
This results in the following NPE:
java.lang.NullPointerException
at loci.formats.in.FluoviewReader.initStandardMetadata(FluoviewReader.java:328)
at loci.formats.in.BaseTiffReader.initMetadata(BaseTiffReader.java:98)
at loci.formats.in.BaseTiffReader.initFile(BaseTiffReader.java:577)
at loci.formats.FormatReader.setId(FormatReader.java:1426)
at loci.formats.ImageReader.setId(ImageReader.java:835)
To reproduce:
- Import the sample file from QA-17055 via Omero Insight 5.2.2
- Verify that the same Null Pointer Exception is reproduced
To test:
- Update the formats-gpl lib …

FluoviewReader - Null Pointer Fix (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

This is the same as gh-2130 but rebased onto dev_5_1.
----
This prevents large multi-tile files from having incorrect plane offsets after the 2GB mark.
See
https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=4710&p=16480#p16480
In the process of uploading the test file; test instructions and configuration PR forthcoming.

LIF: use long offsets for tile acquisitions (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This is the same as gh-2257 but rebased onto dev_5_1.
----
See https://trello.com/c/y5FN422r/61-deltavision-reader-date-parsing
With this PR included,:
- Deltavision datasets like the one liked from the card should have their date correctly parsed by Bio-Formats 
- working distance should be stored using the native unit (MM)
- check the automated tests pass agains the repository with the new sample DV file included
- open the sample file with `showinf -nopix -omexml-only ` and check that no warning is output regarding the date format, the `AcquisitionDate` is populated in the OME-XML metadata and the `Objective` `WorkingDistanceUnit` is expressed in `mm`.

Deltavision: new date format and native units (rebased onto dev_5_1)

---

tools/source-archive.py

Correct  timestamp
```
ant release
```
Check `ant/gitversion.xml` and `cmake/GitVersion.cmake` in the two tar archives.

source-archive: Set antversion.xml and GitVersion.cmake mtime

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

ref: http://trac.openmicroscopy.org/ome/ticket/13179
Please try opening the 'nd2' file from QA 17099 in FIJI/ImageJ. Without this PR you should be getting a String parsing exception. This PR should fix that issue, and open the image without any issues. Also compare the values for the 'emission wavelengths' between NISElements Viewer and Bio-Formats, and check if the values match.
@melissalinkert @jburel : As always, please let me know if the code change looks fine.

NativeND2Reader: Fix for the emmission wavelength

---

components/formats-gpl/src/loci/formats/in/APLReader.java

#2307 This PR is a follow up to the user reported issues in https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8013#p16861
The associated ticket is http://trac.openmicroscopy.org/ome/ticket/13174
There are a number of associated QA files provided in QA-17057 and QA-17107
Testing showed a range off issues causing various failures. This PR will address the following fixes:
- Files which do not have all the dimensions listed will be defaulted
- Files which have filename and file path switched, if the filename does not exist the filepath will be parsed to retrieve the filename 
- Files where the filename is unreadable, some of the data from the mtb files are using unkown charsets. Without being able to tell which charset is used the values, most importantly the filename will be …

Fixes for the APL Reader

---

tools/source-archive.py

This is the same as gh-2311 but rebased onto dev_5_1.
----
Correct  timestamp
```
ant release
```
Check `ant/gitversion.xml` and `cmake/GitVersion.cmake` in the two tar archives.

source-archive: Set antversion.xml and GitVersion.cmake mtime (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-March/005868.html
To test, use the file referenced in https://github.com/openmicroscopy/data_repo_config/pull/93.  Verify that without this change, ```showinf``` produces an exception as shown in the thread.  With this change, 60 series should be present, each with a single plane.  The images and metadata can be compared with Nikon's NIS Elements viewer.

ND2: fix detection of planes with interleaved metadata blocks

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See https://trello.com/c/mVFYhwcJ/87-ome-tiff-missing-metadata-file
This commit partly reverts a previous bug fix for OME-TIFF with `BinaryOnly`  blocks where the `MetatadaFile` check in `isThisType(RandomAccessInputStream)` was solely based on the file extension. Instead, an extra check is performed at the `isThisType(String, boolean)` level if `metadataFile` has been set by `isThisType(RandomAccessInputStream)` to parse the metadata.
- check the automated tests pass on the OME-TIFF files of the data repository especially the filesets with companion OME-XML
- test the new sample fileset using a binary-only OME-TIFF with the metadata file being stored into an OME-TIFF file - see also https://github.com/openmicroscopy/bioformats/issues/2308
- test QA 16990 as described in …

Improve handling of OME-TIFF multi-file filesets with partial metadata blocks

---

components/formats-common/src/loci/common/DataTools.java
components/formats-common/test/loci/common/utests/DataToolsTest.java

See http://trac.openmicroscopy.org/ome/ticket/7782
This PR adds a number of utility functions to `DataTools` allowing to generically:
- account for decimal separators in different locales (`.` vs `,`)
- parse a String into Double, Float, Integer...
- handle NumberFormatException thrown when parsing
Unit tests have been added to cover the newly added functions.
As discussed in http://trac.openmicroscopy.org/ome/ticket/7782, following the acceptance of this new API, all readers should be reviewed and string parsing should use this new API. I will review all candidate readers and open a corresponding card. Note this review should likely be done down the development line when we are sure we are not releasing any bug fix 5.1.x release.

DataTools: add number parsing API 

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/perkinelmer-ultraview.txt

This is the same as gh-2325 but rebased onto dev_5_1.
----
fixes the broken link to the microscope information

PerkinElmer UltraVIEW VoX link (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2016-February/003588.html
To test, use the file in ```curated/zeiss-czi/niko``` (it will be ~100GB).  The images are quite large; the easiest first test would be to select a few ~2kx2k tiles and check the display in ImageJ vs Zeiss' ZEN.  It would be good to try importing into OMERO as well, to validate that all of the pixel data is read correctly, but this will take a while as pyramids will need to be generated.
Configuration PR is: https://github.com/openmicroscopy/data_repo_config/pull/96

Zeiss CZI: fixes for files with multiple mosaics and positions

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This is the same as gh-2314 but rebased onto dev_5_1.
----
See https://trello.com/c/mVFYhwcJ/87-ome-tiff-missing-metadata-file
This commit partly reverts a previous bug fix for OME-TIFF with `BinaryOnly`  blocks where the `MetatadaFile` check in `isThisType(RandomAccessInputStream)` was solely based on the file extension. Instead, an extra check is performed at the `isThisType(String, boolean)` level if `metadataFile` has been set by `isThisType(RandomAccessInputStream)` to parse the metadata.
- check the automated tests pass on the OME-TIFF files of the data repository especially the filesets with companion OME-XML
- test the new sample fileset using a binary-only OME-TIFF with the metadata file being stored into an OME-TIFF file - see also …

Improve handling of OME-TIFF multi-file filesets with partial metadata blocks (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/APLReader.java

This is the same as [gh-2304](https://github.com/openmicroscopy/bioformats/pull/2304) but rebased onto dev_5_1.
----
#2307 This PR is a follow up to the user reported issues in https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8013#p16861
The associated ticket is http://trac.openmicroscopy.org/ome/ticket/13174
There are a number of associated QA files provided in QA-17057 and QA-17107
Testing showed a range off issues causing various failures. This PR will address the following fixes:
Files which do not have all the dimensions listed will be defaulted
Files which have filename and file path switched, if the filename does not exist the filepath will be parsed to retrieve the filename
Files where the filename is unreadable, some of the data from the mtb files are using unkown …

Fixes for the APL Reader (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This is the same as gh-2290 but rebased onto dev_5_1.
----
ref: http://trac.openmicroscopy.org/ome/ticket/13179
Please try opening the 'nd2' file from QA 17099 in FIJI/ImageJ. Without this PR you should be getting a String parsing exception. This PR should fix that issue, and open the image without any issues. Also compare the values for the 'emission wavelengths' between NISElements Viewer and Bio-Formats, and check if the values match.
@melissalinkert @jburel : As always, please let me know if the code change looks fine.

NativeND2Reader: Fix for the emmission wavelength (rebased onto dev_5_1)

---

components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
components/specification/src/ome/specification/XMLMockObjects.java

See https://trello.com/c/pBQgFTMS/117-fakereader-fix-microbeam-with-multiple-screens
This PR fixes an indexing bug in the `XMLMockObjects.createPlate()` method which caused all fake HCS files with multiple screens to be invalid as multiple `Experiment` objects were created with the same ID. Unit tests are also added to `FakeReaderTest` to cover the multiple screens test case and include some testing of the `MicrobeamManipulation` option.
To test these changes, check fake HCS files with more than one screen have a valid OME-XML:
```
$ showinf -nopix -omexml "SPW&screens=2.fake
$ showinf -nopix -omexml "SPW&screens=2&plates=3.fake
$ showinf -nopix -omexml "SPW&screens=2&withMicrobeam=true.fake
```

Fake: fix HCS fake files with multiple screens

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is the same as gh-2268 but rebased onto dev_5_1.
----
Fixes https://trac.openmicroscopy.org/ome/ticket/13095
To test, use the file from QA 16882.  Without this change, ```showinf -minmax``` should show that the first series has non-zero pixels, and the remaining four series have all zero pixels.  With this change, the same test should show that all five series have non-zero pixels (which should also be obvious from looking at the images).  The images and dimensions can also be compared against Zeiss' ZEN software.
This is the same as gh-2305 but rebased onto dev_5_1.
----
See http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2016-February/003588.html
To test, use the file in curated/zeiss-czi/niko (it will be ~100GB). The images are quite large; the easiest first test would be …

Zeiss CZI: 5.1.9 backports

---

docs/sphinx/users/imagej/index.txt

This is the same as gh-2316 but rebased onto dev_5_1.
----
See https://trello.com/c/Sqm8TR76/5-document-the-exporter-big-tiff-workflow
/cc @pwalczysko, @hflynn

ImageJ plugin docs: add note about exporter file extensions (rebased onto dev_5_1)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/lavision-imspector.txt

Our current representative set of LaVision Imspector files included in the daily automated tests only contain files generated with the 4.0 and 4.1 versions of ImspectorPro. /cc @imunro

Add officially supported versions to the LaVision Imspector format

---

components/formats-gpl/src/loci/formats/in/PQBinReader.java

For very large files this reader was prohibitively slow. See https://trac.openmicroscopy.org/ome/ticket/13183
Test using curated .bin files. A larger example is available in QA 17134. Should now load in < 1min.

Update PicoQuant reader to always buffer data.

---

components/formats-bsd/src/loci/formats/out/ICSWriter.java

See https://github.com/openmicroscopy/bioformats/issues/2237 and
https://trello.com/c/L7dtKWsl/96-bio-format-exporter-issues
To test, use the macro from gh-2237 and test cases (1) and (2) from the Trello card.  Verify that no exceptions are thrown during conversion, and that the resulting files are ~4 MB each and are reported by showinf as having 15 Z sections (1 timepoint, 1 channel).  Also verify that converting the ```Organ of corti``` sample to a single .ics file does not behave differently with this change; be sure to test conversion in both ImageJ and bfconvert, and check each plane in the resulting file against the original data.
Note that there are likely still some edge cases here.  The "correct" way to do this across all writers would be to add API similar to suggestions in …

ICS writer: fix dimension population for split files

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/lavision-imspector.txt

This is the same as gh-2337 but rebased onto dev_5_1.
----
Our current representative set of LaVision Imspector files included in the daily automated tests only contain files generated with the 4.0 and 4.1 versions of ImspectorPro. /cc @imunro

Add officially supported versions to the LaVision Imspector format (rebased onto dev_5_1)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/3i-slidebook.txt

Updates the slidebook format page to point to how to update the new DLLs. For now the /info/slidebook URL needs to redirect to https://www.openmicroscopy.org/site/support/slidebook but once 3i are sorted, it should be changed to point at their page (see #2289 for context)
cc @sbesson - can you set up the redirect please?

Linking to slidebook6 page

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/3i-slidebook.txt

This is the same as gh-2341 but rebased onto dev_5_1.
----
Updates the slidebook format page to point to how to update the new DLLs. For now the /info/slidebook URL needs to redirect to https://www.openmicroscopy.org/site/support/slidebook but once 3i are sorted, it should be changed to point at their page (see #2289 for context)
cc @sbesson - can you set up the redirect please?

Linking to slidebook6 page (rebased onto dev_5_1)

---

components/formats-common/test/loci/common/utests/LocationTest.java

The unit tests have been failing regularly lately due to a connection
time-out. As the checks operated on this URL are also asserted by
https://www.openmicroscopy.org/site/products/images, removing as a duplicate.
To test this PR, check https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-build-win/ and https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-build/ pass.

Remove duplicate Location unit test case

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13112.
This fixes the case when a color camera is used (so each plane has 3 RGB
channels), and multiple channels are acquired potentially in addition to
multiple timepoints and/or Z sections.
To test, use the files from QA 16911 and QA 16919.  Compare the images as shown in Leica's LAS X or LAS AF Lite software against what is shown by ImageJ with and without this change.  Also verify that with this change, no error messages are shown when opening either file in ImageJ.

Leica LIF: fix multi-dimensional data from color cameras

---

components/bio-formats-plugins/src/loci/plugins/in/DisplayHandler.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterOptions.java
components/bio-formats-plugins/src/loci/plugins/in/MainDialog.java
components/bio-formats-plugins/src/loci/plugins/in/importer-options.txt
components/bio-formats-plugins/src/loci/plugins/util/ROIHandler.java

The PR adds a choice for the user to determine whether to import ROIs to the ImageJ ROI manager or create a new overlay and add them to that. The choice is disabled if the _Display ROIs_ is disabled.

Add ROI import to ImageJ overlay

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#19](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/19/).
----
--no-rebase

Update POM version numbers to 5.1.9

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2228 but rebased onto develop.
----
As usual, the date is best guess - happy to change it.
I didn't see any C++ PRs since 5.1.7, so assuming a placeholder is enough (/cc @rleigh-dundee).

Add version history for 5.1.8 (rebased onto develop)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#20](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/20/).
----
--no-rebase

Update POM version numbers to 5.1.10-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12978
To test, use the following datasets mentioned in the ticket:
* QA 16996 (OME-TIFF)
* QA 11328 (Zeiss LSM)
* QA 16981 (Zeiss LSM)
* QA 17012 (Zeiss LSM)
Verify that without this change, ```showinf -nopix -omexml``` shows validation errors indicating invalid ```Plane``` elements in the generated OME-XML.  With these changes, there should be no ```Plane``` validation errors.  The Zeiss LSM datasets should also be checked against Zeiss' ZEN Lite software, as the fix for those datasets was to introduce rotation and phase support to the Zeiss LSM reader.

Resolve Plane population errors for Zeiss LSM and OME-TIFF

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2336 but rebased onto develop.
----
Preliminary draft for the version history. Please feel free to point out edits/corrections.
@melissalinkert @jburel @sbesson @joshmoore

Add version history for 5.1.9 (rebased onto develop)

---

docs/sphinx/developers/jace/overview.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/213/warnings3Result/ - I deleted the link initially thinking it hadn't been released since 2010, then re-read the page and realised it's now part of the XuvTools download. Not sure if we want to remove the link and leave the text though - the info on the page is rather out of date, linking to LOCI and broken doc links.

Fix libBlitzBioFormats link

---

docs/sphinx/developers/jace/overview.txt

This is the same as gh-2351 but rebased onto dev_5_1.
----
See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/213/warnings3Result/ - I deleted the link initially thinking it hadn't been released since 2010, then re-read the page and realised it's now part of the XuvTools download. Not sure if we want to remove the link and leave the text though - the info on the page is rather out of date, linking to LOCI and broken doc links.

Fix libBlitzBioFormats link (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/test/loci/formats/utests/FilePatternBlockTest.java

This PR fixes the detection of comma-separated pattern blocks.
The first commit addresses a minor problem where the `fixed` and `numeric` properties where not set for csv blocks, although they are general enough to make sense in all cases.
The second commit fixes a more serious problem where block strings where checked for range structure (`<START-STOP:STEP>`) first and then for csv structure. This made pattern blocks with dashes in their csv elements unusable. For instance, without this PR, FilePatternBlock would try to interpret `<Cy3-B,DAPI>` as a range from `Cy3` to `B,DAPI`, leading to a `NumberFormatException`.
Note that a side effect of this is that now single element blocks, e.g., `<foo>`, are considered comma-separated lists with one element, rather than ranges with step 1, so …

Fix csv pattern blocks

---

cpp/test/ome-xml/transform.cpp

With the patched xalan source from https://github.com/ome/ome-cmake-superbuild/pull/56 it's now safe to test downgrade failure for map annotations.  This patch adds the ability to know if a test will throw and exception or not, and check for this accordingly.
**Do not merge before https://github.com/ome/ome-cmake-superbuild/pull/56 **
--------
Testing: Check jobs are green.  The tests will segfault and fail if it's not handled, or else fail if the test passes rather than failing as required.

cpp: transform test: Handle MapAnnotation downgrade

---

components/formats-gpl/src/loci/formats/in/NiftiReader.java

As discussed in the mailing list, I changed planeSize to long to prevent the seek position calculation from overflowing on large .nii files.

Fixes crash when loading large .nii files

---

components/formats-gpl/src/loci/formats/in/LiFlimReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-April/005940.html
This change should fix the issue reported in the ome-users thread while preserving compatiblity with existing `li-flim` filesets. Additionally, the exposure time should now be stored using the native unit in the metadata.
To test this PR, check the automated tests pass and review the sample files under `curated/li-flim`.

LiFlimReader: fix ExposureTime check and use native units

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

Fixes the bug introduced by 7aecd02.  See https://trello.com/c/OV5y9vcP/201-thumbnail-outage.
I was testing with a subset of one of the affected plates (see ```/ome/team/mlinkert/sysgro/```); without this change, ```showinf -minmax``` on series greater than 1 shows only blank planes.  With this change, every series has unique data.

Flex: fix file indexing when multiple runs are present

---

components/formats-api/src/loci/formats/FormatReader.java

This PR addresses a performance issue in `FormatReader.getUsedFiles` that can get very serious for formats with a large number of files in multiple series (e.g., `ScreenReader`).
The current implementation iteratively updates a `Vector` with the contents of arrays returned from `getSeriesUsedFiles`. To avoid duplicates, each filename from `getSeriesUsedFiles` is checked to see if it already belongs to the vector before adding. The problem is that `Vector.contains` is O(n), which makes the whole update operation **quadratic**.
A previous attempt at fixing the problem (see #1028) only made things better for single-series images: updates for subsequent series are still performed in the same way.
On my laptop, `ScreenReader.getUsedFiles` on [a TARA screen …

getUsedFiles performance fix

---

components/formats-bsd/src/loci/formats/FilePatternBlock.java
components/formats-bsd/src/loci/formats/IllegalBlockException.java
components/formats-bsd/test/loci/formats/utests/FilePatternBlockTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Same changes as #2145, but rebased onto metadata.
**Update:** also included (part of) #2190 so that the new test is run by `ant`

Fixes and unit test for FilePatternBlock (metadata)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
pom.xml

This reverts commit 4d9b7966bc1383c9f30bc90c4cee843c0f0fe51a.
See https://trello.com/c/P0qiWL1n/123-drop-merge-build-pom-profile for the the corresponding discussion

Revert "Add a merge build profile to POMs"

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Rebase of #2161 onto `metadata`. It also adds the test to `testng.xml` (in `develop` this happened in #2190). It does *not* include the change to `FilePattern` from 4329e2fe021bf252f0d133ee001c4827e38e3048, because that's already been merged to `metadata`.

Unit test for FilePatternBlock

---

components/formats-bsd/src/loci/formats/AxisGuesser.java
components/formats-bsd/test/loci/formats/utests/AxisGuesserTest.java

This PR changes `AxisGuesser`'s static fields that define known axis prefixes (`AxisGuesser.{Z,C,T,S}`) to `public`. Users need to know what pattern block prefixes lead to automatic axis assignments, and this is indeed documented in the [sphinx docs](https://www.openmicroscopy.org/site/support/bio-formats5.1/formats/pattern-file.html).
Another problem with those fields is that their names are too short, making the code harder to read and debug. Since they're going public, this was the last chance to make them longer, so I've changed them to `AxisGuesser.{Z,C,T,S}_PREFIXES`

AxisGuesser: public axis prefixes

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/varian-fdf.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-latest-docs/124/warnings3Result/ - Varian link was breaking the build as it was being redirected to Agilent, who bought the company some years ago according to their website.
I followed the existing examples which have owner above developer on the autogen page despite it being the other way around on the built format pages so hopefully it will work ok and not upset the autogen build!

Add Varian owner link

---

docs/sphinx/conf.py.in
docs/sphinx/themes/globalbftoc.html

See https://trello.com/c/K0EpMdAx/128-bf-docs-sidebar-menu-still-links-to-bf-c-downloads
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/
Not to be backported

Update cpp downloads link in sidebar

---

components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java

The issue can be reproduced by opening a set of images grouped using a pattern where the index of the first image is not zero. Instead adding the index of the first image to calculate the index of the last image should be sufficient to group all files together.
See http://forum.imagej.net/t/little-bug-in-bio-formats-importer/1461
- open the fileset included in the ImageJ forum thread, check the original issue using Bio-Formats 5.1.9 (only 2 files grouped) and check all 6 files are grouped using either Pattern or Dimensions is restored with this PR included
- modify filenames to vary the first index and increment of each axis and check the grouping still works as expected when using the Dimensions option. For instance, a fileset with the following pattern:
``` …
```

Fix Bio-Formats importer bug for file grouped with the "Dimensions" option

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java
components/test-suite/src/loci/tests/testng/TestTools.java

This is building upon the commits in https://github.com/openmicroscopy/bioformats/pull/2282
This has extended the Out Of Memory exception handling to other tests in the FormatReaderTest.
There are the possibilities of some memory leaks with the tests but those are still being investigated.

TestNG - OutOfMemory handling

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

--rebased-from #2168
See the above PR for testing instructions.
Also see https://www.openmicroscopy.org/community/viewtopic.php?t=8042&p=17018#p17018 for a sample SVS file (http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs) which fails to convert with bfconvert without this PR.

TiffSaver: fix recorded offsets to non-interleaved RGB tiles (5.1)

---

components/formats-bsd/src/loci/formats/AxisGuesser.java

Addresses a problem found by @joshmoore in #2368 after it was merged, i.e., the fact that I've used an external library in the public API. With this change, each set of prefixes not a true immutable set, but rather an unmodifiable view of a mutable `HashSet`. However, there's no way to modify the `HashSet` because only the unmodifiable wrapper has a reference to it.

AxisGuesser: do not use Guava

---

components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java

This is the same as gh-2380 but rebased onto dev_5_1.
----
The issue can be reproduced by opening a set of images grouped using a pattern where the index of the first image is not zero. Instead adding the index of the first image to calculate the index of the last image should be sufficient to group all files together.
See http://forum.imagej.net/t/little-bug-in-bio-formats-importer/1461
- open the fileset included in the ImageJ forum thread, check the original issue using Bio-Formats 5.1.9 (only 2 files grouped) and check all 6 files are grouped using either Pattern or Dimensions is restored with this PR included
- modify filenames to vary the first index and increment of each axis and check the grouping still works as expected when using the Dimensions option. For …

Fix Bio-Formats importer bug for file grouped with the "Dimensions" option (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java

See https://trac.openmicroscopy.org/ome/ticket/13220 and https://github.com/openmicroscopy/bioformats/issues/2367
The [removal of the 3i Slidebook DLLs](https://github.com/openmicroscopy/bioformats/pull/2300) from the source code repository in Bio-Formats 5.1.9 caused warnings to be systematically printed for non-Fiji/ImageJ Windows users of Bio-Formats.In particular, when constructing an `ImageReader` and initializing the `SlideBook6Reader`, the [following line](https://github.com/scijava/native-lib-loader/blob/native-lib-loader-2.1.0/src/main/java/org/scijava/nativelib/NativeLibraryUtil.java#L275) in the native library loading library is now throwing an exception at the WARN level due to the DLL removal.
To mitigate this issue, an initial proposal was to use the logging to silence these …

Slidebook DLL warnings

---

cpp/cmake/GTest.cmake

See https://github.com/ome/ome-cmake-superbuild/pull/64

cmake: Remove VC11 faux variadic templates workaround

---

components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/test/loci/formats/utests/FilePatternTest.java
components/formats-gpl/src/loci/formats/in/MIASReader.java

This PR removes a restriction in `FilePattern.getPrefix` that prevents the definition of patterns where one or more blocks appear in the dirname (rather than in the basename). This allows to match layouts where, for instance, data for different channels is stored in different directories:
```
/tmp/c<1,2>/foo.fake
```
Note that this is not hypotetical: we have exactly this problem with one of the IDR datasets.
As a side effect, this also removes a semantic discrepancy between `FilePattern.getPrefix()` and `FilePattern.getPrefix(int i)`, so that now the former behaves like the latter with an argument of `0`.

FilePattern: allow pattern blocks in the dirname

---

components/formats-api/src/loci/formats/DelegateReader.java

This fixes the edge case where ```setUseLegacy(true)``` was called, but the
legacy reader throws an exception during setId triggering the native
reader instead.
Prior to this commit, the result of calling openBytes after setId would
have been a slightly cryptic exception indicating invalid core metadata.
Now, calling openBytes after setId should pass off to the native reader
without error.
Testing is easiest in ImageJ, preferably on a non-Windows machine.  First open ImageJ and select ```Plugins > Bio-Formats > Bio-Formats Plugins Configuration```, then select ```Nikon ND2``` in the ```Formats``` tab and make sure the ```Use Nikon's ND2 library...``` box is ticked (it shouldn't be by default).  Without this change, opening either of the .nd2 files in test_images_good/nd2 should result in …

Fix reader delegation when the legacy reader is enabled but not working

---

components/formats-bsd/src/loci/formats/out/APNGWriter.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12943.
To test, use ```test_images_good/ome-tiff/multi-channel-4D-series.ome.tif```, or any other multi-dimensional file.  Use ```bfconvert``` to convert the file to a variety of output file names, e.g.:
* ```test.png```
* ```test_S%s.png```
* ```test_C%c.png```
* ```test_S%s_C%c_Z%z_T%t.png```
Without this change, ```bfconvert``` should run without error, but only ```test.png``` should be readable by ```showinf``` or ImageMagick (```display```); all other .png files should show an error message upon reading.
With this change, ```bfconvert``` should still run without error, and all .png files should be readable by both ```showinf``` and ImageMagick.  Note that ImageMagick doesn't support PNG files with multiple planes, so only the first …

APNG export: fix frame count and footer writing

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-lsm.txt

BF docs builds were unstable this morning because this link was broken. Replacement link is their homepage as found via google search. Should make the docs green again.

Fix SVI Huygens link

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-lsm.txt

This is the same as gh-2391 but rebased onto dev_5_1.
----
BF docs builds were unstable this morning because this link was broken. Replacement link is their homepage as found via google search. Should make the docs green again.

Fix SVI Huygens link (rebased onto dev_5_1)

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/volocity-library-clipping.txt
docs/sphinx/formats/volocity.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/1245/warnings3Result/
Browsing around, it seems like PE are in the process of updating their website and some of their redirects are a bit shot! This is an older page but the new one (http://www.perkinelmer.com/category/cellular-imaging-software) has no mention of Volocity so it seemed like the best option. Hopefully it'll stick around!

Updating volocity links

---

ant/java.xml
ant/logback.xml
components/formats-api/build.xml
components/formats-bsd/build.xml
components/formats-common/build.xml
components/formats-gpl/build.xml
components/metakit/build.xml
components/ome-xml/build.xml

See https://trello.com/c/ISuLct1l/125-formats-bsd-unit-tests-take-too-long-to-run
This PR starts addressing test issues at the logging level with the following changes:
- the Ant test targets now use the `logback.xml` under `ant` (like the Maven test targets)
- the `FATAL` logging configuration in `ant/logback.xml` is removed.
The impact of this PR should be the following:
- Ant-based tests should have reduced logging (https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build/ and https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-build-win) especially the Formats BSD tests should have no more logs due to the JPEG2000 tests
- Formats BSD Maven-based tests should now hide the stack trace due to the ClassList error. As a results the log  of the Maven components in the [Travis matrix …

Tests and logging

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/volocity-library-clipping.txt
docs/sphinx/formats/volocity.txt

This is the same as gh-2397 but rebased onto dev_5_1.
----
See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/1245/warnings3Result/
Browsing around, it seems like PE are in the process of updating their website and some of their redirects are a bit shot! This is an older page but the new one (http://www.perkinelmer.com/category/cellular-imaging-software) has no mention of Volocity so it seemed like the best option. Hopefully it'll stick around!

Updating volocity links (rebased onto dev_5_1)

---

components/formats-gpl/src/loci/formats/in/SlideBook6Reader.java

This is the same as gh-2381 but rebased onto dev_5_1.
----
See https://trac.openmicroscopy.org/ome/ticket/13220 and https://github.com/openmicroscopy/bioformats/issues/2367
The [removal of the 3i Slidebook DLLs](https://github.com/openmicroscopy/bioformats/pull/2300) from the source code repository in Bio-Formats 5.1.9 caused warnings to be systematically printed for non-Fiji/ImageJ Windows users of Bio-Formats.In particular, when constructing an `ImageReader` and initializing the `SlideBook6Reader`, the [following line](https://github.com/scijava/native-lib-loader/blob/native-lib-loader-2.1.0/src/main/java/org/scijava/nativelib/NativeLibraryUtil.java#L275) in the native library loading library is now throwing an exception at the WARN level due to the DLL removal.
To mitigate this issue, …

Slidebook DLL warnings (rebased onto dev_5_1)

---

docs/sphinx/developers/xsd-fu.txt

Dave Kuhlman released an updated version yesterday and the URL has changed.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again.
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/xsd-fu.html#special-thanks

Fix generateDS link

---

docs/sphinx/developers/xsd-fu.txt

This is the same as gh-2404 but rebased onto dev_5_1.
----
Dave Kuhlman released an updated version yesterday and the URL has changed.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-5.1-merge-docs/ green again.
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.1-staging/developers/xsd-fu.html#special-thanks

Fix generateDS link (rebased onto dev_5_1)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#21](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/21/).
----
--no-rebase

Update POM version numbers to 5.1.10

---

components/formats-bsd/test/spec/schema/Schema_Transform_Test.java

This is a new Bio-Formats test based off https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroJava/test/integration/ExporterTest.java
- The main goal of the test is to validate the downgrade and upgrade process of schema transforms.
- The base image data is generated from XMLMockObjects.
- Images are generated for simple images, images with ROI's and images with Annotations
- For each of the above there is a test to validate the image from XMLMockObjects, test the downgrade transforms and test the upgrade transforms
- The transforms performed are parsed from the catalog file ome-transforms.xml
- Additionally upon completing the transforms in each test I have read the image in OMEXMLReader which will in turn upgrade to the current schema and validate it

Schema Transform Test

---

docs/sphinx/about/whats-new.txt

This is the same as gh-2402 but rebased onto develop.
----
Adds version history for 5.1.10 release. Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html

Add 5.1.10 version history (rebased onto develop)

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-5.1-latest-version-bump#22](https://ci.openmicroscopy.org/job/BIOFORMATS-5.1-latest-version-bump/22/).
----
--no-rebase

Update POM version numbers to 5.1.11-SNAPSHOT

---

docs/sphinx/developers/xsd-fu.txt

This is the same as gh-2410 but rebased onto dev_5_1.
----
Reverts openmicroscopy/bioformats#2404

Revert "Fix generateDS link" (rebased onto dev_5_1)

---

components/formats-bsd/src/loci/formats/in/FlowSightReader.java

Satisfies https://github.com/openmicroscopy/bioformats/pull/2318#issuecomment-218255604 by logging the issue now handled by https://github.com/openmicroscopy/bioformats/pull/2318/commits/1187fe7ea98b715136819996a05a6e038fb5fed7. Unfortunately I am not aware that we have the original data that triggers the issue.

log when using workaround for .cif issue from bad TIF tag

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageFaker.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/formats-common/src/loci/common/DebugTools.java
components/formats-common/src/loci/common/Log4jTools.java
components/formats-common/src/loci/common/LogbackTools.java
components/formats-common/test/loci/common/utests/DebugToolsTest.java
components/formats-common/test/loci/common/utests/testng-template.xml
components/formats-gpl/matlab/bfInitLogging.m
components/formats-gpl/test/matlab/ReaderTest.m
components/formats-gpl/test/matlab/TestBfInitLogging.m

See http://trac.openmicroscopy.org/ome/ticket/13151
This PR reviews the `loci.common.DebugTools` class and its logging framework implementations `loci.common.Log4jTools` and `loci.common.LogbackTools` to:
- respect logging frameworks (log4j/logback) initialized via a binding-specific configuration file
- prevent `DebugTools.enableLogging(String)` from overriding initialized logger levels
- addition of a new `DebugTools.setRootLevel(String)` to set the level of the root logger with its `Log4jTools` and `LogbackTools` implementations
- addition of `DebugTools.enableLogging()` the core function for initialization the logging system which is conditional to the return code of  `DebugTools.isEnabled()` and delegates the initialization to the corresponding logging framework classes
- …

Logging improvements

---

components/formats-bsd/src/loci/formats/Memoizer.java

Addresses a problem where `Memoizer.wrap` was issuing a warning if any of the relevant `MetadataOptions` was `null`. Since `MetadataOptions.getMetadataOption` returns `null` to signal that the requested option is not set, getting a `null` is not a sign that something went wrong, so I've changed `wrap` to silently return the unwrapped reader in this case.
**NOTE: this was breaking the Travis build by increasing the Maven test output from ~9K to ~75K lines.**
Other problems fixed here:
* If the whole `options` container was `null`, `wrap` returned `null`, while the docs state that the original reader would be returned unwrapped (which seems the sensible thing to do, so I've changed the code to match the docs and not the other way around)
* The code was giving up too early by returning the …

Memoizer.wrap: fix handling of MetadataOptions

---

ant/java.xml
ant/logback.xml
components/formats-api/build.xml
components/formats-bsd/build.xml
components/formats-common/build.xml
components/formats-gpl/build.xml
components/metakit/build.xml
components/ome-xml/build.xml

Rebases #2396 onto metadata. Brings the Maven test output line count from 9158 down to 3525 (Maven 3.0.5 on my laptop), reducing the risk that Travis will break again soon.

Tests and logging (metadata)

---

docs/sphinx/developers/generating-test-images.txt

This adds an example to the fake images workflow which clarifies how to connect the regions and plates (or images) when creating fakes.
To test, check https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/generating-test-images.html
@sbesson

Fake images doc

---

components/formats-bsd/src/loci/formats/AxisGuesser.java
components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/test/loci/formats/utests/AxisGuesserTest.java
components/formats-gpl/src/loci/formats/in/ScreenReader.java

Adds two new features to `ScreenReader`:
* An `AxisTypes` setting can be added to each `Well` entry to override the automatic type guessing performed by `AxisGuesser`. The value should be a string of `Z|C|T` characters, one for each pattern block (e.g., `AxisTypes = CT`)
* A `ChannelNames` setting can be added to each `Well` entry to override the channel names. The value should be a comma-separated list, e.g., `ChannelNames = DAPI,Cy3`
Also adds a new `overrideAxisTypes` method to `FileStitcher`, which allows to externally set the axis types before `setId` is called. In this case, `FileStitcher` uses the new `AxisGuesser(int[], ...)` (see 19ef8e25d6a8244575a78d031c8715331da6e337) that sidesteps axis types guessing (i.e., the `AxisGuesser` is only used for `getAdjustedOrder`).
Note that, …

ScreenReader enhancements

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/ColumbusReader.java

From the original PR by @melissalinkert :
> The file to import is MeasurementIndex.ColumbusIDX.xml, though I'd expect a directory import to work as well (if slightly slower). Choosing any of the TIFFs in the `$timestamp` subdirectory will not result in a plate import.
> This should match up with the number of TIFF files - one file per field and well, for N total TIFF files. Physical pixel sizes, channel names, wavelengths, and timestamps should all be present. As noted in the reader, the channel color is present in the dataset but I'm unsure of how to parse it at the moment, so the colors shown on import are coming from the emission wavelengths.
The datasets of interest for the IDR are:
* https://trello.com/c/1cXLMIan/226-bakal-lab-nf-kappa-b-activation-idr0019-sero-nfkappab
* …

Columbus export read

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-axiovision-zvi.txt

Previous link was broken - https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/263/warnings3Result/ - poking around their website, this is the only Axiovision page now and is linked from their Microscopy software for biology & medicine section even though it's labelled as material science when you link through.
Should make the build green again.

Update axiovision link

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

Fixes  https://trac.openmicroscopy.org/ome/ticket/13226
As indicated in the command help, this option should display the current library version and exit. This commit skips the initial upgrade check if the argument is passed.
To test this PR, run the command line tools *offline* and check:
- `showinf -version` and `bfconvert -version` do not throw a `java.net.UnknownHostException`
- `showinf test.fake` and `bfconvert test.fake` throw a `java.net.UnknownHostException`

Do not run upgrade check when passing -version

---

docs/sphinx/developers/index.txt
docs/sphinx/developers/java-library.txt
docs/sphinx/developers/logging.txt
docs/sphinx/developers/matlab-dev.txt

This PR adds a page to the Sphinx developer documentation to describe the logging framework (slf4j + log4j/logback) used by Bio-Formats and the methods of the `DebugTools` utility class.
It also includes some documentation of the breaking logging API changes in https://github.com/openmicroscopy/bioformats/pull/2372.

Logging developer documentation 

---

components/specification/publish

See https://trello.com/c/zkbHhnNO/31-schema-release-process and https://github.com/openmicroscopy/bioformats/pull/1985 for an earlier version of this PR
This PR streamlines the XSD schema release workflow as follows:
- unifies the schemas generation under a single root to include both pre and post 2007 schemas including @rleigh-dundee's suggestion in https://github.com/openmicroscopy/bioformats/pull/1985#issuecomment-142570844
- removes deprecated `web-extras` and `Samples` which is managed and released independently under a different location
To test this PR
- run ``cd components/specification && ./publish`` and check no error is thrown
- review the diff between the `published` folder generated under specification and the live schemas. The pre-2007 schemas should be added to the the …

Schema publication

---

components/formats-gpl/src/loci/formats/in/SDTReader.java

To test should load all curated .sdt files but larger files (see QA17189 for sample file from Ninewells) should load in 10s of seconds rather than 10s of minutes.

Address slow loading of .sdt files beyond an arbitrary threshold.

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-May/006046.html
To test, verify that ```showinf -nopix -omexml``` without this change only shows timestamps for the first two planes (c == 0 t == 0 and c == 1 t== 0).  With this change, timestamps should be shown for all planes, and the timestamps for all channels of the same timepoint should be the same.

Zeiss CZI: fix timestamp indexing when multiple separate channels are present

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Fixes a problem in HCS-style `.stk` datasets (see #2151) that was causing `MetamorphReader.openBytes` to always return the first plane regardless of the requested index.
#2151 introduced a convention where a `.stk` file whose UIC4 `StageLabel`s are `"Scan A01", "Scan A02", ...` is interpreted as a plate. In particular, image planes are mapped to different series. The problem is that #2151 does not change anything in `MinimalTiffReader.openBytes`, where TIFF IFDs are mapped to plane indices, not series indices.

Fix HCS variant of MetaMorph STK

---

components/formats-bsd/src/loci/formats/in/FilePatternReader.java

Adds the following to `FilePatternReader.openBytes`:
* a `helper.setSeries` call to so that the correct planes are returned when stitching multi-series files
* a `helper.close` call to match `helper.setId` (avoids file leaks)

FilePatternReader: fix openBytes

---

components/formats-bsd/src/loci/formats/FileStitcher.java

Keep individual readers from `ExternalSeries` open and don't re-initialize them in `initReader`. A test on `idr0010` data shows that, without this, individual readers can be reinitialized thousands of times if they are multi-series.

FileStitcher: avoid re-initializing underlying readers

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See https://trac.openmicroscopy.org/ome/ticket/13107
At the Bio-Formats command-line tools level, this PR adds a `reader.close()` call if a `FormatException` is thrown by `reader.setId()` reproducing the NPE described in the ticket. In addition these exceptions are not handled more gracefully using logging and should return a non-zero return code.
This PR should be tested at using either one of the QA files linked to the ticket or any of the [multi-file OME-TIFF filesets](https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/data.html#multi-file-ome-tiff-filesets) after deleting one of the TIFF files:
- at the Bio-Formats level, `showinf /path/to/broken_image.ome.tiff` should print an error statement and the full stack trace should be shown when using `showinf -debug …

OME-TIFF: fix NPE when closing reader for partial multi-file filesets

---

components/formats-common/src/loci/common/DataTools.java
components/formats-common/test/loci/common/utests/DataToolsTest.java
components/formats-gpl/src/loci/formats/in/SVSReader.java

See https://trello.com/c/ErnjO26c/113-review-number-parsing-across-readers and the file uploaded as QA 17150.
To test this PR,
- check opening the SVS file from the QA above without this PR throws a `FormatNumberException`
- check the same file can be opened with this PR

SVS: fix FormatNumberException by using the DataTools parsing API

---

components/formats-bsd/build.xml
components/formats-bsd/test/loci/formats/utests/SixteenBitLosslessJPEG2000LongRunningTest.java
components/formats-bsd/test/loci/formats/utests/SixteenBitLosslessJPEG2000Test.java
components/formats-bsd/test/loci/formats/utests/testng-long-running.xml

See https://trello.com/c/ISuLct1l/125-formats-bsd-unit-tests-take-too-long-to-run
This PR proposes to reduce the time spent in the default Formats BSD unit tests with the main bottleneck being the `SixteenBitLosslessJPEG2000Test` class which loops over every short value from -32,768 to +32,767.
- add an increment field in `SixteenBitLosslessJPEG2000Test` controlling the loop of `testLosslessPixels`
- set this increment to `1024` by default
- define another test class and use the TestNG Factory annotation to set the increment to `1` and test all short values
- leave `testng.xml` consumed by the default Maven `test` target unchanged
- define a new `testng-long-running.xml` configuration file and `test-long-running` Ant target allowing to run the full test using the entire Short range.
- …

Formats-bsd: unit tests performance

---

components/formats-gpl/src/loci/formats/in/ZeissZVIReader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-December/005759.html.
The corresponding test file is in ```data_repo/inbox/zeiss-zvi/pradeep```; note that it is smaller than the file mentioned on the mailing list (5 tiles, 2 timepoints).  Compare the file as displayed by Zeiss' ZEN software with what is shown by showinf or ImageJ.  Without this change, there should be small but noticeable differences between ZEN and Bio-Formats when changing timepoints.  With this change, there should be no noticeable differences.

Zeiss ZVI: rework image ordering calculation to allow for tiles

---

components/specification/publish

See https://trello.com/c/SBhCiJwz/153-update-schema-index-page and https://trello.com/c/SWRU2CID/151-schema-web-pages-navigation
Following the reworking of the schema release workflow, this PR:
- marks the `OMERO` and `Editor` schemas as Legacy as opposed to Active and drops the link to the generated OMERO schema documentation
- removes the link to the legacy `XMLschemas` URL post-unification
- adds relative links to the individual schema overview pages as proposed by @rleigh-dundee
- updates the links to the model documentation and add link to the schema version history
- inverts the order of the history and schemas sections 
To test this PR, run the `publish` script from `components/specification` and review the generated output under `published`.

Schemas: index improvements 

---

components/formats-api/test/loci/formats/utests/FormatToolsTest.java

Minor unit tests optimization to use DataProvider carried over from https://github.com/openmicroscopy/bioformats/pull/2448

Combine FormatTools.defaultMinMax() unit tests using DataProvider

---

components/xsd-fu/templates-java/AggregateMetadata.template
components/xsd-fu/templates-java/DummyMetadata.template
components/xsd-fu/templates-java/FilterMetadata.template
components/xsd-fu/templates-java/MetadataRetrieve.template
components/xsd-fu/templates-java/MetadataStore.template
components/xsd-fu/templates-java/OMEXMLMetadataImpl.template
components/xsd-fu/templates-java/OMEXMLMetadataImpl_Channel_ID.template
components/xsd-fu/templates-java/OMEXMLModelEnumHandler.template
components/xsd-fu/templates-java/OMEXMLModelObject.template
components/xsd-fu/templates-java/OMEXMLModelObject_Reference.template
components/xsd-fu/templates-java/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template
components/xsd-fu/templates-java/OMEXMLModelObject_XMLAnnotation_update_Value.template

Follow-up work of https://github.com/openmicroscopy/bioformats/pull/2450. This commit should update the style of the generated Java classes to match the rest of the code base.
See https://github.com/openmicroscopy/bioformats/pull/2453/files?w=1 for the diff without whitespace changes.
Check all Bio-Formats jobs are green and that the non-whitespace difference between the `develop/latest/generated_sources` and `develop/merge/generated_sources` branches of @snoopycrimecop's fork is empty.

Unify Java templates indentation to 2 spaces

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-bsd/src/loci/formats/tools/CommandLineTools.java
components/formats-bsd/src/loci/formats/tools/TiffComment.java
components/formats-bsd/src/loci/formats/tools/XMLValidate.java

See https://trac.openmicroscopy.org/ome/ticket/8260 and https://trac.openmicroscopy.org/ome/ticket/13226 
This PR initiates the refactoring of the common functions used across the various command-line interfaces into a central class under `formats-bsd`. Currently this refactoring is limited to the version printing and the upgrade checking but more could be migrated there in the future.
Summary of changes:
- add a `loci.formats.tools.CommandLineTools` class defining both command-line arguments and methods
- migrates arguments and code used in `showinf`, `bfconvert`, `tiffcomment` and `xmlvalid`
- decouples the version and upgrade check  logic by running the upgrade check *after* the version handling
- gracefully handles `UnknowHostException` in the `UpgradeChecker` allowing to prevent …

Command-line tools: common methods refactoring

---

cpp/lib/ome/xml/model/detail/OMEModelObject.cpp

Rather than waiting for an exception to be thrown by the
Element RAII wrapper, check whether it will throw
beforehand.  This isn't strictly necessary, but it makes
the processing slightly more efficient and, more
importantly, makes it easier to debug the model code
since only important exceptions will be thrown.
--------
Testing: Check builds are green.  There's no change in functionality since this is purely an optimisation, so nothing specific to test with respect to behaviour changes.

cpp: ome-xml: Throw less exceptions in OMEModelObject::getChildrenByTagName

---

ant/xsd-fu.xml
components/autogen/build.properties
components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-bsd/test/loci/formats/utests/SPWModelMock.java
components/formats-bsd/test/spec/schema/SchemaResolverTest.java
components/formats-gpl/test/loci/formats/utests/InOutCurrentTest.java
components/formats-gpl/test/loci/formats/utests/xml/OMEXMLServiceTest.java
components/formats-gpl/test/loci/formats/utests/xml/Upgrade200809Test.java
components/formats-gpl/test/loci/formats/utests/xml/Upgrade200909Test.java
components/formats-gpl/test/loci/formats/utests/xml/Upgrade201004Test.java
components/formats-gpl/test/loci/formats/utests/xml/Upgrade201006Test.java
components/formats-gpl/test/loci/formats/utests/xml/Upgrade201106Test.java
components/ome-xml/src/ome/xml/meta/AbstractOMEXMLMetadata.java
components/specification/publish
components/specification/released-schema/2016-06/catalog.xml
components/specification/released-schema/2016-06/ome.xsd
components/specification/released-schema/catalog.xml
components/specification/src/ome/specification/XMLWriter.java
components/specification/transforms/2015-01-to-2016-06.xsl
components/specification/transforms/2016-06-to-2015-01.xsl
components/specification/transforms/ome-transforms.xml
cpp/cmake/XsdFu.cmake
pom.xml

See https://trello.com/c/dFKmII6U/155-2016-06-schema-release
This PR completes the work on the 2016-06 model by:
- renaming the `2016-DEV0` schema as `2016-06` and updating all locations consuming it
- resetting the version of the 2016-06 schema to 1
- updating the `publish` script to move the deprecated schema namespaces to the legacy section and document the namespace unification
Note this PR does not include the link to the 2016-06 oXygen documentation which requires the new schema publication to be generated. The link will be upgraded (and released) in a follow-up PR.

2016-06 model

---

components/specification/released-schema/2016-06/ome.xsd

As spotted by @sbesson - this had been missed when the new file was made.

Updating date on ome.xsd

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/alicona-3d.txt

This is the second time I've had to fix this link and as it's no longer hosted by the company and is 13 years old, I propose just dropping the link.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again.

Remove dead alicona 3D spec doc link

---

components/xsd-fu/python/ome/modeltools/language.py
components/xsd-fu/python/ome/modeltools/property.py

Tweak the unit types inside the python generator.  This essentially changes `Quantity<Unit, double>` to `Quantity<Unit, Value>`.  Note `double` is the default type in the Quantity template and so not actually generated.  Example: `Quantity<Length>` becomes `Quantity<Length, NonNegativeFloat>`.  This involves no code changes--it's completely transparent from an end use point of view.  Unless you were using values out of range of course, in which case it will now correctly throw an exception!
Future work: A corresponding change to the Java code generator would be useful, if there's a way to do that with the existing Quantity and Unit generics.
--------
Testing: Check jobs are green.  Also check generated source changes.

xsd-fu: Specialise C++ Quantity types by both unit and value

---

docs/sphinx/about/whats-new.txt

Based on https://trello.com/c/CCldRgeg/145-final-review-of-the-model-breaking-changes
Staged on http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html
Could maybe do with re-ordering/subsections changing but at least we have the content there, although I've maybe given unnecessary detail on some and not enough on others.
Plan is to edit this for the 5.2.0 release rather than leave the milestone as a separate stand-alone history so this is an intermediate 'getting stuff down on the page' PR to a certain extent anyway.

5.2.0-m4 version history

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#2](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/2/).
----
--no-rebase

Update POM version numbers to 5.2.0-m4

---

docs/sphinx/themes/globalbftoc.html

Missing `http:` which breaks the docs when not staged on openmicroscopy.org

docs: Fix licensing URL in global TOC

---

components/formats-common/src/loci/common/DebugTools.java

The switch from throwable to ReflectiveOperationException does not catch `java.lang.NoClassDefFoundError` thrown by `Log4jTools`.
To test this PR, check `loci_tools.jar` on ImageJ stalls when running the Bio-Formats Importer without this PR but works as expected with this PR included.

Catch LinkageError to fix loci_tools with ImageJ

---

components/formats-api/pom.xml
components/formats-api/src/loci/formats/ClassList.java
components/formats-api/test/loci/formats/utests/ClassListTest.java
components/formats-api/test/loci/formats/utests/iterables.txt

This PR is an incremental step towards the reader discoverability described in https://github.com/openmicroscopy/design/issues/42. The changes in this Pull Request are restricted themselves to `ClassList` which is used in conjunction with the `readers.txt/writers.txt` configuration files in `ImageReader/ImageWriter` to instantiate a series classes implementing the `IFormatReader/IFormatWriter` interface.
The major changes proposed in this PR are the following:
- refactors the `ClassList` notably decomposes the constructor with a configuration file into  a set of public methods can be tested independently and expose more granularity for the generation of class lists
- improves error handling when dealing with invalid input streams
- add `append()`, `prepend()` methods allowing to combine …

ClassList: discovery improvements 

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/test/loci/formats/utests/FormatToolsTest.java

See discussion in https://github.com/openmicroscopy/bioformats/pull/2437 for more context. Similarly to the existing `FormatTools.getPhysicalSize()` methods, this PR adds a set of three methods to the `FormatTools` class allowing to format a stage position from an input `Double` and an input unit:
- `FormatTools.getStagePosition(Double, String)`
- `FormatTools.getStagePosition(Double, Unit<Length>)`
The use case for these methods is the parsing of string values across the readers in a safe manner. In particular, combined with `DataTools` utility methods, the following forms:
```
Length pos = FormatTools.getStagePosition(DataTools.parseDouble(value), unit);
```
should allow to handle most invalid cases and prevent the usage of `try/catch` statement.
Unit tests have been added to …

Add helper methods to FormatTools for creating stage position lengths

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

Fixes https://github.com/openmicroscopy/bioformats/issues/2308
This Pull Request fixes the `MicroManagerReader` reader to handle large datasets saved as image stack and split over multiple files (i.e. datasets larger than 4GB). While testing a sample dataset, a second issue was fixed by improving the way each image dimensionality is parsed from the metadata file.
- in `parsePosition()`, the number of IFDs were added to the current plane at the end of each loop as well as in the call to `parseKeyValue()` causing an `ArrayIndexOutOfBoundsException` when dealing with multiple files
- the `dimensionOrder` was previously unconditionally set to `XYZCT` causing wrong files to be returned by `Position.getFile()` under some conditions. For the sample multi-file dataset, this caused …

Micromanager: fix multi-file image stacks and dimensionorder

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#4](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/4/).
----
--no-rebase

Update POM version numbers to 5.2.0-m5

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/test/loci/formats/utests/FormatToolsTest.java

Add corresponding unit tests checking the returned length is null
Following up of the discussion in https://github.com/openmicroscopy/bioformats/pull/2448#discussion_r69686940

Handle NaN values in FormatTools.getStagePosition()

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/alicona-3d.txt
docs/sphinx/formats/princeton-instruments-spe.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/PxU8TWGe/66-new-formats-documentation
This adds a format page for SPE and adds it to the supported formats table. Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/supported-formats.html
N.B. Alicona 3D whitespace fix because I didn't run autogen build to update the docs page on #2468

Add format page for SPE

---

components/autogen/src/format-pages.txt
components/formats-gpl/src/loci/formats/in/SPCReader.java
docs/sphinx/formats/becker-hickl-fifo.txt
docs/sphinx/metadata/SPCReader.txt
docs/sphinx/supported-formats.txt

This documents the format support added in https://github.com/openmicroscopy/bioformats/pull/1992
I've assumed MIF because when I looked at the reader it talks about companion files, this may not be correct.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/metadata/SPCReader.html and http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/becker-hickl-fifo.html

Add SPC FIFO format page

---

docs/sphinx/about/whats-new.txt
docs/sphinx/index.txt

See https://trello.com/c/9mgNoo67/21-version-history-prs
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html
m4 content is edited as plan is to build up content but end up with only 1 version history entry for 5.2.0.

Update version history for m5

---

docs/sphinx/users/ome-server/index.txt

This removed the old LOCI trac ticket link which is making the docs build unstable (see https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/337/warnings3Result/) and while I was at it, I figured I may as well update the 'Upgrading' section as well as there is no point it linking to the current release when we don't support OME server any more and haven't done since 5.0.0.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/users/ome-server/index.html once built

Update OME server page

---

components/bio-formats-tools/src/loci/formats/tools/TiffComment.java
docs/sphinx/users/comlinetools/edit.txt

See https://trello.com/c/pqx8FSLk/160-can-comment-ome-tiff-but-not-plain-tiff for reference
This PR adds a note to the Sphinx documentation page and the `tiffcomment` usage to mention the `ImageDescription` tag requirement in the TIFF file.

Tiffcomment: add note about ImageDescription tag

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/becker-hickl-fifo.txt

See https://trello.com/c/hjZpniE2/166-make-becker-hickl-fifo-spc-files-public
This adds a link to the now public samples and a note regarding what the files are currently supported as suggested by @imunro 
Will be staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/becker-hickl-fifo.html

Add SPC-FIFO public images & support note

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nifti.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/HAiHHpHf/126-nifti-public-samples
and https://github.com/openmicroscopy/data_repo_config/pull/116
This adds the public samples link and also the .nii file extension to the supported formats table and format page (it had previously only been added the the dataset structure table as this is updated from the reader code automatically).
Will be staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/formats/nifti.html
N.B. we may also want to add .nii.gz when https://github.com/openmicroscopy/bioformats/pull/2493 is merged.

Add nifti public sample link & missed extension

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/NE6UFb5k/70-better-document-breaking-reader-changes - on further thought it seemed best to mark those format fixes which constitute breaking changes in the existing list, something we can easily carry forward for all further releases, rather than add another separate list to repeat info.
I rearranged the page at the same time although maybe we want to put the top level API changes back at the top and just leave the model stuff at the bottom, not sure what other people think - more recent releases have format fixes first but going back to the last major release, they were lower down the list.

Rearrange 5.2 history & mark breaking readers

---

components/specification/publish

Under http://www.openmicroscopy.org/Schemas/ --
> Generated documentation for the schemas is available at: http://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2015-01/ome.html
should now be OME-2016-06.

update schema link to 2016-06 for publication

---

components/specification/samples/2016-06/timestampannotation.ome.xml

For some reason, an extra `>` got inserted in the sample during the generation making it invalid. Since this sample contains non-POSIX timestamps, it is excluded from the C++ tests and could not be detected. The re-enabling of the XML tests for the OME-XML/OME-TIFF readers in https://github.com/openmicroscopy/bioformats/pull/2501 successfully flagged this file as invalid.
To test this PR check that `xmlvalid` fails on the OME-XML file without this PR but passes with the PR included.

Fix timestamp annotation 2016-06 OME-XML sample

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This PR reverts skips in https://github.com/openmicroscopy/bioformats/commit/dbd5f824f8c581d5f8476f03d5f580b4090ac077 to investigate issues when converting/validating OME-XML /cc @dgault @rleigh-dundee

Re-include OME-XML and OME-TIFF samples when testing valid OME-XML

---

components/formats-bsd/src/loci/formats/gui/ImageViewer.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-gpl/matlab/createMinimalOMEXMLMetadata.m

This is a fix for the generation of invalid OME XML when files are read through OMETiffReader.
The setPixelsBinDataBigEndian is only called if the PixelsBinData > 0 otherwise setPixelsBigEndian is used instead.
This can be tested using the FormatReaderTests with the following PR included - https://github.com/openmicroscopy/bioformats/pull/2501

Fix for invalid setPixelsBinDataBigEndian

---

components/formats-common/test/loci/common/utests/LocationTest.java

Fix https://trac.openmicroscopy.org/ome/ticket/13272 by allowing Maven tests to pass even when offline. Specifically, check that:
* when online, *all* `LocationTest` methods pass
* when offline, *some* `LocationTest` methods skip, the rest pass
* in both cases, `mvn test` succeeds.

if offline, skip LocationTest cases that require connectivity

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trello.com/c/OHKk0BiI/161-jpeg-xr.
This adds more polished support for slide data from Axio Scan.Z1 systems.  Slides should now be detected as a complete full-resolution image (instead of each tile being a separate series), pyramid sub-resolutions are detected, and label/overview images are detected.
This is excluded for now, pending conclusion of m5 and a configuration PR.  Further testing instructions will be added once the configuration PR is set - I'm just in the process of importing the 13 files for which configurations have changed, verifying that the new behavior is correct, and assembling supporting screenshots.

Zeiss CZI: add support for slides

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

The buffer size should be 16 for all RandomAccessInputStream instances.
This is consistent with other TIFF-based readers, and should be faster in general than a 1MB buffer.
See testing information in https://github.com/openmicroscopy/bioformats/pull/2338.  This affects OME-TIFF only, so the other formats listed there can be ignored.

OME-TIFF: reduce buffer size used for RandomAccessInputStreams

---

components/formats-gpl/src/loci/formats/in/KodakReader.java

Fixes the bug reported in https://github.com/openmicroscopy/bioformats/issues/2491.
We don't have any shareable files that exhibit this problem out of the box, but there is an artificial one uploaded to ```curated/bip/samples/``` (see the readme in that folder for provenance).  To test, use that file and confirm that ```showinf -normalize``` without this change results in an exception as reported in the above issue.  With this change, ```showinf -normalize``` should show the image window without an exception.
Corresponding config PR: https://github.com/openmicroscopy/data_repo_config/pull/114

Kodak: handle CCD temperature stored in hexadecimal

---

docs/sphinx/about/index.txt
docs/sphinx/users/fiji/index.txt
docs/sphinx/users/imagej/index.txt
docs/sphinx/users/imagej/installing.txt
docs/sphinx/users/imagej/load-images.txt

Fiji wiki is now redirecting to ImageJ wiki and a bunch of the contact methods have been updated/replaced/discontinued. This fixes up the links, removes things no longer in use and generally updates the docs.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/index.html, https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/users/imagej/index.html and following pages.
If whoever reviews this has time to check the rest of the ImageJ/Fiji pages for any more updates needed, that would be much appreciated - would be good to have them up-to-date for 5.2.0

Update ImageJ/Fiji links & docs

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This is a follow up PR to https://github.com/openmicroscopy/bioformats/pull/2502
In this PR I have made the following changes based on discussions and feedback:
- Deprecated the getMetadataStoreForConversion and getMetadataStoreForDisplay  methods in the OMETiffReader as done in ome/ome-files-cpp@5bc636b
- Dropped the call to getMetadataForConversion in OMETiffReader
- Dropped the call oto getMetadataForDisplay in ImageInfo 
- When using using showinf with the --omexml flag is set then the validation flag will also be set to true (unless the novalid flag is also set in which case it will override)

OME Tiff - Deprecating getMetadataStoreForConversion and Display

---

components/autogen/src/format-pages.txt
components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/NiftiReader.java
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/nifti.txt
docs/sphinx/supported-formats.txt

Supersedes https://github.com/openmicroscopy/bioformats/pull/2493
This PR adds support for gzipped compressed `.nii.gz` filesets by using  `checkSuffix()` which supports compression extensions rather than `String.endsWith()`. The `RandomAccessInputStream` constructor internally uses `Location.getHandle()` which in turns handles compressed files. 
The new extension is also registered in the reader, `readers.txt` and `format-pages.txt` and the documentation pages are regenerated accordingly.
A data repository PR will be opened to add the configuration for the public `nii.gz` samples available at http://nifti.nimh.nih.gov/nifti-1/data.

Add nii.gz support to NiFTi reader

---

components/xsd-fu/python/ome/modeltools/language.py
components/xsd-fu/xsd-fu

This PR adds, during code generation, a comparison of the properties used in MetadataStore, MetadataRetrieve and MetadataConverter.
Any discrepancies between these files will list the properties missing during the output of xsd-fu
To test:
- Run the code generation either directly from xsd-fu or through other means eg msv generate-sources
- Verify that the output lists validation differences (can search for the string MetadataValidation)
- Currently the ShapeType and LightSourceType are the only properties returned

xsd-fu - MetadataConverter validation

---

components/autogen/src/format-pages.txt
docs/sphinx/developers/java-library.txt
docs/sphinx/formats/pict-macintosh-picture.txt
docs/sphinx/formats/quicktime-movie.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/353/warnings3Result/ - Apple have moved their download links under support.apple.com/downloads breaking our links.
In investigating this I discovered the other links we have (in the java-library.txt & pict-mactintosh-picture.txt format page) are referencing Quicktime for Java which seems to have been depreciated in 2009 so I'm not sure how to handle these. @sbesson suggests the reader using it may be essentially legacy anyway, so we could remove the reference from https://www.openmicroscopy.org/site/support/bio-formats5.2/developers/java-library.html altogether, but that still leaves https://www.openmicroscopy.org/site/support/bio-formats5.2/formats/pict-macintosh-picture.html - should this reader become legacy …

Quicktime download links & reader clarifications

---

components/bio-formats-tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/xsd-fu/pom.xml

While working on generating the [list of dependencies](https://trello.com/c/QYoTKrkG/62-review-dependencies) for 5.2.0, I realized the `url` section is not defined for the components licensed with the Simplified (2-clause) BSD license. This commit should add a reference to a proper URL.
To test it, check the `share/server/dependencies.html` page from the OMERO-DEV-merge-build server and verify the licenses of the `ome` components include correct hyperlinks in the license column.

Add reference URLs for the Simplified BSD license in the POMs

---

components/formats-api/src/loci/formats/DelegateReader.java

This is a followup to issues spotted in https://github.com/openmicroscopy/bioformats/pull/2473#issuecomment-237785374 which is as a result of https://github.com/openmicroscopy/bioformats/pull/2473
After investigation this was caused by the delegateReader making 2 calls to setID, once using the super.setId and then another to setId on the legacy or native reader. The first call was initialising a blank OMEXML object in AbstractOMEXMLMetadata as part of the dumpXML command. This meant that any future calls to dumpXML were using the blank root object.
As the first call to super is redundant this can be removed. This will allow the delegateReader to initialise with only a single call to setID. It may also be worth investigating if the dumpXML function is required to set the root object.
This …

DelegateReader - Remove call to super.setId(id);

---

docs/sphinx/developers/code-formatting.txt
docs/sphinx/developers/index.txt

Add initial page for documenting code formatting style.  It's initially minimal, covering basic Java and XML formatting.
https://trello.com/c/8cJWPYOQ/429-document-new-xml-style

docs: Add code formatting page

---

docs/sphinx/developers/ReadPhysicalSize.java
docs/sphinx/developers/export2.txt
docs/sphinx/developers/file-reader.txt

This PR adds a new sample file and brief documentation regarding the reading of physical size dimensions and converting them to display in another quantity unit.
The need for this was raised in a discussion of the ImageJ forums - http://imagej.1557.x6.nabble.com/bioformats-retrieve-calibration-in-JAVA-td5014616.html#a5014627
The new sample file provided is based on the ImageJ example provided here https://gist.github.com/ctrueden/6282856

Docs: New Physical Size Example

---

tools/test-build

While reviewing https://github.com/openmicroscopy/bioformats/pull/2520, I realized that Travis was no longer treating warnings as error as we do in our CI jobs. This commit should restore this behavior.
See https://travis-ci.org/sbesson/bioformats/builds/152396660 for an expected of failure on top of this commit.

Set SPHINXOPTS option to fail on warnings in Travis build

---

docs/sphinx/developers/building-bioformats.txt
docs/sphinx/developers/java-library.txt

This PR adds documentation on using Bio-Formats as a Maven dependancy through Eclipse. Sample code for the pom dependancy as well as the custom repository are provided. The repository can be added in either the pom or the users settings file, so its worth ensuring that the instructions are clear for either purpose.
Some additional things of note:
- Is the repo location correct (http://artifacts.openmicroscopy.org/artifactory/repo) ?
- Should we recommend using the bioformats-package or individual componets?

Docs: Eclipse instructions for using Maven

---

docs/sphinx/developers/index.txt

Temporary fix until we have the navigation sorted and can link to the properly web-hosted docs.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/index.html

Add C++ download link in notebox

---

docs/sphinx/developers/java-library.txt

See https://trello.com/c/BR4c2921/41-keep-up-to-date-concise-list-of-dependencies
Note that code.google.com URLs don't work any more so I've updated the links from the file attached to the card to the redirected URLs (some were auto-redirecting, others just had a holding page with a new link one - I've replaced both)
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/developers/java-library.html

Add BF dependencies table to java-library

---

components/autogen/src/format-pages.txt
docs/sphinx/about/whats-new.txt
docs/sphinx/supported-formats.txt

See https://trello.com/c/hboEAfgG/21-version-history-prs - this should add all the remaining items, bar any currently open docs additions which we may want to add.
Also adds pyramid support to CZI as I noted no docs follow-up had happened from https://github.com/openmicroscopy/bioformats/pull/2481
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html

Finalise 5.2.0 history

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#6](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/6/).
----
--no-rebase

Update POM version numbers to 5.2.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#7](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/7/).
----
--no-rebase

Update POM version numbers to 5.2.1-SNAPSHOT

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
docs/sphinx/users/comlinetools/conversion.txt

See https://trac.openmicroscopy.org/ome/ticket/13273
Testing:
Run `bfconvert test.image [-nolookup] test.ome.tiff`.  Run `showinf` and `tiffinfo` on the result to check that the image remains viewable and has the correct photometric interpretation.  Given a source image with a lookup table, the OME-TIFF output should contain photometric=palette; with `-nolookup` it will contain photometric=minisblack.

ImageConverter: Allow disabling of LUT conversion

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

The addition of MetadataOnly elements for OME-XML containing no BinData or TiffData elements should now be handled via the MetadataTools API. There is no reason to have some special handling in the ImageInfo class which should return the OME-XML using the MetadataRetrieve interface directly.
To review this PR, run 
```
showinf -nopix -omexml /path/to/ome.xml
```
on a valid OME-XML file e.g. one of the OME samples and check the `MetadataOnly` block is no longer populated but `BinData` blocks are available.

Remove unnecessary BinData/MetadataOnly handling in ImageInfo

---

docs/sphinx/users/i3dcore/index.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/380/warnings5Result/ - googling didn't reveal anything that looked like a definitive homepage for this, just a bunch of different GitHub repos, tutorials etc so I've removed the link altogether but if someone wants to suggest a good replacement, I'll be happy to add one back in.

Remove dead java4cpp link

---

components/formats-common/src/loci/common/IniParser.java

This fixes a bug which was [reported on the ImageJ forum](http://forum.imagej.net/t/2443).
The sample non-working file has been uploaded as [QA 17305](http://qa.openmicroscopy.org.uk/qa/feedback/17305/).
-------
Here is a sample TIFF description header produced by a Hamamatsu instrument which previously failed to parse using the `IniParser`:
```
Created by Hamamatsu Inc.
Fri, 19 Aug 2016 15:42:31 Central Daylight Time
[ CALIBRATION ]
title = Default
units = Pixels
symbol = Px
factor = 1.000000
scale_len = 100.000000
[ CAPTURE DEVICE ]
Camera Type = D_CAM
Camera Name = C12345-67CU S/N: 987654
Camera Size = 2048x2048
Bit Depth = 16-Bit
Binning = 1
Capture Region = (X0=300, Y0=900, Width=1600, Height=324)
[ CAPTURE SETTINGS ]
eOffset1 = 100.00
eCoeff1 = 0.49000
Exposure1 = 0.450000 s
[ …
```

Make the INI parser less stringent

---

components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java

What it does
-----------
Fixes the stitching of file patterns in the ImageJ plugin, where the dirname part was being duplicated.
Background
----------
#2352 changed the semantics of `FilePattern.getPrefix` to allow pattern blocks in the whole filename, rather than in the basename alone. Now the first prefix of a file pattern string is whatever comes before the first pattern block, *including* parent directories, if any. This means that the logic in `FilePatternDialog.harvestResults`, which rebuilds the pattern string from prefixes and blocks, has to start from an empty string.
Testing
-------
Place two single-plane images corresponding to different time points (or z sections, or channels: all that matters is that they have the same XY size) in a newly created directory, e.g.:
``` …
```

ImageJ plugin: fix file pattern prefix

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#8](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/8/).
----
--no-rebase

Update POM version numbers to 5.2.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#9](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/9/).
----
--no-rebase

Update POM version numbers to 5.2.2-SNAPSHOT

---

docs/sphinx/developers/examples/ExampleSuite.java
docs/sphinx/pom.xml

See https://trello.com/c/lFM1xUyH/40-sphinx-example-suite-class
Following the migration of all Java examples under `docs/sphinx/developers/examples`, this PR adds a top-level class to run all examples with a single command and uses this class in the top-level `pom.xml`.
To review this PR:
- check Travis is green as the Maven matrix builds will execute this class as part of the test phase of the `docs/sphinx` component
- run `mvn` locally and check `docs/sphinx/target/classes` contains the fake files used for running the example and the OME-TIFF files generated from the conversion/export examples.
A few comments:
- except for `ReadPhysicalSize` which outputs some content, there is no console trace of the example executed. Is it worth adding some logging/`System.out.println` to the main …

Maven examples: add top-level example suite class

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

The usage of JDK 8 on various full repository jobs (Windows, breaking) highlighted some issues with the series 1 of some of the FV1000 filesets. Preliminary testing shows that the ordering of the `previewNames` was not fixed and depends on the parsing of the INI file. See https://trello.com/c/l2oMl30u/37-investigate-jdk-specific-automated-test-failures
This PR should address these ordering issues by:
- parsing the indexes of the preview/reference files from the INI keys into a `Map<Integer, String>` using the same strategy as the parsing of `filenames` and `roiFilenames`
- converting this map into a list of `previewNames`.
As multiple key prefixes where found across our sample files, a new static field `PREVIEWNAMES_PREFIX` is added to the review for future additions and the parsing …

FV1000 reader: fix preview names ordering

---

components/bio-formats-plugins/src/loci/plugins/in/SwapDialog.java

Issue was discovered by user email - http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-August/006129.html
Associated QA-17311
To reproduce:
- Using Fiji import an image with different dimension sizes for each series
- Select the Swap Dimensions
- Select a series with dimensions differing that of the last series
- Verify that the dimensions shown in the Swap Dialog are incorrect
- Verify that an IllegalArgumentException is thrown when attempting to open the image
To test:
- With the PR applied reproduce the steps above
- Verify that the correct dimensions are displayed in the dialog
- Verify that the image opens as expected
- Retest with other series and combinations of series

Dimension Swap Dialog - Incorrect dimension sizes

---

components/formats-common/src/loci/common/DataTools.java
components/formats-common/test/loci/common/utests/DataToolsTest.java

Issue raised in - https://github.com/openmicroscopy/bioformats/issues/2551
As NumberFormat in Java is not thread-safe it is recommended to create a separate format instance for each thread. See Synchronization under https://docs.oracle.com/javase/8/docs/api/java/text/NumberFormat.html  
To achieve this I have wrapped the NumberFormat instance in ThreadLocal to provide a separate instance for each individual thread.
To reproduce:
An example of a failing test can be found here: https://github.com/sbesson/bioformats/commit/8697cf56c575e02532b307e61858995f90b8014d

Use ThreadLocal with NumberFormat

---

cpp/lib/ome/xml/OMETransform.h

A pre-2016-06 OME-TIFF with spurious `MetadataOnly` element (i.e. most of them) would throw an exception on upgrade during transformation.  We retry without validation as done elsewhere; this logs a warning to the terminal:
```
Image: /home/rleigh/images/vessels.ome.tiff
Using reader: OME-TIFF (Open Microscopy Environment TIFF)
Error at file "OME-XML text", line 1, column 60942
Message: element 'MetadataOnly' is not allowed for content model '(Channel*,(BinData+|TiffData+|MetadataOnly),Plane*,AnnotationRef*)'
Error at file "membuf", line 1, column 60959
Message: element 'MetadataOnly' is not allowed for content model '(Channel*,(BinData+|TiffData+|MetadataOnly),Plane*,AnnotationRef*)'
Error at file "OME-XML text (current schema)", line 1199, column 10
Message: element 'MetadataOnly' is …
```

cpp: OMETransform: Handle validation errors during transformation

---

cpp/test/ome-xml/CMakeLists.txt
cpp/test/ome-xml/quantity-electricpotential.cpp
cpp/test/ome-xml/quantity-frequency.cpp
cpp/test/ome-xml/quantity-length.cpp
cpp/test/ome-xml/quantity-power.cpp
cpp/test/ome-xml/quantity-pressure.cpp
cpp/test/ome-xml/quantity-temperature.cpp
cpp/test/ome-xml/quantity-time.cpp
cpp/test/ome-xml/quantity.cpp
cpp/test/ome-xml/quantity.h

The number of templates exceeded the symbol limit on some platforms when built with debug symbols.
Fixes https://trello.com/c/yFMSI6L1/24-re-enable-brill
Testing: Check all builds are green.  Will fix the failing debug build on FreeBSD (though I'm surprised it didn't also break Windows which has a similar limit).

test: quantity: Split into multiple object files

---

components/formats-api/src/loci/formats/ClassList.java
components/formats-api/src/loci/formats/FormatTools.java
components/formats-bsd/src/loci/formats/gui/DataConverter.java
components/formats-gpl/src/loci/formats/services/NetCDFServiceImpl.java
components/formats-gpl/utils/ExtractSDTData.java
components/metakit/src/ome/metakit/Column.java
components/metakit/src/ome/metakit/MetakitReader.java

this is a mechanical change so that a simpler library method can be used. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.
In the event of conflicts I'll remove the problem changes from this PR.

switch to String.indexOf(int) in various classes including Metakit

---

components/formats-bsd/src/loci/formats/ChannelMerger.java
components/formats-bsd/src/loci/formats/ChannelSeparator.java
components/formats-bsd/src/loci/formats/DimensionSwapper.java
components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/src/loci/formats/Memoizer.java
components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-bsd/src/loci/formats/in/DicomReader.java
components/formats-bsd/src/loci/formats/in/EPSReader.java
components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/src/loci/formats/in/FitsReader.java
components/formats-bsd/src/loci/formats/in/ICSReader.java
components/formats-bsd/src/loci/formats/in/JPEG2000Reader.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-bsd/src/loci/formats/in/NRRDReader.java
components/formats-bsd/src/loci/formats/in/TiffReader.java
components/formats-bsd/src/loci/formats/out/OMETiffWriter.java

this is a mechanical change so that a simpler library method can be used. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.
In the event of conflicts I'll remove the problem changes from this PR.

switch to String.indexOf(int) in various BSD formats code

---

components/autogen/src/FormatPageAutogen.java
components/autogen/src/MakeDatasetStructureTable.java
components/autogen/src/format-pages.txt
components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-bsd/src/loci/formats/tools/MakeTestOmeTiff.java
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/ome-tiff.txt
docs/sphinx/formats/tiff.txt
docs/sphinx/supported-formats.txt

To match the available writer extensions, and to match the C++ behaviour.
Testing: It should be possible to save and then read `ome.tf2`, `ome.tf8` or `ome.btf` files.  Likewise without the `ome.` part for plain big TIFFs.

Enable support for BigTIFF reader file extensions

---

components/formats-common/src/loci/common/IniParser.java
components/formats-common/test/loci/common/utests/IniParserTest.java

See https://trello.com/c/RsYkLAFK/18-tests-add-ini-parser-unit-tests
Following https://github.com/openmicroscopy/bioformats/pull/2537, this PR adds a new unit test class covering the various forms of INI files currently handled by the `loci.common.IniParser` class. It also fixes the warnings in `IniParser` reported by `mvn findbugs:check` by refactoring the header parsing logic.
To test this PR, check Travis is green and/or run the Maven tests on `formats-common` locally and review whether all use cases of the implementation in `IniParser.parseINI(BufferedReader)` are unit tested.

IniParser unit tests

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/ome-tiff.txt
docs/sphinx/formats/ome-xml.txt
docs/sphinx/supported-formats.txt

Noticed while reviewing https://github.com/openmicroscopy/bioformats/pull/2565, the OME-TIFF and OME-XML pages do not include the 2016-06 schema version. This PR adds the version to the `format-pages.txt` and regenerates the format pages using the `autogen` targets.

OME formats pages: add 2016-06 version

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#10](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/10/).
----
--no-rebase

Update POM version numbers to 5.2.2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#11](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/11/).
----
--no-rebase

Update POM version numbers to 5.2.3-SNAPSHOT

---

components/formats-common/src/loci/common/DataTools.java
components/formats-common/src/loci/common/IniParser.java
components/formats-common/src/loci/common/ReflectedUniverse.java
components/formats-gpl/src/loci/formats/in/BaseZeissReader.java
components/formats-gpl/src/loci/formats/in/BioRadGelReader.java
components/formats-gpl/src/loci/formats/in/BioRadReader.java
components/formats-gpl/src/loci/formats/in/BioRadSCNReader.java
components/formats-gpl/src/loci/formats/in/GatanDM2Reader.java
components/formats-gpl/src/loci/formats/in/GatanReader.java
components/formats-gpl/src/loci/formats/in/ImarisHDFReader.java
components/formats-gpl/src/loci/formats/in/ImarisTiffReader.java
components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaHandler.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java
components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java
components/formats-gpl/src/loci/formats/in/ND2Handler.java
components/formats-gpl/src/loci/formats/in/NDPIReader.java
components/formats-gpl/src/loci/formats/in/NDPISReader.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/src/loci/formats/in/NikonElementsTiffReader.java
components/formats-gpl/src/loci/formats/in/NikonTiffReader.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java
components/formats-gpl/src/loci/formats/in/ZeissTIFFHandler.java
components/formats-gpl/src/loci/formats/in/ZeissZVIReader.java

this is a mechanical change so that a simpler library method can be used in our GPL reader code. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.
This PR also adjusts a couple of common utility classes in the same way.

switch to String.indexOf(int) in various GPL-licensed readers (part one)

---

components/formats-gpl/src/loci/formats/in/BDReader.java
components/formats-gpl/src/loci/formats/in/BrukerReader.java
components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/formats-gpl/src/loci/formats/in/FlexReader.java
components/formats-gpl/src/loci/formats/in/FluoviewReader.java
components/formats-gpl/src/loci/formats/in/INRReader.java
components/formats-gpl/src/loci/formats/in/IPWReader.java
components/formats-gpl/src/loci/formats/in/ImaconReader.java
components/formats-gpl/src/loci/formats/in/ImprovisionTiffReader.java
components/formats-gpl/src/loci/formats/in/InveonReader.java
components/formats-gpl/src/loci/formats/in/IvisionReader.java
components/formats-gpl/src/loci/formats/in/OxfordInstrumentsReader.java
components/formats-gpl/src/loci/formats/in/SBIGReader.java
components/formats-gpl/src/loci/formats/in/SDTInfo.java
components/formats-gpl/src/loci/formats/in/SEQReader.java
components/formats-gpl/src/loci/formats/in/SPCReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java
components/formats-gpl/src/loci/formats/in/ScreenReader.java
components/formats-gpl/src/loci/formats/in/SimplePCITiffReader.java
components/formats-gpl/src/loci/formats/in/SlidebookTiffReader.java

this is a mechanical change so that a simpler library method can be used in our GPL reader code. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.

switch to String.indexOf(int) in various GPL-licensed readers (part two)

---

components/formats-gpl/src/loci/formats/in/AFIReader.java
components/formats-gpl/src/loci/formats/in/CellWorxReader.java
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/HISReader.java
components/formats-gpl/src/loci/formats/in/HRDGDFReader.java
components/formats-gpl/src/loci/formats/in/HitachiReader.java
components/formats-gpl/src/loci/formats/in/KodakReader.java
components/formats-gpl/src/loci/formats/in/L2DReader.java
components/formats-gpl/src/loci/formats/in/LiFlimReader.java
components/formats-gpl/src/loci/formats/in/MIASReader.java
components/formats-gpl/src/loci/formats/in/MolecularImagingReader.java
components/formats-gpl/src/loci/formats/in/PCIReader.java
components/formats-gpl/src/loci/formats/in/PCORAWReader.java
components/formats-gpl/src/loci/formats/in/PDSReader.java
components/formats-gpl/src/loci/formats/in/PerkinElmerReader.java
components/formats-gpl/src/loci/formats/in/PrairieMetadata.java
components/formats-gpl/src/loci/formats/in/PrairieReader.java
components/formats-gpl/src/loci/formats/in/TCSReader.java
components/formats-gpl/src/loci/formats/in/TillVisionReader.java
components/formats-gpl/src/loci/formats/in/TrestleReader.java
components/formats-gpl/src/loci/formats/in/UnisokuReader.java
components/formats-gpl/src/loci/formats/in/VarianFDFReader.java
components/formats-gpl/src/loci/formats/in/VisitechReader.java

this is a mechanical change so that a simpler library method can be used in our GPL reader code. It may not make much difference but sets a good example for others writing further code based on our existing code. https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.

switch to String.indexOf(int) in various GPL-licensed readers (part three)

---

components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterMetadata.java
components/formats-bsd/src/loci/formats/in/ICSReader.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-gpl/src/loci/formats/in/BaseZeissReader.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java
components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/formats-gpl/src/loci/formats/in/FluoviewReader.java
components/formats-gpl/src/loci/formats/in/ImprovisionTiffReader.java
components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/MIASReader.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/src/loci/formats/in/SEQReader.java
components/formats-gpl/src/loci/formats/in/TCSReader.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

@rleigh-codelibre [spotted](https://github.com/openmicroscopy/bioformats/pull/2572#r78906989) that it might be better to extend strings with characters instead of strings where possible: this PR effects that, hoping to set a good example. https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-full-repository/ suffices for testing.

append characters instead of strings

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

**Reference:** 
https://trac.openmicroscopy.org/ome/ticket/13239
http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-May/006030.html
**Testing Instructions:** 
Open the following Image from QA17192 in ImageJ/Fiji,
Conv 2 3 colors.czi
and 
1) check if the image opens. (without this PR, you should get an exception: as shown in the ticket)
and
2) check if there are 9 channels.
and,
1) Split the image into three stacks (3 channels each),
2) And view the images in composite mode: [Image-->Color-->make Composite]
this will allow you to see the 3 channels as 3RGB images individually and these can be compared with Zen Lite.
@melissalinkert

ZeissCZIReader : Fix imageCount for RGB images

---

components/specification/released-schema/2016-06/ome.xsd
components/specification/transforms/2016-06-to-2015-01.xsl
components/xsd-fu/cfg/enum_handler.cfg

Increments OME-XML schema version attribute value and adds acquisition modes,
* BrightField
* SweptFieldConfocal
* SPIM
and parsing for,
* Laser Scan Confocal
* Swept Field Confocal
The schema namespace is left unchanged.

add enumeration values for acquisition mode

---

components/formats-bsd/src/loci/formats/out/ICSWriter.java

This issue was raised via the Image J forum - http://forum.imagej.net/t/release-of-bio-formats-5-2-0/2523/9
When exporting to ics format the ordering of the image dimensions was incorrect with images from different channels being displayed in the wrong position.
This issue started occuring after other fixes to the ICSWriter in this PR: https://github.com/openmicroscopy/bioformats/pull/2315
The original issue that the PR was solving was: https://github.com/openmicroscopy/bioformats/issues/2237
Note there is an additional issue which can lock up the exporter, this is still open and is not aimed to be fixed yet - https://github.com/openmicroscopy/bioformats/issues/2238
**To reproduce:**
- Import a suitable multi dimensioned image using Bio-Formats
- Export the image to the ICS format
- Open …

ICS Writer - incorrect planes

---

components/formats-gpl/src/loci/formats/in/ImprovisionTiffReader.java
components/formats-gpl/src/loci/formats/in/ND2Handler.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/test/loci/formats/utests/ND2HandlerTest.java

See https://trello.com/c/b4oDFIo4/21-remove-instances-of-deprecated-sanitizedouble
This PR completes the deprecation of the `DataTools.sanitizeDouble()` in https://github.com/openmicroscopy/bioformats/pull/2285 and updates the few places across the code still relying on the deprecated API to use `DataTools.parse*` instead.
This PR should have no functional effect mostly cleanup. To test it:
- check the build does not warn about these deprecated classes anymore
- check the automated tests are still passing with this PR included
- optionally open a couple of files from the two affected formats and check the metadata is unchanged without and with this PR e.g. by comparing the ouput of `showinf -omexml-only` 
Open questions:
- how to handle ND2 metadata where the value is -1?

DataTools: remove internal usages of deprecated API

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

See  http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-September/006183.html and https://trac.openmicroscopy.org/ome/ticket/13261
For large dimensions (over 32767), using readShort() wraps the value to a negative. This commit explores using readUnsignedShort() instead to retrieve the  time dimension while remaining in agreement with the DV specification.

Deltavision: use readUnsignedShort() to read time dimensions

---

components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java
components/test-suite/src/loci/tests/testng/TestTools.java

This PR addresses a problem I've encountered while building a test case based on a plate from `idr0009-simpson-secretion`. The dataset is structured as follows:
```
AcquisitionLog.dat
data/
.DS_Store
experiment_descriptor.dat
experiment_descriptor.xml
```
Where `data` contains the individual TIFF files. The configuration file generated with `gen-config` looked fine:
```
[experiment_descriptor.xml global]
...
[experiment_descriptor.xml series_0]
[experiment_descriptor.xml series_1]
...
```
However, the test failed, complaining about `AcquisitionLog.dat` not being configured. Here is a breakdown of what happens:
* To build the list of files to be tested, `FormatReaderTestFactory` walks the entire tree and builds an initial list with everything in it (almost everything, as .DS_Store is …

FormatReaderTestFactory: list files as returned by getCurrentFile

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-bsd/test/loci/formats/utests/tiff/BaseTiffReaderMock.java
components/formats-bsd/test/loci/formats/utests/tiff/BaseTiffReaderTest.java

Issue was discovered while testing QA-17365 as part of https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8124&p=17519#p17519
An object of type String [] is read for the creation date of the file, but the array itself is empty leading to an index out of bounds exception.
To test:
- All unit tests and data repo tests must remain green
- Read image from QA-17365 using Bio-Formats and verify that an array out of bounds exception is thrown
- Apply the PR
- Reopen the file and verify that no exception is thrown

BaseTiffReader - Index out of bounds exception 

---

docs/sphinx/about/whats-new.txt

See https://trello.com/c/8jQ8JPgo/21-version-history-prs
Will be staged at https://www.openmicroscopy.org/site/support/bio-formats5.2-staging/about/whats-new.html when built

Add 5.2.3 version history to docs

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#12](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/12/).
----
--no-rebase

Update POM version numbers to 5.2.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#13](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/13/).
----
--no-rebase

Update POM version numbers to 5.2.4-SNAPSHOT

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

This PR initiates the `dev_5_3` development branch initially dedicated to the architecture of the Bio-Formats components.

Update POM version numbers to 5.3.0-SNAPSHOT

---

.travis.yml
ant/toplevel.xml
tools/test-build

See https://trello.com/c/noU6gku8/14-review-docs-strategy
With this PR, the top-level `docs-sphinx` target used by the release jobs amongst others should no longer produce a PDF but still a zip containing the HTML sources /cc @hflynn 
While reviewing this we might want to make sure that the names of the Javadocs vs Sphinx docs zips are sensible/consistent as we will expose them in the downloads pages.

Ant: remove the pdf generation from the top-level documentation target

---

ant/toplevel.xml
components/bundles/bioformats_package/build.xml

See https://github.com/openmicroscopy/bioformats/pull/2609 where this was suggested. Once built, the javadoc zip should now be bio-formats-javadocs-VERSION.zip (likely 5.2.3-DEV).
I also tidied up a couple of pdf references not removed in the linked PR above.

Add version number to Javadoc zip

---

components/formats-bsd/src/loci/formats/in/FilePatternReader.java

The combination of Memoizer, FilePatternReader, and MetamorphReader
caused stk files to be leaked. Specifically, the call to helper.setId
in FilePatternReader.reopenFile initialized a MinimalTiffReader whose
`in` field was never cleaned up. Any call to setId should first check that
the helper is closed.
See: https://trello.com/c/rH1TEEZW/18-file-leak

FilePatternReader: close helper proactively

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See
https://trello.com/c/aTV56qEX/6-fix-ome-tiff-regression-plane-population
To test, check the output of ```showinf -nopix -omexml``` with the files from QA 17375 and 16996 and verify that the ```The*``` values on the ```Plane```s are correct and that there are no relevant validation errors.  For QA 16996, ```TheZ``` and ```TheT``` were set in the file, but ```TheC``` was missing.  For QA 17375, all three values are set, but the order does not necessarily match ```DimensionOrder``` and some planes do not have a ```Plane``` element at all.

OME-TIFF: fix Plane population to preserve existing The* values

---

ant/global.properties
components/forks/poi/pom.xml
components/metakit/pom.xml
components/ome-xml/pom.xml
docs/sphinx/build.xml
docs/sphinx/conf.py.in
docs/sphinx/developers/components.txt
docs/sphinx/developers/service.txt
docs/sphinx/users/fiji/index.txt
pom.xml

- Switch to using maven central or ome-common in place of the old formats-common.
- Update the documentation to use ome-common and replace links which are no longer valid in the source tree; handle the differences between the split repos when building the documentation
Testing: Check that the ant and maven builds continue to work.  Check the documentation links.
Will the javadoc links need fixing up to use a different location for the ome-common documentation; it's currently using the -latest doc links, but they might disappear after merging?
/cc @sbesson

Use ome-common 5.3.0 release from maven central

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/pcx-pc-paintbrush.txt
docs/sphinx/formats/zeiss-axiovision-tiff.txt
docs/sphinx/formats/zeiss-axiovision-zvi.txt
docs/sphinx/formats/zeiss-czi.txt
docs/sphinx/formats/zeiss-lsm.txt

These ZEISS links were making the build unstable (see https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/440/warnings3Result/) and although the new build is green, they are still redirecting so this PR updates them.

Update redirecting ZEISS links

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#14](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/14/).
----
--no-rebase

Update POM version numbers to 5.2.4

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#15](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/15/).
----
--no-rebase

Update POM version numbers to 5.2.5-SNAPSHOT

---

.travis.yml
tools/test-build

The `findbugs:findbugs` Maven phase was added to the Travis test script as a way to flag errors. However this is generated a report while the command to fail the build is `findbugs:check`. The latter generates many warnings across components which cannot be fixed in the main Bio-Formats source code without significant work. Instead these should be fixed and activated in each decoupled component.
This commit removes `findbugs:findbugs:` from the Travis test and simplifies the YML file to clarify the fact we are testing a 2x2 matrix (Ant/Maven with JDK 7/8).
To test this PR, check Travis is green and the time of  `oraclejdk8/maven` component is reduced to match roughly the time of the `openjdk8/maven` component.

Remove findbugs from Travis and simplify the yml configuration file

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-axio-csm.txt
docs/sphinx/formats/zeiss-axiovision-tiff.txt
docs/sphinx/formats/zeiss-axiovision-zvi.txt
docs/sphinx/formats/zeiss-czi.txt
docs/sphinx/formats/zeiss-lsm.txt
docs/sphinx/supported-formats.txt

Fixes up the ZEISS links which may be redirected but are still upsetting the build -https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/443/warnings3Result/
(I also fixed up the CZI links while I was at it, given that was redirecting too, and linking to the CZI specific page twice was inconsistent with the other pages where the ZEISS developer link goes just to the homepage)
Should make the merge build green again.

Fix other ZEISS links
