components/formats-gpl/pom.xml

This PR is a follow up to https://github.com/openmicroscopy/bioformats/pull/2624
The ome-poi version has been changed to 5.3.0 from 5.3.0-SNAPSHOT.
The repository previously used for the snapshot has been removed in favour of Maven central.
To test: Verify that builds remain green

Update ome-poi to 5.3.0

---

components/formats-gpl/build.xml

This PR is a follow up to https://github.com/openmicroscopy/bioformats/pull/2624
This test was incorrectly removed in https://github.com/openmicroscopy/bioformats/pull/2624/commits/1e7a361d0705686f6ffaff588621eee324deebb7
The test-no-poi target has been restored.
To test:
- Verify that the builds and tests remain green
- Use ant test locally to verify that the test-no-poi runs successfully

Restore no-poi ant test

---

ant/global.properties
ant/global.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/test-suite/pom.xml
docs/sphinx/build.xml
docs/sphinx/conf.py.in
docs/sphinx/developers/matlab-dev.txt
pom.xml

Also fix up doc links to use versioned ome-xml javadocs, as for ome-common.
Testing: Check and and maven builds continue to work and that jobs remain green.  Check matlab links for MetadataStore/Retrieve.

All component versions are defined in root pom

---

components/formats-gpl/pom.xml
pom.xml

Bumps the version of ome-mdbtools from 5.3.0-SNAPSHOT to 5.3.0
- Removes the test repo as jar is now located on maven central
- Uses the new versioning as introduced in https://github.com/openmicroscopy/bioformats/pull/2637

Bump ome-mdbtools version to 5.3.0

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-axiovision-zvi.txt

Fixes https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/454/warnings3Result/
Download link is now at the bottom of the product page because you have to give your personal details to get the free version.
Should make the build green again. 
Staged at http://www.openmicroscopy.org/site/support/bio-formats5.3-staging/formats/zeiss-axiovision-zvi.html

Fix Axiovision download link

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#17](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/17/).
----
--no-rebase

Update POM version numbers to 5.3.0-m1

---

ant/java.xml

See https://trello.com/c/MeIS9tyf/21-test-jobs-rearchitecture. The migration of the Ant build system to use `Maven Ant Tasks` in https://github.com/openmicroscopy/bioformats/pull/2622 greatly improved the build system and dependency management.
Prior to 5.3.0-m1, the Ant build was fully contained within the source code directory using embedded dependencies and generating all artifacts under `artifacts`. With the change above, the build logic now uses the Maven repository both for the project dependencies but also the individual components.
One downside of this approach has been reported in the CI environment where builds were previously implicitly relying on the build containment and are now failing due to race conditions and/or overwriting SNAPSHOT artifacts which could be used by other …

Improve Ant jar and bundle target to honor maven.repo.local variable

---

docs/sphinx/developers/building-bioformats.txt
docs/sphinx/developers/components.txt
docs/sphinx/developers/overview.txt

See https://trello.com/c/phPRO185/34-developer-documentation-updates
As well as reviewing the staging pages https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/developers/overview.html etc, the tester needs to check that the decoupling of ome-xml means there are no post-import errors when importing the BF source into Eclipse - import 5.3.0-m1 to test.

update developer docs

---

components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java

This PR has the same purpose as #2596, but it restores the original string representation of each path after removing redundancies. This prevents problems on tests that rely on symlinks (such as `test_images_good`).

Test suite: use canonical paths to remove duplicates

---

components/test-suite/src/loci/tests/testng/ConfigurationTree.java
components/test-suite/src/loci/tests/testng/TestTools.java

Reverts #1912.
Discussed with @sbesson: these changes were needed to support the peculiar link structure in `test_images_good` and should not be needed anymore now that we're moving to a "proper" subset. On one hand, this revert simplifies the code; on the other hand, I've found out that the path relocation feature added in #1912 was generating wrong paths with the new subset layout.

Revert changes to handle symlinks with external configuration

---

components/formats-gpl/test/loci/formats/utests/ND2HandlerTest.java

I discovered while testing https://github.com/openmicroscopy/bioformats/pull/2647 that when importing a fresh copy of Bio-Formats into Eclipse that I would see an error due to ND2HandlerTest having a mismatch between its package and location. I have updated the package to match the file location.
To reproduce:
- In Eclipse, do File -> Import -> Existing Maven projects and import Bio-Formats without the PR, verify that an error is shown
To test:
- With the PR, reimport the project as before and verify that no error is present

ND2HandlerTest - Update package to match location

---

components/formats-gpl/build.xml
components/test-suite/build.xml
components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java
components/test-suite/src/loci/tests/testng/MetadataConfigurableTest.java
components/test-suite/src/loci/tests/testng/TestTools.java

The `test-metadata` target in `components/formats-gpl/build.xml` was broken due to an obsolete TestNG option (`sourcedir`). This PR fixes the target and moves it (along with the test it refers to) to `test-suite`, since it's actually not a unit test and it's not formats-gpl-specific. Rather, it tests metadata levels on a single user-specified file:
```
ant -f components/test-suite/build.xml test-metadata -Dtestng.filename=/path/to/image.ext
```

Fix test-metadata and move it to test-suite

---

.classpath-template
.gitignore
docs/sphinx/developers/useful-scripts.txt
setup.cfg
tools/test-build

Following the 5.3.0-m1 decoupling, this cleans up a couple of additional files in the top-level:
- setup.cfg is removed as all Python components have been migrated away
- the `test-build` script is reviewed to remove the obsolete `cpp` and `flake8` targets as well as the documentation
- the `.classpath-template` and `.gitignore` files are reviewed to removed decoupled/obsolete components and folders which should be ignored by the top-level `target`, `test-output`.... folders generated by the build system

Test build cleanup

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/volocity-library-clipping.txt
docs/sphinx/formats/volocity.txt

See https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/478/warnings3Result/ - PerkinElmer seem to be in the process of re-organizing their website, this is the replacement equivalent link. Should make the build green again.

Update volocity links

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/developers/artifactory/pom.xml
docs/sphinx/pom.xml
pom.xml

This PR reviews the `repositories` and `pluginRepositories` section defined in the POMs of the various components of Bio-Formats and performs the following changes:
- defines the default set of repositories to look up for dependencies in Maven Central first and the OME Maven repository next (the distinction between individual repository is only used for `distributionManagement` and deploying)
- defines the default set of plugin repositories to look up in Maven Central repository
- cleans up all redundant redefinitions of `repositories` across components including the Sphinx developers example
- overrides `repositories` in the `formats-gpl` POM to include Unidata releases repositories
On top of reducing the POM complexity, this change should further reduce the number of requests to OME …

POM repositories cleanup

---

components/test-suite/build.xml
components/test-suite/logback-target-test-runner.xml
components/test-suite/target-test-runner

Addresses https://trello.com/c/jGrPs6c9/16-fix-integration-tests
Following the build changes in https://github.com/openmicroscopy/bioformats/pull/2622, the `test-file-handles` and `test-openbytes-performance` targets of the `test-suite` component ended up broken. Historically these targets were relying on the `target-test-runner` Python script to generate a TestNG XML file from a test class, a series of target files and run the tests. With the removal of the JARs from the source code, reconstructing the CLASSPATH necessary to run the tests cannot be simply achieved in `target-test-runner`.
Instead this PR reduces the `target-test-runnner` scope to only generating the TestNG file and uses the Ant `testng` target to run the tests using the generated XML file. The single-threaded nature of …

Fix test-suite targets to use TestNG

---

components/bio-formats-plugins/src/loci/plugins/in/ThumbLoader.java
components/formats-api/src/loci/formats/FormatTools.java
components/formats-bsd/src/loci/formats/ChannelSeparator.java
components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/codec/JPEGXRCodec.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/formats-gpl/src/loci/formats/services/JPEGXRService.java
components/formats-gpl/src/loci/formats/services/JPEGXRServiceImpl.java
pom.xml

Requires https://github.com/ome/ome-common-java/pull/8
This is a port of work done on private 5.1-based branches to support JPEG-XR-compressed .czi data.  There are also a few changes in the ImageJ plugin to fix obvious problems with reading and displaying RGB thumbnails.  JPEG-XR decoding is provided by an additional dependency on:
https://github.com/glencoesoftware/jxrlib
Relevant data for testing is listed in https://trello.com/c/OHKk0BiI/41-jpeg-xr.  A configuration PR for the public datasets on that card is forthcoming; the private datasets can be reviewed and tested as a follow-up to this PR.  All of the test files contain larger pyramids, so testing in ImageJ/showinf is a little tricky.  The last 2 series in each file are label/macro images which should open easily.  Remaining …

Add JPEG-XR support for CZI data

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Similar to https://github.com/openmicroscopy/bioformats/pull/2667 except the version numbers bump was achieved with
```
mvn versions:set -DnewVersion=5.3.0-m2 -DgenerateBackupPoms=false
```
and updating `release.version` and `STABLE_VERSION` manually.

Bump version numbers to 5.3.0-m2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Following the m2 milestone this PR should restore the version numbers to 5.3.0-SNAPSHOT

Bump version numbers to 5.3.0-SNAPSHOT

---

tools/bump_maven_version.py

See https://trello.com/c/3R8rGfYV/54-fix-version-bump-script
The introduction of `jxrlib` in 5.3.0-m2 broke the script used to bump versions - see https://github.com/openmicroscopy/bioformats/pull/2667 
This PR reduces the scope of the script by restricting the version bump to the `pom-bio-formats` artifact. This modified has been used to produce #2668 and #2671 but should be retested independently using e.g.
```
./tools/bump_maven_version.py 5.4.0
./tools/bump_maven_version.py 5.4.0-SNAPSHOT
```
It should also  work with the option allowing to switch the `groupId` /cc @joshmoore

Increase specificity of the artifactId version replacement

---

components/bio-formats-plugins/pom.xml
components/bundles/bioformats_package/assembly.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/assembly.xml
components/bundles/loci_tools/pom.xml

See https://trello.com/c/i1XLwx3M/29-review-bundles
This adds version information to the manifest of Maven-built bundles and excludes ImageJ (```net.imagej:ij```) from bundles built with both Maven and Ant.
To test, build ```bioformats_package.jar``` and ```loci_tools.jar``` with both Ant (```ant clean jars tools```) and Maven (```mvn clean package install```).  Check the ```META-INF/MANIFEST.MF``` in all jars, and verify that all have matching information, including version number, git commit, and build date.  Also check that ImageJ is no longer included in any of the jars - each should be ~15MB smaller.

Bundle cleanup

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/gatan-digital-micrograph.txt

See https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-latest-docs/261/warnings3Result/ - looks like they are updating their website but this will hopefully remain a valid link since their EMAN wiki home link in the top left goes to this URL.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/formats/gatan-digital-micrograph.html

Update EMAN link

---

components/formats-bsd/test/loci/formats/utests/MemoizerTest.java

Addresses several issues with `MemoizerTest`, mostly unused / redundant / duplicate code and the fact that temporary files were not being removed.
Since this PR contains whitespace changes, and to ensure no critical check has been inadvertently removed, it's best to review it one commit at a time, in order.
Functional checks include verifying that all tests pass and do not leave temporary files and directories around.
Some commit-specific additional notes:
* b975b61b3d57677f4ae1aca0b122d9ce5f446a90: `testng.Assert{JUnit,}` have opposite conventions on tested vs expected argument ordering. Existing tests were using the `testng.Assert` convention.
* 332f17bc5386865b769ef385ea8147c014907f82: uses `File.setWritable`'s return value to simplify the check and to take into account failures due to …

MemoizerTest refactor

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/build.xml
docs/sphinx/conf.py.in
pom.xml

Simplify the specification of these component versions.  Since they are coupled, use a single `ome-model.version` property for both.

build: Unify specification and ome-xml versions

---

components/formats-api/src/loci/formats/FormatWriter.java
components/formats-api/src/loci/formats/IFormatWriter.java
components/formats-api/src/loci/formats/ImageWriter.java
components/formats-api/src/loci/formats/WriterWrapper.java
components/formats-bsd/build.xml
components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml
components/formats-bsd/test/loci/formats/utests/tiff/ByteArrayHandleMock.java
components/formats-bsd/test/loci/formats/utests/tiff/TiffWriterMock.java

Adds the following new API functions:
public int getTileSizeX()
public int getTileSizeY()
int setTileSizeX(int tileSize) throws FormatException
int setTileSizeY(int tileSize) throws FormatException 
The base implemenattion of these functions will default to full image height and width and return these values when you try to set to any other tiling size.
Any writer that uses the TiffWriter will have its own implementation which will allow any multiple of 16 to be used as a tile size. If a non multiple of 16 is provided then the tileSize will round to the nearest 16 and return this value to the caller.
For the TiffWriter, if a tile size has been set when saveBytes is called then the provided byte array will be written out in tiles of this size.
For testing the following combinations of Tiff …

Tiling API and Tiff Writer implementation

---

components/formats-bsd/build.xml
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

Follow up of https://github.com/openmicroscopy/bioformats/pull/2663
This PR primarily addresses the issue flagged by https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest/350/ i.e. the addition of the `testng` parameter in #2663 failed the default `ant test` command.
The first commits improve the robustness of the percentage detection by:
- isolating the property parsing to a method run before the test class
- handling the case where the property value is equal to `${<key>}`
- handling the cases where non-numeric values are passed to the property
- bounding the percentage between 0 and 100
Additionally the last commit addresses https://github.com/openmicroscopy/bioformats/pull/2663#discussion_r90668700 by using range-based loops for readability.
To test this PR, in addition to the CI …

Tiled writing tests improvements

---

components/formats-bsd/src/loci/formats/in/OMEXMLReader.java

The reader made the assumption that `BinData` was only found inside `Pixels`.  However, it's also contained within `Mask`, and the reader was stripping out all `BinData` content when initially reading the OME-XML (it pre-processes it with a custom SAX parser before creating the `MetadataStore`).  This change makes the stripping selective, so it only occurs for `BinData` elements contained within Pixels.
This is related to https://github.com/ome/ome-model/pull/14 but is not coupled to it (it's useful for testing #14 with the sample in https://github.com/ome/ome-model/pull/13), but can be merged independently.  If you test these without this PR, you'll see that the ROI sample gets the `BinData` stripped out of the `Mask` ROI, and with this PR, it's correctly retained.
Testing: Check builds …

OMEXMLReader: Handle BinData in non-Pixels elements such as Mask

---

components/formats-gpl/octave/PKG_ADD
docs/sphinx/users/octave/index.txt

This function has been deprecated in Octave. Replacing by the recommended alternative which works since Octave 3.8 and is not a problem for the bioformats package which already requires Octave 4.0.0.

octave: use usejava() instead of deprecated octave_config_info()

---

components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java

In the "remove duplicates" phase, `FormatReaderTestFactory` ignores `setId` failures, effectively preventing files that would fail the test right at `setId` from being tested at all.
With this PR:
1. If `setId` fails in the remove duplicate phase, the method breaks immediately (we have to catch, print error and rethrow because testng swallows exceptions thrown by factory methods)
2. If anything else goes wrong in the remove duplicate phase the file is kept in the list, so that it gets tested later

Test suite: don't exclude files that cause setId failures

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#20](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/20/).
----
--no-rebase

Update POM version numbers to 5.3.0-m3

---

components/formats-api/src/loci/formats/ImageReader.java
components/formats-bsd/test/loci/formats/utests/ImageReaderTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

This is a porting of https://github.com/openmicroscopy/bioformats/pull/2013/commits/f0d58c2cd9b8db921aa5886916e3f7ec8a42aa0e to the current state. Without this, a call to `reader.getMetadataOptions().set*` on an `ImageReader` instance won't be reflected in the actual reader (unless it's the first one in the list).
More specifically, **without** this PR, `testOptionsImplicit` is expected to fail, while `testOptionsExplicit` should pass because `ImageReader.setMetadataOptions` already assigns the provided instance to all readers. I've added the test anyway to prevent regressions on this front. **With** this PR, both tests should pass.
Note that I couldn't place the unit test under `formats-api` because it wouldn't work there (no concrete readers). Although this may look weird, we currently …

ImageReader: ensure options reflect those of the actual reader

---

pom.xml

See https://trello.com/c/pUrwD3HA/55-jxrlib-0-2-1-os-x-10-10-and-later for related reading 
As per https://blog.travis-ci.com/2016-11-17-retiring-some-osx-images/, a new
patch release of jxrlib was cut with a reduced but maintainable OSX version
support matrix. This commit update the jxrlib dependency shipped with
Bio-Formats accordingly.
This bump should have no functional impact. All CI jobs should remain green. With regard to testing support, JPEG-XR compressed CZI file should open under both OSX 10.10 or more recent versions.

Bump jxrlib to version 0.2.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#22](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/22/).
----
--no-rebase

Update POM version numbers to 5.3.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#23](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/23/).
----
--no-rebase

Update POM version numbers to 5.3.1-SNAPSHOT

---

components/formats-bsd/build.xml
components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

This is a bug fix for an issue reported in https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8179&p=17776#p17776
The lastIFD was being written incorrectly due to https://github.com/openmicroscopy/bioformats/pull/2663/commits/4d48e1144da4c1035ff3a79ddcd556bd2c46582d which was part of https://github.com/openmicroscopy/bioformats/pull/2663
With this PR all non tiled behaviour should be identical as to prior to 5.3.0
This PR also introduces a new unit test to help ensure that such an issue will be caught in future:
- The new saveBytes test is largely similar to the tiled writing unit tests which had been added previously
- A new system prop has been added to enable the test in the same way as for the tiling test
- The tiling and saveBytes tests have both then refactored to reduce …

TiffWriter - fix for incorrect last IFD and new unit test

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#24](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/24/).
----
--no-rebase

Update POM version numbers to 5.3.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#25](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/25/).
----
--no-rebase

Update POM version numbers to 5.3.2-SNAPSHOT

---

components/autogen/src/MakeDatasetStructureTable.java
components/autogen/src/doc/FormatTable.vm
components/autogen/src/doc/meta-summary.vm
docs/sphinx/developers/conversion.txt
docs/sphinx/developers/export2.txt
docs/sphinx/developers/file-reader.txt
docs/sphinx/developers/generating-test-images.txt
docs/sphinx/developers/java-library.txt
docs/sphinx/formats/dataset-table.txt
docs/sphinx/formats/index.txt
docs/sphinx/index.txt
docs/sphinx/metadata-summary.txt
docs/sphinx/supported-formats.txt
docs/sphinx/users/index.txt

See https://trello.com/c/SnUesylG/505-ditching-docs-pdfs this cleans up the now unused latex directions for tables.
@rleigh-codelibre not sure if there is also more build clean up that could happen in this repo too

Remove tabularcolumns from docs

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Hello,
this is a 're-open' of #1232, which I couldn't reopen after pushing the patch rebased to current develop.
It's been two years since I proposed this; and I still think that it's very useful for people working with ND2 files, especially for large files (hundreds of GB) over network (eg. 100 Mbit), the current state is … suboptimal.
Given the great speed advantage possible with this, I think it's definitely worthwhile to debug any remaining problems (@melissalinkert mentioned wrong C/Z/T demensions for certain non-public files).
Maybe with a heuristical approach the chunk map code could just be used when it's known to deliver the right results. (If no 'complete' bugfix can be found.) (However, given my knowledge of ND2 files I'm unaware of any scenarios where wrong dimensions should …

Use chunkmap for Nikon ND2 files to speed up processing

---

components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/test/loci/formats/utests/FileStitcherTest.java

In most cases, there is no need to do anything to propagate options in reader wrappers. This is due to the fact that they do not have their own options instance, but rather refer to that of their wrapped reader.
`FileStitcher` is an exception though, since it uses several external readers to do its job, while the "standard" `ReaderWrapper` contract assumes there is only one wrapped reader, whose behaviour will be somehow modified by the wrapper. In practice, `FileStitcher` has two main states:
1. **before calling setId** the file pattern hasn't been seen yet, so `FileStitcher` does not have enough info to even decide *how many* subreaders it needs. Options consistency is guaranteed in this state, but the only subreader is a placeholder;
2. **after calling setId** concrete subreaders are …

Options propagation: FileStitcher

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/zeiss-axiovision-tiff.txt
docs/sphinx/supported-formats.txt

Use the correct `.tif` file extension to match the reader and all existing samples.

autogen: Update Zeiss TIFF file extensions

---

components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

Backported from private @glencoesoftware PRs.  This updates ```MetamorphHandler``` to parse all stored channel names, and fixes ```MetamorphTiffReader``` to treat two planes with unique channel names and Z positions as just 2 channels, instead of 2 channels x 2 Z sections.  It also updates ```MetamorphTiffReader``` to set ```Channel.EmissionWavelength``` when appropriate.
I don't have real data that can be copied to data_repo, but an artificial dataset that exhibits the problem is now in ```data_repo/curated/metamorph/thomas/test.tif``` (generated from ```data_repo/curated/metamorph/thomas/t_test2001.tif```).  Without this change, ```showinf test.tif``` should show SizeZ = 2 and SizeC = 2.  ```tiffinfo test.tif | grep -c "TIFF Directory"``` should confirm that there are only two planes in …

Metamorph TIFF: wavelength population and dimension calculation fix

---

components/formats-bsd/src/loci/formats/in/NativeQTReader.java

This fixes ```openBytes``` to return the correct tile when ```y``` is greater than 0 and only one channel is present.
To test, use ```data_repo/curated/quicktime/curtis/mri-stack-native.mov```.  Without this change, compare the images shown by ```showinf mri-stack-native.mov``` and ```showinf -crop 0,113,186,113 mri-stack-native.mov```.  The second test specifies coordinates for the bottom half of the original image, but will return the top half instead.
The same test with this change should show the bottom half of the original image as expected.
https://github.com/openmicroscopy/data_repo_config/pull/165 proposes adding the test file to the list covered by https://ci.openmicroscopy.org/view/Bio-Formats/job/BIOFORMATS-DEV-merge-performance, as that would have caught this problem. …

QuickTime: respect openBytes' tile Y coordinate

---

components/bio-formats-plugins/src/loci/plugins/in/SeriesDialog.java
components/bio-formats-plugins/src/loci/plugins/in/ThumbLoader.java
components/formats-bsd/src/loci/formats/DimensionSwapper.java

See https://trello.com/c/ATAFHVLS/12-regression-in-imagej-plugin
622b9cc fully reverts the changes to ```loci.plugins.in.ThumbLoader``` from 5.3.0-m2 noted on the card.  The usage of ```loader.interrupt()``` specifically resulted in a race condition in which a ```java.nio.channels.ClosedChannelException``` could be thrown when reading multiple series from the same dataset.  The exception was intermittently reproduceable when opening multiple series from a macro; opening by clicking ```Plugins > Bio-Formats > Bio-Formats Importer``` may have been affected, but I have so far been unable to reproduce an exception via that path.  I have not tested other scripting languages in ImageJ.
cba8592 disables creation of the ```ThumbLoader``` when macro options are present.  This should resolve the …

ImageJ: resolve thumbnail loading regression

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#26](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/26/).
----
--no-rebase

Update POM version numbers to 5.3.2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#27](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/27/).
----
--no-rebase

Update POM version numbers to 5.3.3-SNAPSHOT

---

components/formats-bsd/build.xml
components/formats-bsd/pom.xml
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

See https://trello.com/c/WZkp5y0e/9-increase-default-percentage-of-writing-tests
- the first commit fixes a bug found when running only non-tiling tests. Without this PR `{ant,mvn} test -Dtestng.runWriterSaveBytesTests=100 -Dtestng.runWriterTilingTests=0` should fail. With 209b3ca, the non-tiling tests should be configured using the correct variable and tests should run as expected.
- the second commit sets non-zero default values for the percentage of tiling and non-tiling tests. With this commit, a subset of the the TIFF writing tests should always be executed when running the default command.
- check the Travis and Jenkins builds remain green and that  `{mvn,ant} test` includes tiling and non-tiling TIFF writing tests
- check the number of Formats BSD unit tests in …

TIFF writing tests: define non-zero default percentages

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci-tools/pom.xml
components/bundles/ome-tools/pom.xml
components/forks/jai/pom.xml
components/forks/mdbtools/pom.xml
components/forks/poi/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-common/pom.xml
components/formats-gpl/pom.xml
components/metakit/pom.xml
components/ome-jxr/pom.xml
components/ome-xml/pom.xml
components/specification/pom.xml
components/stubs/lwf-stubs/pom.xml
components/stubs/mipav/pom.xml
components/test-suite/pom.xml
components/xsd-fu/pom.xml
pom.xml

_Not_ having this PR caused open PRs built in the local devspace cache to be treated as the official 0.3.0 release.

Bump to 0.3.1-SNAPSHOT (in IDR group)

---

components/bundles/bioformats_package/build.xml

See https://trello.com/c/IFSFT27n/10-add-news-to-all-archives and https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8188
This addition should mirror the packaging of the Octave and command-line tools bundles by adding the Bio-Formats version history file as a NEWS. This should allow to simplify the identification of the toolbox version without using the API until we suffix the package name with a version number.
To test this PR, check all CI jobs remain green especially the ones testing MATLAB and that the bfmatlab.zip bundle now includes a NEWS.rst file with the version history.

Also copy the version history file as NEWS.rst into the MATLAB bundle

---

components/formats-bsd/build.xml
components/formats-bsd/pom.xml
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

This is a follow up to https://github.com/openmicroscopy/bioformats/pull/2717
There was a bug when attempting to set the 2 test properties (percentageOfTilingTests and percentageOfSaveBytesTests) individually. The value of percentageOfTilingTests was always using the correct setting. For percentageOfSaveBytesTests, if it was set to 0 then it would use the correct setting, otherwise it was using the value from percentageOfTilingTests.
This fix allows percentageOfSaveBytesTests to be set correctly independent of percentageOfTilingTests.
The second commit updates the default number of tests run, this should mean that the Travis unit tests or default ant and maven unit tests will not time out.
To test:
- Run the unit tests with -Dtestng.runWriterTilingTests=100 and …

Bug fix and update default test percentages for TiffWriterTest

---

components/formats-gpl/src/loci/formats/in/ImprovisionTiffReader.java

To test, use ```data_repo/curated/improvision/karsten/Spiro.tiff``` and ```data_repo/curated/improvision/Vessels 32-bit Col.tif```.
Without this PR, ```showinf -nopix -omexml``` on each file should show that the ```Color``` attribute on ```Channel``` is not set.  With this PR, the same test should show a valid ```Color``` set for each ```Channel```.  ```Vessels 32-bit Col.tif``` should have a single channel set to ```-1``` (white), as it is an RGB image.  ```Spiro.tiff``` should have colors that match the channel names (```green``` and ```pink```); this can be confirmed by opening in ImageJ with the color mode set to ```Colorized```.
I would expect automated tests to be unaffected by this change.

Improvision TIFF: read channel colors, if present

---

components/formats-gpl/src/loci/formats/in/NiftiReader.java

This fixes a few problems with byte alignment when reading non-core metadata from NIFTI headers, most notably switching from ```readChar()``` to ```readByte()```.  This also changes unit handling to use the current API instead of multiplying by a factor of 1000 to get micrometers or seconds.
To test, verify that the changes match the NIFTI specification: https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields.  Without this change, ```showinf -nopix data_repo/curated/public/NIH/minimal.hdr``` should show ```Intent name: n1``` in the original metadata - this is suspicious because it is the magic string expected in the last four bytes of the file.  With this change, the same test should not show an ```Intent name``` key, as the field is empty.
Some configurations are affected (see …

NIFTI: fix up extended metadata parsing

---

components/bio-formats-tools/build.xml
components/bio-formats-tools/pom.xml
components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java
components/bio-formats-tools/test/testng.xml

See https://trac.openmicroscopy.org/ome/ticket/10517
Although widely used in our daily usage and y the community, we currently lack test coverage of our Bio-Formats command-line tools. This usually implies that some combinations of options are rarely if not never tested and might be subject to regression when proposing fixes or functionalities.
This commit declares `org.testng` as a dependency of the `bio-formats-tools` module like the other components and provides a first test class for `ImageConverter`. As command-line tools classes have private constructors and use `System.exit()`, the security manager is overriden at set up and restored at teardown while individual methods invoke `ImageConverter.main() `directly.
The expected outcome of this proposal is to start adding unit tests for …

Add minimal framework for testing the command line tools via TestNG

---

components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

This follows on from https://github.com/openmicroscopy/openmicroscopy/pull/4992 to address problems reported by @pwalczysko when working with Metamorph TIFF plates, specifically ```curated/metamorph/alessandro/Metamorph-TIFFs/```.
Without this PR, ```showinf -nopix -omexml Metamorph-TIFFs/001.tif``` should result in an ```OutOfMemoryError```.  Importing into OMERO is expected to fail similarly.  With this PR, the same ```showinf``` test should show generated OME-XML without throwing an exception or resulting in validation errors.
With this PR, importing ```Metamorph-TIFFs/001.tif``` into OMERO should result in a Plate with 2 wells.  None of the imported Images should end up under ```Orphaned Images```.  Note that a valid plate name is not present in the dataset, so ```setPlateName``` is …

Fix support for Metamorph TIFF plates

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java

This fixes the CellWorX plate naming bug reported by @pwalczysko and @dominikl in https://github.com/openmicroscopy/openmicroscopy/pull/4992#issuecomment-272880607.
The test dataset is ```data_repo/curated/cellworx/pki/SKMEL28_10K_1.HTD```.  Without this PR, ```showinf -nopix -omexml SKMEL28_10K_1.HTD``` should show OME-XML with a ```Plate``` ```Name``` set to ```pki``` (the folder containing the dataset).  No other attributes on ```Plate``` will be present apart from ```ID```.
Moving or copying the .HTD and *.pnl files to a different containing folder and repeating the test should show that the ```Plate``` ```Name``` changes to match the containing folder name.
With this PR, the same ```showinf``` test should indicate that the plate name is always ```SKMEL28_10K_1```, regardless of the …

CellWorX: fix plate name and dimensions

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2728
In the case of stopped acquisition, the number of timestamps stored in the LIF file can be lower than the number of planes. With this commit, timestamps are parsed as Double rather than double and only non-null timestamps are stored in the OME metadata.
To test this PR, use the sample file from https://trac.openmicroscopy.org/ome/ticket/12793. After opening the image using the command-line tools, the ImageJ plugin or another Bio-Formats client, the planes corresponding to the Z-sections of some images should not contain any `DeltaT` attribute with this PR included (as opposed to extreme negative values without). The corresponding planes should also be blank.

Leica-LIF: do not store missing timestamps in the OME metadata

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java

An issue was reported during the testing of Bio-Formats 5.3.0 tile writing that errors were encountered when using bigTiff. 
The unit test additions here show that an Exception was indeed being thrown when writing multi series bigTiff images. In fact the same issues can be seen when writing tiles or using the standard TiffWriter. The unit test currently does not write multi series for non tiled scenarios but this can easily be modified to  add that option if required.
**The error:**
The error that was being seen was a NullPointerException when calling saveBytes (without an IFD) and could occur when attempting to read any of the following tags from the IFD when writing the image: STRIP_OFFSETS, IFD.TILE_OFFSETS, IFD.STRIP_BYTE_COUNTS, IFD.TILE_BYTE_COUNTS
**Details of what is happening:** …

TiffWriter - Exception when writing bigTiff multi series

---

docs/sphinx/developers/examples/ExampleSuite.java
docs/sphinx/developers/examples/OverlappedTiledWriter.java
docs/sphinx/developers/examples/SimpleTiledWriter.java
docs/sphinx/developers/examples/TiledReaderWriter.java
docs/sphinx/developers/tiling.txt

This PR contains a number of updates to the tiling example files and documentation.
- Includes an example file (OverlappedTiledWriter) for tiled reading and writing in scenarios ()
- Fixes a bug in the existing TiledReaderWriter which was not properly initialising the tiling parameters
- Removes the catching of exceptions from the existing examples to allow for the above bug to be caught by CI in case of regression
- Adds an example of using the sizeX and sizeY parameters to the fake files in ExampleSuite
- Updates the tiling sphinx documentation to include further description of overlapped tiling examples
Testing required:
- Ensure that the ExampleSuite runs successfully with the new OverlappedTiledWriter example included
- Ensure all existing examples in that ExampleSuite continue to …

Overlapped tiling example and docs

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-December/006286.html
This should resolve some strange behavior when exporting from an
ImagePlus that represents signed data.  There are two parts to the fix:
1. don't overwrite the MetadataStore's pixel type from int* to uint*
2. when filling the byte[] to pass to saveBytes, use the ImageProcessor's calibration table to determine the real pixel values
To test, use QA 17471 and the ImageJ macro at the end of the above thread (adjusting the file paths as needed).  Without this change, run the macro in ImageJ and verify that the two histograms have different min/max values but the same overall shape.  Verify that ```showinf -minmax -range 1 1``` on the original .dv shows that the pixel type is int16, and that ```showinf …
```

ImageJ: preserve original pixel values when exporting signed data

---

components/bio-formats-plugins/src/loci/plugins/config/LIFWidgets.java
components/bio-formats-plugins/src/loci/plugins/util/LociPrefs.java
components/formats-gpl/src/loci/formats/in/LIFReader.java

Follow up to https://github.com/openmicroscopy/bioformats/pull/2727.
This adds a new ```leicalif.old_physical_size``` boolean option to make physical X and Y size calculation backwards compatible with 5.3.2 and earlier.  By default, the option is set to ```false```.
To test, choose any Leica .lif file from ```data_repo/curated/leica-lif```.  Record the values of ```PhysicalSizeX``` and ```PhysicalSizeY``` shown in the OME-XML produced by ```showinf -nopix -omexml```, both with 5.3.2 and with develop not including this PR.
With this PR, ```showinf -nopix -omexml``` on the same file should result in ```PhysicalSizeX``` and ```PhysicalSizeY``` values that match the recorded output from develop.  With this PR and ```showinf -nopix -omexml -option leicalif.old_physical_size true```, …

Leica LIF: add option to preserve pre-5.3.3 physical sizes

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/leica-lif.txt

See https://github.com/openmicroscopy/bioformats/pull/2739
If we decide to change the option name, this will need to be updated.
I do wonder if we need a separate page that covers the options in general - I didn't see anything existing apart from Javadocs.  I can start something here if desired, or add a 5.3.x card.

Add documentation for new Leica LIF metadata option

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

This is a bug in ImageConverter which saw `IllegalArgumentException` thrown with `Invalid image index` when valid parameters had been entered.
This is caused when the image converter command line tool was used with a parameter such as -z or -channel, but not -series. In the case of a specific channel or z plane being requested the writers metadata is configured to override the number of z planes or channels with the value 1. When -series was being used the behaviour was correct as the writer made a new metadata object from the readers values and overwrote them. Without -series however the readers metadata was being overwritten which then resulted in the Exception.
Trac ticket for issue: https://trac.openmicroscopy.org/ome/ticket/13316#ticket
Related forum thread: …

ImageConverter - Invalid image index bug fix

---

docs/sphinx/developers/examples/ExampleSuite.java

In the ExampleSuite it was possible to see NullPointerExceptions when run multiple times without cleaning the directory. An example of this can be seen in https://travis-ci.org/openmicroscopy/bioformats/jobs/196902278
This fix will remove any existing output files if they already exist before beginning writing.
I opted for this approach rather than deleting files on exit as this is part of the ExampleSuite rather than a unit test and as such users may not wish to have output files removed immediately if they are using this as a base.
To reproduce:
- With the PR included run a clean Maven install using `mvn clean install`
- This should complete successfully without error
- Now rerun without cleaning using `mvn install`
- Verify that a NullPointerException is seen in the output
to testy:
- …

ExampleSuite - clean existing output files

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#28](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/28/).
----
--no-rebase

Update POM version numbers to 5.3.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#32](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/32/).
----
--no-rebase

Update POM version numbers to 5.3.4-SNAPSHOT

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/leica-lif.txt

See also https://trello.com/c/9F2PqPfJ/73-review-latest-leica-lif-specification-documents
Also fixes a typo in the year for the version 1 specification.

Add version 3.2 specification to Leica LIF format page

---

docs/sphinx/Makefile
docs/sphinx/about/index.txt
docs/sphinx/build.xml
docs/sphinx/conf.py.in
docs/sphinx/users/index.txt
docs/sphinx/users/ome-server/index.txt

Initially discussed with @jburel, the `omerodoc` extlink in the Bio-Formats documentation forces us to maintain a mapping with the version of a consumer application like OMERO. Since the decoupling of both components, this reverse mapping does not make sense e.g. a stable Bio-Formats series could be either consumed in either none or multiple stable series of OMERO.
This PR redirects all links to the OMERO documentation to the product page. In addition the unused Jenkins extlinks are also removed.
The documentation builds should remain green and the new links should point to the correct OMERO page.

Documentation: OMERO extlink cleanup

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

We previously assumed tiles are always the outermost dimension. This is
not always the case, resulting in mixed up frames for certain scan
types.

Correct order of frames for tilescan with timeseries

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/leica-lif.txt

See https://trello.com/c/kbbtkZr7/11-lif-documentation
This adds a link to the new public images to https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/formats/leica-lif.html using the standard template

Add link to public LIF samples

---

components/forks/jai/src/com/sun/media/imageioimpl/common/ImageUtil.java
components/formats-bsd/src/loci/formats/services/JAIIIOServiceImpl.java

This PR introduces a change required to use Bio-Formats with OMERO
when Java 1.9 is used
This should not change the behaviour with previous versions of Java.
In Java 9, ``javax.imageio.spi.ServiceRegistry`` checks if the requested service is an implementation of the Image I/O service provider interface. This module used the Image I/O service registry for loading external utility services like logging and caching. This is not an intended use and is now prohibited by the Java 9 runtime. javax.imageio.spi.ServiceRegistry uses 'java.util.ServiceLoader' internally.
Detailed of the error
https://trello.com/c/Eh7p5387/18-to-watch-java-1-9
Check that tests are green (especially svs)

Java9 General service loading

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

This prevents exceptions when exporting images that were not opened via the Bio-Formats importer, and thus do not have a complete OMEXMLMetadata store.
See https://github.com/openmicroscopy/bioformats/issues/2752
Without this PR, running the macro listed on gh-2752 (on Windows) or the following on Mac/Linux should result in the ```NullPointerException``` noted on the issue:
```
run("Mitosis (26MB, 5D stack)");
run("Bio-Formats Exporter", "save=[/tmp/test.ics]");
```
With this PR (and after removing the output file), the same test should result in a completed export with no error messages.  This bug was introduced by https://github.com/openmicroscopy/bioformats/pull/2696

ImageJ: fix NPE when check pixel type

---

pom.xml

See https://trello.com/c/InWdSfGf/8-ome-xml-transform-in-bf
Various aspects of the work included out in Bio-Formats 5.2.0 have been about improvement the ROI branch of the OME data model. Additionally, similar work was carried out at the OMERO level to align the data with the model, especially to handle transforms (see https://github.com/openmicroscopy/design/issues/33 for the underlying design issue and https://github.com/openmicroscopy/openmicroscopy/pull/4672 for the reference work).
Despite all this work, `Shape.Transform` remain non-functional when importing/exporting from OME-TIFF files where ROI shapes are defined with Transform attributes. 
The 5.4.0 release of the OME model components includes non-breaking code generation changes allowing to handle Shape Transform attributes …

Bump ome-model to version 5.4.0

---

components/formats-gpl/src/loci/formats/in/Ecat7Reader.java

See http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2017-January/003870.html
Extends the magic string to use a more generic regexp matching various sample filesets (external contribution by Torsten Stoeter).
As per the request of the author, the initial sample data submitted together with the patch will be kept private. Another artificial sample file reproducing the issue was submitted privately and will be made public under the CC-BY 4.0 license.

Allow support for different versions of ECAT7 files

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/ecat7.txt

See https://trello.com/c/VdFhKgTO/13-extended-support-for-ecat7-format for context
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/formats/ecat7.html

Add link to ECAT7 public samples

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#33](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/33/).
----
--no-rebase

Update POM version numbers to 5.3.4

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#34](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/34/).
----
--no-rebase

Update POM version numbers to 5.3.5-SNAPSHOT

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/perkinelmer-ultraview.txt

See https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/607/warnings3Result/ this updates the link and should make the build green again.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.3-staging/formats/perkinelmer-ultraview.html

Fix Ultraview pdf link

---

components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://trello.com/c/XA5EtcYa/101-fix-plate-naming-for-cellvoyager
CellVoyager datasets were previously untested in OMERO or by regular CI builds.  This adds a plate name as referenced on the card (in 6568998 specifically), but also fixes a number of issues that prevented automated testing and import into OMERO.
It may be easiest to review the diff with ```w=1```, as the final commit (b7de1e1) changes all of the many tabs to spaces for consistency with other readers.  I resisted making more extensive whitespace changes to fully bring the reader into line, but can do so here or elsewhere if desired.
https://github.com/openmicroscopy/data_repo_config/pull/177 adds all 3 known CellVoyager datasets to ```data_repo/curated/cellvoyager```.  As these are previously untested, it would be best …

CellVoyager: metadata fixes and general maintainability improvements

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/nifti.txt

The existing AFNI links seem to have been reorganized or put pages under authentication. This commit redirects the format page links to use https://nifti.nimh.nih.gov/ instead.
To test this PR, check the docs build become green again and the the new NifTI links make sense.

Fix NifTI public specification and data sets links

---

components/formats-gpl/src/loci/formats/in/BaseZeissReader.java

Backported from a private PR.  This ensures that the ```bitsPerPixel``` field in ```CoreMetadata``` is always set to match the final pixel type, and populates any channel colors that were parsed in the ```MetadataStore```.
The bits per pixel change should only affect ```uint16``` or ```int16``` files where the acquisition bit depth in the global metadata table is not a multiple of 8, and the RGB channel count is greater than 1.  A suitable test file would be ```data_repo/curated/zeiss-zvi/dan/adultNr1.zvi```, but there may be others.
Without this PR, confirm that ```showinf -nopix -omexml``` on the chosen file shows a pixel type of ```uint16``` and valid bits per pixel of 8.  The ```Color``` attribute on ```Channel``` should not be present in the OME-XML.  With this PR, the same test …

Zeiss ZVI: set valid bits per pixel and channel colors

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12939
To test this PR in addition to the automated builds. open the file mentioned in the ticket with the command-line tools `showinf -omexml-only` and check the `Image` element has an `InstrumentRef` with this PR and none without.

Add missing Image-Instrument ref in GatanReader

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/FormatWriter.java
components/formats-api/src/loci/formats/MetadataTools.java
components/formats-api/src/loci/formats/ReaderWrapper.java

This is part of the work to review the resources of various components for potential resource leaks.
As part of this I have completed an initial pass of the formats-api component and reviewed any warnings.
This PR cleans up some simple warnings throughout covering the following:
Remove unused imports
Remove some unused variables
To test:
All builds and tests should remain green

Formats-API: Initial warnings cleanup 

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java
components/formats-bsd/src/loci/formats/out/OMETiffWriter.java
components/formats-bsd/test/loci/formats/utests/out/OMETiffWriterTest.java

Adds an option to save an OME-TIFF dataset as binary TIFF + companion XML.
To test, convert any image (e.g., [PR2729_frameOrderCombinedScanTypes.lif](http://downloads.openmicroscopy.org/images/Leica-LIF/michael/PR2729_frameOrderCombinedScanTypes.lif)) to OME-TIFF with and without the companion file option, then compare the two `showinf` outputs:
```
./bfconvert PR2729_frameOrderCombinedScanTypes.lif PR2729_frameOrderCombinedScanTypes.ome.tif
./showinf -nopix PR2729_frameOrderCombinedScanTypes.ome.tif >standalone.out
./bfconvert -option ometiff.companion PR2729_frameOrderCombinedScanTypes.companion.ome PR2729_frameOrderCombinedScanTypes.lif PR2729_frameOrderCombinedScanTypes_binonly.ome.tif
./showinf -nopix PR2729_frameOrderCombinedScanTypes.companion.ome >companion.out
```
The `*.out` …

Write OME-TIFF as binary + companion

---

components/formats-gpl/src/loci/formats/in/ScreenReader.java

Adds support for a new `ExcludeReaders` entry in the `Plate` section that allows to exclude some readers from the list considered by `ImageReader`.
Example:
```
[Plate]
Name = Foo
Rows = 8
Columns = 12
Fields = 1
ExcludeReaders = loci.formats.in.Reader1,loci.formats.in.Reader2
```
This is useful in cases where a multi-file format is detected (e.g., due to the presence of specific TIFF tags) which would override the desired arrangement described in the file patterns.

ScreenReader: exclude selected readers

---

components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

See https://trello.com/c/NBMgI8Xz/113-change-the-file-creation-semantics-in-the-unit-tests
Also move the security manager logic to After and Before Method to allow individual test methods to be run via `mvn test` (see https://trello.com/c/WhRvUkyL/111-image-converter-tests-throw-if-run-individually)
To test this PR, check the Travis and Jenkins builds remain green and that the new logic is easy to understand. Also run individual methods as mentioned in the card above and check the individual tests now pass.

ImageConverterTest: create temporary directories using java.nio.file

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This speeds up pixel data access when tiles from a large uncompressed image with no internal tiling are requested via openBytes.  Only the specific tile specified in the call to openBytes is read from disk, instead of the entire image being read and then copied.
See https://trello.com/c/YIaXQGvp/105-investigate-zeiss-czi-pyramid-generation-performance and https://github.com/openmicroscopy/data_repo_config/pull/179
Automated tests should pass using the configuration PR both with and without this PR - the actual pixel data should be the same regardless.
Performance testing was done by iterating over all tiles in all planes, using the optimal tile width and height reported by the reader as a guide.  Specifically, something like this:
```
ImageReader reader = new ImageReader(); …
```

Zeiss CZI: make large uncompressed images more performant

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

This backports existing commits from two private pull requests.  See https://trello.com/c/ciKINMvW/18-dicom-support-for-directory-image
There are three things to test.  First is the physical size configuration change in 184c2f2 and https://github.com/openmicroscopy/data_repo_config/pull/183.  Most existing DICOM files are unaffected; the relevant specification is http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_10.7.html#sect_10.7.1.3
Second is the plane position parsing in eefed6c.  Without this PR, ```showinf -nopix -omexml curated/dicom/charles/img1582.dcm``` should not have any of the OME-XML ```Position*``` attributes set on ```Plane```.  With this PR, all ```Position*``` attributes should be set according to the ```0020,0032 Image Position (Patient) #1``` key in …

DICOM: add support for DICOMDIR files

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
components/formats-gpl/utils/CommentSurgery.java
components/formats-gpl/utils/EditTiffComment.java

This PR is a follow up to https://github.com/openmicroscopy/bioformats/pull/2738 and https://github.com/openmicroscopy/bioformats/pull/2722
Functionality should remain unchanged with this PR, its aim to close all opened resources in TiffSaver, refactor and tidy the TiffSaver code and close any unclosed TiffSaver resources elsewhere in the codebase.
The following changes have been made:
- Remove unused variable declarations in TiffSaver
- Closed resources which had previously remained open
- Refactored the writeIFD method to use a new private writeIFDStrips method. The intention here is to improve the readability of the code without having a long try finally block of code.
- Closed instances of TiffSaver which had previously been left open (Cases in which the calling function managed and …

TiffSaver - Ensure resources are closed

---

components/bio-formats-plugins/src/loci/plugins/in/Calibrator.java
components/bio-formats-plugins/src/loci/plugins/in/Colorizer.java
components/bio-formats-plugins/src/loci/plugins/in/Concatenator.java
components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java
components/bio-formats-plugins/src/loci/plugins/in/ImagePlusReader.java
components/bio-formats-plugins/src/loci/plugins/in/UpgradeDialog.java
components/bio-formats-plugins/src/loci/plugins/macro/LociFunctions.java
components/bio-formats-plugins/src/loci/plugins/out/Exporter.java
components/bio-formats-plugins/utils/Mass_Importer.java

This is part of the work to review the resources of various components for potential resource leaks.
As part of this I have completed an initial pass of the bio-formats_plugins component and reviewed any warnings.
This PR cleans up some simple warnings throughout covering the following:
- Remove unused imports
- Close resources which are left open
This is by no means an extensive or complete cleanup of warnings, simply some initial cleanup which would be easy and safe while identifying potential resource leaks.
**To test:**
- All builds and tests should remain green
- Run ImageJ tests from release process

Bio-Formats Plugins: Warnings cleanup

---

docs/sphinx/conf.py.in
docs/sphinx/themes/globalbftoc.html

Updates the documentation configuration to point at the latest 5.4 downloads/API.

Use latest Bio-Formats 5.4 redirects

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#37](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/37/).
----
--no-rebase

Update POM version numbers to 5.4.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#38](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/38/).
----
--no-rebase

Update POM version numbers to 5.4.1-SNAPSHOT

---

docs/sphinx/about/whats-new.rst

Reproduces the content from the announcement that was missed from the initial version history. 
See https://trello.com/c/Q2Dg6ZZH/123-backport-version-history-from-5-4-0
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.4-staging/

Add content missed for 5.4.0 history

---

components/formats-gpl/src/loci/formats/in/MIASReader.java

Potential ArrayIndexOutOfBoundsException can occur when no tiff files are found located in channel specific subdirectories.
`MIASReader.initFile` looks for two alternative layouts when browsing well directories:
1. Image files directly under the `Well????` dir
2. Image files under channel-specific subdirectories of the `Well????` dir
In the former case, empty directories are skipped in [line 541](https://github.com/openmicroscopy/bioformats/blob/8e3558fa4efe57a095394310205d67165f5fd08c/components/formats-gpl/src/loci/formats/in/MIASReader.java#L541)
In the latter, if all subdirectories are empty, the `tiffFiles` array will be empty and [line 618](https://github.com/openmicroscopy/bioformats/blob/8e3558fa4efe57a095394310205d67165f5fd08c/components/formats-gpl/src/loci/formats/in/MIASReader. …

MIAS Reader -  Unhandled Exception

---

components/formats-gpl/src/loci/formats/in/BDReader.java

ref: https://trello.com/c/sQsD1Sy6/124-bd-pathway-reader-misclassifies-directory
Testing instructions : 
1) Create a new directory.
2) Copy a png file, .lsm file and an .ome.tiff file into the directory.
3) Create a subdirectory called "Experiment.exp"
4) Now using Fiji, try opening the files within the folder (.png, .lsm, .ome.tiff) one after the other.
Expectation 
Without this PR
png file should open without any issues, but the other two files should throw errors.
With this PR
All files under the main directory should open without any issues.
The subset jobs have been run here:
https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/399/
Please check if it is green.
@sbesson @pwalczysko

BDReader: Minor fix to check if Experiment.exp is a directory

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/aperio-svs-tiff.rst
docs/sphinx/formats/hamamatsu-ndpi.rst
docs/sphinx/formats/hamamatsu-vms.rst
docs/sphinx/formats/leica-scn.rst

See https://trello.com/c/NlcprkHA/12-make-openslide-test-data-public
I've removed the Openslide links because the provenance for the files is listed in the readme anyway and we don't have it for any of the other samples on the format pages.
Staged at https://www.openmicroscopy.org/site/support/bio-formats5.4-staging/formats/hamamatsu-ndpi.html and https://www.openmicroscopy.org/site/support/bio-formats5.4-staging/formats/hamamatsu-vms.html

Add Hamamatsu public sample links

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://trello.com/c/Uzb4YXli/116-andor-abd-vs-oiympus-fluoview-date-format
Although the `test-suite` configuration generation logic allows to store acquisition dates in the configuration files, these values are only used in the sanity check of `testSaneOMEXML`. In order to properly address issues like https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8238 together with non-regression tests, it is necessary to have acquisition dates tested as part of the `test-automated` target. Rather than creating another test, this PR proposes to extend the `testDeltaT` non-regression test and also compare read acquisition date with the values stored in the configuration files.
A companion configuration PR should adjust all the incorrect values. In additional to verifying the logic, the …

Add image acquisition tests as part of the testDeltaT

---

docs/sphinx/about/index.rst

See https://trello.com/c/BC2QUyPW/9-versioning-policy-5-4-x-updates
This commit makes official rules which have been almost in place for the last patch/minor releases and should improve transparency for consumers.
- Precise the OMERO/Bio-Formats versioning decoupling point
- Use [semantic versioning](http://semver.org/) for the Bio-Formats API policy. This policy has been effectively in place since Bio-Formats 5.4.0.
- Increase the stringency of the serialization policy
- Add paragraph about the versioning of individual format changes
In terms of release, as per the usage of semver for the API, one expectation is that it should be possible to have more minor releases of Bio-Formats containing API backwards-compatible additions, format reader additions and/or backwards-incompatible or …

Versioning clarifications

---

components/formats-gpl/utils/ReadWriteInMemory.java
docs/sphinx/developers/examples/ExampleSuite.java
docs/sphinx/developers/examples/ReadWriteInMemory.java
docs/sphinx/developers/in-memory.rst
docs/sphinx/developers/index.rst
docs/sphinx/developers/java-library.rst

This PR follows on from the request in https://github.com/openmicroscopy/bioformats/issues/2775
Adding new documentation for an existing file available in utils. I have kept the file in its original location rather than moving it too the docs examples folders, this however is easily changed if its believed the examples folder is a better home for it.
To test:
- Ensure builds are green
- Test all links and markup is displaying correctly
- Ensure text is suitable for describing the use case for both reading and writing in-memory

Add sphinx doc for in-memory read and write

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

OBF is backward compatible, so the reader should be forward compatible.

Enable forward compatibility

---

docs/sphinx/about/whats-new.rst

For a list of included PR's:
Versioning clarifications - https://github.com/openmicroscopy/bioformats/pull/2813
Add sphinx doc for in-memory read and write - https://github.com/openmicroscopy/bioformats/pull/2812
Add Hamamatsu public sample links - https://github.com/openmicroscopy/bioformats/pull/2809
Options doc - https://github.com/openmicroscopy/bioformats/pull/2804
BDReader: Minor fix to check if Experiment.exp is a directory -
https://github.com/openmicroscopy/bioformats/pull/2802
Imago doesn't exist anymore - https://github.com/openmicroscopy/bioformats/pull/2801
Update focalpoint link - https://github.com/openmicroscopy/bioformats/pull/2800
MIAS Reader - Unhandled Exception - https://github.com/openmicroscopy/bioformats/pull/2799
Enable forward compatibility OBF - …

Add version history for 5.4.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#39](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/39/).
----
--no-rebase

Update POM version numbers to 5.4.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#40](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/40/).
----
--no-rebase

Update POM version numbers to 5.4.2-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/FilePatternReader.java

* Adds support for passing key/value pairs to `FilePatternReader` via comment lines
* Adds selective reader exclusion and channel names setting via the above feature
Example:
```
/foo/C<a,b>.pattern
```
See also: #2758 (same feature for `ScreenReader`)

FilePatternReader: KV pairs

---

components/formats-gpl/src/loci/formats/in/ScreenReader.java

Changes `getSeriesUsedFiles` to use a set rather than a list, to avoid duplicates. Note that, if calling `getUsedFiles`, to expose this bug it takes a mini-screen with one series (i.e., one well with one field). This is due to the fact that when there are multiple series, `FormatReader.getUsedFiles` merges partial lists into a set anyway.

ScreenReader: ensure used files contain no duplicates

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/jeol.rst
docs/sphinx/users/idl/index.rst

Fixes broken links reported in https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/672/. Staged at http://www.openmicroscopy.org/site/support/bio-formats5.4-staging/users/idl/index.html and http://www.openmicroscopy.org/site/support/bio-formats5.4-staging/formats/jeol.html.

fix broken doc links to websites

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#41](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/41/).
----
--no-rebase

Update POM version numbers to 5.5.0-SNAPSHOT

---

ant/global.xml

In https://github.com/openmicroscopy/bioformats/pull/2644, the hardcoding of the Git revision number into a properties file was replaced by the introspection of the `Implementation-Build` property in the JAR manifest.
While the [Build Number Plugin](http://www.mojohaus.org/buildnumber-maven-plugin/) is directly used for the Maven build, additional logic was added to the Ant build in `ant/global.xml` to parse the SCM revision.  Whilst testing the Ant-generated command-line tools, it was noticed that for non SNAPSHOT builds, the VCS revision is set to be equal to the release version:
```
$ ~/bftools-5.4.0/showinf -version
Version: 5.4.0
Build date: 20 March 2017
VCS revision: 5.4.0
```
This commit fixes the behavior of the Ant calculation of the `build.version` property to use `git …

Fix Ant build.version property for non-SNAPSHOT versions

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/OIRReader.java

See https://trac.openmicroscopy.org/ome/ticket/13082 and https://github.com/openmicroscopy/data_repo_config/pull/186
This adds a new reader to handle Olympus .oir files and updates ```readers.txt``` accordingly.  No other readers or components should be affected.
As noted on the ticket, the Olympus plugin for ImageJ should be used for validation (http://imagej.net/OlympusImageJPlugin).  A screenshot and exported OME-TIFF from this plugin are present in the same ```data_repo``` directories as each valid .oir (see note on the configuration PR).
A few specific things to check apart from passing tests would be:
* metadata shown in screenshots is visible in the original metadata table and, where reasonable, the generated OME-XML
* channel colors are the same when opening an .oir with the …

Add support for Olympus OIR

---

components/formats-gpl/src/loci/formats/in/FluoviewReader.java

See https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8238 for more context
The FluoviewReader is used for both Olympus FluoView and Andor ABD TIFF formats given their similarity. As reported in the OME forums, the date format for Andor files is wrongly parsed. This commit uses the proper convention and should fix the issue for Andor files.
Parallely to the open-source thread, we contacted Andor and received confirmation this is the expected behavior. A companion PR will be opened to update the configuration for existing Andor ABD TIFF files in our data repository.

Fix acquisition dates format for Andor ABD TIFF format

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

Here we use NDPIReaders and merge the RGB intensities instead of using ChannelSeparators as before.
Otherwise the images have been black for most  (non red) channels.

merge RGB intensities using NDPIReaders

---

components/formats-gpl/src/loci/formats/in/ND2Handler.java

This PR is a followup to https://github.com/openmicroscopy/bioformats/issues/2820 for testing
In the sample file related to the above Github issue we are setting bitsPerPixel as 14 but the PixelType is set to INT8. The original PixelType of the image would have been UINT16 but is overwritten by parsing "uiBpc" with a value of 8.
The possible tags which can be found in the ND2 file appear to be "uiBpc", "uiBpcInMemory" and "uiBpcSignificant". Originally we were parsing "uiBpcInMemory" but this was updated in https://github.com/openmicroscopy/bioformats/commit/63572fbc557f4e01514135e252d2464f2ac8193f

ND2Handler - Only use uiBpcInMemory and uiBpcSignificant

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

See https://github.com/openmicroscopy/data_repo_config/pull/193 and https://github.com/openmicroscopy/bioformats/pull/2814#pullrequestreview-34300051
Without this PR, ```showinf``` or opening in ImageJ should result in an exception for all 6 new .oir files noted in the configuration PR above.  With this PR, the same testing procedure used for #2814 should pass and repository tests of existing data should remain green.
Be aware that the screenshots and OME-TIFF exports are a little less complete this time.  One of the files (noted on the configuration PR) could not be opened in the Olympus ImageJ plugin, and the ```SampleImagesWS``` files open but do not allow metadata to be displayed.
Also note that the window shown in ImageJ when ```Display metadata``` is checked should now order all …

OIR follow-up fixes

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

This issue was discovered in QA-17698
In this case the image description is empty and a parser exception is thrown. Although the images can still be opened and displayed as the exception is caught and a warning message is output rather than an uncaught exception. The reader currently checks for a Null description, but in this scenario the length is 0 and the value is an empty string instead.
Without this PR a SAXParseException is encountered
`[WARN] Could not parse description as XML
org.xml.sax.SAXParseException: Premature end of file.
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
at loci.common.xml.XMLTools.parseDOM(XMLTools.java:215)
at …

OBFReader - Empty Description

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

See https://github.com/openmicroscopy/bioformats/pull/2759#issuecomment-297320194 and https://trello.com/c/aUkOf0QT/10-ndpis-follow-up
@sbesson did most of the work in c8a6218, I just added a couple of commits to fix failing tests.  There is also a corresponding configuration PR: https://github.com/openmicroscopy/data_repo_config/pull/196
Things to check are that:
1. builds continue to pass
2. code changes look sensible
3. changed pixel data in series 5 of both ```test3.ndpis``` makes sense
Point 3 is the only reason a configuration PR was necessary.  Without this PR, the first two channels of series 5 were blank (```showinf -series 5 -minmax``` or ImageJ can confirm), with only the third channel containing data matching series 5 of the corresponding .ndpi file.  With this PR, each …

NDPIS: switch back to using ChannelSeparator

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

See https://trello.com/c/iXCflqLT/588-hipsci-davide-danovi-idr0034-kilpinen-hipsci and dataset in ```data_repo/from_IDR/operetta```.
I haven't tested importing into OMERO, but ```setId``` should work and planes can be read.  As with other readers, blank planes are returned when an expected file is missing.

Operetta: make sure TIFF files exist before reading

---

docs/sphinx/developers/format-documentation.rst

Adds entries for `mif` and `pyramid` to `format-documentation.rst`.

Docs: update section on adding format/reader docs

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#42](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/42/).
----
--no-rebase

Update POM version numbers to 5.5.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#43](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/43/).
----
--no-rebase

Update POM version numbers to 5.5.1-SNAPSHOT

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

See https://trello.com/c/kbzOM2NF/298-incorrect-dimensions-used-for-autoscaling-in-imageinfo
As noted on the card, the original exception can be reproduced without this PR using ```showinf -series 0 -autoscale -crop 0,0,512,512 data_repo/curated/hamamatsu/public/openslide/CMU-3.ndpi```, or any other use of ```-autoscale``` combined with ```-crop```.  With the PR, the same command should result in an image of the size specified by ```-crop```.  Note that ```-crop``` does not apply if ```-thumbs``` is also used, which is why there is a special case.

ImageInfo: fix image dimensions when the '-autoscale' option is used

---

components/autogen/build.xml
components/autogen/src/gen-meta-support.py

See https://trello.com/c/GTMfjd5R/34-fix-bio-formats-autogen-jobs
Following the decoupling of the model components in Bio-Formats 5.3.0, the assumption that the generated ome-xml sources are available in the source tree is no longer correct. A long term solution might be some API to introspect the model elements.
As Bio-Formats is now following semantic versioning and the list of elements should only change for major version bumps, this PR tackles the issue by hardcoding the list of elements. This list will need to be reviewed during model development. 
Additionally this PR uses the logback.xml in the `ant` folder similarly to the other components to reduce the amount of logging generated by the `autogen` targets by default.

Autogen: gen-meta-support fix

---

components/formats-gpl/src/loci/formats/in/CellH5Reader.java

This should fix the exception thrown when recycling an IFormatReader to reopen another CellH5 file.
See https://trello.com/c/hTxcpCtl/37-full-repository-skipped-filesets for more background, without this PR trying to open 2 CellH5 files reusing the same reader (see this [gist](https://gist.github.com/sbesson/775de3588d5bee00c018d67ea94a01c7) for an example) should fail when initializing the second file with an exception of type
```
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Object not found ["H5Gtraverse.c line 755 in H5G_traverse_real(): component not found"]
at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Dopen(Native Method)
at ch.systemsx.cisd.hdf5.hdf5lib.H5D.H5Dopen(H5D.java:78)
at ch.systemsx.cisd.hdf5.HDF5.openDataSet(HDF5.java:753)
at …
```

Clear initialized List variables in CellH5Reader.close()

---

components/formats-api/src/loci/formats/FormatTools.java

This PR is in relation to https://github.com/openmicroscopy/bioformats/issues/2847
An associated sample file can be found in QA-17718
The IndexOutOfBoundsException is thrown as the file has 4 samples per pixel but 1 effective channel. All of the other utility methods take a reader as an input parameter and use the following for dimensions:
`    int zSize = reader.getSizeZ();
int cSize = reader.getEffectiveSizeC();
int tSize = reader.getSizeT();`
In this case MetadataRetrieve is available but not the reader, as such getEffectiveSizeC or getImageCount are not able to be used. The `int sizeC = retrieve.getPixelsSizeC(series).getValue();` will return 4 which will then result in the out of bounds exception.
I have updated this to use `int sizeC = retrieve.getChannelCount(series);` which should …

FormatTools - Chanel IndexOutOfBoundsException

---

docs/sphinx/developers/examples/ExampleSuite.java
docs/sphinx/developers/examples/OrthogonalReader.java
docs/sphinx/developers/file-reader.rst

This adds an example class for reading and writing XZ and YZ planes, written by @emilroz.
The main file reading/API description page seemed like the best place to link it, but can certainly move or add links elsewhere if anyone has a better idea.

Docs: add orthogonal plane example

---

components/test-suite/src/loci/tests/testng/FileHandleTest.java

See https://github.com/openmicroscopy/data_repo_config/pull/201#issuecomment-301613406
With this PR, https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-breaking-performance/ should become green again.

FileHandleTest: exclude JHDF5 native libraries

---

components/formats-gpl/src/loci/formats/in/CellH5Reader.java

See https://trello.com/c/Rlg1SdFD/12-cellh5-broken-tile-loading
While testing the new iviewer app on a CellH5 file, a bug was discovered related to opening of subsets of CellH5 files, namely `openBytes(r, no, x, y, w, h)` for `y>0`. 
This commit fixes this behavior by adjusting the origin of the block array to account for the vertical origin in the private `getImageData` method.
In addition to the automated testing (which should not be affected as we are not testing any non (0,0) based tiles, it might be useful to check that plane loading either using the full planes or tiles now works as expected. https://gist.github.com/sbesson/2d3ea28313dfdb2988df8b3b368a5432 shows the testing script used in MATLAB against a sample `.h5` data but can be converted in Java or other language.

Fix CellH5Reader.openBytes() for non-zero y values

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

This should resolve http://trac.openmicroscopy.org.uk/ome/ticket/13325 and points 6 and 9 of http://trac.openmicroscopy.org/ome/ticket/12935#comment:8.  See also https://trello.com/c/y6KpD3sU/7-czi-tickets
To test, use the following files (all referenced on cards/tickets above):
* ```curated/zeiss-czi/zeiss/ZEN 2.1 blue LSM 800 -May2015/LambdaCh10T3ConvertedForZENblack.czi```
* ```curated/zeiss-czi/zeiss/ZEN 2.1 blue LSM 800 -May2015/LambdaCh10T1ConvertedForZENblack.czi```
* ```curated/zeiss-czi/zeiss/ZEN 2.1 blue LSM 800 -May2015/ConfocalCh3T1Z54BigFrameSize.czi```
* ```curated/zeiss-czi/nottingham/incorrect-colors/Image 6_Structured Illumination.czi```
* ```curated/zeiss-czi/nottingham/incorrect-colors/SIM SpinalChord2ch SeqFrame modeLongerExpo_OutResaved.lsm```
* …

Zeiss CZI and LSM channel fixes

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#44](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/44/).
----
--no-rebase

Update POM version numbers to 5.5.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#45](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/45/).
----
--no-rebase

Update POM version numbers to 5.5.2-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/CellH5Reader.java

This is the same as gh-2845 but rebased onto metadata54.
----
This should fix the exception thrown when recycling an IFormatReader to reopen another CellH5 file.
See https://trello.com/c/hTxcpCtl/37-full-repository-skipped-filesets for more background, without this PR trying to open 2 CellH5 files reusing the same reader (see this [gist](https://gist.github.com/sbesson/775de3588d5bee00c018d67ea94a01c7) for an example) should fail when initializing the second file with an exception of type
```
Exception in thread "main" ncsa.hdf.hdf5lib.exceptions.HDF5SymbolTableException: Symbol table:Object not found ["H5Gtraverse.c line 755 in H5G_traverse_real(): component not found"]
at ch.systemsx.cisd.hdf5.hdf5lib.H5.H5Dopen(Native Method)
at ch.systemsx.cisd.hdf5.hdf5lib.H5D.H5Dopen(H5D.java:78)
at …
```

Clear initialized List variables in CellH5Reader.close() (rebased onto metadata54)

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

Performance tests highlighted some file handle leaks in the NDPISReader initialization step. This commit should ensure all resources are closed by created the RandomAccessInputStream with a try-with-resources block before creating each TiffParser.

NDPISReader: make sure TiffParser streams are closed

---

components/formats-gpl/src/loci/formats/in/VeecoReader.java

VeecoReader.openBytes needs to flip the image retrieved using the HDF service vertically to match the expected origin in Bio-Formats. This commit should fix the implementation to work for any version of (y,w) when retrieving a tile and fix the openbytes tests.

Fix VeecoReader openBytes for tiles where y is larger than 0

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trello.com/c/6aobhHCH/43-zeiss-czi-truncated-file-handling, https://trac.openmicroscopy.org/ome/ticket/13217, and https://trello.com/c/y6KpD3sU/4-czi-tickets
To test, use the file from QA 17168 and the files in ```curated/zeiss-czi/nottingham/truncated-files```.
Without this PR, ```showinf``` on QA 17168 should throw the exception listed in https://trac.openmicroscopy.org/ome/ticket/13217.  With this PR, ```showinf``` should result in a ```FormatException``` indicating that pixel data was not found.  Opening the file in ZEN should confirm that there are no valid pixels.
Without this PR, ```showinf``` on each of the files in ```curated/zeiss-czi/nottingham/truncated-files``` should throw an exception as listed in https://trello.com/c/6aobhHCH/43-zeiss-czi-truncated-file-handling …

Zeiss CZI: better handling of truncated/invalid files

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

Under some circumstances, filter names in OIBs/OIFs are `"---"` instead of `""`. This triggers parsing of the transmittance range cut-in and cut-out values from the name which raises an ArrayIndexOutOfBoundsException in [FV1000Reader.java#L1103](https://github.com/openmicroscopy/bioformats/blob/9088cd5a056d742066d2befdf19a83c71ec76e5d/components/formats-gpl/src/loci/formats/in/FV1000Reader.java#L1103).

FV1000Reader: fix "---" filter models

---

components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-gpl/test/loci/formats/utests/xml/OMEXMLServiceTest.java

`OMEXMLServiceImpl.transformToLatestVersion` is currently not handling `null` results from `getOMEXMLVersion`. This leads to an unhandled `NullPointerException` propagating to upper layers. For instance, in `OMETiffReader` the NPE is thrown [here](https://github.com/openmicroscopy/bioformats/blob/0e53c11bea06021d941007fe14531104e9881b3c/components/formats-bsd/src/loci/formats/in/OMETiffReader.java#L487) but the block expects to catch a `ServiceException`.
With this PR, the `null` value is handled and a `ServiceException` is thrown. New unit tests have been added to test both this specific scenario and `transformToLatestVersion`'s "normal" functionality.

Fix NPE in OMEXMLServiceImpl

---

pom.xml

The version bump should only include C++ and documentation changes - see [5.5.0](https://github.com/ome/ome-model/milestone/5?closed=1), [5.5.1](https://github.com/ome/ome-model/milestone/6?closed=1), [5.5.2](https://github.com/ome/ome-model/milestone/7?closed=1), [5.5.3](https://github.com/ome/ome-model/milestone/8?closed=1) and [5.5.4](https://github.com/ome/ome-model/milestone/9?closed=1) milestones.
To test this PR, check all unit and integration tests remain green.

Bump ome-model to 5.5.4

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See http://trac.openmicroscopy.org/ome/ticket/13186 and https://trello.com/c/y6KpD3sU/10-czi-tickets
To test, use the two files in ```curated/zeiss-czi/aaron/ticket-13186```.  Verify that ```showinf -nopix``` without this PR matches the behavior described in the mailing list thread linked from the ticket.  With this PR, the dimensions reported by ```showinf``` for each file should match the description in the mailing list thread and ZEN.

CZI: fix detection of Z line scans

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

Following https://github.com/openmicroscopy/bioformats/pull/2858, this PR reviews the channel metadata population section of the `FV1000Reader` to use `DataTools.parseDouble`when appropriate and move the filter checking  logic to the `ChannelData` setters.
With this PR included, the automated tests should keep passing for all `oib/oif` samples.

Fv1000: channel metadata population refactoring

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#46](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/46/).
----
--no-rebase

Update POM version numbers to 5.5.2

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#47](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/47/).
----
--no-rebase

Update POM version numbers to 5.5.3-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See https://trello.com/c/TaqXNGco/152-nd2-pixel-offset.
From the Nikon ND2 samples in our repository, it seems like having an odd size both alongside the X dimension and the C dimension is necessary and sufficient to have the scanline padded.
This PR simplifies the `NativeND2Reader.getScanlinePad()` method to use this simpler calculation. To test this PR, check the automated tests keep passing against all ND2 samples. Additionally, test the sample file provided in the [Fiji forum thread](http://forum.imagej.net/t/importing-nd2-files-results-in-horizontal-lines-for-channels/5607) and check that without this PR, the image display with some horizontal lines while with this PR, it matches the expectation from NIS Elements.

ND2 scanline pad fix

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Resolves point 7 of http://trac.openmicroscopy.org/ome/ticket/12935.  See also https://trello.com/c/y6KpD3sU/4-czi-tickets
To test, use ```data_repo/curated/zeiss-czi/zeiss/ZEN 2.1 blue LSM 800 -May2015/ConfocalCh1T15Z1Bleaching2ROIS/ConfocalCh1T15Z1Bleaching2ROIS.czi```.  Opening in ZEN should show two ROI shapes in red: one rectangle and one closed contour.  Without this PR, ```showinf -nopix -omexml``` should only show the rectangle shape being parsed; opening in ImageJ with ```Display ROIs``` checked can also confirm this.
With this PR, the same test should show an additional polygon shape which approximates the shape shown in ZEN.  As far as I can see, the points defined in the .czi file are the control points for a set of Bezier curves, which is why the shapes will not exactly …

CZI: store bezier ROIs as Polygons

---

components/formats-gpl/src/loci/formats/in/KodakReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13321.  See also https://trello.com/c/tcGhzBQl/96-bug-kodakreader
To test, use the .bip file from QA 17540.  Without this change, ```showinf``` should throw an ```IllegalArgumentException``` as noted in the ticket.  The file is not a Kodak .bip file, however, as it only contains unrelated text data (this can be confirmed by opening in a text editor).  With this change, ```showinf``` should correctly throw ```UnknownFormatException```.

Kodak .bip: enforce stricter file type checking

---

components/formats-gpl/src/loci/formats/in/SIFReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13313
The ```Pixel number``` line contains the dimensions of the originally
acquired image, which may not match what is actually stored in the file.
The line following ```Pixel number``` contains the bounding box of the stored image.
To test, use the file from QA 17457.  Without this change, ```showinf``` should throw an exception as indicated in the ticket.  With this change, the file should initialize without exception and result in 500 timepoints of 181x181 image planes.  As this is floating point data, it may be easier to check the actual image data in ImageJ instead of ```showinf```.

Andor SIF: fix support for images that were cropped

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

- Check that it's not a TIFF
- Check that the file size meets a minimum size
Testing: Check with the images from QA 17411 https://www.openmicroscopy.org/qa2/qa/feedback/17411/ which should now be detected as TIFF, not DeltaVision.

DeltaVision: Improve accuracy of isThisType stream checks

---

components/formats-gpl/src/loci/formats/in/BioRadGelReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13094
The ```skip``` field used to calculate the pixel data offset is 4 bytes wide.  Previously submitted files only required the lower 2 bytes, though, so it had been assumed to be 2 bytes wide.
To test, use the file from QA 16880.  Without this change, ```showinf``` should result in an exception as indicated in the ticket.  With this change, ```showinf -autoscale -minmax``` and/or ImageJ should display a reasonable-looking gel image without throwing an exception.

Bio-Rad Gel: fix width of pixel data offset field

---

components/formats-gpl/src/loci/formats/in/MINCReader.java

See https://trello.com/c/9iQdOahX/52-qa-17215-minc-metadata
d3b69ef addresses point 1 on the card; 52050fc addresses point 3, and fa6bab1 addresses point 2.  Only d3b69ef affects the configurations of existing MINC files.
To test, use the file from QA 17215 as indicated on the card.  Without this change, ```showinf -omexml``` should show a uint16 image with ```PhysicalSizeX```, ```PhysicalSizeY```, and ```PhysicalSizeZ``` reported in micrometers and no ```Plane``` elements.  With this change, the pixel type should be int16, all physical sizes should be reported in millimeters, and there should be one ```Plane``` and associated ```Position{X,Y,Z}``` for each image.  The original metadata and output of ```mincheader``` and ```mincinfo``` referenced on the card should confirm that the new …

MINC metadata parsing improvements

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

ZEN often shows timestamps calculated from the T increment, instead of the actual timestamps that are stored with each plane.  We now store the increment in Pixels.TimeIncrement, so that it is easy to work with either timestamp interpretation.
Resolves point 8 of http://trac.openmicroscopy.org/ome/ticket/12935
The new ```timeIncrement``` variable is not needed after ```setId```, so it is ```transient``` to be non-breaking.
To test, use ```data_repo/curated/zeiss-czi/zeiss/ZEN 2.1 blue LSM 800 -May2015/ConfocalCh1T15Z1Bleaching2ROIs/ConfocalCh1T15Z1Bleaching2ROIs.czi```.  Open in ZEN, then mouse over the ```Time``` slider and observe the ```dt``` value in the mouse-over label at various timepoints:
Compare with the value of ```TimeIncrement``` on ```Pixels``` as reported by ```showinf …
```

CZI: populate Pixels.TimeIncrement

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/cellsens-vsi.rst
docs/sphinx/supported-formats.rst

We have two specification documents for Olympus' CellSens .vsi format, both of which were missing from the format page.  See ```data_repo/curated/specs/VSI File Format v1.6.pdf``` and ```data_repo/curated/specs/XV VSI File Format v1.3_confidential.pdf``` (both private).
Discussed with @sbesson in connection with https://list.nih.gov/cgi-bin/wa.exe?A2=IMAGEJ;2b3255.1706

Docs: update CellSens VSI page to include spec list

---

components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trac.openmicroscopy.org/ome/ticket/12935#comment:8 and https://trello.com/c/y6KpD3sU/6-czi-tickets
325a4c9 addresses point 2 on the ticket comment, d026924 addresses point 3, 8a596d1 addresses point 4, and 0242c1d addresses point 5.
To test points 2 and 3, compare ```showinf -nopix -omexml``` against the ```Info``` tab in ZEN for each of the following files.  The ```Stage Position``` in ZEN should match ```PositionX``` and ```PositionY``` in the OME-XML, and the ```Detector Gain``` for each channel in ZEN should match the ```Gain``` for each channel's linked ```Detector``` in the OME-XML.  File list:
```
zeiss-czi/zeiss/ZEN 2.1 black LSM 880 -May 2015/Fluo#1_ZEN2-1-Airyscan.czi
zeiss-czi/zeiss/ZEN 2.1 black LSM 880 -May 2015/Lambda1.czi
zeiss-czi/zeiss/ZEN 2.1 black LSM 880 …
```

CZI: remaining fixes for ticket 12935

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This code fix was suggested by Nick Trahearn on a mailing list thread: http://lists.openmicroscopy.org.uk/pipermail/ome-users/2017-June/006532.html
Description from the mailing list thread:
On line 972 there's a loop where each series is checked to see if it is blank (meaning that no planes correspond to this series). If one is found then it is removed from the list of series. However, the index variable, r, is not updated after the removal. So when the loop starts its next iteration, and r is incremented, the following series gets skipped. If there are multiple blank series in a row then the ones that are skipped don't get removed.
This is simple to readjust the index after removal of an empty plane to deal with instances of multiple empty planes in a row.
To test:
Ensure all builds, …

CZI: Deal with multiple empty planes in a row

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#48](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/48/).
----
--no-rebase

Update POM version numbers to 5.5.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#49](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/49/).
----
--no-rebase

Update POM version numbers to 5.6.0-SNAPSHOT

---

components/bio-formats-plugins/src/loci/plugins/in/ImagePlusReader.java

This issue was raised by mailing list thread http://lists.openmicroscopy.org.uk/pipermail/ome-users/2017-June/006527.html
The problem occurring is an out of memory exception occurring while opening all series in the QA file with the options "open all series" and "concatenate series when compatible".
From debugging and taking memory dumps the issue is due to the full metadata being stored on every ImagePlus object before concatenation. Each ImagePlus object is around 60MB, however 59MB of each of those is a String which is the metadata key value pairs stored in an Info String.
As these objects are being concatenated together there is no need to store the entire metadata string on each one.
A sample file is available for testing: QA-17769
See …

Plugins: Concatenated images memory fix

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Rebases https://github.com/openmicroscopy/bioformats/pull/2827 on top of `metadata54`. This makes `OperettaReader.java` identical to the version on `metadata` except for the following:
```diff
diff --git a/components/formats-gpl/src/loci/formats/in/OperettaReader.java b/components/formats-gpl/src/loci/formats/in/OperettaReader.java
index 07540af130..470c846632 100644
--- a/components/formats-gpl/src/loci/formats/in/OperettaReader.java
+++ b/components/formats-gpl/src/loci/formats/in/OperettaReader.java
@@ -2,7 +2,7 @@
* #%L
* OME Bio-Formats package for reading and converting biological file formats.
* %%
- * Copyright (C) 2005 - 2016 Open Microscopy Environment:
+ * Copyright (C) 2005 - 2017 Open Microscopy Environment:
*   - Board of Regents of the University of Wisconsin-Madison
*   - …
```

Rebase operetta fixes

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

The merge commit lost these changes from `metadata` leading to idr0010 showing only A1.
See https://trello.com/c/aRc1bvJJ/73-idr0010-wrong-image-shown

Metamorph: resurrect changes from gh-2411

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/imspector-obf.rst
docs/sphinx/formats/quicktime-movie.rst
docs/sphinx/formats/tiff.rst

Fixing 4 broken documentation links: 
https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/766/warnings3Result/new/
To test:
- Ensure builds are green and links are valid

Docs: Fix broken links

---

components/formats-bsd/src/loci/formats/in/JPEGReader.java
components/formats-bsd/src/loci/formats/in/TileJPEGReader.java

See https://trello.com/c/M8PidMnv/16-use-jpegturboservice-to-read-large-jpeg-images
There are two new files in ```data_repo/curated/jpeg/big-images```, both of which were created by copying the raw bytes from the first strip in the first IFD of an existing .ndpi file.
With and without this change, attempting to open ```smithd_20111115_2.ndpi.jpg``` (from ```data_repo/curated/hamamatsu/david-smith/smithd_20111115_2.ndpi```) should throw a ```javax.imageio.IIOException``` as noted on the card.  This is because the image dimensions exceed 65500 x 65500 (the maximum allowed by JPEG), and so are set to 0.
Without this change, ```showinf -nopix``` on ```PB_9217_Retina_04 - 2010-07-16 19.04.48.ndpi.jpg``` (from ```data_repo/curated/hamamatsu/harvey/PB_9217_Retina_04 - 2010-07-16 …
```

JPEG: support images with more than Integer.MAX_VALUE pixels

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#50](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/50/).
----
--no-rebase

Update POM version numbers to 5.6.0-m1

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://trac.openmicroscopy.org/ome/ticket/5871 and https://trac.openmicroscopy.org/ome/ticket/13057
This adds support for Z stacks and ROIs to ```GatanReader```, and cleans up several bugs in tag parsing accordingly.
To test ROI support, use ```data_repo/curated/gatan/melissa/annotation-test.dm3``` and ```data_repo/curated/gatan/melissa/annotation-test.tif```.  Without this PR, ```showinf -omexml -nopix annotation-test.dm3``` should not show any populated ROIs.  With this PR, the same test should show 8 ROIs linked to the ```Image```, and no OME-XML validation errors.  Opening ```annotation-test.dm3``` in ImageJ with this PR and ```Display ROIs``` checked should show 8 ROIs, all matching what is in ```annotation-test.tif``` (which has the ROIs burned in).
To test Z stack support, use …

Gatan dm3/dm4: add stack and ROI support

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/12469, see also https://trello.com/c/y6KpD3sU/18-czi-tickets
I would expect tests to remain green and memo files to be unaffected.  The following are new or previously untested files:
```
data_repo/curated/zeiss-czi/qa-11007/SCC47 EGF647 LAMP1488 - LAMP1 only 3D with 405 2_PALM - KAthrin.czi
data_repo/curated/zeiss-czi/qa-11007/SCC47 EGF647 LAMP1488 - EGF only 3D with 405_PALM.czi
data_repo/curated/zeiss-czi/qa-17616/abeta647-dilution1milliontimesnanomolar.czi
data_repo/curated/zeiss-czi/qa-9410/cav_PALM_drift_correct_Convert to Image.czi
data_repo/curated/zeiss-czi/zeiss/ZEN 2.1 black LSM 880 -May 2015/Image 5_PALM_verrechnet.czi
data_repo/curated/zeiss-czi/zeiss/ZEN 2.1 black LSM 880 -May 2015/PALM_OnlineVerrechnet.czi …
```

CZI: add basic support for PALM data

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Rebases #2827 on top of `develop`. This makes `OperettaReader.java` identical to the version on `metadata54` (see #2892).

Rebase operetta fixes onto develop

---

ant/toplevel.xml

This prevents the Maven *-dependencies.xml files from being retained in ```components/bundles/*/build```, as that can cause the bundle jars to include a confusing mix of dependencies.
To reproduce the original problem:
```
$ git checkout v5.4.0 # no Olympus .oir support
$ find . -name *-dependencies.xml -exec rm {} \; # clean cached dependencies so that build is really 5.4.0
$ ant clean jars tools
$ showinf -nopix olympus-oir/olympus/40X_4CH_XY.oir # should throw UnknownFormatException as expected
$ git checkout develop # has Olympus .oir support since v5.5.0
$ ant clean jars tools # don't explicitly clean cached dependencies
$ showinf -nopix olympus-oir/olympus/40X_4CH_XY.oir # incorrectly throws UnknownFormatException
```
Repeating the above test, replacing ```develop``` with this PR's …

ant: remove bundles build files during 'clean'

---

components/formats-bsd/src/loci/formats/codec/JPEGTileDecoder.java
components/formats-bsd/src/loci/formats/in/TileJPEGReader.java
components/formats-gpl/src/loci/formats/in/HamamatsuVMSReader.java
pom.xml

Clean up automatically to prevent resource leaks.  Followup for the corresponding change in ome-codecs.
Testing: check all jobs are green.

JPEGTileDecoder: Implement and use AutoCloseable

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#52](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/52/).
----
--no-rebase

Update POM version numbers to 5.6.0-m2

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/andor-sif.rst
docs/sphinx/supported-formats.rst

While testing a PR in Bio-Formats 5.5.3 (https://github.com/openmicroscopy/bioformats/pull/2876) I noticed that we were missing SIF on the formats docs pages.
I have tried to base the ratings on the comments from https://trello.com/c/WmLyfC5N/7-rfe-update-format-metadata-support-ratings
The reader itself is very basic and doesn't support many metadata fields.

Add missing SIF format to docs

---

components/bio-formats-plugins/src/loci/plugins/config/CellSensWidgets.java
components/bio-formats-plugins/src/loci/plugins/util/LociPrefs.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java
docs/sphinx/formats/options.rst

See https://trello.com/c/fkWsjC4R/157-vsi-detect-warn-about-missing-ets-folder
This updates ```CellSensReader``` to detect whether one or more .ets files are expected.  By default, if an .ets file is expected but not present, then a message will be logged at ```WARN```.  If the new ```cellsens.fail_on_missing_ets``` option is set to true, then a ```FormatException``` will be thrown instead.  If an .ets file is present but not expected, a message will be logged at ```WARN``` no matter what.
We have the following datasets with no .ets file:
```
/ome/data_repo/curated/cellsens/samples/Channels/Composite.vsi
/ome/data_repo/curated/cellsens/samples/Count & Measure/Cell Multichannel-z-stack corr..vsi
/ome/data_repo/curated/cellsens/samples/Count & Measure/Cell Multichannel-z-stack.vsi …
```

CellSens .vsi: add option to fail on missing .ets file

---

docs/sphinx/developers/index.rst
docs/sphinx/developers/wsi.rst

See https://trac.openmicroscopy.org/ome/ticket/10794 and
https://trello.com/c/XdXPofKo/100-add-a-page-explaining-digital-pathology-formats
This adds a basic description of pyramids and the API that we have to support them, as well as referencing the existing pyramid/resolution example code.

Add page referencing pyramid/resolution support

---

components/autogen/src/format-pages.txt
docs/sphinx/_templates/globalbftoc.html
docs/sphinx/about/index.rst
docs/sphinx/about/whats-new.rst
docs/sphinx/conf.py.in
docs/sphinx/developers/reader-guide.rst
docs/sphinx/formats/index.rst
docs/sphinx/formats/ome-tiff.rst
docs/sphinx/formats/ome-xml.rst
docs/sphinx/index.rst
docs/sphinx/pom.xml
docs/sphinx/supported-formats.rst
docs/sphinx/users/index.rst
docs/sphinx/users/ome-server/index.rst

See https://trello.com/c/UeQVAofv/170-docs-check-internal-urls-in-bf
This updates the old plone links to use the new website URLs and removes unused extlinks and updates the downloads and javadoc links to 5.6.x
No decision has been made yet re: the future status of downloads.oo.org

Update website & other docs URLs

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This removes the addition of an unused (and unreferenced) IFD for each call to `TiffSaver.writeImage()` in `TiffSaver.writeIFDStrips()`.  This fixes the problem noted [here](https://trello.com/c/YBsFrE0Q/171-performance-problem-writing-tiles).
Testing: With and without this PR, try bfconverting a large file to a TIFF or OME-TIFF with different tiling parameters.  Without the PR, small tile sizes e.g. 64×64 will cause the file size to bloat dramatically.  This will not occur with the PR merged.

TiffSaver: Don't write new IFD for each tile

---

components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

Issue was raised in QA-17827
The file contains a single Z plane which was leading an ArrayIndexOutOfBoundsException
To reproduce:
- Without the PR import the file from QA-17827 to reproduce the error
To test:
- With the PR read the file from QA-17827 and verify that it opens and displays correctly
- Ensure all builds and tests are green

MetamorphReader - Fix for ArrayIndexOutOfBoundsException

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trello.com/c/Y03GIZk6/145-zeiss-czi-initialization-hanging
Blank images are returned instead for the missing pyramid.
To test, use the file in QA 17740.  Without this change, ```showinf -nopix -noflat``` will enter an infinite loop.
With this change, the same command should result in the file being initialized successfully.  There should be 6 pyramids (one per ZEN scene), with the fourth pyramid (series 3 and all resolutions) being blank.  The remaining images can also be compared with ZEN to verify that everything looks correct.

CZI: prevent infinite loop when a scene with a pyramid is missing

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#54](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/54/).
----
--no-rebase

Update POM version numbers to 5.6.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#56](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/56/).
----
--no-rebase

Update POM version numbers to 5.6.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Issue was originally raised in forum thread https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8325
A sample set of files was also provided in QA-17824
In short each plane should have a unique delta T value, however each channel has the same timepoints as the that of the first channel. This is due to the fact that for the given sample file set, the channels are split across files but when determining which file to read in order to populate metadata the channel index is not taken into account.
Opening this PR to test against other filesets in the data repo

Metamorph: Correct DeltaT across channels

---

docs/sphinx/_templates/globalbftoc.html

See https://trello.com/c/ALSwsNNV/91-add-previous-navigation and https://github.com/openmicroscopy/ome-documentation/pull/1734/
This PR updates the sphinx docs sidebar menu to match OMERO - linking to the downloads and documentation indexes to allow users to find previous versions as all the links on the new website are to the latest release only.

Update doc sidebar for previous version navigation

---

components/bio-formats-plugins/src/loci/plugins/macro/LociFunctions.java

Issue was discovered while investigating https://www.openmicroscopy.org/community/posting.php?mode=reply&f=13&t=8353
In ImageJ when you open the Bio-Formats Macro doc via:
`Plugins -> Bio-Formats -> Bio-Formats Macro Extensions`
The following function is missing:
`Ext.getSeriesMetadataValue(field, value)`
PR adds the missing function

Plugins: Missing macro doc

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#57](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/57/).
----
--no-rebase

Update POM version numbers to 5.7.0-SNAPSHOT

---

docs/sphinx/users/imagej/features.rst
docs/sphinx/users/imagej/options.rst
docs/sphinx/users/index.rst

This is a follow up to https://github.com/openmicroscopy/bioformats/pull/2891
Adds a new docs page for configuring of the Bio-Formats plugin, namely the slice label pattern.

Docs: Add new plugins options page

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#59](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/59/).
----
--no-rebase

Update POM version numbers to 5.7.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#60](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/60/).
----
--no-rebase

Update POM version numbers to 5.7.1-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/TiffReader.java

When working with OME-TIFF files with large metadata (e.g. 38 megabytes on one of our z-stacks), the TiffReader bogs down with some inefficient string handling.  This patch seeks to at least do the concatenation in a single preallocated buffer, instead of flipping back and forth between String and StringBuilder continually.
Why this particular parsing routine (which tries to extract property-esque key-value pairs) is being called on OME-XML at all is a mystery to me, but since it is, we may as well not spend 10s of minutes on string buffer mismanagement.
I can provide a sample OME-TIFF image with such large metadata if necessary.

Improve string handling for large metadata

---

docs/sphinx/developers/index.rst
docs/sphinx/users/index.rst

The format options page can be difficult to find if you don't already know it exists.  This adds links to the options page from the ```users``` and ```developers``` index pages, so that it's hopefully more accessible to newcomers.

Reference format options page from user/developer pages

---

components/formats-bsd/src/loci/formats/tiff/IFD.java

Make the getIFDTextValue faster by preferring the non-regexp version of replace.

prefer the non-regexp version for replacing substrings

---

components/formats-gpl/src/loci/formats/in/ImspectorReader.java

This fixes several metadata parsing bugs in ```ImspectorReader``` that affect the dimensions and ```ModuloAlongT```.  The following tickets should be fixed with these changes:
https://trac.openmicroscopy.org/ome/ticket/13002
https://trac.openmicroscopy.org/ome/ticket/13180
https://trac.openmicroscopy.org/ome/ticket/13181
https://trac.openmicroscopy.org/ome/ticket/13182
Existing Imspector .msr files should be unaffected, but new files for QA 17102 and QA 11369 need to be tested.  Ticket 13180 references a file in QA 17101, but the same file is also present in QA 17102.
For each file, check ```showinf -nopix -omexml``` and verify that the ```step``` in ```ModuloAlongT``` matches the time per FLIM channel referenced in each ticket (usually 220.875 ps).  If an expected value is not in the …

Imspector metadata fixes

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

See https://trac.openmicroscopy.org/ome/ticket/4166
This updates ```TiffParser``` to use ```Integer.reverse(int)``` to reverse the bits in each byte of a tile when the ```FillOrder``` tag is set to 2.  The reversal is performed immediately after the tile buffer is read from the file, before any decompression or unpacking takes place.  An extra check is added to the tile reading logic, so that the special case of returning a single raw tile is never used for ```FillOrder == 2```.
This is a much simpler approach than either of the fixes proposed on the ticket, as it does not require any additional API or changes to other components.  It should be safe for a patch release, but is not urgent and can be deferred if needed.
To test, use the …

TIFF: add support for FillOrder == 2

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Ported from a private PR.  The original test case requiring these changes could not be shared, so a similar test case was manufactured by copying ```data_repo/curated/nd2/christian/CW002_3_rfp.nd2``` to ```data_repo/curated/nd2/christian/missing-dimensions-test.nd2``` and slightly modifying the ```ImageTextInfo``` block to remove Z dimension information.
To test 6174d49, use ```data_repo/curated/nd2/christian/missing-dimensions-test.nd2```.  Without this PR, ```showinf -nopix``` should report 60 series.  With this PR, the same test should show 61 Z sections, matching ```data_repo/curated/nd2/christian/CW002_3_rfp.nd2```.
To test 36c24de, use ```data_repo/curated/nd2/hallie/RNAi Plate 4.nd2``` and ```data_repo/curated/nd2/qa-17785/spc2493.nd2```.  Using ```showinf -nopix -omexml```, …

Nikon ND2: Z dimension and position fixes

---

components/formats-bsd/src/loci/formats/in/TiffReader.java

See https://trello.com/c/dmISsgn6/118-4gb-imagej-tiffs-not-supported
Without this PR, >4GB ImageJ TIFFs were only supported if multiple Z sections and/or timepoints were present.  This changes the ImageJ comment parser to check the IFD count against the total expected image count, not just the expected Z and T counts.
To test, use ```data_repo/curated/tiff/samples/melissa/imagej-4gb/4gb-imagej.tif``` (created by opening the ```.fake``` in the same directory in ImageJ, then selecting ```File > Save As > Tiff...```).  Without this PR, ```showinf -nopix``` should report a single plane.  With this PR, the same test should report 2050 channels, matching the ```.fake``` file.  All other dimensions and pixel data should also be the same between the two files.

TIFF: support >4GB ImageJ TIFFs with multiple channels

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/tiff.rst
docs/sphinx/users/imagej/index.rst

This updates the TIFF format page to include a brief description of support for ImageJ TIFFs and adds a corresponding export-related usage tip to the ImageJ user page.
See also https://github.com/openmicroscopy/bioformats/pull/2957

Update documentation to reference support for ImageJ TIFFs

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#61](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/61/).
----
--no-rebase

Update POM version numbers to 5.7.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#62](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/62/).
----
--no-rebase

Update POM version numbers to 5.7.2-SNAPSHOT

---

components/bio-formats-plugins/src/loci/plugins/util/LibraryChecker.java

`java.version` version comparison is broken with Java 9.  Use a safe comparison using functionality already built into ImageJ.
Testing: Run ImageJ with a build containing the fixes in this PR.  If you can open the importer dialogue, this is working correctly (with Java 7 or 8).  It should also open with Java 9 (with latest daily imagej build), but there may be other Java 9 issues, so working with Java 9 isn't strictly required.

bio-formats-plugins: LibraryChecker: Use safe version check

---

components/formats-bsd/src/loci/formats/in/GIFReader.java

See https://trello.com/c/abmCVITh/149-animated-gif-in-omero and
https://trac.openmicroscopy.org/ome/ticket/12962
To test, use the file from QA 11167.  Without this change, compare ```showinf -range 3 3``` (or any range of planes not including 0) against the corresponding planes shown by just ```showinf```.  The plane shown by ```showinf -range 3 3``` should be obviously different, though ```showinf -range 0 0``` will match the first plane in ```showinf```.
With this PR, the same tests should result in all planes matching.
This should be safe for a patch release, as it should not break memoization.

GIF: fix behavior of openBytes when reading planes out of order

---

components/formats-bsd/src/loci/formats/in/EPSReader.java

To test, use ```data_repo/curated/eps/melissa/sample.eps``` (created from ```data_repo/curated/tiff/pablo/sample.tif```).
Without this PR, ```showinf``` should result in an exception:
```
Exception in thread "main" java.io.EOFException: Attempting to read beyond end of file.
at loci.common.ByteArrayHandle.readShort(ByteArrayHandle.java:333)
at loci.common.RandomAccessInputStream.readShort(RandomAccessInputStream.java:573)
at loci.formats.in.EPSReader.openBytes(EPSReader.java:131)
at loci.formats.FormatReader.openBytes(FormatReader.java:886)
at loci.formats.ImageReader.openBytes(ImageReader.java:441)
at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
at …
```

EPS: fix pixel data reading in the embedded TIFF case

---

docs/sphinx/about/bug-reporting.rst
docs/sphinx/conf.py.in
docs/sphinx/developers/building-bioformats.rst
docs/sphinx/index.rst
docs/sphinx/users/focalpoint/index.rst
docs/sphinx/users/idl/index.rst
docs/sphinx/users/imagej/index.rst
docs/sphinx/users/imagej/installing.rst
docs/sphinx/users/matlab/index.rst
docs/sphinx/users/mipav/index.rst
docs/sphinx/users/octave/index.rst
docs/sphinx/users/visad/index.rst
docs/sphinx/users/visbio/index.rst

See https://trello.com/c/WnTLpmC6/4-make-bio-formats-prereqs-obvious
This adds reminders that BF requires Java 7 or above. 
While I was editing, i noticed the hardcoded 5.6 versioned downloads and API links - I've changed these to use the current version number so we don't have to keep updating them and also amended the various download links on pages to point at the latest downloads page on the new website where they are referring to latest or new versions (this does mean we have a slight mish-mash of 'this version' and 'latest version' links so I'm happy to change all of them to match if we can agree a preference between the two).

Add java 7 reminders & fix downloads

---

components/autogen/src/format-pages.txt
docs/sphinx/formats/amersham-biosciences-gel.rst
docs/sphinx/formats/tiff.rst

The Data Gallery had moved and was 404  and making the build yellow - https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/875/warnings3Result/
While I was updating that anyway I noticed the awaresystems links which auto-redirect to https and figured I may as well update them too as I did a similar fix on the Model docs -https://github.com/ome/ome-model/pull/56/commits/3abc2e9b53372c4190a3ccfd1c3ea16dbd9c072b

Fix data gallery link & add https to awaresystems

---

components/formats-gpl/src/loci/formats/codec/JPEGXRCodec.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

As with several other codecs, ```JPEGXRCodec``` now uses ```options.interleaved``` to determine how pixel data should be returned.  This is useful for any future readers that might use ```JPEGXRCodec``` and expect non-interleaved images.  ```ZeissCZIReader``` expects interleaved images, but is updated to supply more parameters via ```CodecOptions```.  f00b70, 797dee8, and 6dc10da were backported from private PRs; the remaining commits are minor cleanup.
It looks like ```JPEGXRCodec``` was never migrated to https://github.com/ome/ome-codecs, which is why I haven't opened a PR there as well.
There should be no difference in functionality from the CZI perspective, so testing is a matter of code review and verifying that builds remain green.

JPEG-XR: allow non-interleaved data to be returned

---

docs/sphinx/developers/components.rst

Correct link and reference new upstream source repository.

docs: sphinx: Correct jai-imageio link

---

components/formats-gpl/pom.xml

Following upstream deployment changes on the http://artifacts.unidata.ucar.edu repository, the Ant build of Bio-Formats is seemngly broken during the `mvn-ant-tasks:dependencies` build step of the `formats-gpl` component. The Maven build seems to be unaffected by these changes.
This commit tries to fix these issues by disabling the snapshots retrieval from the Unidata repository. In practice, there should be no harm in doing so as the only dependency we are consuming is the netcdf and we should not use SNAPSHOTS with the unidata-releases repository.
- [Travis builds](https://travis-ci.org/openmicroscopy/bioformats/builds/300148474) also affected by these changes should be green with these changes
- the Bio-Formats Jenkins jobs on the [OME …

Disable snapshots for the unidata-releases Nexus repository

---

components/formats-gpl/pom.xml
pom.xml

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2991
Reproducing the last reported failures with an Ant-based build from a clean Maven repository locally and looking at the details of the faulty artifacts, I realized there was a permanent redirect from http to https when retrieving dependencies from http://artifacts.unidata.ucar.edu/.
This PR review the URLs of all `repositories` and `snapshotRepositories` declared in the various  `pom.xml` (Central, Unidata & OME Artifactory) to use HTTPS consistently. This change is expected to fix the issues raised in https://github.com/openmicroscopy/bioformats/pull/2991#issuecomment-344055075 and https://github.com/openmicroscopy/bioformats/pull/2991#issuecomment-344056024.
Similarly to …

Review all repositories to use HTTPS rather than HTTP

---

CONTRIBUTING.md

Noticed while prepping docs training - we now have docs for this so externals shouldn't necessarily have to ask for help.

Add format/reader doc page guide to CONTRIBUTING

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Fixes https://trac.openmicroscopy.org/ome/ticket/13237
To test, use the dataset in ```data_repo/curated/deltavision/michael/ticket-13237/```.  This was created by copying ```data_repo/curated/deltavision/michael/mtools/CTR_centrosome_01_R3D.dv``` to ```01_R3D.dv``` and placing ```01_R3D.dv.log``` from the ticket attachment in the same directory.
Comparing ```showinf -nopix 01_R3D.dv``` with and without this change should show that there are more original metadata key/value pairs with this change.  The log file lines noted on the ticket should be represented by original metadata with this change.  There should be no difference in pixel data or image dimensions.

Deltavision: parse more key/value pairs from the log file

---

components/autogen/src/format-pages.txt
docs/sphinx/about/whats-new.rst
docs/sphinx/formats/cellsens-vsi.rst
docs/sphinx/formats/jpeg-2000.rst
docs/sphinx/formats/khoros-viff-bitmap.rst
docs/sphinx/formats/kodak-bip.rst
docs/sphinx/formats/nikon-nis-elements-nd2.rst
docs/sphinx/formats/olympus-cellrapl.rst
docs/sphinx/formats/olympus-fluoview-fv1000.rst
docs/sphinx/formats/olympus-fluoview-tiff.rst
docs/sphinx/formats/olympus-oir.rst
docs/sphinx/formats/olympus-scanr.rst
docs/sphinx/formats/targa.rst
docs/sphinx/formats/tiff.rst
docs/sphinx/users/micromanager/index.rst

In conjunction with #2995 this should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again.
Deleted links are currently broken and either never expected to be fixed or have been broken repeatedly in the past and therefore don't seem worth the effort to try and maintain even if the current breakage is temporary.

Fix or remove broken links

---

components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

If only one exposure time is defined, use it for all planes.  See
https://trello.com/c/jAeCrkSt/27-metamorphreader-exposuretimes-test-failure
To test, compare the ```ExposureTime``` values shown by ```showinf -nopix -omexml data_repo/curated/metamorph/chris/Foo/exp1_w1_s1_t1.tif``` with and without this PR.  With this PR, every ```Plane``` should have a valid ```ExposureTime```.  Also review the corresponding configuration PR (forthcoming, based upon https://github.com/openmicroscopy/data_repo_config/pull/147) and verify that builds remain green.
This is not urgent at all, but should be safe for a patch release.

Metamorph TIFF: populate exposure times for all planes

---

docs/sphinx/conf.py.in

Re: https://github.com/openmicroscopy/sphinx-ignore-links/issues/1
This removes use of the ignore list repo and adds links that are working but failing the linkchecker to a list in the conf.py.in instead.

Replace sphinx-ignore-list repo with list in conf.py.in

---

docs/sphinx/developers/index.rst

See https://trello.com/c/AprHWzB8/601-references-to-trac - as part of reviewing links to Trac in our docs, this adds a link to Trello for external devs to follow BF development plans.

Add Trello link for BF external developers

---

components/autogen/src/format-pages.txt

For section [Bio-Rad Gel] I updated the fields: weHave, weWant, and notes.
Unfortunately, the documentation will not build for me using ant.  It complains of missing remote dependencies.
I have to the best of my knowledge written the ini file so it should make a valid .rst file.  I believe it should be ok.
This pull request is in reference to https://github.com/openmicroscopy/bioformats/issues/2971
The errors to: ```ant -f build.xml gen-format-page``` are below:
```
BUILD FAILED
/Users/itsayellow/git/bioformats/ant/java.xml:44: Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'edu.ucar:netcdf:jar': Cannot find parent: edu.ucar:thredds-parent for project: null:netcdf:jar:null for project null:netcdf:jar:null …
```

Bio rad gel format update

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This PR is being used to test a fix for https://trello.com/c/RyXt2BAg/177-nd2-incorrect-channel-count
Essentially a single channel single plane image is being mistakenly read as a 3 channel rgb image.
When there is only a single image offset the availableBytes is based on `in.length` which is not an accurate measure of the true image size. As such for single plane images they can be mistakenly modified from single channel to rgb.

ND2: Incorrect channel size

---

docs/sphinx/developers/java-library.rst

This is a fix for the docs build https://ci.openmicroscopy.org/view/Failing/job/BIOFORMATS-DEV-merge-docs/928/
The original link not longer works and tries to incorrectly redirect. The https link functions as before:
Old link -   http://www.unidata.ucar.edu/software/netcdf-java/documentation.htm
New link - https://www.unidata.ucar.edu/software/netcdf-java/documentation.htm
To test:
- Ensure that the docs builds remain green

Use HTTPS for link to Unidata site

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#64](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/64/).
----
--no-rebase

Update POM version numbers to 5.7.3-SNAPSHOT

---

ant/toplevel.xml

While looking at other targets, I noticed this one was broken because this component no longer has any utilties at all.  This PR removes the unused and broken target.
Testing: Check builds remain green.  There are no remaining uses of this target, so nothing should break.

ant: Remove broken utils-formats-api target

---

.appveyor.yml
tools/test-build
tools/test-build.bat

This is a Windows equivalent to the existing travis support: a top-level `.appveyor.yml` and a `tools/test-build.bat` script.  A test matrix tests the maven and ant builds with Java 1.7 and 1.8 (1.7/ant excluded because current Ant releases don't work with Java 1.7 anymore).  `.m2` and python virtualenv are cached between runs (though I'm not entirely certain the venv caching is working between runs); the m2 caching is.
While I'm sure we can improve this further, this is an initial working example of how we could improve our CI testing by building routinely on Windows for every open PR.
This can be tested by enabling Appveyor support for the snoopy bioformats git branch and then running the merge-push job.  See https://ci.appveyor.com/project/rleigh-codelibre/bioformats/build/1.0.19 for …

appveyor: Add appveyor configuration

---

components/formats-gpl/src/loci/formats/in/MRCReader.java

See https://trac.openmicroscopy.org/ome/ticket/8688
To test, choose any file from ```data_repo/curated/mrc/``` and verify that ```showinf -nopix``` with this change shows ```ISPG``` and ```Is data cube``` entries in the original metadata table.  The location of the ISPG field was determined from http://www.ccp4.ac.uk/html/maplib.html#description
I would expect builds to remain green and memo files to be unaffected, so this should be safe for a patch release.

MRC: read the ISPG field and store in original metadata

---

components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java
components/formats-gpl/src/loci/formats/in/ColumbusReader.java

CellVoyagerReader and ColumbusReader both assumed that the file passed to ```isThisType``` was not in the root directory.  This caused problems for TIFF/OME-TIFF files that were placed in the root directory.  
To test, copy any OME-TIFF to ```/``` on Linux/OS X or ```C:\``` (or equivalent) on Windows.  I used ```data_repo/curated/ome-tiff/ome-schemas/2016-06/MitoCheck/00001_01.ome.tiff```.
Without this change, ```showinf -nopix /00001_01.ome.tiff``` should result in the following exception:
```
Exception in thread "main" java.lang.NullPointerException
at loci.common.Location.<init>(Location.java:104)
at loci.common.Location.getParentFile(Location.java:623)
at loci.formats.in.CellVoyagerReader.isThisType(CellVoyagerReader.java:256)
at …
```

Fix NPEs when an OME-TIFF is in the root directory

---

docs/sphinx/conf.py.in

This link has been very flaky recently but the consensus is to leave it in place and make the linkchecker ignore it rather than delete it from the docs. Issue maybe connected to US funding and go away again in future.
Should make https://ci.openmicroscopy.org/view/Docs/job/BIOFORMATS-DEV-merge-docs/ green again

Add flaky nifti link to ignore list

---

components/formats-gpl/src/loci/formats/in/TillVisionReader.java

This should resolve potential test failures as noted on
https://trello.com/c/cTcGjV4m/511-distributed-repository-tests
See also https://web-proxy.openmicroscopy.org/next-ci/job/BIOFORMATS-full-repo/245/console
To test, verify that the BIOFORMATS-full-repo for the ```tillvision``` directory turns green.  BIOFORMATS-merge-full-repository should be unaffected.

TillVision: sort the .pst directory listing

---

Dockerfile

- use the jdk:8 image as the base
- builds Bio-Formats using the Ant build system
- defines the test-automated target as the entry-point
- defines expected paths for the image data and configuration files
With the assumptions above, an image can be built and tested as follows
$ docker build -t bf .
$ docker run -v /path/to/data:/opt/data -v /path/to/config:/opt/config bf

Add first version of Dockerfile for running the tests standalone

---

components/formats-bsd/src/loci/formats/tools/AmiraParameters.java
components/formats-gpl/src/loci/formats/in/AmiraReader.java

Closes #2982
Allow `AmiraMesh` or `Avizo` in the file header.
Testing: see #2982 for sample file.
Test configuration in https://github.com/openmicroscopy/data_repo_config/pull/245

AmiraReader: Handle 'Avizo' in the file header

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

See https://trello.com/c/cTcGjV4m/511-distributed-repository-tests
Similar to 896adaf1d2dacf275100c87a2e23b1dfe05b86bc, this commit should sortthe directory listing so that the `reader.getCurrentFile()` returns the same master file for a Metamorph fileset independently of the environment.
With this PR, both the non-distributed and the distributed automated tests are expected to pass against the `metamorph` folder

Metamorph: sort the directory listing during initFile()

---

components/autogen/src/format-pages.txt
docs/sphinx/conf.py.in
docs/sphinx/formats/aperio-afi.rst
docs/sphinx/formats/aperio-svs-tiff.rst
docs/sphinx/formats/leica-lcs-lei.rst
docs/sphinx/formats/leica-lif.rst
docs/sphinx/formats/leica-scn.rst
docs/sphinx/formats/micro-manager.rst
docs/sphinx/users/micromanager/index.rst

Fixes recent issues with broken external links in the Bio-Formats documentation
- Leica Microsystems: the previous Aperioscope page seems to have been removed without being redirected. c194270 fixes the broken URLs by pointing to the landing page of `Digital Pathlogy>Manage` instead.
- Micro-Manager: consistently use https://micro-manager.org/
- check BIOFORMATS-DEV-merge-docs passes
- manually check the individual Leica links. The Leica Microsystems URL has been added to the `linkcheck_ignore` blacklist list due to an issue with the SSL certificate (see https://github.com/ome/ome-model/pull/63#issuecomment-353068173)

Update reference URLs for the Aperio ImageScope and Micro-Manager

---

components/test-suite/src/loci/tests/testng/Configuration.java

Using FormatTools for the physicalSize values was applying rounding which was inconsistent with the values stored in the readers under certain scenarios. 
Other FormatTools functions such as getTime and getWavelength do not apply any such rounding and as such should not have any impact.

Configuration: Use raw physicalSize values not FormatTools

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

With the current implementation of `FormatReaderTest.testMemoFileUsage()`, it is possible that two independent tests started at the same time against filesets in the same directory will use the same cache directory for creating serialization files leading to possible race conditions and sporadic failures.
With the ongoing work to run distributed automated test per format folder, this scenario is becoming increasingly possible. To reduce this risk, this commit is now generating unique directories using UUID.randomUUID() rather that System.currentTimeMillis().
To test this PR, I would expect no negative import on the [full repository job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-full-repository/) while in the meantime this should remove intermittent failures in the distributed …

Use UUID for generating unique memo file directories

---

components/autogen/src/format-pages.txt
docs/sphinx/developers/components.rst
docs/sphinx/formats/jpeg-2000.rst
docs/sphinx/users/matlab/index.rst

See https://trello.com/c/ZEetFk4Z/4-document-conflicting-matlab-jars-re-bug-report-cannot-open-jp2-file-created-by-stereoinvestigator

Document conflicting JAI-imageIO issues

---

ant/java.xml
components/bio-formats-plugins/src/loci/plugins/in/FilePatternDialog.java
components/bio-formats-plugins/src/loci/plugins/util/DataBrowser.java
components/bio-formats-tools/src/loci/formats/tools/PrintFormatTable.java
components/formats-bsd/src/loci/formats/in/DicomReader.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-bsd/src/loci/formats/tools/AmiraParameters.java
components/formats-gpl/src/loci/formats/in/BaseZeissReader.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/MetamorphHandler.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/formats-gpl/src/loci/formats/in/SEQReader.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/formats-gpl/src/loci/formats/in/ZeissTIFFHandler.java
components/formats-gpl/src/loci/formats/in/ZeissTIFFReader.java
excludebugs.xml

See https://trello.com/c/5E3itceq/179-findbugs-sbscusestringbufferconcatenation
7913cae alone updates the Findbugs configuration to detect ```SBSC_USE_STRINGBUFFER_CONCATENATION``` (http://findbugs.sourceforge.net/bugDescriptions.html#SBSC_USE_STRINGBUFFER_CONCATENATION).  This is done by changing the reporting level to ```medium``` but filtering out all ```medium``` priority bugs apart from ```SBSC_USE_STRINGBUFFER_CONCATENATION```.  Using ```medium``` priority with no filtering results in thousands of additional bugs being detected.
The remaining commits address bugs reported by ```ant -Dfindbugs.home=/path/to/findbugs-3.0.0 findbugs``` with 7913cae included in the build.  Actual functionality should not be affected, so I would expect builds to remain green.
I would also expect this to …

Detect and fix Findbugs' SBSC_USE_STRINGBUFFER_CONCATENATION

---

docs/sphinx/developers/generating-test-images.rst

When a fake image is detected as SPW (i.e. any HCS key has a value greater
than zero), the default value of all HCS keys (except screens) becomes 1.

Clarify the default values of HCS keys for fake images

---

components/formats-gpl/src/loci/formats/in/SDTInfo.java

This is for an issue raised on the mailing list - http://lists.openmicroscopy.org.uk/pipermail/ome-users/2017-October/006718.html
Associated sample file: QA-18098
The problem is caused by reading the block length of the data block and attempting to skip that number of bytes. The expected result from skip bytes should be that it attempts to skip the number of bytes provided and if the end of the file is reached returns the actual number skipped (eg https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html#skipBytes(int)). However  NIOFileHandle in common throws an exception. 
For compressed data the number of available bytes in the file may be less. We have other sample files of this nature (QA-11079) which similarly attempt to skip a number of bytes which do not exist, by …

SDT - Handle IllegalArgumentException

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes #3023
Exception was being thrown when a parsed layer did not create an ROI. The next time an ROI is added the index used for the ROI was then incorrect. Further investigation may be needed to determined if the skipped layer should indeed be creating an ROI of some form.
To test:
- Use the sample file from the associated issue
- Without the PR, read the file from https://github.com/openmicroscopy/bioformats/issues/3023 and verify that an IndexOutOfBoundsException is thrown
- With the PR, read the file from https://github.com/openmicroscopy/bioformats/issues/3023 and verify that it opens and displays correctly

CZI: Allow layers that do not create ROI

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#65](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/65/).
----
--no-rebase

Update POM version numbers to 5.7.3

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#66](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/66/).
----
--no-rebase

Update POM version numbers to 5.8.0-SNAPSHOT

---

.appveyor.yml
components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/ScreenReader.java
components/formats-gpl/test/loci/formats/utests/in/4W2F.screen
components/formats-gpl/test/loci/formats/utests/in/4W2Fsparse.screen
components/formats-gpl/test/loci/formats/utests/in/ScreenReaderTest.java
components/formats-gpl/test/loci/formats/utests/in/minimal.screen
components/formats-gpl/test/loci/formats/utests/testng.xml
pom.xml
tools/test-build
tools/test-build.bat

See https://trello.com/c/oP1oQobf/612-idr0035-caie-drugresponse-bbbc021 
The import of IDR 0035 revealed an issue when populating the channel names using the `ChannelNames` value of the `.screen` files. The bug mostly arose in the case of sparse screens i.e. when not all wells and fields are populated.
This PR should include the fix (using the well-sample index rather the well index) as well as a minimum set of unit tests for `ScreenReader` including a test of the minimum specification for screen files as well as a screen file reproducing the issue 13588b7 .
With this PR, Travis should remain green and including the new `ScreenReaderTest` unit tests. Additionally, the screen files generated in https://github.com/IDR/idr-metadata/pull/255 should properly populate the channel names for all …

ScreenReader: fix channel names population

---

components/bio-formats-plugins/src/loci/plugins/in/ImportProcess.java
components/bio-formats-plugins/src/loci/plugins/in/ImporterOptions.java

When coupled with `setGroupFiles(true)`, this lets you pass a file pattern directly to the `ImporterOptions` as an id, similarly to what you can do with the interactive `FilePatternDialog`.
See:
* http://lists.openmicroscopy.org.uk/pipermail/ome-users/2017-December/006824.html
* http://forum.imagej.net/t/group-images-with-bioformats-in-java-code/7893
The following code now works in my tests:
```java
final String id = "/Users/curtis/data/mri-stack/slice00<05-24>_mri-stack.tif";
ImporterOptions options = new ImporterOptions();
options.setUsingPatternIds(true);
options.setGroupFiles(true);
options.setId(id);
ImagePlus[] imps = BF.openImagePlus(options);
for (final ImagePlus imp : imps)
imp.show();
```
(The TIFFs were created by splitting the MRI Stack sample and saving each as a separate …

Add setFilePatternIds method to ImporterOptions

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Ported from a private PR; to test, use QA 17826.
Without this change, ```showinf -omexml -nopix Index.idx.xml``` should show OME-XML that does not contain instrument, wavelength, exposure time, etc. values.  With this change, all of the following should be present:
```
Objective.NominalMagnification
Objective.LensNA
Channel.ExcitationWavelength
Channel.EmissionWavelength
Plane.ExposureTime
Plane.DeltaT
Image.AcquisitionDate
```
This likely requires a minor version since it requires configuration changes (PR forthcoming) and adds new fields to an inner class.

Operetta: improve MetadataStore population

---

components/formats-gpl/src/loci/formats/in/LIFReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Resolves http://trac.openmicroscopy.org/ome/ticket/4568
To test, use ```data_repo/curated/leica-lif/alex/2010-11-29-test-for-OME.lif```.  Without this change, ```showinf -nopix``` should show just one used file (the .lif itself).  With this change, ```LASAF_CP.xsl```, ```LeicaLogo.jpg```, and ```Pos002_S001.xml``` should also appear on the used files list.
The extra files are a result of exporting the XML metadata for a single series in the .lif file using Leica's LAS AF software.  The .xml file does not include any additional metadata that isn't already in the .lif, but it is nicely formatted and easier to read (and references the .xsl/.jpg).  None of the files are parsed; they are just attached as companion files.  ```showinf -nopix -trace``` can now be used to show the XML that is in …

Leica LIF: attach companion metadata files if present

---

components/formats-gpl/src/loci/formats/in/I2IReader.java
components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

This fixes exceptions reported by @emilroz and @chris-allan when reading extensionless TIFFs with CellProfiler/python-bioformats.  A minimal test case that mimics use of Bio-Formats in CellProfiler/python-bioformats is here:
https://gist.github.com/melissalinkert/f6df0c5efe58c8c0500697727df5a096
To test, copy ```data_repo/curated/tiff/carolyn/tumor_1.tif``` to ```~/pr-test``` and download and compile the above class.  ```java -mx1024m CPTest ~/pr-test``` without this PR should throw:
```
Exception in thread "main" java.lang.IllegalArgumentException: -33551872 must not be null or non-negative.
at ome.xml.model.primitives.NonNegativeInteger.<init>(NonNegativeInteger.java:48)
at ome.xml.model.primitives.PositiveInteger.<init>(PositiveInteger.java:46)
at …
```

Improve precision of isThisType(RandomAccessInputStream) for MRC, I2I, and Zeiss LSM

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

This PR is in relation to https://www.openmicroscopy.org/community/viewtopic.php?t=8425&p=18953
The associated Trello card is https://trello.com/c/fUhH0Cxo/141-cellsens-vsi-npe-in-openbytes
Sample files can be found in QA-18870 and QA-17728
The issue was caused by an unknown compression type of value 5. From the user feedback this has been identified as Lossless JPEG. This PR adds support using the existing LosslessJPEG codec.
To test:
- All builds and tests should remain green
- With this PR opening QA-18870 should result in a NullPointerException
- With this PR opening QA-18870 should display the images correctly without error

VSI: Add support for Lossless JPEG

---

components/formats-bsd/src/loci/formats/tiff/IFD.java

Trello: https://trello.com/c/ylVCzWR0/24-crash-with-trace-log-level
This missing case broke TRACE log output.
Testing:
- set `level=TRACE` in `tools/logback.xml`
- run showinf on a tiled TIFF
- will throw when it hits the offsets/byte count fields calling `printIFD` in `TiffParser`.
- will stop throwing and correctly dump the IFD values with this patch applied

formats-bsd: tiff: Handle OnDemandLongArray in IFD.printIFD()

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

Trello: https://trello.com/c/CQo5glGl/23-tiling-size-bug-creates-broken-tiff-files
The tile size fields were being overwritten with the series image height and width.  With multi-series images, this leads to subsequent series having incorrect tile sizes.  Never overwrite the set size.
This is quite a nasty bug, since it can create corrupt TIFF files with tile sizes which aren't a multiple of 16.
Testing:
- Try running `bfconvert` with the SCN file from QA#17671.
- Check the tile sizes with `tiffinfo | less`, they should all be 512x512 but everything after the first IFD will have the image width and height from the previous series as the tile width and height
- Apply this patch and rebuild.  Testing should now show 512x512 for all IFDs

formats-bsd: TiffWriter: Don't clobber the tile size between series

---

components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java

Trello: https://trello.com/c/v6sJ0mQ2/25-showinf-report-tile-sizes-for-each-series
Useful for checking the tile size for any reader to ensure the tile sizes are correct.
Testing:
- run showinf with a tiled tiff and an untiled tiff.  Both should report the "optimal" tile size values for each series.

tools: ImageInfo: Report tile size in core metadata

---

components/bio-formats-plugins/src/loci/plugins/in/ThumbLoader.java
components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/src/loci/formats/readers.txt
components/formats-bsd/src/loci/formats/gui/AWTImageTools.java
components/formats-gpl/src/loci/formats/in/VectraReader.java

See https://trello.com/c/bRR5zfc7/200-add-support-for-perkinelmer-vectra-qptiff-files
This will require a minor release, as it introduces a new reader and adds an API method to ```loci.formats.gui.AWTImageTools```.
Vectra/QPTIFF is a pyramid TIFF format used for both whole slide scans (fluorescence or brightfield) and multispectral images with smaller (< 2k x 2k) XY dimensions.  Whole slide scans typically use the file extension ```.qptiff``` while other data types use the extension ```.tif```.
To test use, the sample files from https://github.com/openmicroscopy/data_repo_config/pull/248.  The image and series counts reported by ```showinf``` should be such that the sum of the image counts matches the number of IFDs (i.e. ```tiffinfo /path/to/file | grep -c "TIFF Directory"```).  Verify …

Add support for PerkinElmer Vectra/QPTIFF files

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Only one set of ```DisplaySetting``` data is preserved, so that datasets with
one set of settings per plane or tile do not cause the original metadata
table to be too big.  Most of these values are available elsewhere, but the optional display gamma value is only stored under ```DisplaySetting```.
See https://github.com/openmicroscopy/bioformats/commit/169ae85ec4cb8282ad03310714f44a0eaf51ced8 for the original commit disabling ```DisplaySetting``` population.
To test, use pretty much any dataset from ```data_repo/curated/zeiss-czi```; I used ```greg/Experiment-519.czi``` and ```silke/White_574.czi```.  Without this change, ```showinf -nopix``` should not show any original metadata keys beginning with ```DisplaySetting```.  With this change, the same test should show several keys beginning …

CZI: preserve DisplaySetting metadata in the original metadata table

---

components/formats-gpl/src/loci/formats/in/VectraReader.java

See https://github.com/openmicroscopy/bioformats/pull/3017/files#r164682665
There should be no difference in functionality, so builds should remain green.  Apart from build status checks and code review, no other testing is required.
This should be safe for a patch release, so could be pushed to 5.8.1+ as needed.

Vectra QPTIFF: use try-with-resources in isThisType

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This should only affect multi-file OME-TIFF datasets, and only when file grouping is disabled (e.g. via the ```-nogroup``` option to ```showinf```). 
To test, use the ```tubhiswt-4D``` dataset from http://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/
Without this change, ```showinf -nogroup -omexml``` with ```tubhiswt_C0_TP0.ome.tif``` and ```tubhiswt_C1_TP0.ome.tif``` should show 10 timepoints and 1 Z section, with OME-XML that does not represent everything in the file's OME-XML comment.  ```showinf -nopix tubhiswt_C0_TP0.ome.tif``` should show that the entire dataset's dimensions are 43 timepoints, 10 Z sections, and 2 channels; each file contains all Z sections for a single timepoint and channel.
With this change, ```showinf -nogroup -omexml``` with …

OME-TIFF: try harder to preserve metadata when files are ungrouped

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/IonpathMIBITiffReader.java

Ionpath's technology, Multiplexed Ion Beam Imaging (MIBI), uses secondary ion mass spectrometry (SIMS) to image tissue sections. We would like to get a reader into bioformats for the use of our beta customers. I've suggested creating a SIMS domain since there are multiple other SIMS Imaging modalities out there.
I have tested this with loci.formats.tools.ImageInfo, and have a sample image I am happy to provide. I saw that one can upload images to http://qa.openmicroscopy.org.uk/qa/upload/ but I was not sure how to tag it as being of this type, which seems necessary in order to use it for testing.
Thanks in advance!

Add reader for IonpathMIBI TIFF

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-gpl/src/loci/formats/in/IonpathMIBITiffReader.java

Follow-up of https://github.com/openmicroscopy/bioformats/pull/2959, this PR:
- removes the imaging domain API and uses `UNKNOWN_DOMAIN` for the new reader - see https://github.com/openmicroscopy/bioformats/pull/2959#issuecomment-365058850 for the discussion
- updates the new reader to comply with the Bio-Formats formatting style (performed using https://github.com/google/google-java-format/)
This PR should not affect the existing data repository tests using the IonPath MIBI sample file. For code review, it might be useful to use https://github.com/openmicroscopy/bioformats/pull/3073/files?diff=split&w=1 to ignore the whitespace changes.
I have not included a format documentation page. This will need to be done separately, probably after the inclusion of …

Ionpath MIBI reader fixes

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

See https://trello.com/c/Ka8DVIjp/22-oir-support-for-sub-files
There are 8 new datasets to test in ```data_repo/curated/olympus-oir```:
```
martin/20170824_JupGFP_HisRFP_wL3_30xSI_4xzoom_0p5z_A01_G001_0001.oir
olympus/2017-11-20/fish_overview/fish-overview-night.oir
olympus/2017-11-20/stimulation_exp/stimulation_exp.oir
olympus/2017-11-20/xytz_golgi/xytz_golgi.oir
qa-17917/f10010.oir
qa-17919/f10187.oir
qa-17922/example_multipart.oir
qa-18802/20171020_JupGFPHisRFP_L3_30xSI_galvo_p5z_p1xy_better_than_nyquist.oir
```
For each, open in the Olympus ImageJ plugin (https://imagej.net/OlympusImageJPlugin) and compare with using Bio-Formats in ImageJ.  Dimensions, channel names, colors, and physical pixel sizes should be the same.  ```showinf -omexml -nopix``` on each file should also show valid …

Olympus OIR: add support for datasets with multiple files

---

docs/sphinx/conf.py.in

See https://trello.com/c/u46NyzEK/204-versioned-api-downloads-links-in-configpyin
This won't pass the linkchecker until the 5.8.x links exist when there's a release build ready so adding an exclude label
EDITED to remove label - redirects added now

Update API & downloads links to 5.8

---

components/formats-gpl/src/loci/formats/in/IonpathMIBITiffReader.java

This commit closes the variables initialized by `setId` on `close`.
Without this commit, testing 2 IonPath MIBI files using `test-suite`, or recycling an existing `ImageReader` to reopen a second sample file should fail with an `IndexOutOfBoundsException` or similar (see [log](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-repository-subset/548/console)). With this commit, the automated tests should pass against multiple samples of the new format.

IonpathMIBITiffReader: clear initialized variables on close()

---

docs/sphinx/conf.py.in

Added this link to the ignore list as it's currently breaking the docs build. Assume this is temporary and we'll be able to close next week but if not this can be merged for 5.8.0 and I'll revisit the ignore list again for 5.8.1 as needed.

Ignore mdbtools link

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Backported from private PRs.  If a Z step is present, then the values for ```Plane.PositionZ``` are calculated by using the first plane's position and the Z step.  This prevents ```Plane.PositionZ``` from being set to the same value for all Z slices in a dataset.  This is typically a problem in datasets with fused tiles.
To test, use the files whose configurations are updated in https://github.com/openmicroscopy/data_repo_config/pull/258.  Open each in ZEN, and note the relative Z position and units for each plane by mousing over the ```Z-Position``` slider in the bottom left portion of the window.  ```showinf -omexml -nopix``` should show absolute positions in ```PositionZ``` on ```Plane```, with the same spacing and units as the relative Z positions in ZEN.

Zeiss CZI: use Z step when Z positions are not enumerated

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#67](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/67/).
----
--no-rebase

Update POM version numbers to 5.8.0

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#68](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/68/).
----
--no-rebase

Update POM version numbers to 5.8.1-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

This is the same as gh-3065 but rebased onto metadata54.
----
ref: https://trello.com/c/dqTlLuXf/637-serge-pelet-single-cell-data#comment-5a783cf80e00f887aa369c3f
1) Test via Fiji, Command line tools and check if the file opens appropriately via Bio-Formats.
Without this PR you should get an exception (as shown in the trello card).
2) Check if the subset job listed below is green.
@sbesson

MicroManagerReader: Minor fix to handle metadata block closing (rebased onto metadata54)

---

.appveyor.yml
.travis.yml
components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Same as https://github.com/ome/ome-common-java/pull/16 (see this PR for rationale and testing instructions).  Note ome-common and other dependencies are unchanged because it doesn't have a compile- or runtime-dependency upon the new version.

build: Update maven plugin versions

---

components/formats-bsd/src/loci/formats/AxisGuesser.java
components/formats-bsd/src/loci/formats/FileStitcher.java
components/formats-bsd/src/loci/formats/in/FilePatternReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This expands the case for detecting a channel axis based upon ```red```, ```green```, and ```blue``` in the file names.  Matching at least two of ```r```, ```g```, and ```b``` is now sufficient instead of all three.  Stitching of files containing a pyramid is also fixed.
To test, use ```data_repo/curated/fake/samples/multi-channel-pattern/channels.pattern```, which contains:
```<red,green,greenyellow>.fake```
Without this PR, ```showinf -nopix channels.pattern``` should result in 3 Z sections and 1 channel, despite the fact that the file names indicate channel colors.  With this PR, the same test should show 1 Z section and 3 channels as expected.
To test pyramid stitching changes, use ```data_repo/curated/pyramid/pattern/channels.pattern```, which contains: …

File patterns: expanded support for multi-channel pyramids

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

[Trello](https://trello.com/c/jzajo8mX/226-tile-writing-logic-bug)
This change removes what appears to be an unused parameter.  `TiffWriter` has a `prepareToWriteImage` method which has a [plane] `no` parameter.  However, when writing a tiled image, this was being called with the `tileNo` [the tile number on a plane; actually the tile number within the area being written].  This inconsistent calling behaviour meant that `prepareToWriteImage` could not tell whether a plane number or a tile number had been passed.  Looking at the usage of `no` in this function, the `initialized[][]` array indexing looks broken when called with a tile number, because it's sized by the plane count for each series, and it looks like it will potentially misbehave when writing tiles--there's some logic to …

TIFF tile index fix

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java
docs/sphinx/developers/generating-test-images.rst

The INI file can now optionally contain one table per series, named "series_n"
(where n is the 0-based series index).  Each table can describe the
exposure time, X position, Y position, and Z position for any subset of
the planes in the series, using the following keys (where i is the
0-based plane index):
```
ExposureTime_i
ExposureTimeUnit_i
PositionX_i
PositionXUnit_i
PositionY_i
PositionYUnit_i
PositionZ_i
PositionZUnit_i
```
This corresponds to the keys used by the ```.bioformats``` files used for data
testing.
To test, use the new example in ```data_repo/curated/fake/samples/ini```.  ```showinf -nopix -omexml multiSeries-metadata.fake``` with this change should show exposure times and plane positions populated according to the key/value pairs in …

Fake: allow per-plane ExposureTime/Position{X,Y,Z} keys in the INI file

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

See https://trello.com/c/FDmPiqW5/225-imagej-plugin-too-many-dialog-boxes-when-attempting-to-export-images-with-an-unsupported-pixel-type
To test, use the macro code on the Trello card.  Without this PR, an initial unsupported pixel type error message is shown, followed by one message per plane in the ```ImagePlus``` being exported (as described in the card).  With this PR, a single unsupported pixel type error is shown and then the exporter plugin finishes immediately.

ImageJ exporter: stop plugin when unsupported pixel type is found

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/jai/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

This patch release only contains the [Micro-Manager fix](https://github.com/openmicroscopy/bioformats/pull/3071) required to import idr0040.
Once merged and released to Artifactory, a corresponding PR will need to be opened against `openmicroscopy/metadata53` to consume it in IDR 0.4.7.

Bump IDR Bio-Formats version to 0.4.3

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

Trello card: https://trello.com/c/Mn05nSBh/29-remove-dangerous-tiffwriter-special-case
The existing behaviour seems rather ad-hoc and potentially dangerous.
- We ignore the SPP the user specified and write out something completely different, silently
- `ChannelSeparator` and `bfconvert` already provide the means to do this explicitly and intentionally
- While the aim of this appears to be as an aid toward greater interoperability with other software, it prevents the user writing out e.g. images with 2 or 4 samples per pixel.  If the user is writing out an OME-TIFF, the `TiffData` elements won't be able to represent the altered structure (the separated planes), and the file will not be readable as an OME-TIFF because the OME-XML metadata will not match the TIFF `SamplesPerPixel`
This logic …

TiffWriter: Don't split planes when using nonstandard SamplesPerPixel

---

components/formats-bsd/src/loci/formats/in/TiffReader.java

This corrects for the case where the file was processed by some other
software after being saved in ImageJ, which overwrites the first IFD's
ImageJ comment but not the comments from subsequent IFDs.
To test, use the sample dataset in ```data_repo/curated/tiff/samples/melissa/imagej-last-ifd/```.  As noted in the readme, this was generated by opening ImageJ, clicking ```File > Open Samples > Neuron```, then ```File > Save As > Tiff...``` resulting in ```Rat_Hippocampal_Neuron.tif```.  The following commands were then run:
```
echo "original comment deleted" > comment
tiffset -sf 270 comment Rat_Hippocampal_Neuron.tif
```
```tiffinfo Rat_Hippocampal_Neuron.tif``` will confirm that the first IFD's comment is ```original comment deleted``` and the remaining IFDs' …

Check the last IFD for an ImageJ comment

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java

If the ```NEW_SUBFILE_TYPE``` tag has a non-standard type or count such that the value is not inlined, then casting its value to ```Number``` without explicitly filling in the IFD will result in an exception.
To test, use the new ```data_repo/curated/tiff/samples/melissa/long8-subfiletype/Cell_Colony.tif``` file, which was generated from ImageJ sample data as described in the readme.  ```tiffdump``` should confirm that the type for tag 254 (```NEW_SUBFILE_TYPE```) is 16 (```LONG8```) and that the value is 1.
Without this PR, ```showinf Cell_Colony.tif``` should result in this exception:
```
Exception in thread "main" java.lang.ClassCastException: loci.formats.tiff.TiffIFDEntry cannot be cast to java.lang.Number
at …
```

TIFF: make sure IFDs are filled in before being used

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

If every image is contained in a single tile, we likely can't reliably calculate the image offsets.  Reading all of the offsets is a little slower, but is more accurate.
To test, use the three single-file datasets referenced in the config PR:
```
data_repo/curated/flex/qa-7469/002002.flex
data_repo/curated/flex/lee/RLM1 SSN3 300308 008015000.flex
data_repo/curated/flex/tony/001001000_objects.flex
```
Open each in ImageJ with and without this PR, and note the obvious differences for ```qa-7649``` and ```tony``` especially.  With this PR, ```showinf -trace``` on each file and series should log the scaling factor and offset to the first strip for each plane.  The logged offsets should match what ```tiffdump``` reports for the ```StripOffsets``` tags, and the …

Flex: read image offsets when a single tile is used

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#69](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/69/).
----
--no-rebase

Update POM version numbers to 5.8.1

---

components/autogen/pom.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
docs/sphinx/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#70](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/70/).
----
--no-rebase

Update POM version numbers to 5.8.2-SNAPSHOT

---

components/formats-bsd/src/loci/formats/Memoizer.java

Introduces an overridable method that can be used to work around https://trello.com/c/q5L39XPZ/5-bioformatscache-is-expecting-read-write until Memoizer officially supports read-only access to its memos. Should not change Memoizer's behavior in any material way.
Currently open only for comment, **not for merging**.

Have Memoizer.getMemoFile use an isWritableDirectory helper.

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trello.com/c/m7LqcpdM/167-czi-reader-fails-when-the-extension-is-missing and #2916.
As noted in the card and original PR, use an existing .czi file from ```data_repo/curated/zeiss-czi/``` to test.  I used ```data_repo/curated/zeiss-czi/aaron/101post.czi```, but you may wish to use something different.  Copy the file to a different directory and remove the extension. e.g.:
```
$ cp data_repo/curated/zeiss-czi/aaron/101post.czi ~/101post
```
Without this PR, ```showinf ~/101post``` should throw ```StringIndexOutOfBoundsException``` as noted in the original bug report: https://www.openmicroscopy.org/community/viewtopic.php?f=6&t=8336
With this PR, the same test should result in successful initialization and images being displayed.  Apart from file names, there should be no …

Zeiss CZI: fix handling of files with no extension

---

components/formats-api/src/loci/formats/ImageReader.java

This won't prevent initialization from being attempted, but alerts the user that the file may be corrupt before any calls to isThisType(...).  Fake files and files initialized via a specific format reader
(e.g. TiffDelegateReader) will not show this message.
See https://trello.com/c/AjjsuGr3/54-change-error-msg-for-empty-file
An exception could be thrown instead of logging at ```ERROR```, but I decided to start with the lower impact option, minimally so that this is sure to be safe for a patch release.
To test, use the steps noted in the card:
```
$ touch empty.tif
$ showinf -nopix -debug empty.tif
```
Without this PR, a ```FormatException``` is logged and ```MissingLibraryException``` is thrown without any immediate indication that the file is empty.  The output suggests that installing …

ImageReader: log an ERROR-level message when finding a reader for an empty file

---

components/bio-formats-plugins/src/loci/plugins/macro/LociFunctions.java

See http://forum.imagej.net/t/macro-error-when-using-planetimings-txt-from-bioformats/10080/ for a description of the issue
This commit adds a null check for the retrieved exposure time before trying to retrieve the value in seconds in the `Ext.getPlaneTimingExposureTime` macro extension like other `Time` and `Length` quantities retrieved by this API.
Running the script provided in the [ImageJ forum post](http://forum.imagej.net/t/macro-error-when-using-planetimings-txt-from-bioformats/10080) above should fail with the current version of Bio-Formats (5.8.1) when using an image with `Plane` elements but no `Plane.ExposureTime` e.g. https://downloads.openmicroscopy.org/images/DICOM/samples/CR-MONO1-10-chest.dcm 
With this PR included, the macro should execute successfully.

Prevent NPE in Bio-Formats ImageJ macro extensions

---

components/formats-bsd/src/loci/formats/in/AVIReader.java

d5fce6a backported from a private PR; 1feb70c added to fix issues with the last plane of the new test file.
To test, use the new ```data_repo/curated/avi/sample-avis/rgb-odd-width/HyperStack.avi```.  As noted in the readme, this is generated by ImageJ and each plane should contain its own 4 digit 1-based index.  Without this PR, ```showinf HyperStack.avi``` should result in each plane being skewed.  With this PR, the same test should show all 4 planes correctly aligned.
The impact of d5fce6a can be assessed from existing tests, but as 1feb70c affects the last plane it would be a good idea to check the last plane of at least a few existing AVIs (RGB or otherwise).  Assuming tests pass, I would expect this to be safe for a patch release.

AVI: fix padding for RGB images

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

See https://trac.openmicroscopy.org/ome/ticket/13238
To test, use the file from QA 17190.  Without this PR, ```showinf 002002011.flex``` should show 3 series as indicated in the original comment on QA.  With this PR, the same test should show a single series with 3 channels.
I would expect builds to pass with no configuration changes apart from adding QA 17190.  This should be safe for a patch release, but is not especially urgent as the original ticket is nearly 2 years old.

Flex: fix incorrect field count for ticket 13238

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

Assumes that the first Image after the pyramid is the macro, and the second (if present) is the macro ROI.  As the commit message suggests, there is a separate private PR with similar changes for SVS and AFI, but I don't plan to backport this until 5.9.0 as it contains other changes which will break memo files.  The Zeiss CZI and CellSens readers on develop use a similar approach to image name population as is used here.
To test, verify that repository builds pass to confirm that image names remain unchanged when resolutions are unflattened.  Also spot check a few .ndpi files from ```data_repo/curated/hamamatsu``` with ```showinf -nopix -noflat -omexml``` to see that the pyramid has a blank image name, and the two extra images are named ```macro image``` and …

NDPI: update Image names to be more meaningful when resolutions are not flattened

---

components/formats-bsd/src/loci/formats/MinMaxCalculator.java
components/formats-bsd/test/loci/formats/utests/MinMaxCalculatorTest.java
components/formats-bsd/test/loci/formats/utests/testng.xml

Backported from a private PR.  This allows min and max values to be calculated for each core index instead of each series, so that the values are not dependent on ```hasFlattenedResolutions()```.
f4a5ad2 is the test case, and 0d8a155 is the fix.  With f4a5ad2 alone, running unit tests should show one failure in ```MinMaxCalculatorTest.testMultipleResolutions```.  With both commits, all unit tests should pass.

MinMaxCalculator: switch from series to core index based indexing

---

components/test-suite/build.xml
components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java

This allows unconfigured files to be skipped, which previously caused the build to fail; now it ignores these files and succeeds.
Sample output for cellomics from https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-folder/6667/console (from https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-repo/49/flowGraphTable/), which was previously failing:
```
[testng] [2018-04-05 22:28:34,319] [main] testng.allow-missing = true
...
[testng] [2018-04-05 22:28:53,117] [main] /data/samples/different-field-count/plate_B03f00d0.C01 not configured (skipping).
[testng] [2018-04-05 22:28:53,118] [main] /data/samples/different-field-count/plate_C03f00d0.C01 not configured (skipping).
[testng] [2018-04-05 22:28:53,118] [main] /data/samples/different-field-count/plate_C03f01d0.C01 …
```

test-suite: Add testng.allow-missing property

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

See https://trello.com/c/5KT3Bvie/1-idr0040-aymoz-singlecell
Currently the Micro-Manager reader uses one of the TIFF filename for populating the ImageName metadata. For typical replica experiments across multiple positions (Pos0, Pos1,...), this results in duplicate image names. This commit now parses the PositionName key/value in the metadata JSON and use it if available to fill the ImageName.
This PR will probably affect the metadata of existing filesets, require a configuration change in which case it might  be more suitable for a minor release increment.
/cc @dominikl

MicroManager: use PositionName key/value for storing the ImageName

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#71](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/71/).
----
--no-rebase

Update POM version numbers to 5.8.2-rc1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#72](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/72/).
----
--no-rebase

Update POM version numbers to 5.8.2

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#73](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/73/).
----
--no-rebase

Update POM version numbers to 5.9.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/CellH5Reader.java
components/formats-gpl/src/loci/formats/in/NDPISReader.java

Matches Oracle's recommendations and convention. Should not change behavior at all.

switch modifier order to "static final" in readers

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/DNGReader.java
components/formats-gpl/src/loci/formats/in/NikonReader.java

In order to support the use of sub-resolutions as intended, remove merging of SubIFDs into the main IFD list by default, by making it a configurable option in MinimalTiffReader as for other options.  This is required by the Canon DNG and Nikon TIFF readers only.
Testing: check all builds are green, including the full repo test.

Remove implicit SUBIFD flattening in TiffParser

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/DNGReader.java
components/formats-gpl/src/loci/formats/in/NikonReader.java

In preparation for sub-resolutions, make the OME-TIFF reader work with the sub-resolution-specific format reader.  There are no behaviour changes with this PR, only a change of base class (and some small cleanups to make it easier to spot real bugs).  This is essentially the same reader changes as in https://github.com/openmicroscopy/bioformats/pull/3119.
Note: Ignore first two commits, which are from https://github.com/openmicroscopy/bioformats/pull/3133 (they will disappear once it's merged).
Testing: make sure that the data repo tests remain green.

OMETiffReader extends SubResolutionFormatReader

---

.appveyor.yml
.travis.yml

The last commit from https://github.com/openmicroscopy/bioformats/pull/3138 but for `east`.  This will speed up the CI wait times, particularly for appveyor by 15-20 minutes per run.
The test matrix size for travis and appveyor will reduce from 6 to 4.
Testing: check the builds are green and that the matrix size has decreased.

ci: Only test ant build with JDK8

---

ant/java.xml
components/bio-formats-plugins/build.xml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/build.xml
components/bio-formats-tools/pom.xml
components/formats-api/build.xml
components/formats-api/pom.xml
components/formats-bsd/build.xml
components/formats-bsd/pom.xml
components/formats-gpl/build.xml
components/formats-gpl/pom.xml
components/test-suite/build.xml

This results in unnecessary hits and biased statistics.  Add `bioformats_can_do_upgrade_check=false` to all test invocations.
The main culprits are the bio-formats-tools unit tests.  However, this PR disables them comprehensively to avoid any potential for future mis-reporting.
Testing: check CI builds are green.

build: Never run upgrade checker when running unit tests

---

components/formats-gpl/src/loci/formats/in/TrestleReader.java

The file passed to setId is now first on the list, and the directory listing is sorted (as for other readers).
See https://github.com/openmicroscopy/data_repo_config/pull/299.
To test, verify that the tests for the ```trestle``` directory pass with this change, compared with https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-test-folder/12878/ without this change.

Trestle: ensure consistent ordering of used files

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

In ND files referencing RGB images, sizeC was getting set to 1 rather than 3.
(The individual STK/TIFF files are properly handled). This change multiplies
the sizeC by 3 for RGB images, and replaces a later use of sizeC with
effectiveSizeC.
The specific failure I was encountering was that the pixel buffer would be too small in calls to openBytes, by a factor of 3. `showinf` for example crashes on such images. I uploaded an example failing image to the Glencoe ftp server as `jmuhlich_metamorph_rgb`. Note that I manually edited the .nd file down from an enormous 450-series slide scan to just a single series. With this patch, this image is handled correctly.

Fix Metamorph RGB series channel count

---

pom.xml

Fixes https://github.com/ome/bio-formats-build/issues/21
When bioformats is built as part of a multi-module project https://github.com/ome/bio-formats-build, it becomes necessary to force the build number to be re-fetch for each module. Otherwise the build number from previous components e.g. `ome-common` is used.
This issue primarily affects development builds of Bio-Formats since release components should consume upstream artifacts. Also only the Bio-Formats API has
The performance overhead should be minimal especially as we decoupled a lot of components.
- build Bio-Formats using https://github.com/ome/bio-formats-build
- look at the content of the  manifest using `unzip -q -c META-INF/MANIFEST.MF formats-gpl.jar`. Without this PR the SHA1 of `ome-common-java` should …

Do not unconditionally force the SCM revision to be fetched only once

---

.appveyor.yml
.gitignore
.travis.yml
components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

[Trello card](https://trello.com/c/Y5MCXFTs/38-backport-needed-maven-fixes-from-east)
Backport of all build-related changes from east for 5.9.0.
- Maven plugin updates
- pom improvements
- ci updates
- ignore IntelliJ files
This allows building and testing with Java 9 and 10, which is useful for development on contemporary systems, e.g. Ubuntu 18.10, where bioformats develop is currently not buildable by default.
Testing: Check CI builds are green.

Build updates

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

This fixes file grouping and well/field indexing when the field count is not consistent for every well.
To test, use the example plate in ```data_repo/curated/cellomics/samples/different-field-count```, which was constructed by copying/renaming ```data_repo/curated/cellomics/omar/FB03f00d0.C01``` as described in the readme.
Without this PR, ```showinf -nopix -omexml plate_B03f00d0.C01``` should have a single series representing one well and field.  The used file list should contain only ```plate_B03f00d0.C01```.  With this PR, the same test should detect all 3 files in the plate, and represent them as 3 series (1 for well B03 and 2 for well C03).
One additional configuration change was necessary to change the well name from A00 to A01 for single file plates …

Cellomics: fix indexing when the field counts are variable

---

components/formats-gpl/src/loci/formats/in/GelReader.java

[Trello](https://trello.com/c/WeajJ80u/242-gel-incorrect-pixel-data)
The use of DataTools.bytesToShort was causing values to wrap around when reading unsigned values which were not representable in a signed short.  Use bytesToInt to avoid this problem.
Testing: Try reading the GEL file from https://www.openmicroscopy.org/qa2/qa/feedback/21519/ with and without this patch.  It should display properly with this patch applied.
Note: may require the GEL configuration test data regenerating for images which were previously being read incorrectly.

GelReader: Don't allow overflow when reading unsigned integer values

---

components/formats-bsd/src/loci/formats/in/EPSReader.java
components/formats-bsd/src/loci/formats/in/MicromanagerReader.java
components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/APLReader.java
components/formats-gpl/src/loci/formats/in/CellSensReader.java
components/formats-gpl/src/loci/formats/in/DNGReader.java
components/formats-gpl/src/loci/formats/in/FV1000Reader.java
components/formats-gpl/src/loci/formats/in/FlexReader.java
components/formats-gpl/src/loci/formats/in/GelReader.java
components/formats-gpl/src/loci/formats/in/ImaconReader.java
components/formats-gpl/src/loci/formats/in/IonpathMIBITiffReader.java
components/formats-gpl/src/loci/formats/in/JPKReader.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java
components/formats-gpl/src/loci/formats/in/MRWReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java
components/formats-gpl/src/loci/formats/in/NDPIReader.java
components/formats-gpl/src/loci/formats/in/NDPISReader.java
components/formats-gpl/src/loci/formats/in/NikonReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java
components/formats-gpl/src/loci/formats/in/TCSReader.java
components/formats-gpl/src/loci/formats/in/TrestleReader.java
components/formats-gpl/src/loci/formats/in/VectraReader.java
components/formats-gpl/utils/ExtractFlexMetadata.java
components/formats-gpl/utils/TiffDumper.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java
tools/test-build

Selected commits from https://github.com/openmicroscopy/bioformats/pull/3145 to add `getMainIFDs` to replace and deprecate `getIFDs`.
`MinimalTiffReader.mergeSubIFDs` is marked `transient` to avoid breaking memos.
Testing: Should be tested by the full repo tests and CI.  May need additional checking for memo breakage.

Backported TiffParser fixes and getIFDs deprecation

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

The original use case was a 12589 x 48981 uint16 .nd2 file.  Reading tiles from approximately the bottom half of the image resulted in an integer overflow when calculating the number of bytes to skip before reading.  This changes all of the relevant ```skipBytes``` calls (which only takes an ```int``` ) to ```seek``` calls, and uses ```long``` multiplication as needed to prevent overflows.
Discussed with @sbesson yesterday, and agreed that a test file would not be necessary given the limited scope of this change (i.e. code review and passing builds are sufficient).  Also /cc @mtbc for review as suggested by @sbesson.

ND2: prevent integer overflow when reading a tile from a large image

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://trello.com/c/3AHJeUPc/236-czi-compressed-pyramidal-error
To test, use the file from QA 20612.  Without this PR, opening the file using ImageJ or ```showinf``` will result in 14 series, most of which look corrupted (as noted on the card).
With this PR, ImageJ or ```showinf``` should report 3 series - one full resolution image, one label, and one macro/overview.  There is no stored pyramid, so there should be no subresolutions detected.  The image dimensions and pixel data should match what is shown in ZEN.
Builds should remain green with this change.  This should be safe for a patch release, so is low priority for 5.9.0 as it could be deferred to 5.9.1.

Zeiss CZI: fix big image edge case when tiling is present but a pyramid is not

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

See https://trello.com/c/O5LkXtx0/29-imagewriter-compression-behaviour
Testing: Run `bfconvert` with and without the `-compression zlib` option, then run `tiffinfo` on both files.  You will see `Compression Scheme: AdobeDeflate` with zlib compression, and the file size should be reduced.

TiffWriter: Add support for DEFLATE (zlib) compression

---

tools/bf.bat
tools/bf.sh

See https://trello.com/c/gcxA7ZMJ/514-tools-downloads-link-falls-out-of-date
The new URLs remove an explicit version number reference, and should currently point to the 5.8.2 download directory.
This shouldn't affect builds or behavior other than changing what is printed when using ```showinf``` or ```bfconvert``` cannot find valid Bio-Formats jars.  Definitely not urgent, and should be safe for a patch release.

Fix download URLs in bf.bat and bf.sh

---

components/formats-api/src/loci/formats/IFormatReader.java

See https://trello.com/c/zgKbVcun/32-add-documentation-for-getusedfiles-ordering
This is a documentation change only, so a review for clarity/correctness should be sufficient.  I would not expect builds to be impacted.
Definitely not urgent, so feel free to push to a later patch release as needed.

Clarify ordering expectation in get*UsedFiles Javadocs

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

This is a follow up to a thread on the forums: https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8522&sid=c0ae5e3d8131cd28aaf123a570cd3ca6
From debugging the file is caught in a while loop at https://github.com/dgault/bioformats/blob/47d5e46ed52f13c1388f7315545bebe684bdcc0e/components/formats-gpl/src/loci/formats/in/OIRReader.java#L615
Each iteration of the loop the file pointer remains unchanged and the length read at https://github.com/dgault/bioformats/blob/47d5e46ed52f13c1388f7315545bebe684bdcc0e/components/formats-gpl/src/loci/formats/in/OIRReader.java#L618 is 0
To test:
- Ensure that all builds and tests remain green
- Without the PR test using QA-21538 and see that importing the file results in an infinite loop
- With the PR reproduce the above test and ensure that the …

OIR - Prevent infinite loop

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

To test, use ```data_repo/curated/metamorph/andressa/MCF-10A/Sparse/Collagen/120806_1_w1Filter_DAPI.TIF```.  First verify that ```showinf -nopix -omexml 120806_1_w1Filter_DAPI.TIF``` (with or without this PR) does not report a ```Plate```, i.e. this is not an HCS dataset.
Without this PR, test code such as:
```
ImageReader r = new ImageReader();
r.setId("/ome/data_repo/curated/metamorph/andressa/MCF-10A/Sparse/Collagen/120806_1_w1Filter_DAPI.TIF");
String[] domains = r.getDomains();
r.close();
for (String d : domains) {
System.out.println("domain = " + d);
}
```
should indicate that this dataset is identified as having the HCS domain, even though it does not report HCS metadata.
With this PR, the same test should result in only the LM domain being reported, …

Metamorph: override getDomains() to check if the current file has a plate

---

components/formats-gpl/src/loci/formats/in/VolocityReader.java

Backport of a private PR.  Volocity allows images to be arranged into separate directories within the .mvd2 database.  This updates the image names to preserve the directory names (if any), so that the original hierarchy is not lost.
To test, check the datasets with changed configurations as noted in the forthcoming configuration PR.  The only changes should be to some image names; in each case, the new name should end with ```/``` plus the old name.
With both PRs included, builds should continue to pass and memo files should be unaffected.

Volocity: expand Image names to include the stack parent name(s)

---

components/formats-gpl/src/loci/formats/in/InveonReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Backported from a private PR.  The data file name stored in the header is not updated if the header and
data files are renamed. If the stored data file name does not exist,
then a file whose name is similar to the header file's name will be used
(if such a file is present).
To test, use the dataset in ```data_repo/curated/inveon/samples/rename-test```.  Without this PR, ```showinf batch1_v1.ct.img.hdr``` should throw a ```FileNotFoundException```.  With this PR, the same test should display images and metadata matching ```showinf data_repo/curated/inveon/samples/batch1_v1.ct.img.hdr```.  The used file list should contain two files, both of which exist.

Inveon: attempt to find renamed data files

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

See https://trac.openmicroscopy.org/ome/ticket/13196.
To test, use the file from QA 17111.  Without this PR, ```showinf -nopix``` should report 43 series, each with ```SizeX``` and ```SizeZ``` similar but ```SizeY``` noticeably different.  With this PR, the same command should show 43 series, each of which has ```SizeX``` equivalent to ```SizeY```.  This should be consistent with the ticket description.  It is probably also worth checking the 256x256 series in ImageJ to verify that the images look plausible for FLIM data.
Builds should continue to pass without any configuration changes for existing datasets.  This might be safe for a patch release, but is definitely low priority either way.

OBF: add basic FLIM support

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

See https://trello.com/c/Zp2rgbqf/246-leica-lif-dimension-problems
To test, use ```data_repo/curated/leica-lif/pascal/test.lif```.  Without this change, verify that the dimension order (```XYCZT```) is incorrect by comparing what LAS X shows against each channel as opened in ImageJ.
I would expect C=0, Z=0, T=0 and C=1, Z=0, T=0 in ImageJ to be from the same channel according to LAS X.
With this change, the same comparison should show that C=0 and C=1 are now distinct channels.  The dimension order should now be reported as ```XYZCT```.  Builds should remain green, and this should be safe for a patch release if needed.

Leica LIF: only prioritize C in dimension order if channels are RGB

---

components/formats-gpl/matlab/bfsave.m

Silent dropping of the dimensionOrder parameter stumped me for some time while trying to combine files.

Warn if passing metadata with dimensionOrder in bfsave

---

components/formats-gpl/src/loci/formats/in/MetamorphTiffReader.java

This is a fix for the NullPointerException and a divide by zero exception as reported in https://github.com/openmicroscopy/bioformats/issues/3166
To test:
- Open the provided sample file in https://github.com/openmicroscopy/bioformats/issues/3166 with Bio-Formats
- Without the PR an exception is thrown, with the PR the file should open and display without error

MetaMorph - Prevent NullPointerException

---

components/formats-bsd/src/loci/formats/FileStitcher.java

See https://trello.com/c/hTxcpCtl/37-full-repository-skipped-filesets
When detecting a pattern based upon a list of file names, ignore any patterns that include file names not in the list.  To test, use the TIFF files in ```data_repo/curated/cellr/kees/7Z5GR81B_DocumentFiles```.  Without this change, ```showinf -nopix -stitch``` on any of them should throw a ```FileNotFoundException```.  With this change, there should be no exception and a single file should be on the used files list.
Unit tests should continue to pass with this change, but there is a chance that this will impact https://web-proxy.openmicroscopy.org/west-ci/job/BIOFORMATS-test-repo/ and require additional fixes.

FileStitcher: do not use detected patterns that include missing files

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#74](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/74/).
----
--no-rebase

Update POM version numbers to 5.9.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#75](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/75/).
----
--no-rebase

Update POM version numbers to 5.9.1-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

See https://trello.com/c/p8Jr7Hub/31-micromanager-v2-error-message
To test, use one of the *_metadata.txt files in ```curated/micromanager/qa-17040```.  Without this PR, ```showinf -nopix``` should not show any warnings during initialization.  The Micro-Manager version should be present in the original metadata table, and should be 2.0.x.  With this PR, the same test should show a warning indicating that the dataset is not officially supported.  The original metadata table should be the same as without this PR.
Datasets acquired with older versions of Micro-Manager should be unaffected; this can be checked with any of the datasets in ```curated/micromanager/public/```.
I wouldn't expect this to affect memo files, in which case it should be safe for a patch release.

Micro-Manager: warn if the dataset was acquired with >1.4.22

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

See https://trello.com/c/VzvQbYBf/14-incorrect-handling-of-similarly-named-oir-files
To test, use the files from QA 21577.  Without this PR, ```showinf -nopix R13L-S2-5_X20_ZOOM1_Z.oir``` should show that ```R13L-S2-5_X20_ZOOM1_Z_CONTROL.oir``` is in the used file list (despite being a separate dataset).  With this PR, ```showinf -nopix``` on either file should show only the selected file in the used file list.
Builds should remain green, and memo files should be unaffected so this should be safe for a patch release.  There is a workaround, though, so could certainly be deferred until after 5.9.1 if needed.

OIR: prevent current file from being overridden if it has the .oir extension

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#76](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/76/).
----
--no-rebase

Update POM version numbers to 5.9.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#77](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/77/).
----
--no-rebase

Update POM version numbers to 5.9.2-SNAPSHOT

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java

See https://trello.com/c/hvjosNYD/18-fake-resolutions
The ```resolutions``` key defines the total number of resolutions, so must be a positive integer.  By default, it is 1.  The ```resolutionScale``` key defines how ```SizeX``` and ```SizeY``` are calculated for each resolution; the sizes are divided by ```resolutionScale``` for each successively smaller resolution.  It must be greater than 1, and is 2 by default.
To test, try ```showinf``` with a few pyramids as indicated in the Javadoc.  Verify that unit tests continue to pass and that the new ```testPyramid*``` tests are being run.

Allow .fake files to represent a pyramid

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://trello.com/c/aNKCQ2Jf/520-gatan-dimensions-information-not-found
To test, use the .dm4 file in ```data_repo/curated/gatan/qa-21652```.  Without this change, ```showinf -debug``` should throw a ```FormatException``` as indicated on the card.  With this change, the same test should successfully initialize the file and read a single image.  The XYZCT dimensions and min/max values should match those of the .tif file in the same directory.
The images should also visually match, but it's probably easier to see when opening in ImageJ.  Note that the pixel types are different (float for .dm4, uint16 for .tif); that seems fine to me, but perhaps @mtbc can confirm if that is unexpected.
This should be safe for a patch release and should not introduce any build failures.

Gatan: handle empty tag type 23

---

components/formats-bsd/src/loci/formats/in/AVIReader.java

Backported from a private PR.  The original bug report indicated that AVI files acquired using software from Keyence (https://www.keyence.com/products/microscope/fluorescence-microscope/index.jsp?_ga=2.138499632.28338486.1533222430-676692882.1533222430) are unreadable due to an extra RIFF chunk at the end of the file which should be ignored.
To test, use ```data_repo/curated/avi/sample-avis/extra-chunk/HyperStack.avi```.  This is not real data, but simulates the extra RIFF chunk written by Keyence software (see the corresponding readme).
Without this PR, ```showinf -debug HyperStack.avi``` should throw the following:
```
loci.formats.FormatException: Sorry, AVI RIFF format not found.
at loci.formats.in.AVIReader.readChunk(AVIReader.java:548) ~[bioformats_package.jar:5.9.1-SNAPSHOT]
at …
```

AVI: skip RIFF chunks with FourCC != "AVI "

---

pom.xml

See https://trello.com/c/jyKnyYF8/5-review-ome-components-dependencies
This PR does not provide any obvious bug fix but updates the version of the low-level OME components to consume releases made in the last 6 months. In particular, this should ensure the contract of the Bio-Formats dependencies declared in its POM matches what is currently shipped by distributions like Fiji.
|  Component   |  Milestones |  Summary
|--------------|-------------|----------
| ome-common   | [5.3.3](https://github.com/ome/ome-common-java/milestone/4?closed=1) [5.3.4](https://github.com/ome/ome-common-java/milestone/5?closed=1) [5.3.5](https://github.com/ome/ome-common-java/milestone/6?closed=1) [5.3.6](https://github.com/ome/ome-common-java/milestone/7?closed=1) | Build updates, Javadoc improvements
| …

Components version bump

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Following an unrelated discussion on issue #2656 , I took a look at the list of objective ids for missing values.  This commit completes the list with the data from the latest version of softWoRx (version 7.0.0).
This commit also adds the name of the objective in front of the id as a comment which hopefully helps in finding issues in filling the correction type.  I was also confused about the calibratedmagnification, I'm not sure how to know if the magnification value is calibrated or not from the data on that file.

DeltavisionReader.java: complete objectives metadata from softWoRx 7.0.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#78](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/78/).
----
--no-rebase

Update POM version numbers to 5.9.2-rc1

---

components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Expands upon https://github.com/openmicroscopy/bioformats/pull/2851.  Backported from a private PR.
To test, use the following files:
```
data_repo/curated/zeiss-czi/nottingham/incorrect-colors/SIM SpinalChord2ch SeqFrame modeLongerExpo_OutResaved.lsm
data_repo/curated/zeiss-lsm/aaron-ostrovsky/ChaMARCM-F000015_Seg002.lsm
data_repo/curated/zeiss-lsm/greg/ChaMARCM-F000374_Seg002.lsm
data_repo/curated/zeiss-lsm/markus/CDW_3.mdb/CDW_3.mdb
data_repo/curated/zeiss-lsm/martin/051215-Dundee/051215-j-tf.mdb
data_repo/curated/zeiss-lsm/martin/sample files.mdb/XYZ-ch0.lsm
data_repo/curated/zeiss-lsm/martin/sample files.mdb/sample files.mdb
```
Without this PR, ```showinf -nopix -omexml``` on each should show that none of the channels beyond the first are colored white.  With this PR, the same test …

Zeiss LSM: explicitly detect SIM data for use in coloring channels

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#80](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/80/).
----
--no-rebase

Update POM version numbers to 5.9.2

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#81](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/81/).
----
--no-rebase

Update POM version numbers to 5.9.3-SNAPSHOT

---

components/test-suite/build.xml
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://github.com/openmicroscopy/data_repo_config/pull/321 and https://trello.com/c/q5mPwXHU/37-review-broken-pyramid-readers
The series table names should match the unflattened series/resolution
indexes.  The table data (SizeX, SizeY, physical sizes, ...) corresponds
to the metadata from a reader with flattened resolutions.  This updates
Configuration to allow the flattened-ness to be specified when setting
the active series or getting the series count.  By default, flattened is
true.  The unflattened pixels tests now check that the unflattened
reader's series count matches the configuration's unflattened series
count.
All of this means that readers that correctly report pyramids will have
passing tests, and readers that do not correctly report pyramids will
fail …

Fix configuration series table retrieval for pyramid detection

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java
components/formats-gpl/src/loci/formats/in/TrestleReader.java
components/formats-gpl/src/loci/formats/in/VectraReader.java

See https://trello.com/c/q5mPwXHU/37-review-broken-pyramid-readers and https://github.com/openmicroscopy/bioformats/pull/3208.
This should fix how pyramids are reported for NDPI, NDPIS (indirectly), Vectra QPTIFF, and Trestle.  Most of the test failures introduced in https://web-proxy.openmicroscopy.org/east-ci/job/BIOFORMATS-test-repo/205/ should be resolved.

Pyramid reader fixes

---

components/test-suite/build.xml
components/test-suite/src/loci/tests/testng/EquivalentPixelsTest.java

To run the test:
```$ ant -Dtestng.src=/path/to/file/A -Dtestng.check=/path/to/file/B test-equivalent```
This follows from https://github.com/openmicroscopy/bioformats/pull/3189 and the discussion in the formats meeting on 15 August.  I would expect the test to pass when comparing the original SVS or Leica SCN file noted on https://github.com/openmicroscopy/bioformats/pull/3189 with the OME-TIFF resulting from ```bfconvert``` (if lossless compression is used).  The test should fail when comparing an SVS/Leica SCN with a converted OME-TIFF that has lossy compression, or when comparing two files that are unrelated.
Depending upon how/where this needs to be run, a next step might be to allow all pairs of files to compared to be specified as either two files or one file with lines similar to …

Add test-equivalent target to compare the pixels in two files

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This prevents integer overflow when reading chunkmaps from files larger than 2GB.  See https://trello.com/c/UtugDbmG/258-nd2-incorrect-sizet-when-chunkmap-enabled; this is backported from a private PR.
To test, use the file in ```data_repo/curated/nd2/kyle-vrtis```.  Without this PR, ```showinf -nopix``` should detect 34 timepoints as noted in the original test on the card.  Opening the file in Nikon's NIS Elements will confirm that there should be 61 timepoints.
With this PR, ```showinf -nopix``` should detect 60 series (positions), 61 timepoints, and 2 channels.  The images should also match what NIS Elements shows.
This should be safe for a patch release assuming tests continue to pass, but I definitely would not expect it to be considered for 5.9.1 so feel free to exclude as needed.

ND2: use long arrays for storing intermediate offset data

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#82](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/82/).
----
--no-rebase

Update POM version numbers to 5.10.0-SNAPSHOT

---

components/formats-api/src/loci/formats/IFormatReader.java

See http://docs.openmicroscopy.org/bio-formats/5.9.2/developers/reader-guide.html
and https://trello.com/c/az76VODG/378-copy-detailed-docs-to-the-javadocs
This expands some of the Javadocs in ```IFormatReader``` to be more consistent with the reader guide.  There are no code changes, so testing only involves reviewing for correctness and formatting.

Update IFormatReader Javadocs to reflect the reader guide

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://github.com/openmicroscopy/bioformats/pull/3184#pullrequestreview-153797483
This just cleans up some duplicate code and documents the ```setupReader(boolean, boolean)``` method that actually constructs a reader.  There should be no change in test behavior, and all builds should continue to pass.

FormatReaderTest: refactor reader setup methods

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-gpl/src/loci/formats/in/DNGReader.java
components/formats-gpl/src/loci/formats/in/NDPIReader.java
components/formats-gpl/src/loci/formats/in/NikonReader.java
components/formats-gpl/src/loci/formats/in/SISReader.java

Backported from a private PR.  See #3200.
To test, use the files in ```data_repo/curated/tiff/bgriffen``` (same as linked from #3200).  Without this PR, ```showinf``` on any file should throw an ```ArrayIndexOutOfBoundsException``` and ```SizeT``` should be 2.  With this PR, the same test should show 2 series each with ```SizeT``` of 1.  The image for each series should be readable without an exception.
```tiffinfo``` on each file will confirm that there are two IFDs, both of which have a subfile type of 0 (i.e. neither is flagged as a thumbnail).  There doesn't appear to be any other metadata in the files to indicate that the second image should be ignored, even though it's pretty clearly just a thumbnail.
It's possible that this may introduce some build failures, as impact is difficult …

TIFF: split IFDs into separate series if the dimensions or pixel type mismatch

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

Backports 3 private PRs.  This improves file grouping and file-to-series mapping for multi-file datasets with and without a ```DICOMDIR``` file.
To test, use the following new datasets:
1. ```data_repo/curated/dicom/melissa/two-files-single-series``` (2 files)
2. ```data_repo/curated/dicom/melissa/two-files-two-series``` (2 files)
3. ```data_repo/curated/dicom/public/nema/Liver/DICOMDIR``` (```DICOMDIR``` + 183 files)
Datasets 1 and 2 are artificial datasets constructed as noted in the respective readmes.  Dataset 3 is directly copied from ftp://medical.nema.org/medical/dicom/DataSets/WG16/Philips/ClassicSingleFrame/Liver/
Without this PR, ```showinf -nopix 0.dcm``` for both datasets 1 and 2 should show 2 series and 3 used files (both datasets are grouped together, with one file omitted). …

DICOM file grouping fixes

---

components/formats-bsd/src/loci/formats/in/TiffDelegateReader.java

See https://trello.com/c/tEwJO09D/263-misleading-jai-error-message-on-corrupt-tiff
```TiffJAIReader``` should now only be used if ```setLegacy(true)``` is explicitly called or ```openBytes``` throws an ```UnsupportedCompressionException```.  See also https://trac.openmicroscopy.org/ome/ticket/4090
To test, use a corrupt TIFF (e.g. ```/ome/team/mlinkert/corrupt.tiff```) and a TIFF with unsupported compression (e.g. ```data_repo/curated/tiff/public/libtiff/fax2d.tif```).  Without this PR, ```showinf -debug corrupt.tiff``` will throw an exception indicating that JAI is missing.  ```xxd corrupt.tiff``` will confirm that there are only 4 bytes in the file (TIFF endian marker and magic bytes), so there is no way it could be initialized by any TIFF reader.  ```showinf fax2d.tif``` will throw …

Restrict use case for TiffJAIReader in TiffDelegateReader

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/MetamorphReader.java

The .scan extension seems equivalent to .nd by visual inspection. This is
reinforced by this Molecular Devices help page:
http://mdc.custhelp.com/app/answers/detail/a_id/19368/~/supported-file-formats

Add .scan extension to MetamorphReader

---

components/formats-gpl/src/loci/formats/in/ZeissTIFFReader.java

See https://trello.com/c/gJ2nQw9v/29-zeiss-tiff-distributed-failures and https://trello.com/c/FQlFqn62/30-axiovision-duplicate-paths-in-usedfiles
This removes a bunch of unused code from ```ZeissTIFFReader```, replaces use of ```CaseInsensitiveLocation``` with ```Location```, and fixes up the resulting file detection issues.
To test, use ```data_repo/curated/zeiss-tiff/qa-21570```.  Without this PR, ```showinf -nopix 250618_J1_diff_D3-2-0002.tif``` should show a used file list with ```250618_J1_diff_D3-2-0002.tif``` listed twice (as described in https://trello.com/c/FQlFqn62/30-axiovision-duplicate-paths-in-usedfiles).  With this PR, the same test should show a used file list with no duplicate entries.
Builds should remain green, and reverting the change to single-thread tests in …

ZeissTIFFReader cleanup

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#83](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/83/).
----
--no-rebase

Update POM version numbers to 6.0.0-m1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#84](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/84/).
----
--no-rebase

Update POM version numbers to 6.0.0-SNAPSHOT

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#85](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/85/).
----
--no-rebase

Update POM version numbers to 6.0.0-m2

---

pom.xml

The main change in this version is the Huffman table fix for images with multiple components (see https://github.com/ome/ome-codecs/pull/8)
Testing:
- Travis/Appveyor should pass and retrieve the latest version of the component
- CI tests should remain green including especially the `quicktime` filesets

Bump ome-codecs version to 0.2.3

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

Backported from a private PR.  Originally part of the same PR as https://github.com/ome/ome-common-java/pull/24 (prior to repo split).
Original use case was larger (~7000 plane) datasets acquired using the diSPIM plugin (https://micro-manager.org/wiki/ASIdiSPIM_Plugin).  I wasn't able to find a way to run a diSPIM acquisition without a connected instrument, so the closest test data is a 5000 T x 5 Z x 2 C multi-D acquisition with the relevant ```SPIMmode``` key added manually.
Complete dataset yet to be uploaded, so not ready for final testing.  Once uploaded, ```showinf -nopix 1.4-large-acq-take-2_1_MMStack_Pos0_metadata.txt``` without this PR or https://github.com/ome/ome-common-java/pull/24 will require ```BF_MAX_MEM``` to be at least 1200 MB.  With a build including both PRs, only 900 …

Micromanager: better handling of very large *metadata.txt files

---

components/formats-gpl/matlab/bfsave.m
components/formats-gpl/test/matlab/TestBfsave.m

This PR updates the MATLAB `bfsave` utility to improve the handling of compression types. The initial implementation was relying `ImageWriter.getCompressionTypes()` which behavior is modified by #3154.
This PR updates the `bfsave` logic to:
- construct a concrete writer using `ImageWriter.getWriter(outputPath)` similarly to e.g. `bfconvert`
- use the API of the concrete writer to access compression types or writer-specific properties
-  MATLAB tests running at https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-matlab/ should be passing
- Using MATLAB or GNUOctave, a couple of scenarios can be tested
* `bfsave(zeros(100,100,'uint8'), '/tmp/out.ome.tiff')` should create an OME-TIFF
* `bfsave(zeros(100,100,'uint8'), '/tmp/out.ome.xml')` should create an OME-XML 
* …

bfsave: do not use ImageWriter.getCompressionTypes() for input check

---

components/formats-api/src/loci/formats/ImageWriter.java

See https://trello.com/c/O5LkXtx0/29-imagewriter-compression-behaviour
Testing: Try `bfconvert -compression zlib` with and without both this PR and https://github.com/openmicroscopy/bioformats/pull/3153
- without both PRs, zlib compression will be allowed, but won't be used
- with https://github.com/openmicroscopy/bioformats/pull/3153 zlib compression will be allowed and will be used
- with this PR but without https://github.com/openmicroscopy/bioformats/pull/3153 zlib compression will be disallowed (tests it fails correctly if a codec is not supported by the chosen writer, but is supported by another writer and ends up in the combined codec list)
The combined codec list is the cause of the problem, and I'm unsure why it's required.  We don't have the same behaviour for any other features …

ImageWriter: Get compression types from the writer in use

---

.travis.yml

See https://changelog.travis-ci.com/stop-a-job-early-if-a-deprecated-jdk-is-configured-76612
Primarily opened against Bio-Formats however as reported recently, all Java components tested by Travis are currently affected by this issue and will need to be patched (see https://github.com/search?utf8=%E2%9C%93&q=user%3Aome+user%3Aopenmicroscopy+oraclejdk10&type=Code).
We have effectively a few options to keep pre-testing compilation on newer Java versions, switch to `openjdk10`, upgrade to `oraclejdk11` or upgrade to `openjdk11`.
Part of this choice might involve considerations about the new policy of Oracle to support shipping free JDK binaries 6 months post-release.

Switch to Oracle JDK 11 as Oracle discontinued JDK 10 support

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/CV7000Reader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Backported from a bunch of private PRs.  See https://trello.com/c/b0nFSUzZ/238-cv7000
To test, use 3 plates in ```/uod/idr/repos/curated/cv7000/glencoe/```.  For each, the ```.wpi``` file is the one to initialize (this is the main metadata file).  The ```DW 0001``` plate has 370 wells - standard 16x24 with D07, E12, H14, H21, I14, I24, J09, J18, K18, L17, L18, M02, P10, and P20 missing.  ```DW 0002``` is a single row (22 wells, H13 and H14 missing) and ```DW 0003``` is a single column (16 wells).  All three are single field, single T, single Z, and 4 channels (```DAPI, 488, 594, mitotracker```).  There are many more plates that cover a wider range of dimensions which could be transferred to ```data_repo```, but this requires coordination due to …

Initial CV7000 reader

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

This automatically prevents ```NumberFormatException```s for invalid double values and handles the case when the decimal separator in the file doesn't match the current locale's decimal separator.
To test, use ```curated/micromanager/pr-3253```, which was copied from ```curated/micromanager/qa-4984/```, but with ```0.5,``` replaced by ```"0,5",``` in ```metadata.txt```.  Without this PR, ```showinf -nopix -omexml metadata.txt``` will throw:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "0,5"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at java.lang.Double.<init>(Double.java:608) …
```

Micromanager: switch to DataTools.parseDouble for double parsing

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

Backported from recent private PR.  Coincidentally addresses at least part of #2811.
To test, use the file from QA 17671.  Without this PR, ```showinf -nopix -noflat``` should show 2 pyramids and no extra images.  ```showinf``` on any of the images should result in a weird pinkish image as documented in #2811.
With this PR, ```showinf -nopix -noflat``` should show 2 pyramids and an extra label image in series 2.  ```showinf``` on any of the images should show normal looking slide images with a white instead of pink background.  Leica/Aperio ImageScope can be used to verify that the images are valid.  Note that the slides are rotated 90 degrees from how they are presented in ImageScope; I don't see any obvious rotation metadata, so the reader doesn't deviate from the X and Y dimensions …

Leica SCN: improvements for Versa datasets

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/ConfigurationTree.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java
components/test-suite/test/loci/tests/testng/ConfigurationTreeTest.java

Fixes recent test issues noted in https://trello.com/c/9MJdfI8N/48-add-test-for-duplicate-used-files, https://trello.com/c/0MB0a98B/66-fix-test-config-to-correctly-generate-new-pyramid-configurations, and https://github.com/openmicroscopy/data_repo_config/pull/331
93a830f should make ```test-config``` work as expected with pyramid files in all formats.  To test, run ```test-config``` and then ```test-automated``` on a directory containing pyramid files in any format (I used a local copy of ```curated/svs/alexandra```) and verify that the tests fail.  Remove the generated ```.bioformats``` file(s), then run the same commands again and verify that the tests pass.
0019a42 and 9286409 from @sbesson add unit tests for ```ConfigurationTree.relocate*``` and e869843 fixes ```ConfigurationTree```, …

Data test updates

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Replaces https://github.com/openmicroscopy/bioformats/pull/3241 and includes the first two commits from https://github.com/openmicroscopy/bioformats/pull/3244.
All of the relevant differences from ```HarmonyReader``` are ported to ```OperettaReader``` in d8dc80d.  40cd547 and 8e8bb0e parses the ```OrientationMatrix``` tag, as noted in https://github.com/openmicroscopy/bioformats/pull/3244#issuecomment-432676269
Excluding for now since this will conflict with #3244. I can also close this and open a PR against https://github.com/sbesson/bioformats/tree/operetta_wellsampleposition, or we can close #3244 in favor of this (whichever is easier for review and IDR testing).

Update OperettaReader to include Harmony improvements

---

components/bio-formats-plugins/src/loci/plugins/config/libraries.txt

The `libraries.txt` file was pointing to some broken legacy URLs. I guess that link checking doesn't cover these.

Fix some plugin OME URLs.

---

pom.xml

This allows us to make use of the changes in 5.3.7 and 6.0.0-m1:
https://github.com/ome/ome-common-java/milestone/8?closed=1
https://github.com/ome/ome-common-java/pull/34
https://github.com/ome/ome-common-java/pull/35
https://github.com/ome/ome-common-java/pull/22
https://github.com/ome/ome-common-java/pull/27
https://github.com/ome/ome-common-java/pull/29
Especially relevant for continuing work on:
https://trello.com/c/spl6WleR/74-ome-tiff-pyramid-testing-phase-ii
https://trello.com/c/OimiHAQY/39-ome-common-profile-tiff-writing
https://trello.com/c/Fig1abYV/239-lif-parsedouble-exception

Upgrade ome-common to 6.0.0-m1

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

Prevents warnings of the form:
```
ome.xml.model.WellSample@557caf28 reference to Image:1 missing from object hierarchy.
```
Files converted without this change cannot be imported into OMERO.

ImageConverter: Remove plates when series is chosen

---

components/bio-formats-tools/src/loci/formats/tools/GenerateCache.java
components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/src/loci/formats/tools/ImageInfo.java
components/bio-formats-tools/src/loci/formats/tools/TiffComment.java

See https://trello.com/c/ko5vYYZ7/35-bfconvert-help-review
This PR primarily reviews the usage of `bfconvert` to list the available list of extension/formats as well as compression schemes for relevant file formats.
Additionally, the upgrade check is skipped if the usage is displayed e.g. when calling `bfconvert` without argument and the utility usage is printed directly to to the stdout independently of the logger level (see https://trello.com/c/FHWeDznP/53-cli-systemout-vs-logging). Similar changes are applied to the other utility classes (`showinf`, `gen-cache`, `tiffcomment`)

ImageConverter: usage extension

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#88](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/88/).
----
--no-rebase

Update POM version numbers to 6.0.0-m3

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

See https://trello.com/c/Fig1abYV/239-lif-parsedouble-exception
All usage of ```new Double``` and ```Double.parseDouble``` in ```LIFReader``` should now be replaced by ```DataTools.parseDouble```.
```showinf curated/leica-lif/qa-21092/1-GBP1-CaaX+LLoMe.lif``` without this PR should throw ```NumberFormatException``` as noted in the Trello card.  The same test with this PR should result in successful reading.
I would expect all tests to pass without configuration changes; memo files should be unaffected.

LIF: unify double parsing to use DataTools.parseDouble(...)

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java
components/formats-bsd/test/loci/formats/utests/out/WriterUtilities.java

b65d8c5 adds a unit test that will save TIFFs in memory with various combinations of endianness, compression, and dimensions.  The test setup is identical to the existing test for writing TIFFs to disk.
With b65d8c5 alone, ```ant test``` or ```mvn``` in ```components/formats-bsd``` should fail.
0c14653 fixes all test failures.  The change to ```TiffWriter``` resolves an issue with writing a single little endian plane; the remaining changes are required for writing multiple planes in memory.  With both commits, ```ant test``` or ```mvn``` in ```components/formats-bsd``` should pass.
Note that only a subset of the tests are run by default; setting ```testng.runWriterSaveBytesTests``` to 100 will run everything.  I did do this locally and all tests passed, but …

Fixes for writing TIFF files in memory

---

components/formats-bsd/src/loci/formats/in/MicromanagerReader.java

This issue was raised in forum thread https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8641&p=20331#p20331
A sample file is available in QA-27124
The thread covers 2 issues:
- The values stored in the metadata when exported from MicroManager differ from those expected. This will need resolution for the MicroManager team
- When opening the OME-TIFF the colors are read from the OME-XML and display correctly based on the stored values. When opening via the metadata file the MicroManagerReader is used and the colors are not stored resulting in different behaviour.
This PR covers the second scenario and should result in the same colors being populated and displayed when opening via either the ome.tiff or the metadata file.
Note the change to remove line 753 was due to it …

MicroManager: Store channel colors consistent with metadata

---

ant/java.xml
ant/package-list
components/bundles/bioformats_package/build.xml

See https://github.com/openmicroscopy/bioformats/pull/3172#issuecomment-412448699
A previous switch to imagej.net had been conflating with other issues related to the CI environment. As  the connection to imagej.nih.gov seems to be frequently flaky in the morning, trying to switch again to imagej.net as the canonical location for the ImageJ API.

Use imagej.net URL for ImageJ Javadoc

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

We currently use properties to allow component versions to be overridden for testing or other purposes.  This PR extends this to the `groupId` property for the ome-model jars.  These properties:
- `ome-model.version`
- `ome-model.group`
may be set on the command-line for both Maven and Ant builds to allow the use of ome-model jars other than the default.  The default behaviour remains unchanged.
Examples of group usage:
```
ant -Dome-model.version=5.6.2 -Dome-model.group=org.openmicroscopy clean jars tools test
mvn -Dome-model.version=5.6.2 -Dome-model.group=org.openmicroscopy
ant -Dome-model.version=5.7.1 -Dome-model.group=net.codelibre clean jars tools test
mvn -Dome-model.version=5.7.1 -Dome-model.group=net.codelibre
```
My intention is to use this with the CI jobs such as [this …

maven: Allow ome-model groupId to be settable via a property

---

.travis.yml
ant/global.xml
ant/java.xml
components/bio-formats-plugins/build.properties
components/bio-formats-plugins/src/loci/plugins/util/LibraryChecker.java
components/bio-formats-tools/build.properties
components/bundles/bioformats_package/build.xml
components/forks/turbojpeg/build.properties
components/formats-api/build.properties
components/formats-bsd/build.properties
components/formats-gpl/build.properties
components/test-suite/build.properties
config/BFSourceFormat.xml
pom.xml

See https://github.com/ome/ome-common-java/blob/v6.0.0-m2/NEWS.md#600-m2-2018-11-30 for the list of changes
Also disables `openjdk7` on Travis and switch to Java 8 as the minimum version.

Bump ome-common to 6.0.0-m2

---

components/formats-gpl/src/loci/formats/in/AFIReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java

This updates ```AFIReader``` to more closely mirror ```SVSReader```, updates image names to use the same format as https://github.com/openmicroscopy/bioformats/pull/3094, and fixes exposure time and channel name metadata.
SVS tests should continue to pass with no configuration changes.  AFI files require updated configuration; the main things to check using any ```.afi``` from ```curated/afi/samples``` are:
* ```showinf -nopix file.afi``` and ```showinf -nopix -noflat file.afi``` show the same series counts and dimensions as ```showinf -nopix file_xyz.svs``` and ```showinf -nopix -noflat file_xyz.svs```
* ```showinf -nopix -omexml file.afi``` shows plausible exposure times - less than 1 second with this change, compared with hundreds of seconds with develop
* …

Improve AFI and SVS metadata

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This is in relation to trying to address performance issues, see https://trello.com/c/OimiHAQY/39-ome-common-profile-tiff-writing and https://github.com/ome/ome-common-java/pull/15
As shown in https://github.com/ome/ome-common-java/pull/15 the problem lies in the repeated calling of setLength on RandomAccessFile.
The issue originally thought to be a Windows issue looks like it may be related to Java versions with RandomAccessFile.setLength being much slower on Java 10 (see https://stackoverflow.com/questions/50450317/randomaccessfile-setlength-much-slower-on-java-10-centos for some info)
In Java 8 setLength does:
```
[pid 49027] ftruncate(23, 53248)        = 0
[pid 49027] lseek(23, 0, SEEK_SET)      = 0
[pid 49027] lseek(23, 0, SEEK_CUR)      = 0
```
While in Java 10 it introduces the …

TiffSaver: Only setLength of output file once

---

.gitignore
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

The writeImage method in TiffSaver does a byte-by-byte copy from the input buffer to the strip buffers, often in non-sequential order (because of interleaving).  I replace this with bulk array copies if the buffers are determined to be of equivalent widths and bit depths.
This work was motivated by the desire to speed up image format conversions for image files in excess of 50GB. In conjunction with additional changes in ome-codecs and ome-common-java, I have achieved a geometric to linear time asymptotic improvement, plus another ~30% speed improvement of just the linear time cost. The patch for ome-codecs and ome-common-java have already been submitted.
Separately, I am in the process of re-working writeIFD to consolidate buffering and file writes, but that isn't fully baked, yet. …

Speed up TiffSaver.writeImage with bulk array writes

---

components/formats-api/src/loci/formats/FormatWriter.java
components/formats-api/src/loci/formats/IFormatWriter.java
components/formats-bsd/src/loci/formats/out/TiffWriter.java
components/formats-bsd/test/loci/formats/utests/out/TiffWriterTest.java
components/formats-bsd/test/loci/formats/utests/out/WriterUtilities.java

This PR is in response to https://trello.com/c/U9gw1uKc/89-tiling-api-tile-size-image-size
The request was to allow the full image size to be a valid tile size.
Without this PR:
- By default tileSizeX is the image width and tileSizeY is the image height
- These default tile sizes indicate that tiling is not being used
- A tileSize of 0 is invalid and throws an exception
With this PR:
- The default tile sizes are now 0
- A tileSizeX of the image width and tileSizeY of the height are valid sizes and tiling will be used
- A tileSize of 0 is valid and indicates that tiling is not being used
I don't believe there is any need to update the tiling developers page at https://github.com/ome/bio-formats-documentation/blob/9bc5d24a4b3a328f36ca8fd4b668bdc731cffa7e/sphinx/developers/tiling.rst

Update default tile size to 0

---

components/formats-api/src/loci/formats/WrappedReader.java
components/formats-bsd/src/loci/formats/FilePattern.java
components/formats-bsd/src/loci/formats/in/FilePatternReader.java

These commits are extracted from https://github.com/openmicroscopy/bioformats/pull/3250 and are intended to support the development of external wrapped readers by moving most of the helper methods out of `FilePatternReader` and into a new `WrappedReader` class.
These commits should result in no changes to the behaviour of `FilePatternReader`. Several arguable improvements could be made to `FilePatternReader` by taking advantage of `WrappedReader`:
- Pass `IMetadataConfigurable` methods to the helper (it is unclear whether this was intentionally omitted from the current `FilePatternReader` class)
- Construct the helper object in `initFile` and call `callDeferredSetters` instead of creating the helper in the class constructor. This would make the class more robust to other future wrappers …

Refactor FilePatternReader into a generic WrappedReader

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

See https://trello.com/c/Qk6NBnPs/92-imagej-ome-tiff-writing-performance
cb82e22 fixes the immediate issue by omitting lookup table saving for any plane that has a default grayscale lookup table.  6e57191 adds an option to always omit lookup tables, which is ```false``` by default.
To test, run this macro:
```
run("Mitosis (26MB, 5D stack)");
// resulting file should be 35 MB
run("Bio-Formats Exporter", "save=macro-no-lut-no-save.ome.tiff do_not_save_lookup_tables compression=Uncompressed");
// resulting file should be 35 MB
// not disabling LUTs doesn't matter here since every plane has the default grayscale LUT
run("Bio-Formats Exporter", "save=macro-no-lut-save.ome.tiff compression=Uncompressed");
// explicitly change the LUT for every plane
run("Thallium");
// resulting file should be …
```

ImageJ exporter: skip grayscale LUTs and allow non-gray LUTs to be omitted

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#90](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/90/).
----
--no-rebase

Update POM version numbers to 6.0.0-m4

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/formats-gpl/src/loci/formats/services/JPEGXRServiceImpl.java

See QA 27169.
The code in the QA issue indicates that several tiles in the lower right corner of the largest image (the file contains a pyramid) cannot be read.  Checking the actual compressed bytes in each tile indicates that a JPEG-XR stream is present, but invalid.  One example is the tile whose upper left corner is (23216, 38012).  Opening the file in ZEN reliably produces this error the first time the mouse is moved over one of the affected tiles:
Subsequent mouse-overs show pixel values of 0 for the last channel.
With this change, the test code in QA and reading affected tiles via ```showinf -crop``` should all work without an exception being thrown.  The wrapped ```ome.jxrlib.FormatError``` should be logged at ```WARN```, though, so it's clear that decodes were not successful.
The …

Zeiss CZI: handle invalid JPEG-XR tiles

---

components/formats-gpl/matlab/bfGetPlane.m

The original code contains a transpose operation `'` for unsigned integer images (i.e. most image files). This transpose incurs a data copy that is not necessary. This commit avoids this data copy by using the Java method `makeDataArray2D` also for unsigned int images, the resulting 2D array is reshaped to a vector to call `typecast`, and then reshaped back (reshaping does not copy data).

Simplified bfGetPlane.m, avoids a data copy

---

components/bio-formats-plugins/src/loci/plugins/out/Exporter.java

See https://github.com/openmicroscopy/bioformats/issues/3127
Both the physical sizes and units are now taken from the ImagePlus' Calibration.  This should have no impact on the common case where physical sizes are unchanged after import, but should fix the case when units are changed after import.
To test, make sure that the original bug is fixed by running the macro in https://github.com/openmicroscopy/bioformats/issues/3127 with this change.  ```showinf -omexml``` on the resulting file should also confirm that the correct physical sizes are stored.  Also test with line 12 of the macro commented out (the first ```run("Properties..." ...```) and uncommented but with a unit that obviously cannot be mapped to an OME unit (I tried ```unit=december```).  Opening files using the Bio-Formats …

ImageJ export: preserve physical size units

---

components/formats-gpl/src/loci/formats/in/BrukerReader.java

Backported from private PRs.  This allows dimensions to be parsed from the optional (but usually present) ```d3proc``` file.  In case of a mismatch between the ```d3proc``` and the ```acqp```, the ```d3proc``` is preferred.  See also http://imaging.mrc-cbu.cam.ac.uk/imaging/FormatBruker
An artificial test dataset is in ```curated/bruker/samples/dimension-mismatch/```.  This is the result of copying the dataset in ```curated/bruker/wis/RA_060110.051/1/``` and modifying line 30 of ```acqp``` to be ```##$NR=5``` (instead of ```##$NR=1```).
Without this PR, ```showinf -nopix curated/bruker/samples/dimension-mismatch/1/acqp``` should show 3 Z sections and 5 timepoints, each of which is 128x128 and 16 bit.  The pixels file is ```curated/bruker/samples/dimension-mismatch/1/pdata/1/2dseq```, …

Bruker: parse dimensions from d3proc file when available

---

components/formats-gpl/src/loci/formats/in/CV7000Reader.java

An arbitrary number of channels can be defined in the ```MeasurementDetail.mrf``` file, and only a subset may be referenced by each field.  This changes how channel counting and indexing is done to look
at the total number of unique channels in a field, instead of the total number of unique channels across all fields/wells.
See https://trello.com/c/b0nFSUzZ/49-cv7000
To test, use the ```Test-plate-1.wpi``` referenced on the card (configuration PR forthcoming).  Without this change, ```showinf -nopix Test-plate-1.wpi``` should show 10 channels.  This is because 10 channels are defined in the corresponding ```MeasurementDetail.mrf```, and the specific subset used varies by field.
With this change, the same test should show 5 channels in each series, which matches the number of unique …

CV7000: fix channel indexing when the stored indexes do not match the count per field

---

components/formats-gpl/src/loci/formats/in/PyramidTiffReader.java

See https://trello.com/c/2BwFsSmS/95-broken-pyramidtiffreader-reader
To test, use any of the files from ```/uod/idr/filesets/idr0053-faas-virtualnanoscopy/20181128-ftp```.  Without this change (on develop), ```showinf -nopix -noflat -omexml``` should show multiple series none of which have a subresolution.  With this change, the same test should show a single series with multiple subresolutions; the ```Image``` count in the resulting OME-XML should be 1.
One of the smaller files has been configured and copied to ```curated/pyramid-tiff/idr0053/MEFS_cryo.tif``` for automated testing.

PyramidTiff: fix subresolution recording

---

components/formats-gpl/src/loci/formats/in/LiFlimReader.java

Big files gave an integer overflow on line 191.

Solve error for big .fli files

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Without this PR, if any plane was not covered by a ```TiffData```, then all ```TiffData``` information was thrown out and the plane count for the current ```Image``` was reset to the IFD count of the current file.  That's not unreasonable for single file datasets, but when multiple files are present this can be problematic.  ece2e8d describes the original use case as MicroManager-acquired data, where the datasets may contain multiple files that are split at 4GB so a single file does not neatly map to a single ```Image```, Z section, timepoint, etc.
A simpler example that demonstrates the problem is in ```curated/ome-tiff/samples/missing-planes```.  This was generated via ```bfconvert -option ometiff.companion test.companion.ome test&sizeZ=10.fake …
```

OME-TIFF: rework how missing planes in TiffData are handled

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

See:
https://trello.com/c/NFuiPd4s/45-large-tiff-0-pixel-value
https://trello.com/c/7pSOeMJF/46-big-tiff-breakage-in-571
https://trello.com/c/fKOcj8sd/47-tiff-incorrect-fillorder
and in particular rationale for this change in https://trello.com/c/fKOcj8sd/47-tiff-incorrect-fillorder#comment-5c1aca32a935af64b5348fb2
Test files are ```curated/tiff/darwinjob/SESSION4_Image2.tif```, ```curated/tiff/qa-20514/819_2.tif```, and ```/ome/team/mlinkert/tiff-fill-order/stephane-dallongeville/716_2.tif``` (not copied due to permissions issues).  All have large XY dimensions, and should be completely black without this PR.  With this PR, all should look like regular whole slide images with white backgrounds.

TIFF: ignore FillOrder unless uncompressed or fax compressed

---

components/formats-bsd/src/loci/formats/in/DicomReader.java
components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-gpl/src/loci/formats/in/CV7000Reader.java
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/MRCReader.java
components/formats-gpl/src/loci/formats/in/MicroCTReader.java
components/formats-gpl/src/loci/formats/in/OperettaReader.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This should reduce the number of compiler warnings, especially in ```formats-gpl```.  Builds should continue to pass and there should be no change in behavior.
Not critical for 6.0.0, these were just annoying while working on https://trello.com/c/5JvwTpLa/6-formattools-refactorings.

Fix some deprecation warnings in formats-bsd and formats-gpl

---

components/formats-gpl/src/loci/formats/in/ND2Handler.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

See https://trello.com/c/UnDryDi9/113-fix-exposure-times-for-control003nd2
https://github.com/openmicroscopy/data_repo_config/pull/353 updates the configuration for public QA 9507 to match the expected ground truth as recorded in https://github.com/openmicroscopy/bioformats/pull/3292#issuecomment-448717313
Exposure times are defined multiple times in multiple places.  This reduces the duplicates so that consecutive times correspond to consecutive channels, and handles the case when the exposure time list is larger than the ```SizeC``` for a single series, but smaller than the sum of ```SizeC``` for all series.
Not sure if this will cause any other test failures, but will keep an eye on tomorrow's build.  If there are additional test failures, it's possible that the configurations would …

ND2: fix handling of duplicate and incomplete exposure time lists

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://github.com/openmicroscopy/bioformats/issues/3188 and QA 21647.
To test, use the file in ```curated/gatan/qa-21647/```.  Without this change, ```showinf -debug``` should throw an ```ArrayIndexOutOfBoundsException```.  With this change, ```showinf -normalize -omexml``` should correctly display the image and OME-XML.

Gatan: allow ROIs to be stored in DocumentObjectList groups

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/MRCReader.java

4b771c5 backported from a private PR; 7cdaac0 added to fix test failures.   See the definition of offsets 196-216 in https://bio3d.colorado.edu/imod/doc/mrc_format.txt.  New style headers have an explicit endianness marker, but old style headers do not.
To test, use the file ```mrc/gh-3297/old-header/```, which was hand-created from an existing sample file (see the readme).  Without this change, ```showinf -nopix``` should throw ```UnknownFormatException```.  With this change, ```showinf -normalize``` should result in the file being detected as MRC, with sensible looking pixel data displayed.
While ```mrc/gh-3297/old-header``` has a little-endian example with an old style header, ```mrc/samples/golgi.mrc``` is a big-endian example with an old style header - so we do have to handle both …

MRC: fix endian detection in isThisType for old style headers

---

components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java
components/test-suite/src/loci/tests/testng/TestTools.java

Prior to this change, any file for which ```isThisType``` did not return true in at least one reader would have been removed from the list of tests.  This meant that regressions affecting ```isThisType``` (especially on non-TIFF readers) were not necessarily detected.
I encountered this issue while in the process of backporting a private PR affecting ```MRCReader```, but it's fairly easy to test even with fake files.  To set up (without this change):
```
$ mkdir $TEST
$ touch $TEST/test.fake
$ ant -Dtestng.configDirectory=$TEST -Dtestng.directory=$TEST test-config
$ touch $TEST/unreadable-file.txt
$ ant -Dtestng.configDirectory=$TEST -Dtestng.directory=$TEST test-automated # this should pass
$ ant -Dtestng.configDirectory=$TEST -Dtestng.directory=$TEST test-automated # this should still …
```

Fix tests to fail when a configured file throws UnknownFormatException

---

components/formats-api/src/loci/formats/CoreMetadata.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

To test, use any pyramid .czi file, e.g. ```curated/zeiss-czi/zeiss/jpeg-xr/a)BF-1scene-nozstack-compression85%.czi```.  Without this PR, examine the original metadata for series 0 with ```showinf -nopix```.  There should be hundreds of keys such as ```Positions|Series 03| #041: 0```, one per tile in each pyramid resolution.  All values for a given series should be equal, and the table for a single series contains the keys for every series.
With this PR, the same test should show a single key in the series original metadata table; nothing else should change.
74d5dac fixes a bug in ```CoreMetadata``` that causes the original metadata tables to be the same for every series.  21f4525 follows on from https://github.com/openmicroscopy/bioformats/pull/2600#issuecomm …

CZI original metadata reduction

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

This prevents an empty ROI from being created when an unsupported shape
type is encountered.  See https://github.com/openmicroscopy/data_repo_config/pull/368#issuecomment-460278230
Without this change, ```showinf -nopix -omexml gatan/emdb/BGal_000438_frames.dm4``` should result in invalid OME-XML due to an empty ROI.  With this change, the OME-XML should be valid with no ROI present (but the unsupported shape type should still be logged).
It's probably worth checking at least a couple of other files that use ```GatanReader```, since this case is not covered by the usual repo tests.  See follow-up test improvement card: https://trello.com/c/iyrJ7nL3/326-allow-metadataoptions-to-be-configured-in-repo-tests

Gatan: do not create empty ROIs

---

components/formats-bsd/src/loci/formats/ChannelSeparator.java
pom.xml

Backported from unmerged private PR.  Uses https://github.com/ome/ome-model/pull/88.
To test, use a file with RGB data and more OME-XML Channel metadata than just a name.  I used ```curated/zeiss-czi/silke/White_574.czi```, but brightfield datasets in most of the WSI formats would work too.  Without this change, ```showinf -nopix -noflat -omexml -separate``` should show one ```Channel``` per original RGB component.  The names of all ```Channel```s in an ```Image``` should be the same, but only the first will have things like wavelengths, detector references, etc.
With this PR, ```showinf -nopix -noflat -omexml -separate``` should show that all ```Channel```s in an ```Image``` are identical apart from the ID.
This could impact OMERO imports, so it probably makes sense to also test a few …

ChannelSeparator: copy all channel metadata instead of just names

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#92](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/92/).
----
--no-rebase

Update POM version numbers to 6.0.0-rc1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#94](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/94/).
----
--no-rebase

Update POM version numbers to 6.0.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#95](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/95/).
----
--no-rebase

Update POM version numbers to 6.0.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

Closes #3282 
Automated tests for Hamamatsu NDPI should remain green incl. the validation of wavelength for existing NDPIS datasets.
The new supplied dataset in #3282 should now open with Bio-Formats: two channels have no emission wavelength while the Cy5 and Trtc channels have an emission wavelength metadata.

NDPISReader: handle variants where a constituent NDPI has no wavelength

---

components/formats-gpl/src/loci/formats/in/ImspectorReader.java

This was reported in http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2019-February/004320.html and can be tested using QA-27309
With the QA file the value of "xyz-Table Z Resolution" is "false", which throws a NullPointerException when parsing the value. This PR adds a check for the null pointer and ignores the value.
To test, use QA-27309, with this PR included the file should open and display without any exception being thrown.

MSR: Add null pointer check for "xyz-Table Z Resolution"

---

components/formats-bsd/src/loci/formats/in/NRRDReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

To test, use the dataset in ```curated/nrrd/public/midas/``` (public data from http://hdl.handle.net/1926/1687).  Without this change, ```showinf 01011-dwi.nhdr -range 0 100``` should throw an ```UnknownFormatException``` in ```openBytes```.  With this change, images should be read without an exception and performance of both ```setId``` and ```openBytes``` should be tolerable.
Memo files should be unaffected and all tests should continue to pass, so this should be safe for a patch release if necessary.

NRRD: add support for raw GZIP-compressed data files

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

Backported from private PR; opening to check test impact, but not expecting this to be included in 6.0.0 (can exclude after one test run if needed).
This ensures that the file path is normalized, so that the file
separators will be the same across all files.  This prevents weird
problems on Windows where passing ```/path/to/file.oir``` throws an
exception but ```\path\to\file.oir``` is fine.
Without this PR and any single-file .oir on Windows:
```
PS E:\tmp>./showinf ./file.oir
```
should throw an exception but ```./showinf .\file.oir``` should successfully read all planes.
With this change, both tests should successfully read all planes.
The incorrect behavior is more immediately obvious in Git Bash, since tab-completing the file name uses ```/```, while tab-completing in PowerShell …

Olympus OIR: compare absolute file paths when reading pixels files

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

This ensures that any TIFF tile with an invalid offset or byte count of 0 will have pixel values set to 0.  Without this change, the tile would have been filled with data from the previously read tile, so the pixel values would have varied depending upon the order in which the tiles were retrieved.
To test, use ```curated/svs/alexandra/UMD001_ORO.svs```.  Compare the images shown by these two commands with and without this PR:
```
$ showinf UMD001_ORO.svs -crop 0,10500,512,541 # bottom 541 pixels
$ showinf UMD001_ORO.svs -crop 0,11040,512,1 # bottom 1 pixel
```
The second command should always show pixel values of 0.  The first command without this PR will show that the bottom row of pixels are not 0; with this PR they should all be 0.
See also …

TIFF: clear buffer before returning when tile byte count or offset is invalid

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-bsd/test/loci/formats/utests/tiff/TiffTileReadingTest.java

If multiple tiles need to be read, then direct copying would have resulted in invalid images.  This bug was only exposed in cases where multiple tiles were read along X, but the requested image width matched the tile width.  Any tiled TIFF can be used to test, but SVS files are the most obvious choice.
Without this change:
- ```showinf svs/alexandra/UMD001_ORO.svs -crop 0,0,240,240``` should look correct
- ```showinf svs/alexandra/UMD001_ORO.svs -crop 10,0,240,240``` should have 10 rows of black pixels at the bottom of the image
- ```showinf svs/alexandra/UMD001_ORO.svs -crop 10,0,239,240``` should look correct
With this change, all 3 tests above should result in correct images.  
edc8d5c alone combined with develop should result in a unit test failure. …

TIFF: restrict direct tile copying to cases where only one tile is read

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

c3161bc fixes a subtle bug in tag parsing that resulted in some metadata being missing or incorrect.  The ```cellsens/olivier/small-tiles/``` dataset should be the only one impacted by this change (see forthcoming configuration PR with screenshots).
The remaining two commits expand support for .vsi files that do not have associated .ets files.  Affected files are:
```
cellsens/samples/Channels/Composite.vsi
cellsens/samples/Count & Measure/Cell Multichannel-z-stack corr..vsi
cellsens/samples/Count & Measure/Cell Multichannel-z-stack.vsi
cellsens/samples/Fluorescence/Dako_CISH.vsi
cellsens/robert/Lung_Mite.vsi
```
In all cases, ```showinf``` should show that the first series is the same with or without this PR.  With this PR, all files should have at least one …

CellSens: fixes for tag parsing and single-file datasets

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#96](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/96/).
----
--no-rebase

Update POM version numbers to 6.0.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#97](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/97/).
----
--no-rebase

Update POM version numbers to 6.1.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/CellVoyagerReader.java
components/formats-gpl/src/loci/formats/in/ScanrReader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://trello.com/c/c9PwJFcK/284-add-configuration-keys-for-hcs-metadata
HCS/SPW datasets are now required to have ```Plate```, ```PlateAcquisition``` (if present), ```Well```, ```WellSample```, and ```WellSample``` position (if present) values configured.  ```test-config``` will generate these values as appropriate.
The test should fail if configured values do not match actual values, or if the reader's ```MetadataStore``` has at least one ```Plate``` that has at least one ```Well``` with at least one ```WellSample``` and any ```Image``` is not linked to a ```Plate```.  This seems fine for most readers, but breaks down for:
- ```ome-tiff/ome-schemas/2010-06/one-screen-one-plate-four-wells.ome.tiff```
* none of the ```WellSample```s have an ```ImageRef```, so no ```Image```s linked …

Add test for HCS metadata

---

components/formats-bsd/pom.xml
components/test-suite/pom.xml

Brings Bio-Formats' perf4j up to the one OMERO needs so as to align them.
Does not address the larger issue that we should be using some other library.

bump perf4j up from 0.9.13 to 0.9.16

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-gpl/src/loci/formats/in/HamamatsuVMSReader.java
components/formats-gpl/src/loci/formats/in/HitachiReader.java

See https://trello.com/c/4tlJlMuC/339-fake-ini-handling-leads-to-spurious-header-key
To test, use a simple dataset like this:
```
$ cat test.fake.ini
[GlobalMetadata]
foo = bar
$ touch test.fake
```
Without this PR, ```showinf -nopix test.fake``` should show two key/value pairs in the global metadata table: ```foo: bar``` and ```header: GlobalMetadata```.  With this PR, only ```foo: bar`` should be present.
Should be safe for a patch release if needed, and very low priority.

Fake: remove "header" key from original metadata

---

components/formats-bsd/pom.xml
pom.xml

@sbesson points out that there is no need to depend on Guava again in Bio-Formats and have to keep versions matching.

Use Guava from OME Common Java.

---

components/formats-bsd/src/loci/formats/in/ICSReader.java

This fixes the issue reading .ics/.ids files written by SVI Huygens, discussed [here on the forum](https://forum.image.sc/t/bio-formats-fails-reading-single-channel-ics-ids-dataset-written-by-svi-huygens/23868?u=imagejan) and on [this trello card](https://trello.com/c/xQW1FyGQ).

ICSReader: safeguard against unitIndex growing too large

---

components/formats-gpl/pom.xml

See https://github.com/scijava/pom-scijava/issues/87
Initially opening to assess the impact of the `jhdf5` dependency bump to the latest patch release.

Upgrade jhdf5 dependency to version 14.12.6

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#98](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/98/).
----
--no-rebase

Update POM version numbers to 6.1.0-m1

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

This has been raised in thread https://forum.image.sc/t/problems-opening-olympus-oir-files-using-bio-formats/24747/2 (which contains a sample file for download) and https://github.com/openmicroscopy/bioformats/issues/3242 
The issue shows up when loading a timepoint from 1000 onwards which would return an empty frame and `[WARN] No pixel blocks for plane #1000`

OIR: Allow more than 1000 time-points

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Thumbnail files with a UUID in the file name may be of the form
```<plate name>_<dimensions>_thumb<UUID>.tif```, not
```<plate name>_<dimensions>_thumb_<UUID>tif```.  Checking the index of
```_thumb``` in the file name catches both cases.
To test use ```curated/cellworx/samples/thumb-test``` (copied from ```curated/cellworx/public/idr0005```, with TIFF files renamed).  With this PR, ```showinf -nopix 2011-04-19-plate-1.HTD``` should throw an exception:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
at loci.formats.in.CellWorxReader.getTiffFiles(CellWorxReader.java:788)
at loci.formats.in.CellWorxReader.initFile(CellWorxReader.java:346)
at loci.formats.FormatReader.setId(FormatReader.java:1389)
at …
```

CellWorX: ignore files that contain "_thumb"

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

Fixes #3359 
There is no obvious rationale for keeping this constructor private and there are examples of downstream code working around the private scope - see https://github.com/spacetx/spacetx-writer/blob/0.1.1/src/main/java/spacetx/FOVTool.java#L430.
In addition to publicizing the constructor, this PR adds a minimal unit test showing the creation of the `ImageConverter` class

Make ImageConverter public

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

If ```setWritingSequentially(true)``` was not called on the ```TiffSaver```, then writing each
resolution of a pyramid in order caused the previous resolution's
dimensions to be used.  This updates the IFD reuse logic so that only
tags which are not present in the ```ifd``` argument are reused.  Use cases
where ```setWritingSequentially(true)``` is called will not be affected.
This should fix https://github.com/ome/bio-formats-examples/issues/48

TIFF: don't assume all IFDs have same XY size during non-sequential write

---

components/formats-gpl/build.xml
components/formats-gpl/pom.xml

Re-opening the effort started in https://github.com/openmicroscopy/bioformats/pull/2938 - see also https://trello.com/c/VrpWk1Fj/119-netcdf-review and discussions in https://github.com/openmicroscopy/bioformats/pull/2928.
At the Bio-Formats level, the primary expectation is that automated tests keep passing especially for all readers using the netcdf service (Minc, Imaris HDF, Veeco). Additionally, this should address known issues with some Imaris IMS files so new files should be included in the testing.
As noted on the previous effort, the biggest known impact might still be at the level of the Bio-Formats/OMERO coupling. Lots of effort are currently put into improving the OMERO 5.5 Java build system and reviewing Java dependencies across the stack …

NetCDF upgrade

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#100](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/100/).
----
--no-rebase

Update POM version numbers to 6.1.0-m2

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

.rcpnl files use a format nearly identical to Deltavision, but the timepoint field is assumed to represent the stage position count.  This was handled by existing logic when the stage positions formed a uniform grid, but we are now encountering files where the Y positions in a row or X positions in a column vary slightly.
To test, copy/symlink ```curated/deltavision/samples/lung-lentiCMtriple-4_R3D.dv``` to ```lung-lentiCMtriple-4_R3D.rcpnl```.  ```showinf -nopix lung-lentiCMtriple-4_R3D.rcpnl``` without this PR will be identical to the same command with ```lung-lentiCMtriple-4_R3D.dv```.  With this PR, the results for ```lung-lentiCMtriple-4_R3D.dv``` should be unchanged, but for ```lung-lentiCMtriple-4_R3D.rcpnl``` there should be 6 series each with 1 …

Assume that all .rcpnl files have one timepoint

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#102](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/102/).
----
--no-rebase

Update POM version numbers to 6.1.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#103](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/103/).
----
--no-rebase

Update POM version numbers to 6.1.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaHandler.java

Bioformats incorrectly loads elliptical/polygon ROIs from LIF files created in newer versions of LAS X because bioformats does not account for the scale factor (which was unused in previous versions of LAS X). 
This PR uses the ROI scale correctly and so can load ROIs created in both older and newer versions.

LIF: Correctly read scale from polygon regions of interest

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

This adds a special case to ```TiffParser``` to treat uncompressed strips that are stored in order with no gaps as a single strip.  This should somewhat improve read times for some TIFF files, but likely won't have a noticeable effect upon repo test times.  Any TIFF files that use compression or store tiles instead of strips should be unaffected.
The main thing to verify is that all builds remain green; can definitely exclude in the morning if anything is failing.  There are no API or memo changes, so this should be safe to defer to a patch release.

TIFF: use fast reading case when image is stored in contiguous strips

---

components/formats-gpl/src/loci/formats/in/ColumbusReader.java

See https://github.com/IDR/idr0056-stojic-lncrnas/issues/3
This should prevent an exception from being thrown if a TIFF file is truncated, and instead return a blank plane and log the details at ```WARN```.  This is consistent with what we do for a few other HCS formats.
I wouldn't expect this to have any impact on tests or memo files.

Columbus: warn and return a blank plane if a file has too few planes

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Most of the datasets we received were composed of TIFF files. Using flex
as the binary container is another variant that needs to be handled
specially to pass the non-regression tests.

Fix FormatReaderTest.isThisType to handle Columbus datasets with flex files

---

components/formats-gpl/src/loci/formats/in/FlexReader.java

Without this change, a truncated file would be rejected from the used file list,
which could completely break plate detection.  With an added barcode
check, plates can include truncated files, and files from different
plates will not be inadvertently grouped together.
To test, use ``` /uod/idr/filesets/idr0056-stojic-lncrnas/20190123-ftp/Stojic_screen B_platesIDR/1982/Meas_01(2014-07-04_14-48-06)/```.  Without this change, ```showinf -nopix``` on any of the files should result in a single series and a single used file.  With this change, all .flex files in the directory should be grouped into a plate.
Tests should continue to pass, and memo files should be unaffected.

Flex: use plate barcode for grouping, so that truncated files are kept

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

To test, use ```curated/gatan/samples/test-tiles.dm3```, which was created using Gatan's GMS 3 (DigitalMicrograph Offline) software (http://www.gatan.com/installation-instructions).  The file has 4 planes, and a ```Montage``` tag structure that was copied from a private file that was expected to contain 4 planes each representing one tile.
Without this PR, ```showinf test-tiles.dm3``` should result in a single series with 4 Z sections.  With this PR, the same test should result in 4 series each with a single plane.  Position data for each plane should be present in the OME-XML.
Only one existing file in the repo (```gatan/qa-11392/Example_Gatan_File.dm4```) has a ```Montage``` tag, but it only has one plane so there should be no change in dimensions for any …

Gatan DM3/DM4: parse "Montage" tag to determine if tiles are present

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

We received a list of lens definitions for IDs 18107 - 18111, which are primarily associated with the ```rcpnl``` variant of Deltavision files.  Most of these are new IDs, but 18107 was already defined with a different NA.  The original NA (0.15) will still be used if the file extension is not ```rcpnl```, otherwise the new NA (0.30) will be used.
As far as I can see, the only file that we have with a lens ID between 18107 and 18111 is ```curated/deltavision/qa-21574/RC_SevenChannelScan.rcpnl```, which uses 18107.  I would expect ```showinf -nopix -omexml RC_SevenChannelScan.rcpnl``` without this PR to have ```LensNA``` on the ```Objective``` set to 0.15, and with this PR to have it changed to 0.30 (as above).  Renaming the file to …

DeltavisionReader: add lens IDs associated with rcpnl files

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Backported from 3 private PRs.
This is meant to bring XY plane positions closer to what is reported in ZEN.  This primarily impacts datasets with at least one pyramid.  No new sample files have been added, so testing involves comparing the ground truth (screenshots in https://docs.google.com/document/d/1iL9h9yQ3AVmmzHkI2NsUoqCI08Kw4V82C4vdv6WB-44/edit) to the updated configuration.
With the forthcoming configuration PR, I wouldn't expect builds to fail.  Feel free to exclude until there is time to review though.

CZI: update plane positions for many datasets

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#104](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/104/).
----
--no-rebase

Update POM version numbers to 6.1.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#105](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/105/).
----
--no-rebase

Update POM version numbers to 6.1.2-SNAPSHOT

---

.travis.yml

Disabling the oraclejdk at least temporarily to fix broken CI

Travis: Disabling oraclejdk

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#106](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/106/).
----
--no-rebase

Update POM version numbers to 6.2.0-SNAPSHOT

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/MikroscanTiffReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java

Submitting a new reader for Mikroscan Tiff files. Mikroscan is a provider of Digital Pathology and Telemicroscopy Solutions.

MikroscanTiffReader Addition

---

components/formats-api/src/loci/formats/readers.txt
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/VentanaReader.java

Backported from private PRs.  See https://trac.openmicroscopy.org/ome/ticket/12899 and https://trello.com/c/oCH7PbA5/10-ventana-bif.
Files have been uploaded to ```inbox/ventana/``` for copying to ```curated``` - there are 5 files total.  With this PR, ```showinf -noflat``` on each should detect a pyramid with 9 or 10 resolutions plus two label/overview series.
Ventana .bif files are TIFF files where the first two IFDs correspond to label/overview/macro images and the remaining IFDs form a pyramid.  Each IFD in the pyramid stores the image as tiles that are typically at least 1k x 1k.
Not all stored tiles are used; the largest IFD in the pyramid contains XML that defines one or more ```AOI```s (areas of interest) that have been scanned.  Any tiles outside scanned AOIs are discarded. …

Add reader for Ventana .bif files

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Sometimes a TIFF file will have smaller XY dimensions than all other TIFF files, and will not match the dimensions recorded in ```Index.idx.xml```.  Instead of throwing an exception, this commit returns a blank plane and logs the file name at ```WARN```.
So far we have only seen this in one specific plate, with no clear indication of how/why one file has smaller dimensions.  It wouldn't surprise me even a little if IDR encounters this at some point, though.
To test, use ```curated/perkinelmer-operetta/samples/smaller-xy```, which is copied from QA 17826 as noted in the readme.  ```showinf -series 7 Index.idx.xml``` without this PR should throw a ```FormatException```.  With this PR, the same command should display 2 channels without an exception; the first …

Operetta: do not attempt to open images that are too small

---

components/bio-formats-plugins/src/loci/plugins/in/ImportProcess.java
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Backported from a private PR; #3394 is related.
Adds support for reading the new panel count field, as well as the extended timepoint count, acquisition date,  and a few new enum values.  I have not yet added new test data to the repo, as I'm waiting on confirmation that the files I have can be shared.  If they can't be, I'll make a few dummy datasets next week based upon what's already in the curated repo.
This affects memo files, so will require a minor release.  The acquisition date changes require a configuration update, which is forthcoming.  I would not expect any other existing tests to fail with the date configuration included, but you may wish to one or two older .dv files with multiple series by hand (e.g. things in ```curated/deltavision/dan/```).

Deltavision panel support

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This fixes automatic stitching for 4 existing files in the repository.  Ground truth screenshots are in https://docs.google.com/document/d/139zYc9i5TPQbS_ai3cKnAWNbdix-4G_zUOwpmZcn2Oo/edit.  With the corresponding configuration PR, tests should continue to pass.

Zeiss CZI: expand case where tiles are automatically stitched

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java
tools/mkplate.py

First four commits backported from a private PR; last commit added to fix test failures.  Also fixes https://trello.com/c/Liyb44EG/279-cellomics-dib-plate-failure
For single well plates, this should fix the well row and column reported by ```showinf -nopix -omexml``` to match what is in the file name instead of always being 0.  For plates with missing fields, in particular cases when the first field index is greater than 0, this should fix indexing so that ```showinf -nopix -omexml``` does not throw an exception or result in orphaned ```Image```s.
To test, use ```inbox/cellomics/samples/large-field-index``` and ```curated/cellomics/qa-21720```.  The former mimics the test dataset for the original private PR.  The first field index is 29; ```showinf -nopix -omexml``` on one of the …

Cellomics: indexing fixes for plates with a single well or missing fields

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java
components/formats-bsd/test/loci/formats/utests/tiff/TiffSaverTest.java

1062297 updates ```TiffSaver.overwriteIFDValue``` to overwrite the original value with 0s before the new value is written.  This means that the original tag value is completely gone, and no longer orphaned but still visible in a hex editor.  This is helpful for anyone using ```overwriteIFDValue``` (or higher-level things like ```tiffcomment```) to de-identify or anonymize TIFFs.
In working on this, it became clear that there was a bug in ```overwriteIFDValue``` when the new value has the same length as the original value (but neither value is inlined).  The bug is exhibited by the unit test in fe4d563, which fails without 1062297 and passes with it.
I would expect all other tests to continue to pass; as this is specific to writing, there should be no memo …

TIFF: fixes for tag overwriting

---

.travis.yml

See https://travis-ci.community/t/travis-ci-doesnt-install-ant-while-using-language-java/3856. Travis CI is now failing since Ant is no longer installed by default on `xenial`.
Having Travis CI green should be the main thing to review.

Install Ant via APT packages

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#107](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/107/).
----
--no-rebase

Update POM version numbers to 6.2.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#108](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/108/).
----
--no-rebase

Update POM version numbers to 6.2.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

The ```Scene``` node (which contains the ```CenterPosition``` coordinate) may be
duplicated, in which case only the first node should be parsed.
This should fix the issue with idr0011 (https://github.com/IDR/idr-metadata/blob/master/idr0011-ledesmafernandez-dad4/screens/Plate1-Blue-A_TS-Stinger.screen#L10), which was throwing:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
at loci.formats.in.ZeissCZIReader.translateInformation(ZeissCZIReader.java:2142)
at loci.formats.in.ZeissCZIReader.translateMetadata(ZeissCZIReader.java:1999)
at loci.formats.in.ZeissCZIReader.initFile(ZeissCZIReader.java:1128)
at loci.formats.FormatReader.setId(FormatReader.java:1389)
at loci.formats.ImageReader.setId(ImageReader.java:843)
at …
```

Zeiss CZI: prevent index out of bounds when populating positions

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This improves the behavior when the .log date is incorrectly formatted or cannot be parsed using the current locale.
See https://github.com/openmicroscopy/data_repo_config/pull/411#issuecomment-511465566.  The issue is that when the ```user.language``` is set to something other than ```en```, log file date parsing is likely to fail since the dates are of the format ```Wed Jun 13 13:45:04 2012```.  Since the .log file date took precedence, this meant that the resulting ```AcquisitionDate``` in the ```MetadataStore``` was locale dependent.  This PR changes the date precedence so that the .log file's date will only be kept if it is present and valid and the .dv date does not exist.
With this code change only, all locales should now consistently fail as they have been for ```fr_FR```.  A …

Deltavision: allow .dv date to override .log date

---

pom.xml

This patch release includes the two following external contributions
- https://github.com/ome/ome-codecs/pull/16
- https://github.com/ome/ome-codecs/pull/17

Bump ome-codecs component to version 0.2.4

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See https://forum.image.sc/t/standard-workflow-and-format-to-handle-huge-slidescanner-images/28159/12
If the the TIFF is stored using very large tile/strips dimensions, `DataTools.safeMultiply32` might throw an IllegalArgumentException before the size comparison can happen.
To test, use the sample file available under `/uod/idr/repos/curated/tiff/tobias`. Without this PR, `showinf` or `bfconvert` should throw an `IllegalArgumentException` while retrieving the optimal tile size and importing into OMERO server should result in an exception during the pyramid generation. With the PR included, it should be possible to read and convert the TIFF file.

MinimalTiffReader: be defensive and use DataTools.safeMultiply64

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

The new objective metadata was provided in thread https://forum.image.sc/t/warning-when-opening-dv-files-in-fiji/27923/2 for a new lensID 20007
This is suitable for a patch release. Testing is simply to ensure that builds and tests are green with no regressions.

Deltavision: Add new objective info for new lensID

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

This updates the units for tile positions to meters, and fixes how tile positions are indexed when there is a mixed tile/non-tile dataset.  Specifically, if a non-tile series is present before a set of tiles, then the first tile's position is applied to the non-tile series (and all remaining positions are off by one).  I don't think we have an example of this that can be added to the repo, but I'll try to make one shortly.
I would expect 3 existing files to be affected, as described in the forthcoming config PR.  The only change is the units of ```PositionX``` and ```PositionY```, which change from ```reference frame``` to ```m```.  This seems to yield positions that are consistent with the physical pixel sizes, and should help anyone trying to stitch tiles. …

Leica LIF: fix units and indexing for tile-based plane positions

---

components/formats-gpl/matlab/createMinimalOMEXMLMetadata.m

See https://forum.image.sc/t/bio-formats-octave-error-on-bfsave/27504/4. This
should fix the execution of bfsave in the GNU Octave environment
The impact of this PR should be tested both in GNU Octave (4.2.0 e.g. available from Ubuntu 18.04) and MATLAB R2017b or later. In both environments, a call to the writer API e.g. using `bfsave(zeros(512,512,10,3,1), 'out.ome.tiff')` should successfully create an output file. Without this PR the command should fail on GNU Octave

Use javaObject to construct Boolean object in GNU Octave

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java

Opened in response to https://forum.image.sc/t/bftools-issue-with-the-tip-of-the-pyramid/28879
In the above scenario the smallest resolution has a width less than the selected tile size, as such the tile size reverts to optimalTileSize which is the full resolution width and height of the image.
This fix will change the default to use the min of optimalTileSize and width.

Converter: Default max tile size to either width or optimalTileSize

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java

Without this change, plane positions were only parsed from the first valid file.  This meant that the positions were correct for however many series were covered by the first file (usually 1, but can be the field count for .pnl files).  All subsequent series reused the first series' positions though, which among other things can cause problems with stitching.
All plates under ```cellworx``` apart from ```cellworx/qa-4207``` are affected; I haven't added any new test data.  An updated configuration PR is forthcoming.
This will add a little time to the initial ```setId``` call, but in local tests the impact wasn't particularly noticeable.  Memo files shouldn't need to be regenerated, and with the configuration PR I would expect tests to pass.

CellWorX/.htd: fix plane positions for series index > 0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#109](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/109/).
----
--no-rebase

Update POM version numbers to 6.2.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#110](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/110/).
----
--no-rebase

Update POM version numbers to 6.3.0-SNAPSHOT

---

components/formats-api/src/loci/formats/FormatTools.java
components/formats-api/test/loci/formats/utests/FormatToolsTest.java
components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This PR contains a set of improvements necessary to add test coverage for multi-file OME-TIFF filesets such as the one created for the [idr0052 study](https://idr.openmicroscopy.org/search/?query=Name:idr0052-walther-condensinmap/experimentA)
- c4aa35f was cherry-picked from the original work of @simleo https://github.com/ome/bioformats/pull/2867 and allows to handle multi-file OME-TIFF with no backlink from the TIFF to the companion OME-XML
- 7b7cc1a and 007f9fa implement `OMETIFFReader.getRequiredDirectories()` (previously always set to 0) by creating a helper `FormatTools` API allowing to compute the maximum number of folders under the common parent
- 3b38dac allow to fix the case of OME-TIFF filesets where files have been mapped using `Location.mapFile()` as it is used in the …

OME-TIFF: improve testing coverage for companion filesets

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/RCPNLReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

This creates a separate ```RCPNLReader``` that handles .rcpnl files, as discussed in various formats meetings.  The only functional difference should be that .rcpnl files are read with ```RCPNLReader``` instead of ```DeltavisionReader```.
I opted not to completely split out the "treat all timepoints as positions" logic since that would require a pretty significant refactoring of ```DeltavisionReader```.  Instead, timepoints-as-positions can now be turned on in ```DeltavisionReader``` (it's off by default).  Adding a proper option would be a possible next step.
Memo files will be impacted since this introduces a new reader, so this will require a minor release.  A configuration PR is forthcoming to update the reader name for existing .rcpnl datasets.

Split .rcpnl checks into separate reader

---

components/formats-gpl/src/loci/formats/in/OpenlabRawReader.java
components/formats-gpl/src/loci/formats/in/PDSReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

The DeltaT test is now much more likely to fail, since the configuration
must exactly match what is reported by MetadataStore.
The test should now fail on any of the following:
- configuration date is null, but stored date is not null
- configuration date is not null, but stored date is null
- both configuration and stored dates are not null, but are not equal
The test should pass if:
- both configuration and stored dates are null
- both configuration and stored dates are not null and equal
As discussed in the formats meeting, this will probably cause a whole bunch of test failures.  I'm happy to have this run once, gather the list of failing folders, and then exclude until I can get a configuration PR opened.

Make AcquisitionDate check more strict

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Opening as a follow up to https://trello.com/c/4PvmeIIP/378-nd2-32-bit-float-being-treated-as-int to test impact on data repo

NativeND2 - Use floating point for 32 bit values

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

Fixes #3439 
Support for the magnification in the Hamamatsu NDPI reader was introduced in Bio-Formats 5.1.0 (#1553). The original implementation makes use of the `Objective.Lens.Magnificant` key in the metadata TIFF tag (65449). Across our samples, the value is found to be always constant and equal to 35.16 for the largest resolution of the pyramid.
This PR adjusts the reader to populate the nominal magnification from the SourceLens TIFF tag (65449) for the pyramidal images. This is in agreement with what NDP.view displays when opening NDPI samples files

NDPIReader: fix nominal magnification population

---

components/formats-bsd/src/loci/formats/in/ICSReader.java

This is a follow up to the thread https://forum.image.sc/t/trouble-with-converter-testconvert-from-bio-formats-tools/29189/5
When using an ICS file from SVI-Huygens then using tiled reading produces inverted bands as in the thread. This fix aims to resolve that issue similar to other readers such as https://github.com/ome/bioformats/blob/develop/components/formats-bsd/src/loci/formats/in/BMPReader.java#L122

ICS: Update y start value when invertY

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Backported from a private PR.  Should fix https://trello.com/c/3eJGDfHh/374-lif-tilescan-flip-and-swap-values-not-being-parsed; the test files are in ```curated/leica-lif/romain```.
To test, compare the results of ```showinf -nopix -omexml curated/leica-lif/romain/tile 002.lif``` with and without this PR.  With this PR, the resulting ```PositionX``` and ```PositionY``` values should match the expectations in https://forum.image.sc/t/tilling-issue-with-lif-file/26843 (i.e. X and Y swapped, and both values multiplied by -1).
Tests should continue to pass, and memo files should be unaffected, so this should be safe for a patch release.

Leica .lif: parse attachments to determine if XY positions should be flipped or swapped

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

When metadataStore is an instance of DummyMetadata it will not
contain any Images. Use the metadataStore's own image count rather than
the file stored image count when indexing the metadataStore's Images.

OBF: Fix outOfBounds exception with DummyMetadata

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

Opening to debug an ongoing timeout issue. May expand into a (developer) feature.

fake: allow injecting sleep on setId and openBytes

---

.travis.settings.xml
.travis.yml

This proposes to update the deployment mechanism of the Bio-Formats JARs (SNAPSHOT and release) to use Travis CI rather than relying on a secondary Jenkins job.
This logic is identical to what is in place for the downstream examples and documentation repositories and has been tested in the context of IDR - see https://github.com/IDR/bioformats/pull/16.
If accepted, the [Jenkins job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-maven/) achieving this task will become redundant and should be disabled and eventually archived when this PR is merged.

Artifactory deployment

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This fixes a few issues in Metamorph file name construction, especially when the wavelength name is not included in the file name.  It also updates some of the plate detection logic, so that potential well labels in the .nd file are considered, and labels similar to ```A1, 1 of 2```, ```A2, 1 of 2```, etc. will result in a plate.
I'll put together a test dataset on Monday, just opening this for now to make sure that tests aren't impacted.

Metamorph plate fixes

---

components/formats-gpl/src/loci/formats/in/BDVReader.java

This is a follow up to the forum thread https://forum.image.sc/t/bio-formats-xml-hdf5-reader-voxel-dimensions/29645/2
The data is present in the XML under ViewSetup as below:
```
<voxelSize>
<unit>um</unit>
<size>0.3518820106983185 0.3518820106983185 0.3518820106983185</size>
</voxelSize>
```
An example dataset with this data present is 100-U-9-MV-f0
This will be memo breaking

BDV: Parse physical sizes from XML

---

components/formats-bsd/src/loci/formats/in/JPEG2000Reader.java
components/formats-bsd/test/loci/formats/utests/ConversionTest.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

The JPEG2000 codec logic has full support for sub-resolution and is used in a couple of places in this code as well as consumers. I realized recently that this is not exposed at the level of the [JPEG2000 file format](https://docs.openmicroscopy.org/bio-formats/6.2.1/formats/jpeg-2000.html) reader so all `.jp2` images are read as single-resolution at the moment.
5e5606c updates the reader to pass the `resolutionLevels` detected by the metadata parser. This will impact the configuration files for all JPEG200 which will need to be regenerated. 
4a50653 is not strictly necessary but addresses the long-standing problem of the file ordering when regenerating configuration files /cc @melissalinkert 
Without this PR,  running `showinf` on JPEG2000 files should show no additional …

JPEG2000 reader: add full support for sub-resolutions

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

An artificial test plate is in ```curated/perkinelmer-operetta/samples/no-first-series```.  Without this change, ```showinf -omexml Index.idx.xml``` will throw an ```IllegalArgumentException```.  This is because the first field in the first well is not recorded in the ```Index.idx.xml```, so X and Y sizes are not assigned to the first series.
With this change, the same command should result in blank planes being displayed. The first series is not removed because that would make it difficult to compare fields across wells.
Other plates and memo files should be unaffected, so this could wait for a patch release.

Operetta: prevent series from having X or Y set to 0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#111](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/111/).
----
--no-rebase

Update POM version numbers to 6.3.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#112](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/112/).
----
--no-rebase

Update POM version numbers to 6.3.1-SNAPSHOT

---

tools/ijview
tools/ijview.bat

When running CLI `ijview` without an ImageJ have the help message suggest a secure URL for downloading code.

Have ijview suggest HTTPS URL for fetching ImageJ upgrades.

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

This should prevent `NullPointerException` using some variants of the LIF
file format as reported in https://forum.image.sc/t/lif-cannot-open-with-bioformats-6-3-0/30856/
/cc @NicoKiaru

Add a null check to LIFReader.checkFlip

---

components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

Mentioned in formats meeting 2019-10-30.  See also discussion in https://github.com/glencoesoftware/raw2ometiff/pull/1.
This should prevent unnecessary array copying when writing a tile buffer whose size matches the expected tile dimensions.  The overall conversion time for large tiled images should be noticeably faster with this PR.  ```bfconvert``` from an NDPI/SVS/etc. to pyramid OME-TIFF would be a good test.

TiffSaver: make tile writing faster

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

Fixes #3461.  The previous behavior was to use the same XY coordinate when reading and writing a tile.  This is fine when there is no cropping, but otherwise results in a coordinate that fails the writer's bounds check.
Without this PR, ``` bfconvert -crop 32256,8704,5120,5120 "test&sizeX=49512&sizeY=38578.fake" test.tif``` should throw:
```
Exception in thread "main" loci.formats.FormatException: X:32256 must be < 5120
at loci.formats.FormatWriter.checkParams(FormatWriter.java:453)
at loci.formats.out.TiffWriter.saveBytes(TiffWriter.java:220)
at loci.formats.tools.ImageConverter.convertTilePlane(ImageConverter.java:878)
at loci.formats.tools.ImageConverter.convertPlane(ImageConverter.java:763)
at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:691)
at …
```

bfconvert: fix the writer's XY coordinate when the input image is cropped

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Backported from a private PR.  See also https://trello.com/c/7MRDBwSn/178-czi-file-not-automatically-stitching
3add3da fixes a problem with the XY sizes when there are multiple positions ("Scenes" in ZEN).  Without this PR, ```qa-17179/WT_calc_after24h_stitch_2.czi``` had the same XY size for all 3 series.  With this PR, the sizes vary slightly between the 3 series.
604a1a0 fixes a problem where some datasets with multiple positions ("Scenes") and multiple mosaics (tiles) were not automatically stitched.  Without this PR, each position and mosaic in ```michael/multipos-z-time-*-tile.czi``` is split into a separate series.  With this PR, the mosaics are correctly stitched.
50da2d0 adds basic parsing for the ```Events``` annotation type, which was required in the original private PR but …

Zeiss CZI: fix some tile stitching and position size issues

---

components/formats-bsd/src/loci/formats/out/ICSWriter.java
components/formats-bsd/test/loci/formats/utests/out/ICSWriterTest.java
components/formats-bsd/test/loci/formats/utests/out/WriterUtilities.java
components/formats-bsd/test/loci/formats/utests/testng.xml

This is a fix for the NPE reported in https://forum.image.sc/t/bio-formats-ics-writer-bug/31423
The issue was due to the Units of the physical sizes being Pixels, which cant be converted to micrometer.
To test:
- From FIJI open the sample file Bat Cochlea Volume
- Using the Bio-Formats Exporter try to save the file as .ics
- Without the PR this should throw a NullPointerException
- With the PR the file should be saved without error
- Verify that the ICS file can be imported and displays as expected

ICSWriter: PhysicalSize NPE fix

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

This is a follow up to address the issues which have been reported in https://github.com/ome/bioformats/pull/3141
In this scenario the dimensions are only updated from the label if they have not already been set.
The provided sample file can be used for testing. Without this PR the second series should throw an exception. With this PR it should read and display without error. 
I will open a config PR with the new sample file.

OBF: Incorrect dimensions fix

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#113](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/113/).
----
--no-rebase

Update POM version numbers to 6.3.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#114](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/114/).
----
--no-rebase

Update POM version numbers to 6.4.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/GatanReader.java
components/formats-gpl/src/loci/formats/in/OperettaReader.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Cleans up a few places where readers were using a deprecated method or variable.  There should be no behavior changes or failing tests; the only difference is that the build log should be a bit cleaner.  Should be safe for a patch release, but definitely not urgent.

Fix a handful of deprecation warnings

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

See https://github.com/ome/bioformats/issues/3346
Without this PR, the following should throw a ```NumberFormatException``` as described in #3346 :
```
$ mkfake .
$ echo "sizeC=3" >>  screen.fake/Plate000/Run000/WellA000/Field000.fake.ini
$ showinf screen.fake
```
With this PR, the same test should successfully display one plane.  Note that ```SizeC``` will be 1 with the test case as written, since only the only .ini file parsed is the one matching what was passed to ```setId``` (```screen.fake.ini``` in this case).  To have ```SizeC``` set to 3, either run:
```
$ showinf screen.fake/Plate000/Run000/WellA000/Field000.fake
```
or:
```
$ echo "sizeC=3" >> screen.fake.ini
$ showinf screen.fake
```
I wouldn't expect this to have any test or memo impact, so should be fine for a patch release …

Fake: allow .ini files in plates created by mkfake

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

See https://trello.com/c/ONAvIZoV/330-add-key-to-configure-deltat
```DeltaT``` can now be set for each plane in the .ini file, just like ```ExposureTime```.  With this PR:
```
$ cat test.fake.ini
[series_0]
DeltaT_0 = 1.5
DeltaTUnit_0 = ms
$ showinf -nopix -omexml test.fake
...
<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
<Image ID="Image:0" Name="test">
<Pixels BigEndian="false" DimensionOrder="XYZCT" ID="Pixels:0" Interleaved="false" SignificantBits="8" SizeC="1" SizeT="1" SizeX="512" SizeY="512" SizeZ="1" Type="uint8">
<Channel ID="Channel:0:0" …
```

Fake: allow DeltaT to be set in INI file

---

components/formats-bsd/src/loci/formats/out/TiffWriter.java

Documents the advice given in https://github.com/ome/omero-downloader/issues/17#issuecomment-574896977.

Add a note about supplying IFD instances for TIFF writing.

---

components/bio-formats-tools/src/loci/formats/tools/XMLValidate.java

See https://trello.com/c/fa7RLnwL/366-character-case-in-validating-xml
Without this PR, this test should throw a ```FileNotFoundException```:
```
$ showinf -nopix -omexml-only test.fake > TEST.ome.xml
$ xmlvalid TEST.ome.xml
```
With this PR, the same test should successfully validate ```TEST.ome.xml```.

xmlvalid: fix lowercasing of file names

---

components/formats-api/src/loci/formats/FormatWriter.java

See https://trello.com/c/zxnORoSU/380-bfconvert-create-subfolders
Without this change, something like ```bfconvert test.fake plate/well/field/test.tiff``` (where ```./plate/well/field/``` doesn't exist) should throw an exception.  With this change, the conversion should be successful.
It's also worth checking something like ```bfconvert "test&sizeZ=3.fake" plate/well/%z/test.tiff``` where there is a pattern in the directory, just to make sure.

FormatWriter: create output file's parent directory if needed

---

components/formats-gpl/src/loci/formats/in/VentanaReader.java

See #3416.
Without this PR, ```showinf -nopix -noflat -omexml``` on the file from QA 27763 should show that ```PhysicalSizeX``` and ```PhysicalSizeY``` are not included in the OME-XML.  With this PR, the same command should show both ```PhysicalSizeX``` and ```PhysicalSizeY``` set to ```0.25```.
Ventana TIFFs (which is what QA 27763 is) are typically converted from .bif files and don't have as much metadata stored in the IFDs for each pyramid level.  Most of the XML on the pyramid IFDs in a .bif file is related to stitching tiles; when the .bif file is converted to a Ventana TIFF, all of that XML is presumably stripped out since it's no longer relevant.
I wouldn't expect any test failures, and memo files should not be impacted.

Ventana: try harder to find physical sizes for prestitched TIFFs

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

If multiple Z sections are present, each one is expected to be in a separate directory as described on line 898.  A test dataset is being uploaded to ```curated/cellworx/samples/multi-z/``` (generated from idr0005).  Without this PR, ```showinf -nopix 2011-04-19-plate-1.HTD``` should throw an exception.  With this PR, ```SizeZ``` should be 2 for every series.  ```showinf -trace 2011-04-19-plate-1.HTD -series n``` for any series should show that the 2 planes are coming from different files.  The planes won't be visually different, so it's worth checking the file names. 
Existing tests should continue to pass.  This will impact memo files, so requires a minor version.

CellWorx: add support for multiple Z sections

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

This corrects for the difference in how Y coordinates are treated between the acquisition software and our model (see the code comment).  To test, open ```incell/michael/firstStack``` (1 well, 6 fields in a 3x2 grid) in ImageJ with ```Open all series``` and ```Stitch tiles``` checked.  Without this PR, there should be a very obvious horizontal line in the middle of the stitched image even when zoomed out.  With this PR, the stitched image should look much better.
Shouldn't affect memo files, but does require a substantial configuration update to change every Y position for every InCell plate.

InCell: invert Y coordinate in plane/field positions

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/formats-bsd/src/loci/formats/out/TiffWriter.java

See https://github.com/ome/bioformats/issues/3404
Adds a ```setCanDetectBigTiff(boolean)``` method to ```TiffWriter``` and corresponding ```-nobigtiff``` option to ```bfconvert```.  If ```-nobigtiff``` is used (== ```setCanDetectBigTiff(false)```), then automatic switching to BigTIFF based upon the number of pixel bytes is turned off.  Extension-based switching is unchanged.
Using ```-bigtiff``` and ```-nobigtiff``` together should exit quickly with an error message, since the correct behavior is ambiguous.
Should not impact memo files or anything on the reading side of the stack, but does require a minor release due to new API.  I don't feel strongly that this needs to be in 6.4.0.

bfconvert: add -nobigtiff option

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

See https://github.com/ome/bioformats/issues/3401.
The JPEG-XR decompression warnings occurred because the pixel data blocks were actually uncompressed.  ```showinf -range 2 2 -series 8``` on the file from QA 27508 without this PR will show an image with all 0 pixel values.  With this PR, there should clearly be image data that aligns with the other channels.  Note that there are still blank areas in each corner, but that is correct.
I don't think this will affect tests (feel free to exclude if it does), and should be safe for a patch release.

Zeiss CZI: check for uncompressed pixels incorrectly flagged as JPEG-XR

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

See https://trello.com/c/JHikBmdv/368-make-tiffparser-and-tiffsaver-closeable and https://github.com/openmicroscopy/bioformats/pull/3331#pullrequestreview-223532670
```TiffSaver``` already implemented ```close()```, so the only change there is to explicitly implement ```Closeable``` which should be pretty safe.
```TiffParser``` needed a new ```close()``` method though, and I'm not 100% sure of the best approach.  Always closing the underlying ```RandomAccessInputStream``` would make sure that the file handle is always closed, but would be problematic for existing code of this form:
```
RandomAccessInputStream s = new RandomAccessInputStream("file.tiff");
TiffParser p = new TiffParser(s);
...
p.close();
s.seek(0);
```
The current approach is to only close the ```RandomAccessInputStream``` …

Make TiffParser and TiffSaver implement Closeable

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-gpl/src/loci/formats/in/VectraReader.java

9e15251 fixes how the ```X_POSITION``` and ```Y_POSITION``` TIFF tags are recorded in the original metadata table for all TIFFs.  Without this change, the ```XPosition``` and ```YPosition``` values were treated as integers, and now they are treated as doubles.  ```showinf -nopix``` on any of the *.qptiff files in ```data_repo/curated/vectra-qptiff/``` should show the difference, and ```tiffinfo /path/to/file | grep Position``` can confirm that this PR is correct.
e9fc01a uses the ```X_POSITION``` and ```Y_POSITION``` TIFF tags to set ```Plane.PositionX``` and ```Plane.PositionY``` in the OME-XML for QPTIFF files.  ```showinf -nopix -omexml``` on any of the *.qptiff files in ```data_repo/curated/vectra-qptiff/``` should show that both values are populated with …

QPTIFF: metadata fixes

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java
components/formats-gpl/src/loci/formats/in/RCPNLReader.java

This is pretty much the same as #3204 . I used a [script](https://github.com/MicronOxford/scripts/blob/master/auto/dvlenses2readercases.pl) to parse the `dvlenses.tab` from the last release of softWoRx and convert to the java code required for the deltavision reader.
This does adds more objectives but also removes a few which I found odd since I don't know from where those were coming (mainly 33a19733b32b and a644a10df03e). At least the change made by ace7daf99e43 are odd because they mark them as Nikon objectives but they are not in the 12000-13999 range.

DeltavisionReader.java: synchronise objectives metadata with softWoRx 7.2.0

---

components/formats-gpl/matlab/bfGetPlane.m
components/formats-gpl/matlab/bfGetPlaneAtZCT.m
components/formats-gpl/matlab/bfTestInRange.m

For MATLAB users, it is confusing on how to use bfGetPlane to get a particular plane at a ZCT coordinate. This pull request adds a function bfGetPlaneZCT that handles that exact scenario and all of the 0-indexing to 1-indexing issues per this thread:
https://forum.image.sc/t/ijm-getdataset-crashing-matlab/27210/9
Additionally this adds a function bfTestInRange.m which provides more efficient range checking than using ismember while producing more readable errors.
bfGetPlane range checking for width and height is done only once.

MATLAB: Add function bfGetPlaneAtZCT.m and improve range checking for bfGetPlane

---

pom.xml

See https://github.com/ome/ome-codecs/milestone/8?closed=1
These changes should have been tested daily in the CI builds for the last month. This bump is primarily to include the new component  in the upcoming release

Bump ome-codecs component to version 0.3.0

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java

This is a fix for https://github.com/ome/bioformats/issues/3512
To test:
- Use bfconvert on a multi series file
- Select a single timepoint, z slice or channel
- Without this PR opening the converted file will throw an ArithmeticException: / by zero
- With this PR the converted file should open without exception
Closes #3512

ImageConverter: MultiSeries fix

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

When reading from a single tile whose byte count is > 2GB,
use ```seek``` instead of ```skipBytes``` to prevent a possible integer overflow.
/cc @chris-allan, @douglasrennick

TIFF: prevent integer overflow when reading from a large tile

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#115](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/115/).
----
--no-rebase

Update POM version numbers to 6.4.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#116](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/116/).
----
--no-rebase

Update POM version numbers to 6.4.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/MikroscanTiffReader.java

The reader was added in #3333 but the correct license was not included back then. This updates the file header using the standard assumptions in terms of license and copyright owner holders.

Add standard GPL-2 license to MikroscanTiffReader

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-bsd/src/loci/formats/in/AVIReader.java
components/formats-bsd/src/loci/formats/in/DicomReader.java
components/formats-bsd/src/loci/formats/in/EPSReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-gpl/src/loci/formats/in/AliconaReader.java
components/formats-gpl/src/loci/formats/in/BioRadGelReader.java
components/formats-gpl/src/loci/formats/in/BioRadReader.java
components/formats-gpl/src/loci/formats/in/HISReader.java
components/formats-gpl/src/loci/formats/in/IMODReader.java
components/formats-gpl/src/loci/formats/in/IPLabReader.java
components/formats-gpl/src/loci/formats/in/ImspectorReader.java
components/formats-gpl/src/loci/formats/in/IvisionReader.java
components/formats-gpl/src/loci/formats/in/LIFReader.java
components/formats-gpl/src/loci/formats/in/LeicaReader.java
components/formats-gpl/src/loci/formats/in/LiFlimReader.java
components/formats-gpl/src/loci/formats/in/MetamorphReader.java
components/formats-gpl/src/loci/formats/in/NAFReader.java
components/formats-gpl/src/loci/formats/in/OpenlabReader.java
components/formats-gpl/src/loci/formats/in/PSDReader.java
components/formats-gpl/src/loci/formats/in/PhotoshopTiffReader.java
components/formats-gpl/src/loci/formats/in/SDTReader.java
components/formats-gpl/src/loci/formats/in/SlidebookReader.java
components/formats-gpl/src/loci/formats/in/TargaReader.java
components/formats-gpl/src/loci/formats/in/VisitechReader.java
components/formats-gpl/src/loci/formats/in/ZeissLMSReader.java
components/formats-gpl/src/loci/formats/in/ZeissZVIReader.java

Inspired by https://github.com/ome/bioformats/pull/3519, https://github.com/ome/bioformats/pull/3303, and https://github.com/ome/bioformats/pull/3157.  This uses ```skipBytes(long)``` in more places where integer overflow seems plausible.
I would expect this to be safe for a patch release and have no impact on tests.  I don't anticipate this will fix any outstanding issues, it's just an attempt at being more defensive.

Use skipBytes(long) in places where integer overflow is possible

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java

The number of well samples/fields of view per well is computed from the total number of acquisition sites and the number of selected sites, determined by XSites, YSites and the SiteSelection<index> entries in the HTD file.
For single site acquisitions (XSites=1, YSites=1), the SiteSelection1 key might be absent from the HTD files. This commit updates the reader to assume the single site is selected.

CellWorX: add support for single site HCS variant

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

Some files have the file type value set to indicate a "new" header format,
but actually have an "old" header format.  This causes the panel/series count
to be wildly inaccurate, which in extreme cases can trigger an ```OutOfMemoryError```.
A basic check on the number of detected panels allows the reader to fall
back to parsing an "old" header instead.
An artificial test file created from one of the public samples is in ```inbox/dv-bad-header``` (see the readme in that directory).  Without this PR, ```showinf``` on the test file should eventually throw an ```OutOfMemoryError```.  With this PR, images should be displayed without error and the output should match the original file from which the test was created.

Deltavision: sanity check the panel count and fall back to old style header

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

Version 6 stacks can be written in chunks (data of distinct stacks can
be written interleaved) and truncated (not all samples of a stack have
to be explicitly written; unwritten samples can be assumed 0 / undefined).
This also adds support for version 4 stack flush points.
These can optionally be used to speed up random access in
compressed stacks.

OBF: Add OBF stack version 6 support

---

pom.xml

See https://github.com/ome/ome-model/blob/v6.1.0/NEWS.md for the list of changes
The latest version of ome-model has been pulled in the daily merge CI builds so I expect tests will keep passing.
Bumping the  component version in the pom.xml is necessary to consume the new `OME Creator` API - see #3541.

Bump ome-model version to 6.1.0

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is meant to fix a case where only one position is present, but the starting index is 10.  The file contains a pyramid, so an incorrect position count completely throws off pyramid building logic.
If this doesn't fail tests, additional commits could be added (here or in a separate PR) to calculate the illumination, phase, etc. dimensions similarly.  I'll find or put together a test file once it's clear that this doesn't break any existing files.

Zeiss CZI: fix position count when the starting index is > 0

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Instead, trust dimension from tag metadata and/or .nd file.  Backported from a private PR.
I wouldn't expect this to have any impact on tests.  I will put together a test file in the next day or two once it's clear that this does not break anything.

Metamorph: don't allow underlying TIFF reader to treat each IFD as a series

---

components/formats-bsd/src/loci/formats/in/DicomReader.java

Files spread across multiple directories are now handled by a ```DICOMDIR``` file that groups everything together.  See previous work in #2785 and #3222.
Main thing to check is that this has no impact on existing tests.  I would expect this to speed up initialization of multi-file datasets, especially in a directory structure similar to:
```
/path/to/dicom/set/1/
/path/to/dicom/set/2/
```
with each fileset containing hundreds or thousands of files.
Not urgent for 6.5.0; assuming tests pass, should be safe for a later patch release.

DICOM: do not check other directories for matching files

---

components/formats-gpl/src/loci/formats/in/BDVReader.java

This fix should greatly improve the performance when reading BDV data in a tiled manner, specifically this should help improve performance in IDR.
This fixes a bug where previously the entire row was being read and then the tile read from it, this fix now takes the x offset and tile width into account when retrieving the pixel data.
To test:
- Open any of the existing BDV samples and verify that the pixel data remains accurate

BDV: Fix for tiled reading

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#117](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/117/).
----
--no-rebase

Update POM version numbers to 6.5.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#118](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/118/).
----
--no-rebase

Update POM version numbers to 6.5.1-SNAPSHOT

---

pom.xml

Should be functionally identical but resolves duplicate class leakages
outlined here:
https://forum.image.sc/t/how-to-resolve-duplicate-classes-in-unshaded-ome-jxrlib-all-artifact/37290

Bump jxrlib version to 0.2.4

---

components/formats-bsd/src/loci/formats/in/OBFReader.java

Follow-up of https://github.com/ome/bioformats/pull/3528, this change adds the file version and stack version (see https://imspectordocs.readthedocs.io/en/latest/fileformat.html for more details) to the global metadata populated by the reader.
/cc @ngladitz

Add OBF file format version and stack version to the global metadata

---

components/formats-gpl/src/loci/formats/in/AFIReader.java
components/formats-gpl/src/loci/formats/in/SVSReader.java

Defends against a potential NPE if either the exposure time or units are missing from an SVS file.  Tests should remain green, and this should be safe for a patch release.

SVS/AFI: fix NPE when exposure time is not defined

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

Fixes typo that caused physical sizes to only be set for the first series.  Requires a configuration change, but tests should otherwise pass and this should be safe for a patch release.

Cellomics: set physical sizes for all series

---

components/formats-gpl/src/loci/formats/in/MikroscanTiffReader.java

See #3571 for more context
This change should allow `MikroscanTiffReader.isThisType(name, open)` to fail in case `open` is set to false i.e. file access is disallowed
I expect this change should have no impact on the standar Bio-Formats detection logic in `ImageReader`. Non-regression CI builds should keep passing against all sample datasets including the Mikroscan TIFF ones.
When the `MikroscanTiffReader.isThisType(name, open)` API is used with `open` set to false like in the case `python-bioformats`, this should prevent all TIFF files to be erroneously flagged as Mikroscan TIFF. The code snippet from https://github.com/ome/bioformats/issues/3571#issuecomment-643281905 could be used for testing this PR after replacing the JAR with a version of Bio-Formats including this PR.

MikroscanTiffReader: set suffixSufficient to false

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

Reported in https://forum.image.sc/t/bfconvert-throwing-an-error-for-an-vsi-file/37185, this fixes a regression introduced in #3518 for multi-series files with varying image sizes
`bfconvert "test&resolutions=2.fake" out.ome.tiff` should suffice to reproduce the issue reported in the forum thread. 205dae6  fixes the issue by only setting the pixel X and Y sizes to the first image. 5561dbb adds a simple test to `ImageConverterTest` which should fail without the fix and pass with it.

Image converter: fix multi-series regression

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is a fix for the reported issue in https://forum.image.sc/t/czi-reader-illuminationtype-mapping-and-exposuretime-units/37557/3 with regards the IlluminationType.
A sample file has been provided in QA-29273 which can be used for testing.
From debugging it appears that the Channel information is correct and contains Epifluorescence:
```
Information|Image|Channel|IlluminationType #1: Epifluorescence
Information|Image|Channel|IlluminationType #2: Epifluorescence
```
However this was then being overridden by the DisplaySettings metadata which contains:
```
DisplaySetting|Channel|IlluminationType: Fluorescence
```
To test:
- Use the provided sample file (QA-29273), without this PR the `IlluminationType` pf the 2 channels should appear as `Other` in …

CZI: IlluminationType not overridden by DisplaySettings

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/ImageReader.java

Do not log id if omero
cc @dgault @sbesson 
see: https://github.com/ome/omero-insight/issues/136

do not log if omero

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This will attempt to use wavelengths from Metamorph XML or original metadata to populate ```Channel.EmissionWavelength``` and ```Channel.LightSourceSettings.Wavelength``` if no other wavelengths are defined.
I think this would be safe for a patch release.  The only potential test impact I would expect is that some files might need to have an emission wavelength added to the configuration.  If that turns out to be the case, I will open a config PR tomorrow.

Metamorph: expand wavelength parsing

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#119](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/119/).
----
--no-rebase

Update POM version numbers to 6.5.1

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#120](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/120/).
----
--no-rebase

Update POM version numbers to 6.6.0-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

This commit deals with the scenario of an IDR submission where plate folders containing the TIFF data + the metadata XML files directly (without the usual Images subdirectory) were found under the same current level. The assumptions of the reader currently causes all other plates to be added to the fileset as ancillary metadata files, increasing the size of the original 7K fileset to 55K and slowing down import down the line.
The new logic adds early directory checks when adding metadata files to skip either the directory containing the master XML file or other directories containing XML files.
From the mainline Bio-Formats, the main impact is that there should be no regression at the level of the automated tests. There should be a slight performance improvement to `setId` as the current …

Operetta: fix metadata files logic to skip plate folders

---

components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

```testConvertResolutionsFlattened``` as introduced in #3553 was failing in the private repo because a reader other than ```OMETiffReader``` was (correctly) picking up the output file and detecting multiple resolutions.
This changes the ```ClassList``` that ```ImageReader``` uses when checking output file dimensions, so that only the 3 expected output formats are present.

Restrict readers used during image conversion tests

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

Test plate is in ```inbox/cellomics-plate-size```.  Compare ```showinf -nopix -omexml``` with and without this PR.  Without this PR, only the first well is linked to the plate.  With this PR, both wells are linked to the plate, and the plate has 384 instead of 96 wells.
This should be safe for a minor release; memo files and tests should be unaffected.

Cellomics: use maximum row/column index to calculate plate size

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/CellWorxReader.java
components/formats-gpl/src/loci/formats/in/MetaxpressTiffReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Most of the logic is still in ```CellWorxReader```, but anything TIFF-specific is in ```MetaxpressTiffReader```.
See https://github.com/openmicroscopy/data_repo_config/issues/452.  A configuration PR is needed to change the reader for MetaXpress datasets identified in that issue.
This requires a minor release; feel free to exclude if needed in the meantime.  Tests should continue to pass with the corresponding configuration changes included.

Split CellWorX and MetaXpress support into separate readers

---

components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
pom.xml

From 2.24.0 to 3.0.0, the kryo project changed its groupId from `com.esotericsoftware.kryo` to `com.esotericsoftware`. Therefore, from Maven's perspective, both of these artifacts can be present on the classpath at the same time, creating duplicate class conflicts. Unfortunately, this scenario is happening when attempting to combine Bio-Formats (which wants kryo 2.24.0) with `graphics.scenery:scenery:0.7.0-beta-7` (which wants kryo 4.0.2).
One solution to this dilemma is to update the version of kryo here to 4.0.2, which is what this PR does. The code still compiles, and tests pass, although I am not certain how thorough (if at all) the kryo-related functionality is exercised.
See also ome/ome-common-java#50.

Update kryo to latest version

---

components/formats-bsd/src/loci/formats/Memoizer.java
pom.xml

Follow up of #3557, this PR bumps the internal version number of the `Memoizer` wrapper and the `ome-common` dependency to use the same `kryo` version across the board.
Tests should be unaffected and keep passing. A test for the version bump would be to test the memo file invalidation workflow:
- create a memo file using the last stable Bio-Formats release e.g. by running `showinf -nopix -cache -debug` 
- reopen the file with a version of Bio-Formats including  this PR  using `showinf -nopix -cache -debug`
- check the memo file has been invalidated and recreated as well as the error message in the log

Increment the Memoizer version

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java
components/formats-gpl/src/loci/formats/services/MDBService.java
components/formats-gpl/src/loci/formats/services/MDBServiceImpl.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Backported from a couple of private PRs.  See also https://trac.openmicroscopy.org/ome/ticket/7092
This updates the ```MDBService``` API to allow retrieval of one table at a time.  ```CellomicsReader``` uses the new API to retrieve just the channel table from the optional companion .mdb file, so that channel names, colors, and plane exposure times are now populated.
This will require a minor release, and may require a configuration PR to add channel/plane metadata.  If there are any other test failures, feel free to exclude for now.

Cellomics: parse channel data from companion .mdb file

---

.travis.yml
pom.xml

See https://forum.image.sc/t/fiji-wont-open-czi-files-after-update-there-was-a-problem-with-the-class-java/40932
for the rationale and the issue with ome-common 6.0.5

Bump ome-common to version 6.0.6

---

components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Matches the behavior of setSeries.  See https://github.com/ome/bioformats/pull/3595#issuecomment-664795854
Without this change, ```ant ... test-config && ant ... test-automated``` on ```zeiss-lsm/jcb``` should result in test failures as described in #3595.  With this change, the same test should result in passing tests with correct configuration.

Zeiss LSM: reset plane cache variables on setCoreIndex

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://github.com/ome/bioformats/pull/3588#issuecomment-663512854
The previous tests for channel and image names check were not failing as expected. This PR fixes the check to handle various scenarios of comparison between strings (note that the `null` value is handled specially).
f2e82c6 also fixes an issue discovered when regenerating configuration files (`zeiss-lsm`) with the pixel hashes of series > 0 being incorrect (and identical).
A companion private PR accompanies this change, updating all configuration files to use the correct metadata.

Improve stringency of ChannelName and ImageName check

---

components/formats-gpl/src/loci/formats/in/SISReader.java

This is a follow up PR to remove some comments and fix some indentation.
This should have no impact on any tests or memo files.

Olympus SIS: Cleanup of comments and indents

---

components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java
components/test-suite/src/loci/tests/testng/FormatReaderTestFactory.java

The `FileStitcher` has been included in the automated tests since the inception of the `test-suite` component. This means that file stitching based on name pattern is automatically executed fo every fileset for every format in the curated QA repository - see [here](https://downloads.openmicroscopy.org/images/DV/U2OS/), [here](https://downloads.openmicroscopy.org/images/DICOM/nema/WG04/IMAGES/J2KR/) or. [here](https://downloads.openmicroscopy.org/images/PNG/user-4/dataset-user-4/) for public filesets where several files are grouped by stitching. For some filesets, the non-stitched filesets have mismatching dimensions and the stitching logic fails. In these cases, the only way to configuration the files for testing is to artificially split them into separate folders - see …

Remove FileStitcher from FormatReaderTest and FormatReaderTestFactory

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/in/DynamicMetadataOptions.java
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is an initial prototype of the potential functionality for persisting options using a .bfoptions file as discussed at the formats meeting this week.
If a reader detects a file in the same folder as the currentId with the same name and extension `.bfoptions` then the options will be parsed from the file
An example of an options file might be:
```
zeissczi.attachments=true
zeissczi.autostitch=true
```
- This is very much an early prototype for discussion but might also be useful for IDR testing
- At the moment this is limited to reading options from file and does not create the file for you
- It is also limited to readers and not writers
- Further error and exception handling would also be needed

bfoptions: Add ability to read options from file

---

components/formats-gpl/src/loci/formats/in/ScanrReader.java

This PR merges the IDR specific changes https://github.com/IDR/bioformats/commit/d74f7f75ea14e7da22604faacef45ead7ff8e10a and https://github.com/IDR/bioformats/commit/563299273fd14e3e5bf0914a36330ee17f093155
A new metadata option `scanr.skip_missing_wells` has been added to retain the original functionality or allow the IDR behaviour to be toggled. This should mean no breakages in behaviour for existing OMERO users.
To test:
- Default behaviour should see missing wells skipped when imported
- Ensure IDR behaviour is not impacted when `scanr.skip_missing_wells` is set to `false`

ScanR: Merge IDR changes and add new option

---

components/formats-api/src/loci/formats/FormatReader.java
components/formats-api/src/loci/formats/in/DynamicMetadataOptions.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Folllowing the new API introduced in https://github.com/ome/bioformats/pull/3605, this PR makes a few modifications primarily in the `test-suite` component in order to run the non-regression tests against filesets containing `.bfoptions` files.
- the readers from `Configuration` and `FormatReaderTest` are systematically initialized with a `DynamicMetadataOptions` instance as the latter is required to load options file
- skip `.bfoptions` file in `FormatReaderTest.isThisType()`
- the options file is appended to the `FormatReader.getUsedFiles` API rather than being prepended. The rationale for doing so is that the `ImageReader.getRequiredDirectories()` determines the reader on the first file in this list. Without this change, `FormatReaderTest.testRequiredDirectories()` was failing with an …

Options: test-suite improvements

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

See https://forum.image.sc/t/problem-reading-some-dm4-files-in-bioformats-6-4-0/36590
This commit tries to address issues with variants of the DM4 file formats which likely were not available when support for montage was added in #3337.
This should be tested using the new sample files uploaded in the image.sc thread as well as checking for regressions using the other DM4 montage sample files.

Gatan DM4: fix support for montages with single Z dimensions

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This request was raised in forum thread https://forum.image.sc/t/scene-numbering-in-omero-from-multi-scene-czi-files/41794
The PR switches the image name which is Scene #0, Scene #&#x2060;1 etc to be 1 indexed. It also adds zero padding when necessary.
As far as I can find we only have 2 datasets in the repo which use this scene number and unfortunately both only have a single digit number of scenes.
To test you can use either of the below:
```
zeiss-czi/zeiss/zen-2012/Multiscene/Mouse-kidney-3-scene_VivaTome_1chZS.czi
zeiss-czi/qa-27169/226-0903_wt_DAPI_0_DsRED_tdT_0_CB-Scene-1-ScanRegion0.czi
```
The updated value can be seen when viewing the Image Name in the OME-XML using (note noflat must be set) :
`showinf -noflat -nopix -omexml path/to/file.czi`

CZI: Pad scene number and switch to 1 indexed

---

components/formats-api/src/loci/formats/ClassList.java
components/formats-api/src/loci/formats/ImageReader.java
components/formats-api/test/loci/formats/utests/ClassListTest.java

Fixes #3580 
This PR reviews the output `git grep -i whitelist` and `git grep -i blacklist`. Proposed changes are quite small and contained but will require a minor version increment due to the API addition.
- add new `ClassList.isAllowedKey(String)` API
- deprecate `ClassList.isWhitelistedKey(String)` and forward it to the new API
- update `ClassListTest.isAllowedKeys()` unit test
- remove blacklist inline comment

Review all instances of whitelist/blacklist

---

components/formats-bsd/src/loci/formats/in/BMPReader.java

Noticed in passing while fixing something else.  Super low priority, just faster to write a PR than an issue.
Without this PR, on a BMP larger than 2 GB:
```
$ showinf -crop 2048,2048,512,512 test.bmp
...
Exception in thread "main" java.lang.IllegalArgumentException: Negative position
at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:712)
at loci.common.NIOByteBufferProvider.allocateDirect(NIOByteBufferProvider.java:127)
at loci.common.NIOByteBufferProvider.allocate(NIOByteBufferProvider.java:112)
at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:647)
at loci.common.NIOFileHandle.seek(NIOFileHandle.java:330)
at loci.common.RandomAccessInputStream.seek(RandomAccessInputStream.java:203)
at loci.formats.in.BMPReader.openBytes(BMPReader.java:125)
at …
```

BMP: fix offset calculation for files larger than 2 GB

---

components/formats-api/src/loci/formats/in/DynamicMetadataOptions.java
components/formats-api/test/loci/formats/utests/DynamicMetadataOptionsTest.java

Discussed during the weekly Formats meeting,
- 6f1716c and be2b2bd address the concern initially raised in https://github.com/ome/bioformats/pull/3605#discussion_r501092971 by making option filenames unique
- b51a2f6 is a minor fix for a warning discovered during testing and should avoid unnecessary warnings related to the `IniList` way of storing headers

Optionsfiles fixes

---

components/formats-bsd/src/loci/formats/in/APNGReader.java

Following an investigation on a hanging import of a PNG, this bug addresses an issue when opening the pixel data of a PNG in tiles and the requested tile height is not a multiple of 8. Under some conditions, this could lead to a height larger than the image height passed to the `APNGReader.decode` and the reader hanging.
This PR should fix the behavior by capping the height passed to `APNGReader.decode` to the image height. It also adds some  preliminary checks to the `APNGReader.decode(PNGInputStream, int, int)` to throw an exception if the dimensions are too large.
Without this PR, some PNG files would fail an OMERO import, hanging during the tile-based min/max calculation step and freezing a server thread indefinitely. With this PR included, the same file should import successfully. …

APNGReader: fix hanging openBytes call

---

components/formats-gpl/src/loci/formats/in/BDReader.java
components/formats-gpl/src/loci/formats/in/CellomicsReader.java
components/formats-gpl/src/loci/formats/in/FlexReader.java
components/formats-gpl/src/loci/formats/in/MIASReader.java

Noticed while working on https://github.com/glencoesoftware/bioformats2raw/pull/69.
Older HCS readers didn't set ```Plate.Rows``` and ```Plate.Columns```, since those values are optional and were introduced in the 2010-04 schema.  The only remaining reader that sets ```Plate.ID``` but not ```Plate.Rows``` and ```Plate.Columns``` is ```CellH5Reader```, but I suspect all of the plate population needs to be rewritten there so will save it for a later date.
Tests should continue to pass, and this should be safe for a patch release.

Populate plate row and column dimensions

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This issue was raised in forum thread https://forum.image.sc/t/error-during-opening-an-nd-file/7131
A sample file was provided via ftp and is located at `repos/curated/metamorph/imagesc-wafle-2020-08-18`. This new dataset will be configured and added to the data repo tests as a follow up.
The bug was caused because the dataset contains multiple series, which had varying dimensions, particularly the effective size C for each differed. This meant that the calculation for the laser index was incorrect. As I believe the value should always be incrementing then basing the index on the existing size should correct for this.
To test:
- All other repo tests should remain green and unaffected
- Without this PR trying to import the file will result in an IndexOutOfBoundsException
- With this PR …

MetaMorph: Correct laser index for multi series datasets

---

components/formats-gpl/src/loci/formats/in/ND2Handler.java

Issue was raised in forum thread https://forum.image.sc/t/command-line-bfconvert-to-convert-nd2-to-tif-java-error/43728/3
A sample file is available in QA-29634 which reproduces the reported bug in BF 6.5.1
To test:
Using the file in QA-29634 attempt to open the image using BF 6.5.1, this should throw a NullPointerException
With the PR included repeat the above and the file should open and display without exception. A warning message will be logged: `[WARN] Could not parse Power value: -nan(ind)`

ND2Handler: Catch NPE when parsing key value pairs

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/TecanReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java
pom.xml

Backported from a private PR.  The new reader adds support for data from this acquisition system: https://lifesciences.tecan.com/plate-reader-live-cell-imaging-cytometry
Plates consist of a sqlite database file, a directory hierarchy containing TIFFs, and optional analysis results in various formats.  Only the sqlite database can be accepted by ```setId```.  No test data yet, but opening the PR now to verify that no existing tests are affected.
As this is a new reader with a new dependency, a minor release will be necessary.

Add Tecan Spark Cyto reader

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/UpgradeChecker.java
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#121](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/121/).
----
--no-rebase

Update POM version numbers to 6.6.0

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml
components/bundles/bioformats_package/pom.xml
components/bundles/loci_tools/pom.xml
components/forks/turbojpeg/pom.xml
components/formats-api/pom.xml
components/formats-bsd/pom.xml
components/formats-gpl/pom.xml
components/test-suite/pom.xml
pom.xml

Generated by build [BIOFORMATS-DEV-latest-version-bump#122](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-latest-version-bump/122/).
----
--no-rebase

Update POM version numbers to 6.6.1-SNAPSHOT

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This PR is attempting to fix an issue raised in https://forum.image.sc/t/bioformats-high-memory-use-for-nd2-files/47187/1
There is a large sample file available which I will make available for testing.
The change is really a follow up to https://github.com/ome/bioformats/pull/1351 and expanding on that logic. I have initially opted for adding an additional condition which complicates the logic but should be the least likely to cause any regressions. If tests continue to pass with this initial commit then I will probably try to loosen and simplify the conditions.

ND2: reset series count to limit offsets

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

Calls to ```addSeriesMeta``` depend upon the current core index, so a call to ```setCoreIndex``` is necessary.
To test, check the ```view.offset*``` keys for each series when running ```showinf -nopix -noflat -series n``` with and without this PR.  Without this PR, only the first series will have ```view.offset*``` keys.  With this PR, all series will have ```view.offset*``` keys and the values should correspond to the OME-XML ```PositionX``` and ```PositionY``` values reported by ```showinf -nopix -noflat -omexml```.
This shouldn't fail builds, and should be safe for a patch release.

Leica SCN: set core index correctly when populating original metadata

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

Existing comment on line 390 indicates that the image position and size values stored in XML are in nm.  This can be verified by comparing the ```view.sizeX``` and ```view.sizeY``` values with the image width, height, and physical pixel size stored in the corresponding IFD. 
A configuration PR is forthcoming, but otherwise tests should continue to pass and this should be safe for a patch release.

Leica SCN: change position units from reference frame to nm

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

Backported from a private PR.  This adds another way to pick the correct band from NDPI files in an NDPIS dataset when the emission wavelengths are missing.
The behavior without this PR was to always pick the first band if the wavelength was not present.  To test, compare ```showinf``` on the ```hamamatsu/svidro``` dataset with and without this PR.  The first two channels in that dataset do not have a defined wavelength.

NDPIS: use transmittance values to pick valid channels if no wavelength

---

components/formats-gpl/src/loci/formats/in/MetaxpressTiffReader.java

Backported from a private PR.  Handles the case when thumbnail files are named ```*_Thumb.TIF```.
Tests should continue to pass, and should be safe for a patch release.

MetaXpress/CellWorX: ignore case when checking for thumbnail paths

---

components/formats-gpl/src/loci/formats/in/CV7000Reader.java

See ```inbox/idr0093/020/```, discussed with @sbesson.  This seems to fix the order of planes returned by ```openBytes``` without affecting channel ordering in the OME-XML.  No idea what if any impact this will have on other CV7000 data though, so may need further adjustment if tests fail.
Note also that the affected dataset actually has 5 channels of TIFF files, but only 4 defined in metadata.  The fifth channel will be ignored completely; the corresponding files will not be preserved on import.  I don't think the reader can realistically do anything about that.
Discussed with @sbesson that the memo file impact here is a little unpleasant.  Memo files won't be invalidated, but trying to use this change with an old memo file means that the fix just won't appear.

CV7000: fix channel-wise ordering of planes

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

```ChannelName_c```, with 0 <= c < channel count.  Test dataset (also in ```curated/fake/samples/channel-name```):
```
$ ls -hl
total 4.0K
-rw-rw-r-- 1 melissa melissa  0 Mar 15 13:21 test&sizeC=3.fake
-rw-rw-r-- 1 melissa melissa 73 Mar 15 13:23 test&sizeC=3.fake.ini
$ cat test\&sizeC\=3.fake.ini 
[series_0]
ChannelName_0 = DAPI
ChannelName_1 = Cy5
ChannelName_2 = FITC
```
```showinf -nopix -omexml test&sizeC=3.fake``` should show OME-XML channel names matching the channel names in the INI.

Fake: allow channel names in series tables

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

Backported from a private PR.  Sometimes XML blocks end with CRLF, which prevented following pixel blocks from being detected - see line 646.
I don't have a relevant test file that can be shared, so the main thing to check is that tests pass and the code change isn't worrying.  In the original test case, metadata was parsed correctly (so plane counts etc. were fine), but none of the pixel blocks were detected so all planes were blank.  None of the other .oir missing pixel block issues describe quite the same behavior, but it's maybe possible that #3242 could be helped by this.  https://trello.com/c/DaXFseys/265-import-issue-with-oir-file-in-imagej-qa-21654 for sure is not fixed.

OIR: trim XML blocks

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

This commit tries to address the remaining issues discussed at https://github.com/ome/bioformats/pull/3032#issuecomment-802096824.
This commit tries to address a scenario where the ND filename contain underscores and unrelated TIF/STK files starting with part of the ND prefix are present in the directory. For instance with the following layout,
```
benchmark_v1_2018_x64y64z1c1s1t1.tif 
benchmark_v1_2018_x64y64z1c2s1t11.nd
benchmark_v1_2018_x64y64z1c2s1t11_w1Laser4054BD4BP.tif
benchmark_v1_2018_x64y64z1c2s1t11_w2Laser4914BD4BP.tif 
```
the current `initFile()` logic would detect the unrelated `benchmark_v1_2018_x64y64z1c1s1t1.tif` as the binary file to initialize.
The proposed fix reviews the code path selecting the STK/TIFF file associated with a ND file and enforces the following rules: …

MetamorphReader: improve the detection of companion binary files

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

See https://forum.image.sc/t/tiff-file-fails-to-open/50416 for a TIFF file failing to open with Bio-Formats
As suggested by @cgohlke in https://forum.image.sc/t/tiff-file-fails-to-open/50416/3, the issue is that `FillOrder` is lsb2msb and the bytes need to be reordered before decompression.
e0c2e8e proposes to extend the scope of https://github.com/ome/bioformats/pull/3306 to handle TIFF files with Deflate compression (codes 8 and 32946).

TiffParser: handle Deflate compressed tiles/strips with lsb2msb order

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

Fixes #3669 
Since the creation of the EmissionFilter metadata is conditional to the
barrierFilter value, this commit ensures a filterIndex variable is initialized
and incremented independently of the channelIndex variable.
Using the sample files uploaded as part of the corresponding issue and either `showinf -nopix  -omexml` or `omero import`:
- one file should fail and the other should read successfully without this PR
- both files should be successfully read with this PR

FV1000Reader: do not assume channels and filters have matching indexes

---

components/formats-gpl/src/loci/formats/in/NDPISReader.java

Backported from a private PR.  Sometimes the ```NDP Shading Data``` block has a channel name that isn't present in the channel name tag.

NDPIS: use channel names from "NDP Shading Data", if available

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

Fixes #3438
To test, use ```showinf -nopix -debug``` on .vsi files in ```inbox/gh-3438```.  Without this PR, an exception should be logged as noted in #3438.  With this PR, there should be no exception.
I would not expect any test or memo file impact; this should be safe for a patch release.

CellSens vsi: fix offset check to prevent seeking beyond EOF

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java

This logic was originally added in #1716.  Original test data for that PR is now added to ```curated/tiff/qa-7589```, and an additional test for this PR is in ```curated/tiff/samples/melissa/imagej-units/1000cmx1000cm-test.tif```.
```showinf -nopix -omexml``` on the files from QA 7589 should show no change in physical pixel size and units with or without this PR.  ```showinf -nopix -omexml``` on ```1000cmx1000cm-test.tif``` without this PR should show physical pixel sizes of 20000cm; with this PR, they should be 20000um == 2cm.
As far as I can tell, this is specific to ImageJ TIFFs with unit set to ```cm``` in the ```Image Properties``` window.

TIFF: only use ImageJ comment units if RESOLUTION_UNIT tag unclear

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Similar strategy as OMERO uses by default, but supports 6 different colors using narrower wavelength ranges.  See table on page 1 of https://www.perkinelmer.com/CMSResources/Images/44-6551APP_PhotocellApplicationNotes.pdf; this should be a better match for the colors shown by Columbus.
To test, use any of the ```curated/perkinelmer-operetta``` plates and verify that ```showinf -nopix -omexml``` shows a valid ```Color``` on each ```Channel```.

Operetta: populate channel color using emission wavelength

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

See https://forum.image.sc/t/opening-images-from-a-yokogawa-cq1-with-bio-formats/52615/
This PR deals with the case of a multi-file OME-TIFF fileset distributed over multiple folders, where the master file containing the metadata is up one directory from the individual files referring to it using the `BinaryOnly.MetadataFile` element.
53621b2 adjust the current directory to use the directory of the metadata file. This allows to compute all the  paths of the TiffData elements relative to this directory.
bd13a7c  also uses `getCanonicalPath()` to resolve the relative paths stored in `BinaryOnly.MetadataFile`
7c28bcc sets the `currentId` to the master metadata file. This is not a rquirement for the fix and can be reviewed/discussed separately if problematic. 
A sample fileset can be …

Update directory for OME-TIFF filesets with BinaryOnly across multiple folders

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

After updating the nd2 format document, the timestamps in the xml document metainfo became incorrect. 
DeltaT is OK:
DeltaT is very very small(Not OK): 
After investigation, it was discovered that the problem was that the timestamps data in the document was searched for by the keyword "CustomData|AcqTimesCache". However, because when identifying it, not the whole keyword was used, but only its beginning "CustomData|A", the application found the wrong keyword and, as a result, incorrect information about the timestamps .

ND2 Reader timestamps data reading issue

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This PR tries to address a regression in the Deltavision reader introduced in Bio-Formats 6.2.0.
Initial support for multi-stage positions was introduced in https://github.com/ome/bioformats/commit/1e6686286760bbac249a64c05e42b5af6ec5a8a2. https://github.com/ome/bioformats/pull/1324 introduced some special handling of cases where some coordinates are equal to 0 and https://github.com/ome/bioformats/pull/3398 added support for detecting backward stages in X.
A representative sample files was uploaded as part of an IDR submission where `uniqueTileX.size()` is 1, `uniqueTileY.size()` is 3 and `hasZeroX` is true. As per the following block
https://github.com/ome/bioformats/blob/b68a64959b9f17ceb6b9cb57c15d7b46b56f23ed/components/formats-gpl/src/loci/formats/in/DeltavisionReader.java#L506-L516 …

Deltavision: fix IndexOutOfBoundsException

---

components/formats-bsd/src/loci/formats/ChannelFiller.java

Fairly certain this will resolve https://trac.openmicroscopy.org/ome/ticket/13258
An underlying format reader's ```getBitsPerPixel()``` applies only to what it returns in ```openBytes```.
The lookup table may contain a larger range of values, so ```getBitsPerPixel()``` now returns
the full pixel type width any time a lookup table is applied.
I would not expect this to have any impact on tests or memo files.  Comparing the output of ```showinf -expand -minmax``` on https://trac.openmicroscopy.org/ome/raw-attachment/ticket/13258/tartan.png with and without this PR should confirm that:
- without this PR, bits per pixel is 4
- with this PR, bits per pixel is 8
- the max pixel values with lookup table applied are greater than 15

ChannelFiller: reset bits per pixel if a lookup table is applied

---

components/formats-bsd/src/loci/formats/in/FilePatternReader.java

To test, use something like:
```
$ cat test.pattern
c<DAPI,FITC>.fake
$ showinf -nopix -omexml test.pattern
```
and verify that channel names are set to ```DAPI``` and ```FITC```.  This will only work when using a pattern file, not with ```showinf -stitch c<DAPI,FITC>.fake```.  I'm not completely opposed to adding this feature to ```FileStitcher``` instead, it just seems simpler and less breaking in ```FilePatternReader```.

Pattern reader: populate channel names from pattern tokens

---

components/formats-api/src/loci/formats/services/OMEXMLServiceImpl.java

Before this change OME schema references for
"http://www.w3.org/2001/xml.xsd" lead to throttled downloads.
After this change an embedded copy from specifications.jar
should be used instead.
This seems to be a more generic solution than what I proposed for #3699 earlier and it does seem to work as well (maybe a tiny bit slower due to the additional catalog processing but still much faster than the initial throttled download).
Again I only half know what I am doing here so I'd appreciate a thorough review of the changes.

OMEXMLService: Use XML catalog in specifications.jar

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Prevents inconsistent resolution counts between the reader and MetadataStore.
This demonstrates the problem:
```
$ bfconvert "test&sizeX=8000&sizeY=8000&resolutions=4.fake" test-pyramid.ome.tiff -noflat
$ bfconvert test-pyramid.ome.tiff -series 0 test-pyramid-series-0.ome.tiff
...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
at loci.formats.out.PyramidOMETiffWriter.close(PyramidOMETiffWriter.java:128)
at loci.formats.ImageWriter.close(ImageWriter.java:469)
at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:749)
at loci.formats.tools.ImageConverter.main(ImageConverter.java:1095)
```
With this PR, the re-running the second ```bfconvert``` command should result in a readable output file with no exception.
Comparing ```showinf -nopix -omexml …
```

OME-TIFF reader: remove resolution annotation when resolutions are flattened

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Setting ```zeissczi.relative_positions``` to true will change the ```PositionX``` and ```PositionY``` values stored in OME-XML to the pixel position instead of the absolute physical stage position.  Setting ```zeissczi.trim_dimensions``` to true will use the pixel block metadata to trim XY dimensions to match what ZEN reports.
Default behavior shouldn't change, so tests should continue to pass.  Comparing e.g. ```zeiss-czi/zeiss/jpeg-xr/*2scenes*.czi``` in ZEN and with each combination of options should be enough to test.  The idea is that with both options set to true, it would be easier to place the images on a canvas just like ZEN does when the ```Scene``` box is unchecked.  As far as I know, ZEN doesn't report the sizes for each individual scene, you have to actually mouse over the …

Add a few options for working with CZI files that have multiple scenes

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
components/test-suite/src/loci/tests/testng/Configuration.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

To test, use any of the files with updated configurations from the forthcoming configuration PR.  Most have more than one resolution per field; it's also not uncommon to have an attachment image similar to a slide overview, although it doesn't look like any of the plates in the repo have this.
The test change allows for series to be marked as unlinked from a plate by design, by setting ```Plate = -1``` explicitly.  Omitting ```Plate``` from the configuration or setting ```Plate = 0``` should behave as before.

Zeiss CZI: detect plates

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Issue was raised on imagesc thread https://forum.image.sc/t/incorrect-default-color-for-channels-when-opening-nd2-images/50734/8
A sample image was provided via Zenodo, when opened with Bio-Formats 6.6.1 the channel names and colours are missing from the OME-XML metadata and the fourth channel displays as Red rather than Magenta.
With this fix the metadata should be present and the colour correct.
To test:
- Using the provided sample check that without this PR the OME-XML Channels are missing the properties Name and Color
- With this PR included the Name and Color values are populated and correct
- Without this PR the 4th channel should display as Red, with the PR included it should be Magenta

ND2: Always fall back to check channel names

---

components/formats-gpl/test/loci/formats/utests/xml/2008-09.ome
components/formats-gpl/test/loci/formats/utests/xml/Upgrade200809Test.java
pom.xml

This is a follow up to https://github.com/ome/ome-model/issues/142
From the 2003-FC spec the CustomAttributes can be positioned in 4 different places. The CustomAttributes which are not at the top level must be copied there before transforming to XMLAnnotations. 
These tests should fail until a transform fix has been included with OME-Model.

200809-Transforms: Add tests for custom attributes

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

See https://forum.image.sc/t/bio-formats-and-lavision-ultramicroscope-ii-issue-a-bug/57663
Debugging the sample file indicates that there is a discrepancy between the number of IFDs reported by `tiffinfo` (820) versus `TiffParser.getMainIFDs` (1) which explains the error message and the zero-value behavior described in the issue.
Looking at the file, the first series IFDs offsets is `3309764368 8068354 12104652 16140950` and the code adjusts for the second offset via the following block which specifically handles the case of non-sequential IFDs for large TIFFs:
https://github.com/ome/bioformats/blob/b67dfcac19b898e9a8e2481e5288bdc4b7aa782d/components/formats-bsd/src/loci/formats/tiff/TiffParser.java#L1392-L1397
I suspect the issue lies with the usage of `Integer.MAX_VALUE` which is the …

TiffParser: fix non-sequential offset correction for TIFF files between 2 and 4 GB

---

components/formats-gpl/src/loci/formats/in/ND2Handler.java
components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

This PR fixes https://github.com/ome/bioformats/issues/3502 issue. 
The solution was tested on the .nd2 documents that I had in my possession. In particular, those that were shared in the issue on the GitHub. The pull request will need to be tested with files from QA-29035 if its possible(I don't have an access to this).
For new documents that do not use xml as metadata, the parser has been changed, as a result of which the order of the demensions is read directly from the metadata (Previously, they were read from the information in the document description).

ND2 Reader Incorrect dimensions

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

This Pr aims to fix the scenario of a partial multi-file OME-TIFF fileset where the master file initialized by `setId` has no `OME.UUID` value. With the current release of Bio-Formats, the reader gets initialized and all the planes associated with the missing files gets silently and erroneously assigned to the initialized file.
The proposed fix offers two behaviors controlled by a new reader option `option ometiff.fail_on_missing_tiff`. In the strict behavior (default), the reader will fail at initialisation and provide a meaningful error about the first missing file (previously `Unmmatched UUID: <uuid>`. In the lenient behavior, all planes associated with the missing  files will be read as blakc.
87b23d9 fixes this behavior by setting an unitialized `currentUUID` (initialized with the …

OME-TIFF: fix handling of partial filesets

---

components/formats-bsd/src/loci/formats/tools/AmiraParameters.java

This issue was raised on forum thread https://forum.image.sc/t/bio-formats-cant-open-newer-am-files-version-3-0/50585
Newer Amira files have metadata keys which begin with the “&” character, for example “&Pixels_per_meter__X_”.
When Bio-Formats tries to read these values it throws an Invalid Key Exception as below:
`loci.formats.FormatException: Syntax Error:19:10: Invalid key`
Sample files have been provided which reproduce the issue. 
To test:
- With Bio-Formats 6.6.1, attempting to read the BF_CheckAmira.am file will result in the Invalid Key exception
- With this PR included the file will be read without exception
- With this PR the metadata for both BF_CheckAmira.am and BF_CheckMIB.am should be the same
A follow up config PR will add the new samples to the repo tests

Amira: Support for Amira 3.0 keys

---

components/formats-bsd/src/loci/formats/out/AVIWriter.java

This PR is in response to an Issue raised (https://github.com/ome/bioformats/issues/3702)
With the sample file provided you can see the time increment is 0.039 which matches the plane delta T times, however when the file is converted to an AVI the resulting file plays with an fps value of 10 which is the default for all format writers.
With this PR the converted sample file should now playback for ~5secs with the correct fps set.
fixes https://github.com/ome/bioformats/issues/3702

AVIWriter: Set fps from Pixels Time Increment

---

components/formats-gpl/src/loci/formats/in/OIRReader.java

This issue was raised on forum thread https://forum.image.sc/t/nullpointerexception-when-opening-oir-files-with-bio-formats/58487 and a sample file was provided which reproduces the exception with Bio-Formats 6.7.0
To test:
- Builds and repo tests should remain green
- Without this PR opening the sample file from the thread should result in `java.lang.NullPointerException`
- With this PR included the file should be opened without exception and the pixel and metadata look sensible

OIR: Fix NullPointerException for Laser Data ID

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Backported from private PRs.
The v6 schema appears to have refactored a bunch of common metadata out of the individual ```Image``` elements and into common ```Channel``` elements (not unlike the OME model).  In addition, orientation matrix application is restricted to non-Phenix data, which should help with #3483.
I wouldn't expect test failures since I don't think we have any v6 data in the repository yet.  I don't have a shareable dataset yet, but can try to make one if needed.

OperettaReader: add support for Phenix v6 data

---

components/formats-gpl/src/loci/formats/in/SVSReader.java

Backported from a private PR.  Instead of assuming that exactly two extra images (label and macro) exist, this adds a check on the IFD descriptions for any non-pyramid IFDs to determine whether a label and/or macro exist.
I would not expect this to cause any test failures ~or memo file changes~, but it may help with #3682.

SVS: check for label/macro instead of assuming they exist

---

components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Ported from a private PR.  Adds support for both zstd variants in Zeiss CZI, using https://github.com/airlift/aircompressor to do the actual decompression.
Test data for ZSTD0, ZSTD1, and corresponding uncompressed data is being uploaded to ```inbox/zeiss-czi-zstd```.  Compressed data should mostly match the corresponding uncompressed data (comparing MD5s/pixel values).  The ```/LLS*``` datasets are an exception due to how they were exported, but should match visually despite the pixel value differences.
I'd expect this to require a minor release since there is a new dependency.

Zeiss CZI: add support for zstd compression

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

This solves the problem in #3708, but it may also be helpful to add a check and error message to the command-line tools and top-level API entrypoints when requested tile sizes are not a multiple of 16, to prevent unexpected results.
Fixes #3708

Use multiple-of-16 tile dimensions when writing TIFFs

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/OIRReader.java
components/formats-gpl/src/loci/formats/in/OlympusTileReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Backported from private PRs.  Support for this format was added in partnership with OLYMPUS EUROPA SE & Co. KG.
The .omp2info file is XML that allows .oir files to be stitched together.  Opening/importing an .omp2info should automatically detect and stitch the .oir files, but opening/importing an .oir file will not attempt to detect an .omp2info.  The documentation page may need to warn about importing a whole directory of data in these formats in OMERO.
Datasets are in ```inbox/olympus-new``` and configuration is forthcoming.  Some metadata parsing needed to be added to ```OIRReader```; the dataset that uses the new timestamp logic is in ```2021-07-19```.  This ImageJ plugin can be used to verify correct behavior:
https://imagej.net/formats/olympus

Add Olympus omp2info reader

---

components/formats-bsd/pom.xml

See https://github.com/scijava/pom-scijava/issues/181
Also explicitly declare common-langs as dependency. It was previously coming as a transitive dependency of cisd:jhdf5:14.12.6 and is used across a few readers.
The `JHDF5Service` consuming this library is in-use for two formats: `CellH5` and `BDV`

Bump cisd:jhdf5 to version 19.04.0

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

This is an attempt to fix the issues reported in https://forum.image.sc/t/bio-formats-vsi-olympus-cellsens-bug/29879/5 and previously on Trello card https://trello.com/c/v47N2hGC/382-vsi-incorrect-metadata-posz-and-exp-time
Initially this is simply setting the physicalSizeZ based on the zIncrement value which is already being parsed.

CellSens: Set physicalSizeZ

---

components/formats-gpl/src/loci/formats/in/GatanReader.java

This issue was raised on forum thread: https://forum.image.sc/t/gatan-dm4-files-wont-open/55627/3
The issue was related to the parsing of metadata values. In this case some of the position where as below:
- -199.355 (This String contains extra null 0 bytes in between each char)
- -199.355 (The same String with the null bytes removed parses without exception)
A sample file was provided which I will include in the data repo and a config PR is to follow before review

Gatan: Strip null chars from value string

---

components/formats-bsd/src/loci/formats/tiff/IFD.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java
components/formats-bsd/src/loci/formats/tiff/TiffSaver.java

This PR aims to address https://github.com/ome/bioformats/issues/3752 while slightly improving TIFF read/write performance.
The performance impact when using JPEG compression can be much bigger when combined with https://github.com/ome/ome-codecs/pull/19
To test, I converted *CMU-1-Small-Region.svs* and *CMU-1.svs* to JPEG with 2 pyramid levels (to avoid memory errors) with bfconvert, with and without the `-no-sequential` flag on a MacBook Pro (M1). I also converted the larger image with Bio-Formats via QuPath.
The changes here were made after using VisualVM to identify which aspects of conversion were slow. Sampling with VisualVM suggested the modifications helped reduce time spent in the relevant methods, and pushed compression/decompression to be the main bottlenecks (along with …

Tiff performance

---

components/formats-gpl/src/loci/formats/in/SVSReader.java

This is a rather simplistic attempt to deal with the issue detected in https://github.com/ome/bioformats/issues/3757
If no image description is present then it will try to treat the series as a label or macro.
Fixes https://github.com/ome/bioformats/issues/3757
To test:
- All existing builds and repo tests should remain green
- Test manually with the new sample file from the thread (also included in the new config PR)
- Test with the sample files impacted by the original PR in https://github.com/openmicroscopy/data_repo_config/pull/503

SVS: Detect label and macro if no image description

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

ND2 metadata parsing fixes

---

components/formats-gpl/src/loci/formats/in/FEITiffReader.java

I don't yet have a file that can be used for testing, but as the title suggests this should fix a problem with pixel sizes not being detected in TIFFs acquired by FEI/Thermo Fisher/? Phenom instruments.  The XML schema for Phenom metadata is slightly different from other FEI TIFFs.
I would not expect this to cause test failures or memo file issues.

FEI TIFF: fix physical pixel sizes for Phenom data

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

This PR is in response to an issue raised on forum thread https://forum.image.sc/t/operetta-bioformats-reading-error-with-big-dataset-and-xml-parsing-crazy-slow/62768/3
In this case the initial XML file is > 800Mb, reading the entire file into a byte array and then String was very memory intensive and time consuming. Reading it in from a Stream provide much improved performance. Without this PR I was struggling to profile the issue as I would run into out of memory exceptions even with what should have been plenty of available memory (8Gb).
With the PR the initial parsing completes in around 26 seconds without the same memory issues.
The later indexing of each of the planes in the dataset still however takes a long time, I will continue profiling that code section to see if further …

Operetta: Use stream for parsing XML

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Backported from a private PR. Test datasets in ```inbox/perkinelmer-phenix```, see corresponding readme for acquisition details.
Different subsets of channels may be acquired at different timepoints. This PR should make it so that the reader no longer assumes that all channels are acquired at all timepoints, which means that the first ```SizeC``` planes are not necessarily representative of a well's field.
Without this change, ```showinf -nopix -omexml``` on either of the test datasets should show that the name/color/wavelengths for the third channel are missing in the OME-XML.  With this change, all 3 channels should be fully populated across the whole plate.
This follows on from the initial Phenix v6 support in https://github.com/ome/bioformats/pull/3734. I would expect this to be safe …

Operetta/Phenix: allow for sparse planes

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java

Backported from a private PR.  This addresses the pyramid performance problem discussed with @sbesson.
Any time a SubIFD contains large amounts of non-pixel data (e.g. a full copy of the OME-XML), ```openBytes``` is slowed down substantially.  This changes the SubIFD reading in ```openBytes``` to only request a single SubIFD, and not even try to read the corresponding ```ImageDescription``` tag since it will be ignored anyway.
7cee004 is a minor improvement to reduce the number of tiles that are checked when reading pixel data.  It could be reverted if any objections.
I wouldn't expect this to address other issues with OME-TIFF read performance, but maybe points to IFD size instead of modality as a point for further investigation.
I would not expect tests to fail or memo files to be …

Improve tile read speeds for some pyramid OME-TIFFs

---

components/formats-gpl/src/loci/formats/in/LIFReader.java

Proposed fix for #3513. Also a change in how laser indices are calculated in the absence of a qualifier. The main reason for the latter is I think this helps line 754 evaluate properly.

Display all channel info in .lif metadata

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

* Avoids a N^2 algorithm by using a hashmap to find the correct plane
* Very significant speedup for big dataset (k.100 000 planes), from 30 minutes to 30s with a 800 Mb xml file

Improves performance of OperettaReader

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Without this PR, creating a fake plate:
```
bfconvert "test&plateRows=16&plateCols=24&fields=40.fake" "test_s%s.ome.tiff" -option ometiff.companion true
```
and then attempting to initialize:
```
showinf -nopix -omexml test_s0.ome.tiff
```
throws an exception due to too many open files. With this PR, the same ```showinf``` command should eventually display OME-XML without an error.
@sbesson reported seeing a similar problem with real data, so hopefully this fixes that case too.

OME-TIFF reader: reduce open file handle count during setId

---

components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/MINCReader.java
components/formats-gpl/test/loci/formats/utests/NetCDFServiceTest.java

bump version

---

components/formats-bsd/src/loci/formats/in/FakeReader.java

If it's at the beginning of initFile, then the sleep happens before `sleepInitFile` can be parsed.
Noticed while trying to write a test for https://github.com/glencoesoftware/bioformats2raw/issues/136.
Compare `showinf test&sleepInitFile=1000.fake` with and without this PR; with this PR, the printed initialization time should be approximately 1 second longer.

Fake: move configurable sleep to the end of initFile

---

components/formats-gpl/src/loci/formats/in/ZeissLSMReader.java

Fixes #3604.
Compare the pixel type and values in QA 29464 with and without this PR. It doesn't look like we have any other 32 bit .lsm files that would be affected.
I'd expect this to be safe (but low priority) for a patch release.

Zeiss LSM: assume 32 bit data is floating point

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Backported from a private PR. This should result in a white background for brightfield data (instead of black), which better matches Zen and other software.
There are a few different ways we can check for a brightfield pyramid (including by channel name),
but checking for RGB + multiple resolutions seems to be reliable so far and does not require a
memo file update.  @swg08 if you have any thoughts on a better way to determine the correct fill color in general, I'd be happy to hear them.
I would expect some MD5 test failures, and will open a matching configuration PR after the tests have run once.

CZI: use fill color of 255 when brightfield data is suspected

---

components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Fixes #3792.
To test, pick an existing configured directory of test data, or set up something simple:
```
$ export TEST_DIR=~/tmp-test
$ mkdir $TEST_DIR
$ touch $TEST_DIR/test.fake
$ ant -Dtestng.memory=1g -Dtestng.directory=$TEST_DIR -Dtestng.configDirectory=$TEST_DIR test-config
```
Run ```ant -Dtestng.memory=1g -Dtestng.directory=$TEST_DIR -Dtestng.configDirectory=$TEST_DIR test-fast``` without this PR and note that 10 tests are skipped, and the log file in `components/test-suite/target` does not reference all of the tests in the `fast` group (e.g. `ChannelNames`, `ExposureTimes`).
Run the same `test-fast` command with this PR; there should be no skipped tests, and all tests in the `fast` group should be in the log file.

Automated tests: make sure the file is initialized before all tests

---

components/formats-gpl/src/loci/formats/in/CellWorxReader.java

To test, use ```metaxpress/samples/multi-channel-test/multi-channel.HTD```. Without this PR, ```showinf -nopix -omexml``` should show 2 channels in the OME-XML, but only the first has an ```EmissionWavelength```. With this PR, the same command should show that both channels have an ```EmissionWavelength``` set, and that the two wavelengths are different. The wavelengths can be compared against the configuration for the original pixels files (see ```metaxpress/samples/multi-channel-test/readme.txt```).

CellWorX/Metaxpress: Read metadata from one file per channel, to preserve all channel data

---

components/formats-gpl/src/loci/formats/in/CellomicsReader.java

See https://github.com/glencoesoftware/bioformats2raw/issues/139#issuecomment-1068319934
Using Java 17 without this PR:
```
$ cat test.pattern
test_c<1-3>.fake
$ showinf -cache test.pattern
...
failed to save memo file: /Users/melissa/test-case/.test.pattern.bfmemo
...
```
The same test with this PR should successfully save the memo file.
Technically breaks memo files (to fix them!), so probably not OK for a patch release.

Make private Pattern field transient

---

components/formats-bsd/src/loci/formats/in/BaseTiffReader.java
components/formats-bsd/src/loci/formats/tiff/TiffParser.java

Compare `showinf -nopix -noflat | grep SampleValue` on the files in `curated/vectra-qptiff/public/perkinelmer` with and without this PR. With this PR, the results should match `tiffinfo -0 | grep "Sample Value"` on the same files.
This shouldn't impact memo files, but test results and run times need to be checked since these changes potentially affect all TIFF-based formats.

TIFF metadata fix

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Backported from a few private PRs.
This makes well names more readable now that #3347 is merged, and adds better checks for invalid TIFFs and supplemental metadata files.
I don't think this will conflict with #3775, and it should be OK for a patch release too.

OperettaReader improvements

---

components/formats-gpl/src/loci/formats/in/DeltavisionReader.java

This adds better handling for the case when the calculated XY tile count is smaller than the number of panels (series) and at least one of the axes is acquired in reverse order.
Fixes #3601. Without this PR, `showinf` on the .dv file from QA 29449 should throw an exception as indicated in #3601. With this PR, the same command should successfully initialize and display an image. The dimensions should match what is in the .dv.log file:
```
XY Dimensions:              1024 x 1024
ZWT Dimensions (expected):  1 x 1 x 1
Panels:                     86
```
Assuming tests pass, this should be safe for a patch release.

Deltavision: another fix for incorrect XY tile count detection

---

components/formats-api/src/loci/formats/readers.txt
components/formats-gpl/src/loci/formats/in/HitachiReader.java

Fixes a variety of issues with Hitachi datasets, which consist of one text file and one pixels file (e.g. TIFF):
- allow the text file to be UTF-16 instead of UTF-8 or ASCII
- assume the physical pixel size units are nanometers instead of micrometers
- use `HitachiReader` when a TIFF pixels file is initialized (so it doesn't matter which file in the dataset is chosen)
- log and attempt to handle renamed pixels files
All of these changes can be tested with existing datasets in `curated/hitachi`.
The physical pixel size change can be tested by comparing the physical size against the burned-in scale bar on the images. This is probably easiest to do by opening in ImageJ and drawing a line over the scale bar.
`showinf` on `curated/hitachi/*/*.tif` should now match …

HitachiReader updates

---

pom.xml

These include dependency version bumps that should address https://github.com/ome/openmicroscopy/pull/6328

Bump ome-common and ome-poi versions

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Continuation of #3766.
#3766 introduced degraded `setId` performance for single file OME-TIFF datasets with a larger number of series. `bfconvert "test&sizeZ=20&series=300.fake" lots-of-series.ome.tiff` produces a file that demonstrates the issue.
With this PR, `showinf -nopix -omexml lots-of-series.ome.tiff` should be noticeably faster than the same command using 6.9.1 or 6.10.0. There should also be fewer `Reading IFDs` lines in the `showinf` output with this PR.
The file handle test case in #3766 should still work with these changes, and tests should continue to pass.
Technically should be safe for a patch release, but given how much we rely on OME-TIFF will definitely need some careful testing to make sure this doesn't make anything worse.

OME-TIFF: improve performance with open file handle reduction

---

components/formats-gpl/src/loci/formats/in/NDPIReader.java

Tag 65459 in particular has ASCII type. The tag type may be stored incorrectly in the file, since the value is more consistent with
a LONG type. We have no documentation on this tag, though, so for now just preventing a ClassCastException is enough.
Fixes #3725. Should be safe for a patch release.

NDPI: fix non-number tag handling for files > 4GB

---

components/formats-bsd/src/loci/formats/in/MinimalTiffReader.java

This adds a check for the `Number` class when retrieving the `SubfileType` TIFF tag. Some files incorrectly store an array in this tag, which causes a `ClassCastException` without this PR.
Should be safe for a patch release.

TIFF: prevent ClassCastException if the SubfileType tag has the wrong type

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

This is meant to preserve scene names in the `Image` name, in cases where the scene name has been set during acquisition. I expect to see some test failures which will require a configuration PR (and will indicate which files can be used to test).
These changes should not affect memo files, and should be safe for a patch release.

Zeiss CZI: use scene names as image names

---

pom.xml

Bumping ome-common to 6.0.13 for release to pick up the latest dependency updates.

Bump ome-common version to 6.0.13

---

components/bio-formats-plugins/src/loci/plugins/util/VirtualImagePlus.java

When one loads a virtual image stack and changes the contrast by e.g. the contrast dialog, the changes are lost when the stack is scrolled, which makes it very inconvenient to look at sequences which need contrast adjustment. In classical ImageJ the contrast is retained. I noticed this behavior with 16 and 32 bit bigtiff files but assume it happens for other file formats as well. 
This issue has been mentioned also in [forum.image.sc](https://forum.image.sc/t/b-c-for-a-whole-virtual-stack-cont/57811). 
If one comments [these lines](https://github.com/ome/bioformats/blob/develop/components/bio-formats-plugins/src/loci/plugins/util/VirtualImagePlus.java#L80-L95), all works as expected. The problem seems to be in the fact that `proc.getChild()`'s min and max values do not reflect the set …

VirtualImagePlus: retain contrast in setSlice

---

components/bio-formats-tools/src/loci/formats/tools/ImageConverter.java
components/bio-formats-tools/test/loci/formats/tools/ImageConverterTest.java

Fixes #3746.
This changes how the `-overwrite`/`-no-overwrite` options and corresponding user prompt work with a use case such as `bfconvert  "test&sizeZ=10.fake" "test_z%z.ome.tiff"`. Without this change, running that command twice with any combination of overwriting options will always result in `test_z0.ome.tiff`, `test_z1.ome.tiff`, etc. being appended to instead of deleted/overwritten or left as-is.
With this change, `bfconvert  "test&sizeZ=10.fake" "test_z%z.ome.tiff"` when run twice with any combination of overwriting options should behave the same as `bfconvert "test&sizeZ=10.fake" test.ome.tiff` when run twice with the same options. There should be no case where the second `bfconvert` command appends to files that already existed.
Right now, if neither `-overwrite` nor …

bfconvert: fix overwrite checking when output path is a pattern

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java

Fixes #3838.
This logic did not appear to be used by any files in the current data repo, and causes problems for files with very small images.
Opening the file in #3838 (copied to `curated/nd2/gh-3838`) without this PR should show a single plane. Without this PR and with `nativend2.chunkmap` set to `false`, there should be 5 timepoints as expected. With this PR and default options, there should be 5 timepoints as well.
Probably safe for a patch release assuming tests pass.

ND2: remove chunkmap skipping logic

---

components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/codec/ZstdCodec.java
components/formats-bsd/src/loci/formats/tiff/TiffCompression.java

Implement zstandard decompression for tif files.
Test tif files compressed with zstd in https://surfdrive.surf.nl/files/index.php/s/BYO0qLnHE9H7fhn, together with original czi images for comparison.

- Implement zstd decompression for tiffs.

---

components/formats-gpl/src/loci/formats/in/FV1000Reader.java

This PR is in response to https://forum.image.sc/t/cannot-open-oib-files-in-imagej/71616/5
Sample files have been provided which use a different Locale format for the double values.
With the current release (6.10.1) this results in an exception as below:
```
java.lang.NumberFormatException: For input string: “211,761.0”
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at loci.formats.in.FV1000Reader.initFile(FV1000Reader.java:498)
at loci.formats.FormatReader.setId(FormatReader.java:1443)
at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:499)
at loci.plugins.in.ImportProcess.execute(ImportProcess.java:142)
at …
```

FV1000: Use DataTools to parse Double values

---

components/formats-gpl/src/loci/formats/in/PCIReader.java

This PR is in response to an issue raised on the forum thread https://forum.image.sc/t/calibration-data-of-pixels-in-cxd-file/72023
A sample file has been provided (https://zenodo.org/record/7107758#.Yy2igHbP1dg) which reproduces the issue with Bio-Formats 6.10.1. I will shortly add the sample file to the data repo and open a follow up config PR.

PCI: Make use of magnification value when calculating physical size

---

components/bio-formats-plugins/src/loci/plugins/in/Importer.java

This is in response to an issue encountered in forum thread https://forum.image.sc/t/exception-issue-when-opening-nd2-files-with-bio-formats/40462/9
When using the BFImport command in a macro, if a FormatException occurred the underlying reader was not properly closed and the file was unable to be renamed.
This will not impact any repo tests and is safe for a patch release.

Plugins: Close reader after format exception in Importer

---

components/formats-bsd/src/loci/formats/FileStitcher.java

See https://github.com/glencoesoftware/bioformats2raw/issues/139#issuecomment-1075268455
```curated/fake/samples/single-file-pattern``` illustrates the problem.  There are two TIFF files that have similar names (```test1.tiff``` and ```test2.tiff```), and a pattern file that lists one of them but does not include ```<``` or ```>``` which would explicitly indicate a file pattern.
Without this PR, ```showinf test1.pattern``` should throw an exception because both ```test1.tiff``` and ```test2.tiff``` are incorrectly picked up, and the two files have different XY dimensions.
With this PR, ```showinf test1.pattern``` should not throw an exception, because only ```test1.tiff``` is picked up.
The work-arounds for this issue in the meantime are:
- don't use a pattern file for a single image file …

FileStitcher: better handling for a single file wrapped in a pattern file

---

components/formats-gpl/src/loci/formats/in/InCellReader.java

Instead, count the number of child ```Image``` elements.  See https://github.com/IDR/idr0061-wolf-spindlepositioning/issues/2.
For almost all datasets, the ```number``` attribute on ```Images``` matches the number of ```Image```s, so I wouldn't expect this to cause any test failures.

InCell 1000/2000: don't trust the plane count in the "Images" element

---

components/formats-gpl/src/loci/formats/in/PCIReader.java

This is a follow up to the original PR https://github.com/ome/bioformats/pull/3880
Comparing the data repo updates to the equivalent HCImage  data suggests that the magnification value should not be used for physical size when the units are Pixels. https://github.com/openmicroscopy/data_repo_config/pull/539
This may mean further repo updates if there are other datasets with pixel units.

PCI: Parse units for physical size

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Backported from a private PR. Opening to see if repo tests fail, will exclude tomorrow if they do. 
This is meant to speed up `setId` time for cases such as the output of `bfconvert "test&sizeZ=4000.fake" test.ome.tiff`.
Unit tests fail without 2ebbc58, which I think actually exposes an issue with bfconvert. `bfconvert "test&sizeC=2&series=3.fake" -tilex 256 -tiley 256 -channel 1 test-split_%x_%y_%m.ome.tiff` results in in this OME-XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Creator="OME Bio-Formats 6.10.0-SNAPSHOT" UUID="urn:uuid:aa1ec1c8-4f03-4f22-9634-345a61d7275a" xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 …
```

OME-TIFF: faster initialization when there are lots of planes

---

components/formats-bsd/pom.xml
components/formats-bsd/src/loci/formats/codec/ZstdCodec.java
components/formats-gpl/pom.xml
components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java
pom.xml

This PR is an initial follow up to https://github.com/ome/bioformats/pull/3867
It replaces the existing Zstd implementation in the ZeissCZIReader with the new ZstdCodec. I added some additional methods to the codec to also enable the usage of an offset and length for decompression.
If the repo tests continue to pass then I will open a second PR to migrate the new ZstdCodec to https://github.com/ome/ome-codecs and then update this PR once `ome-codecs` has been released.
I have removed the duplicate `aircompressor` dependency, which will eventually end up living in `ome-codecs` also.

Zeiss CZI: Use new ZSTD codec

---

.github/workflows/maven.yml

Check that the build is green
Background https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

switch to new output command

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

Exposure times can be recorded with no tag prefix or with the `Microscope ` tag prefix. Some datasets have just one or the other, some have both. The times with no prefix are preferred if present, but the `Microscope ` ones are now used if that is all that is available.
Fixes #3642.
Compare `showinf -nopix -omexml -noflat` on QA 29751 with and without this PR.
This should be safe for a patch release.

Olympus vsi: fix exposure time handling

---

components/formats-bsd/src/loci/formats/in/SlideBook7Reader.java

This is an attempt to fix the issue raised in https://github.com/ome/bioformats/issues/3903
From the Fortinet error report it shows the error within `SlideBook7Reader$CSBFile70$1$1.class` which suggests that the issue was within the second anonymous  inner class within CSBFile70. The second nested `FileFilter` looks to be easily removed and results in the jar passing all of the security checks.
To test:
- Ensure builds and tests continue to pass
- Without this PR the compiled `formats-bsd` jar should fail the Fortinet check in https://www.virustotal.com/gui/home/upload
- With this PR the jar should pass all of the virustotal checks
Fixes #3903

Slidebook7: Remove nested inner class

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Backported from a private PR. Also happens to fix #3884.
Test files are uploading to `curated/zeiss-czi/gh-3884` and will be finished later today. Without this PR, the OME-XML printed by `showinf -nopix -noflat -omexml` should show that the first few `Image`s are linked to a `Plate`, but the majority are orphaned. With this PR, the same check should show all `Image`s linked to the `Plate`, with 9 or 20 fields per well.
This might affect some of the configured `Image` names (in which case I'll open a follow-up config PR), but otherwise I wouldn't expect test failures. This should be safe for a patch release.

CZI: support multiple fields in a plate

---

components/formats-gpl/src/loci/formats/in/VectraReader.java

If a biomarker is set in the original metadata, it will now be saved as the `Name` on `Channel`. The previous name will be saved as `Fluor` on `Channel`, as this is a better match for what the name attribute actually is.
If no biomarker is present, there should be no change in behavior. This seems to be the more common case, as I don't believe we have any example files in the repo that contain a biomarker. The files used to test the private PR unfortunately can't be shared.

QPTIFF: preserve biomarker data in channel name

---

components/formats-bsd/src/loci/formats/tiff/TiffParser.java

Backported from a private PR
This addresses an edge case where the [ReferenceBlackWhite](https://www.awaresystems.be/imaging/tiff/tifftags/referenceblackwhite.html) TIFF tag is read as an array of floats.
In the majority of the TIFF-based samples this tag contains an array of 6 integers as shown by `tiffdump` e.g. using  [a public NDPI sample](https://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/openslide/CMU-1/):
```
% tiffdump CMU-1.ndpi | grep Refere
ReferenceBlackWhite (532) LONG (4) 6<0 255 128 255 128 255>
ReferenceBlackWhite (532) LONG (4) 6<0 255 128 255 128 255>
ReferenceBlackWhite (532) LONG (4) 6<0 255 128 255 128 255>
ReferenceBlackWhite (532) LONG (4) 6<0 255 128 255 128 255>
ReferenceBlackWhite (532) LONG (4) 6<0 255 128 255 128 255>
```
TiffParser uses the …

TiffParser: handle REFERENCE_BLACK_WHITE as an array of floats

---

components/formats-gpl/src/loci/formats/in/LeicaSCNReader.java

This is a test PR for a potential fix to https://github.com/ome/bioformats/issues/3510
Currently color correction is applied for any non Versa systems, in this case an SCN400 system has been used that also does not require correction. Unfortunately I cant find anything else in the metadata that would indicate if correction is or isn't required. Opening this PR as a test to see its impact on other files in the data repo.

SCN: No color correction for SCN400

---

components/formats-bsd/src/loci/formats/in/FakeReader.java
components/formats-bsd/test/loci/formats/utests/FakeReaderTest.java

Noticed while working on tests for https://github.com/glencoesoftware/raw2ometiff/pull/90
The default dimension order is `XYZCT`, independent of whether or not there are RGB channels. Without this PR, a simple test such as `showinf "test&sizeC=3&rgb=3&sizeZ=5.fake"` shows 3 channels merged to RGB planes, with a dimension order of `XYZCT`. This is inconsistent with how other readers report RGB data; `C` should be immediately after `XY`.
With this PR, the same test should show that the dimension order is `XYCZT`. A warning should also be logged to indicate that the default dimension order is being changed.
I think I'd be OK with just warning (or throwing an exception?) if that sounds better than trying to change the dimension order. The workaround is to explicitly specify the correct …

Fake: if there are RGB channels, dimension order needs to be XYC*

---

components/formats-bsd/src/loci/formats/MinMaxCalculator.java

This fixes an arithmetic error which prevented correct min/max values from being reported for some RGB data. The length supplied to `updateMinMax(...)` is expected to be the total number of bytes, including any RGB channels. `updateMinMax(...)` later performs calculations on the length to determine the number of pixels, which are incorrect if the RGB channels are not included.
Non-RGB data (`getRGBChannelCount() == 1`) is unaffected, so anything that includes `ChannelSeparator` as well as `MinMaxCalculator` in the reader stack should not be impacted by this change.
This issue was exposed during testing of https://github.com/glencoesoftware/raw2ometiff/pull/90. The steps to test are:
- convert `curated/zeiss-zvi/cecilia/*.zvi` with bioformats2raw 0.5.0
- convert the bioformats2raw output …

Fix min/max calculation for RGB data

---

pom.xml

Bumping ome-model to the latest 6.3.2 release

Bump ome-model version to 6.3.2

---

components/formats-gpl/src/loci/formats/in/LiFlimReader.java

Currently the LiFlimReader does not support reading msb(most significant bit) 12 to 16 bit conversion.
I have added the functionality to check if msb or lsb should be used based on the packing value, if the packing value equals msb the new msb 12 to 16 bit conversion is used.
If there are any questions please contact me: Shaquile@LambertInstruments.com

Added MSB 12 to 16 bit conversion

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Ported from a private PR.
This addresses a problem where the XY dimensions of a slide were incorrectly set to the XY dimensions of a single tile. Aside from just being wrong, the sizes were small enough that smaller resolutions were calculated to have 0 pixels, which caused other errors.
I expect this to have limited impact on existing datasets; a configuration PR will be opened shortly.

CZI: fix pyramid dimension calculation

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

Backported from a private PR. This is expected to fix #3859.
~`inbox/gh-3859`~`curated/cellsens/gh-3859` can be used to test. I may have additional test datasets, but am waiting for confirmation that they can be shared.
Without this change, `showinf -nopix -noflat` on the .vsi file should throw an exception. With this change, usual `showinf` commands, opening in ImageJ, etc. should display images and metadata without error. The `blob*.ets` and `blob*.meta` files should be included at the end of the used files list.
I would expect this to impact memo files, so requires a minor release.

Olympus .vsi: only read pixels from frame_*.ets files

---

components/bio-formats-plugins/pom.xml
components/bio-formats-tools/pom.xml

At runtime, the `ch.qos.logback` classes are only accessed via reflection.
Specifically, the IJStatusEchoer class is used only by ome-common (!) [in a `ReflectedUniverse` block](https://github.com/ome/ome-common-java/blob/v6.0.13/src/main/java/loci/common/DebugTools.java#L160-L182).
It is best practice for libraries not to impose any specific SLF4J binding on downstream consumers.
> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api.
[Source](https://www.slf4j.org/manual.html#libraries)

Make logback dependencies optional

---

.github/workflows/ant.yml

As discussed with @ome/formats earlier today.
For the Java 1.8/ubuntu-latest ant build only, artifacts should be now be archived, for 30 days only (instead of default 90). Hopefully that's enough to prevent any problems with usage limits.
I did not do anything extra to add commit hashes as suggested in discussions. All of the Bio-Formats builds should already include the commit hash in the `Implementation-Build` of the manifest and the `FormatTools.VCS_REVISION` variable. Using the `bioformats_package.jar` archived here with ImageJ (`Help > About Plugins > Bio-Formats Plugins...`), `showinf -version`, or `java -jar bioformats_package.jar` and then `Help > About...` should all show the 938eca1... commit hash.

Upload one set of artifacts from the GitHub Actions ant build

---

components/formats-gpl/src/loci/formats/in/CellSensReader.java

Fixes #3822.
Without this PR, opening the .vsi file in `curated/cellsens/gh-3822` in QuPath or ImageJ vs. Olympus' OlyVIA shows a subtle difference between the left and right edges, as noted in the initial issue report. The associated .jp2 file visually approximates what OlyVIA shows, but cannot be used for quantitative comparison as it has a different pixel type and channel count.
With this PR, opening the largest resolution from the .vsi file in ImageJ or similar should show that the image is now shifted 34 pixels in X and 1 pixel in Y, matching what OlyVIA shows. This is easiest to see when zooming in on the corners of the image.
The pixel shift is scaled with the resolution index, so opening smaller resolutions should also show a slight difference with this PR. 
This requires a minor …

VSI: respect tile origin metadata

---

components/formats-gpl/src/loci/formats/in/OperettaReader.java

Some Operetta/Harmony/etc. plates will have one or more 32-bit TIFF files essentially at random. These are not recorded as being any different in the `Index.idx.xml` file. We have been told that these files contain invalid data (even if it "looks OK"), so a blank plane (all 0s) should be returned in place of the 32-bit data.
An artificial example is being uploaded to `curated/perkinelmer-operetta/samples/32-bit-file` (see the readme for how it was created). Without this PR, `showinf -series 2 Index.idx.xml` should throw an exception during `openBytes`. With this PR, the same command should show a warning to indicate that one of the files is 32-bit, but should not throw an exception. The first plane in the series should be all 0s.
Additional reports of this …

Operetta/Harmony: ignore any 32-bit TIFF files

---

pom.xml

Bumps components for ome-common-java, ome-metakit and ome-codecs to the latest released versions.

Bump component versions for 6.12.0

---

.github/workflows/ant.yml
.github/workflows/release.yml
components/bundles/bioformats_package/build.xml

This PR creates and uploads the release artifacts when a tag is pushed
4b1f6859f76cae9feb4865b66c19cb487699b903 is needed since the reference ``compile/runtime.classpath`` is no longer found when ant 1.10 is used (that's the version installed via GHA). Open to alternative is someone knows one
Tested via https://github.com/jburel/bioformats/releases/tag/v6.11.1-m1

Release artifacts

---

components/formats-gpl/src/loci/formats/in/LIPixelFormat.java
components/formats-gpl/src/loci/formats/in/LiFlimReader.java

Currently the LiFlimReader does not support reading fli files with Fli header 2.0.
To resolve this I have added the functionality to read the header differently depening on which Fli header version is specified in the opened .Fli file. To support pixelformats, which are used in Fli 2.0 I added LIPixelformats.java which contains helper functions for determening the packing and BitSize configurations of PixelFormats.

Added Fli 2.0 support in LiFlimReader

---

components/formats-gpl/src/loci/formats/in/BioRadGelReader.java

Fixes #3603.
To test, use `bad*.1sc` files in `curated/biorad-gel/qa-294*`. Without this PR, each should be shifted and have noise at the top and/or bottom of the image. This is easiest to see when opening in ImageJ.
With this PR, each of the `*.1sc` files should look correct - no shifting or obviously wrong pixels along the edges. `showinf -minmax -autoscale -fast` with this PR should also show a reasonable image, since the max pixel value is no longer at the upper end of the range.
Should be fine for a patch release, so assigning to 6.12.1 for now. I would not expect this to cause any test failures.

Bio-Rad Gel: fix pixel data offsets for cropped images

---

components/formats-bsd/src/loci/formats/FileStitcher.java

If the helper reader performs file grouping, then `externals` will be null and `noStitch` will be set to `true`. This cleans up a few overlooked places where `externals` was assumed to be non-null. It also logs an `INFO` message if the file pattern is discarded in favor of grouping by the helper reader. We can debate whether this should just be logged, or if throwing an exception is more appropriate.
To test, use `curated/ome-tiff/samples/no-op-file-pattern/multifile.pattern`. Without this PR, run `showinf -nopix multifile.pattern -cache` twice. The first time will succeed, the second time will fail with a `NullPointerException`. With this PR, remove the memo file and perform the same test. Both `showinf` calls should succeed without an exception, and there …

Fix NPEs when a no-op file pattern is encountered

---

components/formats-bsd/src/loci/formats/in/OMETiffReader.java

Fixes #3853 
`File.getCanonicalPath` normalizes paths containing '.', '..' but also resolves symlinks. This behavior breaks some expectations in terms of containment. This commit makes use of `Path.normalize` to avoid the symlink deferencing
I came back to this issue as part of the testing of #3947 as the sample fileset is constructed on top of an OME-TIFF dataset including a companion file.
Without this PR, after creating a symlink to an OME-TIFF fileset including a companion file (as indicated in the issue), `showinf -nopix` should report different listing of used files depending on whether a TIFF file or the companion are used as the input. With this PR included, the listing should be the same and not resolve to the absolute path if a symlinked file is used.

OMETiffReader: normalize paths rather than resolving symlinks

---

components/formats-gpl/src/loci/formats/in/MetamorphReader.java

Prevents a NegativeArraySizeException (or IOException) if the key length is too small or too large. This is expected when the key/value pair is not actually defined in the file. Fixes #3578.
To test, use the datasets in `curated/metamorph/imagesc-39526`. Without this PR, `showinf -nopix -omexml` on the .nd files should throw a `NegativeArraySizeException` as noted in #3578. With this PR, both files should initialize without error.
Should be safe for any patch release; adding to 6.12.1 for initial review.

Metamorph: don't try to read metadata keys that don't exist

---

components/formats-gpl/src/loci/formats/in/ZeissCZIReader.java

Fixes #3710.
See test files in `curated/zeiss-czi/gh-3710`.
Without this PR, `showinf` should report several small series corresponding to individual tiles in a larger image. In some cases, viewing the tiles will show a skewed image.
With this PR, the tiles should be correctly stitched together into a single series which no longer looks skewed. Screenshots from ZEN for comparison are on the corresponding configuration PR.
I would expect one existing file to be affected by this, as noted in the configuration PR. I believe the previous handling of that file was incorrect, and this PR fixes it. Otherwise, I would not expect this to introduce test failures.
This should be safe for a patch release, so assigning to 6.12.1 for now since it isn't especially urgent and there is already a lot in …

CZI: tile stitching fixes when pyramid does not exist

---

components/formats-gpl/src/loci/formats/in/NativeND2Reader.java
components/test-suite/src/loci/tests/testng/FormatReaderTest.java

See https://github.com/glencoesoftware/bioformats2raw/issues/184
To test, use the provided test file, which is copied to `curated/nd2/bioformats2raw-184`. Without this PR, `showinf -nopix` should throw `NegativeArraySizeException` eventually. Adding `-option nativend2.chunkmap false` results in the same exception.
With this PR, `showinf -nopix` should initialize without exception, though it may be a little slow. Reading tiles from the image should result in reasonable looking images. I was not able to open the full image in Nikon's NIS Elements viewer for comparison, but can view a thumbnail and the basic metadata (a screenshot is included in the configuration PR).
The source of the problem was the `CustomDataSeq|edfbox_d` block, which has a data length greater than 2GB. I would expect …

ND2: fix reading of blocks larger than 2 GB
